micronaut.application.name=micronautguide
#tag::ollama[]
# <1>
langchain4j.ollama.base-url=http://localhost:11434
# <2>
langchain4j.ollama.model-name=llama3.2
langchain4j.ollama.timeout=5m
#end::ollama[]
