common:header-top.adoc[]

== Sample Project

You can link:@sourceDir@.zip[download a sample application] with the code examples shown in this article.

== Introduction

Spring Boot and Micronaut applications contain a simple application class which starts the application for you.

== Configuration

=== Spring Boot Validation Dependencies

dependency:spring-boot-starter-validation[groupId=org.springframework.boot]

=== Spring Boot Nested and Validated Configuration

source:GreetingConfiguration[app=springboot]

To use `@ConfigurationProperties` with Spring Boot you need to annotate your Application class with `@ConfigurationPropertiesScan` or register it via  `@EnableConfigurationProperties`:
source:GreetingConfigurationConfig[app=springboot]

==== Spring Boot Tests

test:GreetingConfigurationTest[app=springboot]

test:InvalidGreetingConfigurationTest[app=springboot]

=== Micronaut Nested and Validated Configuration

common:micronaut-validation[]

In Micronaut you don't need to annotate the `@ConfigurationProperties` class with `@Validated`.
Moreover, you need to annotate the inner class with `@ConfigurationProperties` and the `content` field should not be final and have a setter and getter.

source:GreetingConfiguration[app=micronautframework]

==== Micronaut Tests

test:GreetingConfigurationTest[app=micronautframework]

test:InvalidGreetingConfigurationTest[app=micronautframework]

== Next Steps

Read more about https://micronaut-projects.github.io/micronaut-spring/latest/guide/[Micronaut Spring].

common:helpWithMicronaut.adoc[]
