micronaut:
  application:
    name: bookinventory
endpoints:
  health:
    enabled: true
    sensitive: false
---
#tag::oauth2[]
micronaut:
  security:
    token:
      jwt:
        signatures:
          jwks:
            oci:
              url: '${OAUTH_JWKS:`https://idcs-12bzlaba1124141.identity.oraclecloud.com/admin/v1/SigningCert/jwk`}'
#end::oauth2[]