common:header.adoc[]

common:gcp-cloud-run.adoc[]

common:gcp-deploy-requirements2content.adoc[]

common:gcp-billing.adoc[]

common:gcp-containerregistry.adoc[]

== Docker Push

common:google-cloud-registry.adoc[]

:exclude-for-languages:python

:exclude-for-build:maven,pyronaut

Modify your Gradle build to configure the image name:

[source,groovy]
----
...
..
.
dockerBuild {
    images = ["gcr.io/micronaut-guides-xxxxxx/micronautguide:latest"]
}
----

:exclude-for-build:

common:docker-push-gradle.adoc[]

:exclude-for-build:gradle,pyronaut

[source, bash]
----
./mvnw deploy \
     -Dpackaging=docker \
     -Djib.to.image=gcr.io/micronaut-guides-xxxxxx/micronautguide:latest
----

:exclude-for-build:

:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin

Configure the Pyronaut Docker image name in `pyproject.toml`:

[source,toml]
----
[tool.pyronaut.build.docker]
image-name = "gcr.io/micronaut-guides-xxxxxx/micronautguide"
----

Build and push the Docker image:

[source, bash]
----
pyronaut build --docker
docker push gcr.io/micronaut-guides-xxxxxx/micronautguide:1.0.0
----

:exclude-for-languages:

The previous image names use the pattern `gcr.io/micronaut-guides-xxxxxx/micronautguide`. Change it to use your project ID.

You get an output such as:

:exclude-for-languages:python

[source, bash]
----
....
..
.
Pushing image 'gcr.io/micronaut-guides-xxxxxx/micronautguide:latest'.
----

:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin

[source, bash]
----
Docker image build complete: gcr.io/micronaut-guides-xxxxxx/micronautguide:1.0.0
----

:exclude-for-languages:

== Google Cloud Run Deploy

You can https://cloud.google.com/sdk/gcloud/reference/run/deploy[deploy to Google Cloud Run] via the CLI. Use the value you configured in your build as the image argument's value.

:exclude-for-languages:python

[source, bash]
----
gcloud run deploy \
    --image=gcr.io/micronaut-guides-xxxxxx/micronautguide:latest \
    --platform managed \
    --allow-unauthenticated
----

:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin

[source, bash]
----
gcloud run deploy \
    --image=gcr.io/micronaut-guides-xxxxxx/micronautguide:1.0.0 \
    --platform managed \
    --allow-unauthenticated
----

:exclude-for-languages:

common:google-cloud-run-deploy-plain.adoc[]

== Cleanup

common:gcloud-run-services-delete.adoc[]

common:gcloud-delete-project.adoc[]

== Next Steps

:exclude-for-languages:python

You will probably want to deploy to Google Cloud Run from your CI server. https://launch.micronaut.io[Micronaut Launch] contains the https://micronaut.io/launch?type=DEFAULT&name=demo&package=com.example&javaVersion=JDK_25&lang=JAVA&build=GRADLE&test=JUNIT&features=github-workflow-google-cloud-run&version=3.0.3[github-workflow-google-cloud-run] feature, which adds a https://github.com/features/actions[GitHub Actions] workflow that deploys an application to Google Cloud Run from Google Container Registry.

:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin

You will probably want to deploy to Google Cloud Run from your CI server. For Pyronaut applications, run `pyronaut build --docker`, push the generated image tag, and deploy that tag with `gcloud run deploy`.

:exclude-for-languages:

Read more about:

- https://cloud.google.com/container-registry[Google Cloud Container Registry]
- https://cloud.google.com/run[Google Cloud Run]
- https://micronaut-projects.github.io/micronaut-gcp/latest/guide/[Micronaut Google Cloud Platform (GCP)] integration.

common:helpWithMicronaut.adoc[]
