common:header.adoc[]

You are going to deploy a Micronaut application to https://cloud.google.com/run[Google Cloud Run].

> Develop and deploy highly scalable containerized applications on a fully managed serverless platform.

common:gcp-deploy-requirements2content.adoc[]

== Docker Push

common:google-cloud-registry.adoc[]

:exclude-for-build:

:exclude-for-build:maven

Modify your Gradle build and configure the

[source,groovy]
----
...
..
.
dockerBuild {
    images = ["gcr.io/micronaut-guides-xxxxxx/micronautguide:latest"]
}
----

:exclude-for-build:

common:docker-push-gradle.adoc[]

:exclude-for-build:gradle

[source, bash]
----
./mvnw deploy \
     -Dpackaging=docker \
     -Djib.to.image=gcr.io/micronaut-guides-xxxxxx/micronautguide:latest
----

:exclude-for-build:

The previous URL uses the pattern: `gcr.io/micronaut-guides-xxxxxx/micronautguide:latest`. Change it to use your Project ID.

You get an output such as:

[source, bash]
----
....
..
.
Pushing image 'gcr.io/micronaut-guides-xxxxxx/micronautguide:latest'.
----

== Google Cloud Run Deploy

You can deploy to Google Cloud Run via the CLI. Use the value you configured in your build as the image argument's value.

[source, bash]
----
gcloud run deploy \
    --image=gcr.io/micronaut-guides-xxxxxx/micronautguide:latest \
    --platform managed \
    --allow-unauthenticated
----

common:google-cloud-run-deploy-plain.adoc[]

== Next steps

You will probably want to deploy to Google Cloud Run from your CI server. https://launch.micronaut.io[Micronaut Launch] contains feature https://micronaut.io/launch?type=DEFAULT&name=demo&package=com.example&javaVersion=JDK_17&lang=JAVA&build=GRADLE&test=JUNIT&features=github-workflow-google-cloud-run&version=3.0.3[github-workflow-google-cloud-run], which adds a https://github.com/features/actions[GitHub Actions] Workflow that deploys an application to Google Cloud Run from Google Container Registry.

Read more about:

- https://cloud.google.com/container-registry[Google Cloud Container Registry]
- https://cloud.google.com/run[Google Cloud Run]
- https://micronaut-projects.github.io/micronaut-gcp/latest/guide/[Micronaut Google Cloud Platform (GCP)] integration.

common:helpWithMicronaut.adoc[]
