micronaut:
    application:
        name: websocket-chat
    router:
        static-resources: # <1>
            default:
                enabled: true
                mapping: /**
                paths: classpath:public
