common:header-top.adoc[]

== Getting Started

In this guide, we will create a Micronaut application written in @language@ with session based authentication.

The following sequence illustrates the authentication flow:

image::session_based_auth.svg[]

common:requirements.adoc[]

common:completesolution.adoc[]

== Writing the Application

common:cli-or-launch.adoc[]

[source,bash]
----
mn @cli-command@ --features=security-session,views-velocity,reactor,graalvm example.micronaut.micronautguide --build=@build@ --lang=@lang@ --test=spock
----

common:build-lang-arguments.adoc[]

If you use Micronaut Launch, select "Micronaut Application" as application type and add the `security-session`, `views-velocity`, `reactor`, and `graalvm` features.

common:default-package.adoc[]

diffLink:[featureExcludes=geb]

https://guides.micronaut.io/latest/micronaut-intellij-idea-ide-setup.html[Setup IntelliJ IDEA to develop Micronaut Applications].

=== Configuration

Add this configuration to `application.yml`:

common:yaml-dependency.adoc[]

resource:application.yml[tag=security]

<1> Set `micronaut.security.authentication` to `session`. It sets the necessary beans for login and logout using session based authentication.
<2> After the user logs in, redirect them to the Home page.
<3> If the login fails, redirect them to /login/authFailed

=== Authentication Provider

To keep this guide simple, create a naive `AuthenticationProvider` to simulate user's authentication.

source:AuthenticationProviderUserPassword[]

callout:singleton[1]
callout:authentication-provider[2]

=== Apache Velocity

By default, Micronaut controllers produce JSON. Usually, you consume those endpoints with a mobile phone application, or a JavaScript front end (Angular, React, Vue.js, etc.). However, to keep this guide simple we will produce HTML in our controllers.

In order to do that, we use https://velocity.apache.org/[Apache Velocity] and the Micronaut https://docs.micronaut.io/latest/guide/#views[Server Side View Rendering Module].
____
Velocity is a Java-based template engine. It permits anyone to use a simple yet powerful template language to reference objects defined in Java code.
____

Create two velocity templates in `src/main/resources/views`:

resource:views/home.vm[]

resource:views/auth.vm[]

=== Controllers

Create `HomeController` which resolves the base URL `/`:

source:HomeController[]

<1> Annotate with `io.micronaut.security.Secured` to configure security access. Use `isAnonymous()` expression to allow access to authenticated and unauthenticated users.
<2> Annotate with `io.micronaut.http.annotation.Controller` to designate the class as a Micronaut controller.
<3> You can specify the HTTP verb that a controller action responds to. To respond to a GET request, use `io.micronaut.http.annotation.Get`
<4> Use https://micronaut-projects.github.io/micronaut-views/latest/api/io/micronaut/views/View.html[View] annotation to specify which template to use to render the response.
<5> If you are authenticated, you can use the `java.security.Principal` as a parameter type. For parameters which may be `null`, use `io.micronaut.core.annotation.Nullable`.

== Login Form

Next, create `LoginAuthController` which renders the login form.

source:LoginAuthController[]

<1> Annotate with `io.micronaut.security.Secured` to configure security access. Use `isAnonymous()` expression for anonymous access.
<2> Annotate with `io.micronaut.http.annotation.Controller` to designate the class as a Micronaut controller.
<3> Responds to GET requests at `/login/auth`
<4> Use https://micronaut-projects.github.io/micronaut-views/latest/api/io/micronaut/views/View.html[View] annotation to specify which template to use to render the response.
<5> Responds to GET requests at `/login/authFailed`

== Tests

common:geb.adoc[]

Create three pages:

rawTest:HomePage[]

rawTest:LoginPage[]

rawTest:LoginFailedPage[]

Create a test to verify the user authentication flow.

rawTest:SessionAuthenticationSpec[]

callout:micronaut-test[1]
<2> Inject the `EmbeddedServer` bean.

common:testApp.adoc[]

common:runapp.adoc[]

common:graal-with-plugins.adoc[]

common:next.adoc[]

common:helpWithMicronaut.adoc[]
