[micronaut.application]
name = "micronautguide"

#tag::datasource[]
[datasources.default]
schema-generate = "CREATE_DROP"
# <1>
driver-class-name = "oracle.jdbc.OracleDriver"
# <2>
db-type = "oracle"
# <3>
dialect = "ORACLE"
#end::datasource[]

#tag::dialect-options[]
# <1>
[datasources.default.dialect-options]
version = "23.1"
#end::dialect-options[]

#tag::testresources[]
# <1>
[test-resources.containers.oracle]
image-name = "gvenzl/oracle-free"
image-tag = "latest"
startup-timeout = "600s"
#end::testresources[]
