# tag::kafka[]
[kafka]
bootstrap.servers = "cell-1.streaming.us-ashburn-1.oci.oraclecloud.com:9092" # <1>
security.protocol = "SASL_SSL"
sasl.mechanism = "PLAIN"
sasl.jaas.config = "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"<tenancy-name>/<username>/<stream-pool-ocid>\" password=\"<auth-token>\";" # <2>
retries = 3
max.request.size = 1_048_576 # <3>

[kafka.producer]
max.request.size = 1_048_576 # <4>
# end::kafka[]
