[micronaut.application]
name = "chess-game"

# tag::static-resources[]
[micronaut.router.static-resources.default]
enabled = true
mapping = "/**"
paths = ["classpath:public"]
# end::static-resources[]
