[micronaut.application]
name = "micronautguide"

[test-resources.containers.oracle]
startup-timeout = "600s"

# <1>
[micronaut.executors.io]
nThreads = 75

[flyway.datasources.default]
enabled = true

# <2>
[oci.config]
profile = "DEFAULT"

[datasources.default]
dialect = "ORACLE"
db-type = "oracle"
driver-class-name = "oracle.jdbc.OracleDriver"
# <3>
# ocid = ""
# <4>
# walletPassword = ""
# username = "micronautdemo"
# <5>
# password = ""
