[micronaut.application]
name = "micronautguide"

# tag::datasource[]
[datasources.default]
schema-generate = "CREATE_DROP"
driver-class-name = "oracle.jdbc.OracleDriver"
db-type = "oracle"
dialect = "ORACLE"
# end::datasource[]

# tag::testresources[]
[test-resources.containers.oracle]
image-name = "gvenzl/oracle-free"
image-tag = "slim-faststart"
startup-timeout = "600s"
# end::testresources[]
