common:header.adoc[]

common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app-features.adoc[]

Start by creating the main application class. On startup, this class will populate the database with its initial data.

source:Application[]

callout:singleton[1]
callout:application-event-listener-startup-event[2]
callout:constructor-di[number=3,arg0=OwnerRepository]
<4> The database and tables have already been created by the Flyway integration described next, so this data can be saved here.

Create the DDL to model our application's domain, pets and pet owners.

resource:db/migration/V1__schema.sql[]
<1> Create the owner table, for the owners of pets.
<2> Create the pet table, each pet associated with one owner.
<3> Allow only certain values, mirroring our `PetType` Java enum.
<4> Enforce the association with an owner.

Set up the H2 database and Flyway.

resource:application.yml[]
<1> Configure an H2 datasource.
<2> Configure Flyway to set up our database.

Define the service endpoints using JAX-RS.

source:resources/OwnerResource[]
<1> A JAX-RS annotation to define the base URI for methods in this class.
<2> Inject the H2 JDBC repository.
<3> A JAX-RS annotation to define an endpoint for HTTP Get requests. Mapped to the base URI `/owners` since no `@Path` is provided.
<4> The response is converted to JSON automatically.
<5> Paths can be templated for path paremeters, such as the owner's name here.
<6> Associate the template placeholder name with the Java variable.

Test the service endpoints.

test:OwnerControllerTest[]

Or bypass the service layer and test the underlying repositories.

test:PetRepositoryTest[]

common:runapp.adoc[]

common:graal-with-plugins.adoc[]

== Next steps

Read more about https://micronaut-projects.github.io/micronaut-jaxrs/latest/guide/[Micronaut JAX-RS].
