micronaut:
  application:
    name: micronautguide
---
#tag::microstream[]
microstream:
  storage:
    main:
      root-class: 'example.micronaut.FruitContainer'
      storage-directory: 'build/fruit-storage'
#end::microstream[]
