micronaut:
  application:
    name: app
---
#tag::oauth2[]
micronaut:
  security:
    authentication: idtoken # <1>
    oauth2:
      clients:
        cognito: # <2>
          client-id: '${OAUTH_CLIENT_ID:xxx}' # <3>
          client-secret: '${OAUTH_CLIENT_SECRET:yyy}' # <4>
          openid:
            issuer: 'https://cognito-idp.${COGNITO_REGION:us-east-1}.amazonaws.com/${COGNITO_POOL_ID:12345}/' # <5>
    endpoints:
      logout:
        get-allowed: true # <6>
#end::oauth2[]
