common:header.adoc[]

common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app-features.adoc[]

:leveloffset: +1

== Route and Predicate APIs

Create a Predicate API:

source:RoutePredicate[]

and a `Route` API:

source:Route[]

Create a predicate type which will be provided via configuration:

source:ConfigurationRoutePredicate[]

== Configuration

Create an `EachProperty` class to allow the definition of beans of type `Route` via configuration:

source:RouteConfiguration[]

== Route Matcher

Create a functional interface for the route matching API:

source:RouteMatcher[]

and an implementation:

source:DefaultRouteMatcher[]

== Security

source:ApiKeyTokenValidator[]

source:RouteSecurityRule[]

== Gateway Filter

Create a Gateway Filter which uses a https://docs.micronaut.io/latest/guide/#proxyClient[ProxyHttpClient]:

source:GatewayFilter[]

== Tests

We are going to write a test which starts three servers. The gateway proxies the requests to the other servers:

[source, txt]
----
── gateway
    ├── micronaut
    ├── grails
----

Create a controller which is loaded only in the Grails Server leveraging the `@Requires` annotation:

test:Book[]
test:GrailsBooksController[]

Create a controller which is loaded only in the Micronaut Server leveraging the `@Requires` annotation:

test:MicronautBooksController[]

Create a Gateway Test:

test:GatewayTest[]

common:testApp.adoc[]

common:next.adoc[]

Learn more about:

- https://docs.micronaut.io/latest/guide/#proxyClient[ProxyHttpClient]:
- https://docs.micronaut.io/latest/guide/#filters[HTTP Filters]

common:helpWithMicronaut.adoc[]
