common:header-top.adoc[]

== Getting Started

The Micronaut framework ships with security capabilities based on https://jwt.io/[Json Web Token (JWT)]. JWT is an https://tools.ietf.org/html/rfc7519[IETF standard] which defines a secure way to encapsulate arbitrary data that can be sent over unsecure URLs.

In this guide you will create a Micronaut application written in @language@ and secure it with JWT.

The following sequence illustrates the authentication flow:

image::jwt-bearer-token.svg[]

common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app-features.adoc[]

=== Configuration

Note the following configuration in the generated `application.yml`:

common:yaml-dependency.adoc[]

resource:application.yml[tag=security]

<1> Set `authentication` to `bearer` to receive a JSON response from the login endpoint.
<2> Change this to your own secret and keep it safe (do not store this in your VCS).

=== Authentication Provider

To keep this guide simple, create a naive `AuthenticationProvider` to simulate user's authentication.

source:AuthenticationProviderUserPassword[]

callout:singleton[1]
callout:authentication-provider[2]

=== Controller

Create `HomeController` which resolves the base URL `/`:

source:HomeController[]

<1> Annotate with `io.micronaut.security.Secured` to configure secured access. The `isAuthenticated()` expression will allow access only to authenticated users.
<2> Annotate with `io.micronaut.http.annotation.Controller` to designate the class as a Micronaut controller.
<3> You can specify the HTTP verb that a controller action responds to. To respond to a GET request, use the `io.micronaut.http.annotation.Get` annotation.
<4> If a user is authenticated, the Micronaut framework will bind the user object to an argument of type `java.security.Principal` (if present).

== Tests

Create a test to verify a user is able to login and access a secured endpoint.

test:JwtAuthenticationTest[]

callout:micronaut-test[1]
callout:http-client[2]
<3> When you include the security dependencies, security is considered enabled and every endpoint is secured by default.
<4> To login, do a POST request to `/login` with your credentials as a JSON payload in the body of the request.
<5> The Framework makes it easy to bind JSON responses into Java objects.
<6> The Framework supports https://tools.ietf.org/html/rfc6750[RFC 6750 Bearer Token] specification out-of-the-box. We supply the JWT token in the `Authorization` HTTP Header.
callout:body-method[7]

=== Use the Micronaut HTTP Client and JWT

To access a secured endpoint, you can also use a Micronaut HTTP Client and supply the JWT token in the Authorization header.

First create a `@Client` with a method `home` which accepts an `Authorization` HTTP Header.

test:AppClient[]

Create a test which uses the previous `@Client`

test:DeclarativeHttpClientWithJwtTest[]

<1> Inject `AppClient` bean from the application context.
<2> To login, do a POST request to `/login` with your credentials as a JSON payload in the body of the request.
<3> Supply the JWT to the HTTP `Authorization` header value to the `@Client` method.

== Issuing a Refresh Token

Access tokens expire. You can control the expiration with `micronaut.security.token.jwt.generator.access-token.expiration`. In addition to the access token, you can configure your login endpoint to also return a refresh token. You can use the refresh token to obtain a new access token.

First, add the following configuration:

resource:application.yml[tag=refresh]

<1> To generate a refresh token your application must have beans of type:
https://micronaut-projects.github.io/micronaut-security/latest/api/io/micronaut/security/token/generator/RefreshTokenGenerator.html[RefreshTokenGenerator],
https://micronaut-projects.github.io/micronaut-security/latest/api/io/micronaut/security/token/validator/RefreshTokenValidator.html[RefreshTokenValidator], and
https://micronaut-projects.github.io/micronaut-security/latest/api/io/micronaut/security/token/refresh/RefreshTokenPersistence.html[RefreshTokenPersistence].
We will deal with the latter in the next section. For the generator and validator, Micronaut Security ships with
https://micronaut-projects.github.io/micronaut-security/latest/api/io/micronaut/security/token/jwt/generator/SignedRefreshTokenGenerator.html[SignedRefreshTokenGenerator].
It creates and verifies a JWS (JSON web signature) encoded object whose payload is a UUID with a hash-based message authentication
code (HMAC). You need to provide secret to use `SignedRefreshTokenGenerator` which implements both `RefreshTokenGenerator` and `RefreshTokenValidator`.

Create a test to verify the login endpoint responds both access and refresh token:

test:LoginIncludesRefreshTokenTest[]

<1> A refresh token is returned.

=== Save Refresh Token

We may want to save a refresh token issued by the application, for example, to revoke a user's refresh tokens, so that a particular user cannot obtain a new access token, and thus access the application's endpoints.

Persist the refresh tokens with help of https://micronaut-projects.github.io/micronaut-data/latest/guide/[Micronaut Data].

> Micronaut Data is a database access toolkit that uses Ahead of Time (AoT) compilation to pre-compute queries for repository interfaces that are then executed by a thin, lightweight runtime layer.

In particular, use Micronaut JDBC

> Micronaut Data JDBC is an implementation that pre-computes native SQL queries (given a particular database dialect) and provides a repository implementation that is a simple data mapper between a JDBC ResultSet and an object.

The `data-jdbc` feature adds the following dependencies:

:dependencies:

dependency:micronaut-data-processor[groupdId=io.micronaut.data,scope=annotationProcessor,callout=1]
dependency:micronaut-data-jdbc[groupId=io.micronaut.data,callout=2]
dependency:micronaut-jdbc-hikari[groupId=io.micronaut.sql,callout=3]
dependency:h2[groupId=com.h2database,scope=runtimeOnly,callout=4]

:dependencies:

<1> Micronaut data is a build time tool. You need to add the build time annotation processor
<2> Add the Micronaut Data JDBC dependency
<3> Add a Hikari connection pool
<4> Add a JDBC driver. Add https://www.h2database.com/html/main.html[H2] driver

Create an entity to save the issued Refresh Tokens.

source:RefreshTokenEntity[tags=clazzwithoutsettersandgetters|endclass]

<1> Specifies the entity is mapped to the database
<2> Specifies the ID of an entity
<3> Specifies that the property value is generated by the database and not included in inserts
<4> Allows assigning a data created value (such as a `java.time.Instant`) prior to an insert

Create a https://micronaut-projects.github.io/micronaut-data/latest/api/io/micronaut/data/repository/CrudRepository.html[CrudRepository] to include methods to peform Create, Read, Updated and Delete operations with the `RefreshTokenEntity`.

source:RefreshTokenRepository[]

<1>	The interface is annotated with https://micronaut-projects.github.io/micronaut-data/latest/api/io/micronaut/data/jdbc/annotation/JdbcRepository.html[@JdbcRepository] and specifies a dialect of H2 used to generate queries
<2> The `CrudRepository` interface has two generic arguments; the entity type (in this case `RefreshTokenEntity`) and the ID type (in this case `Long`)
<3> When a new refresh token is issued we will use this method to persist it
<4> Before issuing a new access token, we will use this method to check if the supplied refresh token exists
<5> We can revoke the refresh tokens of a particular user with this method

=== Refresh Controller

Enable the https://micronaut-projects.github.io/micronaut-security/latest/guide/#refresh[Refresh Controller] via configuration and provide an implementation of
https://micronaut-projects.github.io/micronaut-security/latest/api/io/micronaut/security/token/refresh/RefreshTokenPersistence.html[RefreshTokenPersistence].

To enable the refresh controller, create a bean of type
https://micronaut-projects.github.io/micronaut-security/latest/api/io/micronaut/security/token/refresh/RefreshTokenPersistence.html[RefreshTokenPersistence] which leverages the Micronaut Data repository we coded in the previous section:

source:CustomRefreshTokenPersistence[]

callout:singleton[1]
<2> Constructor injection of `RefreshTokenRepository`.
<3> When a new refresh token is issued, the application emits an event of type https://micronaut-projects.github.io/micronaut-security/latest/api/io/micronaut/security/token/event/RefreshTokenGeneratedEvent.html[RefreshTokenGeneratedEvent]. We listen for it and save the token in the database.
<4> The event contains both the refresh token and the user details associated to the token.
<5> Throw an exception if the token is revoked.
<6> Return the user details associated to the refresh token, e.g. username, roles, attributes, etc.
<7> Throw an exception if the token is not found.

=== Test Refresh Token

==== Test Refresh Token Validation

Refresh tokens issued by https://micronaut-projects.github.io/micronaut-security/latest/api/io/micronaut/security/token/jwt/generator/SignedRefreshTokenGenerator.html[SignedRefreshTokenGenerator], the default implementation of https://micronaut-projects.github.io/micronaut-security/latest/api/io/micronaut/security/token/generator/RefreshTokenGenerator.html[RefreshTokenGenerator],
are signed.

`SignedRefreshTokenGenerator` implements both https://micronaut-projects.github.io/micronaut-security/latest/api/io/micronaut/security/token/generator/RefreshTokenGenerator.html[RefreshTokenGenerator]
and https://micronaut-projects.github.io/micronaut-security/latest/api/io/micronaut/security/token/validator/RefreshTokenValidator.html[RefreshTokenValidator].

The bean of type `RefreshTokenValidator` is used by the https://micronaut-projects.github.io/micronaut-security/latest/guide/#refresh[Refresh Controller] to ensure the refresh token supplied is valid.

Create a test for this:

test:UnsignedRefreshTokenTest[]

<1> Use an unsigned token

==== Test Refresh Token Not Found

Create a test to verify that sending a valid refresh token that was not persisted returns HTTP Status 400.

test:RefreshTokenNotFoundTest[]

<1> Supply a signed token which was never saved.

==== Test Refresh Token Revocation

Generate a valid refresh token, save it but flag it as revoked. Expect a 400.

test:RefreshTokenRevokedTest[]

<1> Save the token but flag it as revoked

==== Test Access Token Refresh

Login, obtain both access token and refresh token, with the refresh token obtain a different access token:

test:OauthAccessTokenTest[]

<1> Make a POST request to `/oauth/access_token` with the refresh token in the JSON payload to get a new access token
<2> A different access token is retrieved.

common:testApp.adoc[]

common:runapp.adoc[]

Send a request to the login endpoint:

[source,bash]
----
curl -X "POST" "http://localhost:8080/login" -H 'Content-Type: application/json' -d $'{"username": "sherlock","password": "password"}'
----

[source,json]
----
{"username":"sherlock","access_token":"eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzaGVybG9jayIsIm5iZiI6MTYxNDc2NDEzNywicm9sZXMiOltdLCJpc3MiOiJjb21wbGV0ZSIsImV4cCI6MTYxNDc2NzczNywiaWF0IjoxNjE0NzY0MTM3fQ.cn8bOjlccFqeUQA7x7MnfacMNPjSVAtWP65z1c8eaJc","refresh_token":"eyJhbGciOiJIUzI1NiJ9.NDI1ZjAxZTktYTRmYS00MmU5LTllYjctOWU2ZTNhNTI5YmQ1.RUc2iCfZdPQdwg2U0Nw_LLzZQIIDp5_Is2UWeHVZT7E","token_type":"Bearer","expires_in":3600}
----

common:graal-with-plugins.adoc[]

:exclude-for-languages:groovy

Send the same `curl` request as before to test that the native executable application works.

:exclude-for-languages:

== Next steps

Learn more about JWT Authentication in the https://micronaut-projects.github.io/micronaut-security/latest/guide/#jwt[official documentation].

common:helpWithMicronaut.adoc[]
