[micronaut.server]
port = 8081 # <1>

# tag::datasource[]
[datasources.default] # <2>
url = "jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE"
driver-class-name = "org.h2.Driver"
username = "sa"
password = ""
dialect = "H2"
# end::datasource[]

# tag::kafka[]
[kafka] # <3>
bootstrap.servers = "localhost:9092"
# end::kafka[]

[flyway.datasources.default]
locations = ["classpath:db/migration/h2"] # <4>
