common:completesolution.adoc[]

== Writing the Application

The Micronaut framework uses https://opentelemetry.io/[OpenTelemetry] to generate and export tracing data.

OpenTelemetry provides two annotations one to create a span and another to include additional information to the span.

@WithSpan:: Used on methods to creates a new span using a given name or defaults to the method name.

@SpanAttribute:: Used on method parameter to include the value to the span with a given name or defaults to the parameter name.

The `@WithSpan` and `@SpanAttribute` can be used on non-private methods.

If the annotations are not enough, or you want to add tracing to a private method, Micronaut’s tracing integration registers a `io.opentelemetry.api.trace.Tracer` bean which exposes the OpenTelemetry API and can be dependency-injected as needed.

[NOTE]
====
The `io.micronaut.tracing.annotation` are available if you prefer or have an existing Micronaut Application using them.

- `@NewSpan` : Maps to `@WithSpan`
- `@SpanTag` : Identical to `@SpanAttribute`
- `@ContinueSpan` : this annotation is ignored

TODO: Add link to blog/documentation on migrating from
OpenTracing to OpenTelemetry
====

=== Create the Application

common:cli-or-launch.adoc[]

[source,bash]
----
mn @cli-command@ example.micronaut.micronautguide \
    --build=@build@ --lang=@lang@
----

common:build-lang-arguments.adoc[]

common:default-package.adoc[]

If you use Micronaut Launch, select Micronaut Application as application type.

diffLink:[]

common:annotationprocessors.adoc[]

=== Inventory Service

source:InventoryService[]
<1> Inject Tracing bean into class
<2> Creates a new span called "stock-counts"
<3> Adds a label, or tag, called "inventory.item" that will contain the value contained in `item`
<4> Same as `@SpanAttribute("inventory.store-name")`
<5> Same as `@WithSpan("warehouse-order")` with `@SpanAttributes` for item and count

=== Store Controller

This class demonstrates using the `io.micronaut.tracing.annotation` instead of the OpenTelemetry annotations.

[NOTE]
====
If you have the following dependency declared, all HTTP Server methods (those annotated with `@Get`, `@Post` and etc.) will create spans automatically.
dependency:micronaut-tracing-opentelemetry-http[groupId=io.micronaut.tracing]
====

source:StoreController[]
<1> Equivalent to `@WithSpan("store.order")`
<2> Same as `@SpanAttribute("order.item")`and `@SpanAttribute`
<3> Span created automatically if `micronaut-tracing-opentelemetry-http` is declared
<4> Annotation is ignored
<5> Tag is only added to the span if `micronaut-tracing-opentelemetry-http` is declared; otherwise ignored

=== Warehouse Client

You can also mix OpenTelemetry and Micronaut Tracing annotations in the same class.

[NOTE]
====
If you have the following dependency declared, all HTTP Client methods (those annotated with `@Get`, `@Post` and etc.) will create spans automatically.
dependency:micronaut-tracing-opentelemetry-http[groupId=io.micronaut.tracing]
====

source:WarehouseClient[]
<1> Some external service without Tracing





