common:completesolution.adoc[]

common:create-app-features.adoc[]

=== OpenTelemetry

The Micronaut framework uses https://opentelemetry.io/[OpenTelemetry] to generate and export tracing data.

OpenTelemetry provides two annotations: one to create a span and another to include additional information to the span.

@WithSpan:: Used on methods to create a new span; defaults to the method name, but a unique name may be assigned instead.

@SpanAttribute:: Used on method parameters to assign a value to a span; defaults to the parameter name, but a unique name may be assigned instead.

`@WithSpan` and `@SpanAttribute` can be used only on non-private methods.

If these annotations are not enough, or if you want to add tracing to a private method, the Micronaut framework’s tracing integration registers a `io.opentelemetry.api.trace.Tracer` bean, which exposes the OpenTelemetry API and can be dependency-injected as needed.

[NOTE]
====
The following `io.micronaut.tracing.annotation`s are available if you prefer to use them or if you are working on an existing Micronaut application that already uses them.

- `@NewSpan` : Identical to `@WithSpan`, it is used on methods to create a new span; defaults to the method name, but a unique name may be assigned instead.
- `@ContinueSpan` : Used on methods to continue an existing span; primarily used in conjunction with `@SpanTag`.
- `@SpanTag` : Similar to `@SpanAttribute`, it is used on method parameters to assign a value to a span; defaults to the parameter name, but a unique name may be assigned instead. To use the `@SpanTag` on a method argument, the method must be annotated with either `@NewSpan` or `@ContinueSpan`.
====

=== Inventory Service

source:InventoryService[]
<1> Inject Tracing bean into class
<2> Creates a new span called "stock-counts"
<3> Adds a label, or tag, called "inventory.item" that will contain the value contained in `item`
<4> Same as `@SpanAttribute("inventory.store-name")`
<5> Same as `@WithSpan("warehouse-order")` with `@SpanAttributes` for item and count

=== Store Controller

This class demonstrates use of the `io.micronaut.tracing.annotation` instead of the OpenTelemetry annotations.

[NOTE]
====
If you have the following dependency declared, all HTTP Server methods (those annotated with `@Get`, `@Post`, etc.) will create spans automatically.
dependency:micronaut-tracing-opentelemetry-http[groupId=io.micronaut.tracing]
====

source:StoreController[]
<1> Equivalent to `@WithSpan("store.order")`
<2> Same as `@SpanAttribute("order.item")`and `@SpanAttribute`
<3> Span created automatically if `micronaut-tracing-opentelemetry-http` is declared
<4> Required for `@SpanTag`
<5> Tag is only added to the span if `micronaut-tracing-opentelemetry-http` is declared; otherwise ignored

=== Warehouse Client

You can also mix OpenTelemetry and Micronaut Tracing annotations in the same class.

[NOTE]
====
If you have the following dependency declared, all HTTP Client methods (those annotated with `@Get`, `@Post`, etc.) will create spans automatically.
dependency:micronaut-tracing-opentelemetry-http[groupId=io.micronaut.tracing]
====

source:WarehouseClient[]
<1> Some external service without tracing

=== Warehouse Controller

The `WarehouseController` class represents external service that will be called by `WarehouseClient`.

source:WarehouseController[]
callout:executes-on[1]
callout:controller[number=2,arg0=/warehouse]
callout:get[number=3,arg0=getItemCount,arg1=/warehouse/count]
callout:get[number=4,arg0=order,arg1=/warehouse/order]
