common:header.adoc[]

You will use https://www.mongodb.com[MongoDB] for persistence.

common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app-features.adoc[]

=== POJO

Create `Fruit` POJO:

source:Fruit[]

callout:serdeable[]
callout:constraints[]
<3> Since the POJO does not have an empty constructor, use the annotations `@BsonCreator` and `BsonProperty` to define data conversion between BSON and POJO with the MongoDB Java driver. See https://docs.mongodb.com/drivers/java/sync/current/fundamentals/data-formats/pojo-customization/#pojos-without-no-argument-constructors[POJOs without No-Argument Constructor].
callout:creator[]

=== Repository

Create a repository interface to encapsulate the CRUD actions for `Fruit`.

source:FruitRepository[]

callout:valid[]

=== Controller

Create `FruitController`:

source:FruitController[]

callout:controller[arg0=/fruits]
callout:executes-on[]
callout:constructor-di[arg0=FruitRepository]
callout:get[arg0=list,arg1=/fruits]
callout:post[arg0=save,arg1=/fruits]
callout:at-status[]
callout:valid[]

=== Configuration

Create a configuration object to encapsulate the MongoDB database name and collection name.

source:MongoDbConfiguration[]

callout:configuration-properties[]

Define the values via configuration:


resource:application.properties[tag=db]

=== MongoDB repository

Implement `FruitRepository` by using a `MongoDbClient`

source:MongoDbFruitRepository[]

callout:singleton[]
callout:constructor-di[arg0=MongoDbConfiguration]
callout:constructor-di[arg0=MongoDbClient]

By using the feature `mongo-sync`, the application includes the following dependency:

dependency:micronaut-mongo-sync[groupId=io.micronaut.mongodb]

This registers a blocking https://mongodb.github.io/mongo-java-driver/4.0/apidocs/com/mongodb/client/MongoClient.html[MongoClient], which you can inject in other Micronaut beans as illustrated in the above code sample.

=== Test

Add a https://docs.micronaut.io/latest/guide/#httpClient[Micronaut declarative HTTP Client] to `src/test` to ease the testing of the application's API.

test:FruitClient[]

By using the feature `mongo-sync`, the application includes the following test dependencies:

:dependencies:
dependency:junit-jupiter[groupId=org.testcontainers,scope=test]
dependency:mongodb[groupId=org.testcontainers,scope=test]
dependency:testcontainers[groupId=org.testcontainers,scope=test]
:dependencies:

<<Test Resources>> will provide us with a MongoDB instance for local testing and execution.

Create a test:

test:FruitControllerTest[]

common:test-resources-mongodb.adoc[]

common:testApp.adoc[]

common:runapp.adoc[]

[source, bash]
----
curl -d '{"name":"Pear"}'
     -H "Content-Type: application/json"
     -X POST http://localhost:8080/fruits
----

[source, bash]
----
curl -i localhost:8080/fruits
----

[source]
----
HTTP/1.1 200 OK
date: Wed, 15 Sep 2021 12:40:15 GMT
Content-Type: application/json
content-length: 110
connection: keep-alive

[{"name":"Pear"}]
----

common:graal-with-plugins.adoc[]

:exclude-for-languages:groovy

Consume the endpoints exposed by the native executable with cURL:

:exclude-for-languages:

[source, bash]
----
curl -d '{"name":"Pear"}'
     -H "Content-Type: application/json"
     -X POST http://localhost:8080/fruits
----

[source, bash]
----
curl -i localhost:8080/fruits
----

[source]
----
HTTP/1.1 200 OK
date: Wed, 15 Sep 2021 12:40:15 GMT
Content-Type: application/json
content-length: 110
connection: keep-alive

[{"name":"Pear"}]
----

common:next.adoc[]

== Next Steps

Read more about the https://micronaut-projects.github.io/micronaut-mongodb/latest/guide/[integration between the Micronaut framework and MongoDB].

common:helpWithMicronaut.adoc[]
