micronaut:
  application:
    name: micronaut-guide
netty:
  default:
    allocator:
      max-order: 3
#tag::jpa[]
jpa:
  default:
    entity-scan:
      packages:
        - 'example.micronaut.domain' # <1>
    properties:
      hibernate:
        show-sql: true
        hbm2ddl:
          auto: none # <2>
        connection:
          url: ${JDBC_URL:`jdbc:mysql://localhost:3306/db`}
          username: ${JDBC_USER:root}
          password: ${JDBC_PASSWORD:my-secret-pw}
    reactive: true
#end::jpa[]
---
#tag::flyway[]
datasources:
  default:
    url: jdbc:mysql://localhost:5432/db  # <1>
    username: ${JDBC_USER:root}
    password: ${JDBC_PASSWORD:my-secret-pw}
    driverClassName: com.mysql.jdbc.Driver  # <2>
flyway:
  datasources:
    default:
      enabled: true # <1>
#end::flyway[]