micronaut:
  application:
    name: micronaut-guide
netty:
  default:
    allocator:
      max-order: 3
#tag::datasource[]
jpa:
  default:
    entity-scan:
      packages:
        - 'example.micronaut.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        connection:
          url: ${JDBC_URL:`jdbc:mysql://localhost:3306/db`}
          username: ${JDBC_USER:root}
          password: ${JDBC_PASSWORD:}
    reactive: true
#end::datasource[]
---
#tag::flyway[]
flyway:
  datasources:
    default:
      enabled: true # <1>
#end::flyway[]