micronaut:
  application:
    name: micronaut-guide
netty:
  default:
    allocator:
      max-order: 3
#tag::jpa[]
jpa:
  default:
    entity-scan:
      packages:
        - 'example.micronaut.domain' # <1>
    properties:
      hibernate:
        show-sql: true
        hbm2ddl:
          auto: update # <2>
        connection:
          db-type: mysql # <3>
    reactive: true
#end::jpa[]
