micronaut.application.name=micronaut-guide
#tag::static-resources[]
micronaut.router.static-resources.metainforesources.mapping=/**
micronaut.router.static-resources.metainforesources.paths=classpath:META-INF/resources
#end::static-resources[]
#tag::langchain4j[]
langchain4j.open-ai.api-key=${OPENAI_API_KEY:xxx}
langchain4j.open-ai.chat-model.model-name=gpt-4o
langchain4j.open-ai.chat-model.log-requests=true
langchain4j.open-ai.chat-model.log-responses=true
langchain4j.openai.chat-model.temperature=1.0
langchain4j.openai.chat-model.max-completion-tokens=1000
langchain4j.openai.chat-model.frequency-penalty=0
#end::langchain4j[]
