common:header-top.adoc[]

== Sample Project

You can link:@sourceDir@.zip[download a sample application] with the code examples shown in this article.

== Introduction

Both Spring and Micronaut frameworks are dependency injection engines. In this tutorial, we create a bean by "marking" a class as a bean.

== An Interface

With an interface such as:

source:Greeter[app=springboot]

We want to be able to inject a bean of the type `Greeter` into our application.

== Spring Boot @Component

In Spring, we can create an implementation and annotate it with `@Component`.

source:HelloGreeter[app=springboot]

callout:spring-at-component[1]

=== Spring Boot Test

The following test verify it is possible to inject a bean of type `Greeter` in a Spring Boot application.

test:GreeterTest[app=springboot]

callout:spring-boot-test[1]
callout:autowired[number=2,arg0=Greeter]

== Micronaut @Singleton

In Micronaut framework, we can create an implementation and annotate it with `@Singleton`.

source:HelloGreeter[app=micronautframework]

callout:singleton[1]

=== Micronaut Test

The following test verify it is possible to inject a bean of type `Greeter` in a Micronaut application.

test:GreeterTest[app=micronautframework]

callout:micronaut-test[1]
callout:injection[number=2,arg0=Greeter]

== Conclusion

This guide illustrate that marking a class as a bean is similar in both frameworks. Micronaut Framework uses the standard `jakarta.inject.Singleton` and annotation while Spring uses custom annotations.

NOTE: Micronaut Framework generates the necessary information to fulfill the injection points at compilation time.

WARNING: Spring relies on classpath scanning to find classes annotated with @Component. In the Spring Boot application, `HelloGreeter` is detected because the application contains an `Application` with the `@SpringBootApplication` annotation. The `@SpringBootApplication` annotation applies the `@ComponentScan` annotation, which tells Spring to scan the package where the `Application` class is located and its sub-packages

== Next steps

Read more https://guides.micronaut.io/latest/tag-spring_boot_to_micronaut.html[Spring Boot to Micronaut] guides.

common:helpWithMicronaut.adoc[]


