micronaut:
  application:
    name: micronautguide

  security:
    x509:
      enabled: true # <1>

  ssl:
    enabled: true # <2>

  server:
    ssl:
      client-authentication: want # <3>
      key-store:
        path: classpath:ssl/keystore.p12 # <4>
        password: # <5>
        type: PKCS12 # <6>
      trust-store:
        path: classpath:ssl/truststore.jks # <7>
        password: # <8>
        type: JKS # <9>
