micronaut:
  application:
    name: bookrecommendation # <1>
endpoints:
  health:
    enabled: true
    sensitive: false
---
#tag::oauth2[]
micronaut:
  security:
    oauth2:
      clients:
        auth0: # <1>
          client-id: '${OAUTH_CLIENT_ID:xxx}' # <2>
          client-secret: '${OAUTH_CLIENT_SECRET:yyy}' # <3>
          grant-type: 'client_credentials' # <4>
          token:
            url: '${OAUTH_TOKEN_URL:`https://micronautguides.eu.auth0.com/oauth/token`}' # <5>
            auth-method: 'client_secret_post' # <6>
          client-credentials:
            service-id-regex: 'bookcatalogue|bookinventory' # <7>
            additional-request-params:
              audience: '${AUTH0_API_IDENTIFIER:`https://micronautguides.eu.auth0.com/api/v2/`}' # <8>
#end::oauth2[]
