micronaut:
  application:
    name: micronautguide
  executors:
    io:
      type: fixed
      nThreads: 75
datasources:
  default:
    ocid: ocid1.autonomousdatabase.oc1.iad.abuwcl....replaceme # <1>
    walletPassword: replaceme # <2>
    username: micronautdemo
    password: replaceme # <3>
oci:
  config:
    profile: DEFAULT # <4>
flyway:
  datasources:
    default:
      enabled: true
