micronaut:
  application:
    name: micronautguide
  executors:
    io:
      type: fixed
      nThreads: 75 # <1>
datasources:
  default:
    # ocid: <2>
    # walletPassword: <3>
    username: micronautdemo
    password: # <4>
oci:
  config:
    profile: DEFAULT # <5>
flyway:
  datasources:
    default:
      enabled: true
