common:header.adoc[]

common:requirements.adoc[]

common:completesolution.adoc[]

common:test-resources-mosquitto.adoc[]

== Writing the CLI (Command Line Interface) Application

common:cli-or-launch.adoc[]

[source,bash]
----
mn @cli:cli-command@ example.micronaut.micronautguide \
    --features=@cli:features@ \
    --build=@build@ --lang=@lang@
----

common:build-lang-arguments.adoc[]

common:default-package.adoc[]

Rename this `micronautguide` directory to `cli`.

If you use Micronaut Launch, select Micronaut Application as application type and add @cli:features-words@ features.

common:diff.adoc[]

diffLink:[app=cli]

https://guides.micronaut.io/latest/micronaut-intellij-idea-ide-setup.html[Setup IntelliJ IDEA to develop Micronaut Applications].

=== Create an MqttPublisher

Create an interface to publish MQTT topics:

source:TemperatureClient[app=cli]
callout:mqtt-publisher[]
callout:mqtt-topic[]

=== Writing the CLI Command

Create an enum to allow the user to submit temperatures in Celsius or Fahrenheit:

source:Scale[app=cli]

Create a class to show completion candidates:

source:TemperatureScaleCandidates[app=cli]

Replace the command:

source:MicronautguideCommand[app=cli]

:exclude-for-languages:python
callout:picocli-command[]
callout:picocli-option[]
callout:picocli-option-required[]
callout:picocli-completion-candidates-variables[]
callout:field-injection[]
<6> Publish the MQTT topic.
:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin
<1> Inject the MQTT publisher.
<2> Publish the MQTT topic.
:exclude-for-languages:

Replace the generated test with this:

:exclude-for-languages:python
test:MicronautguideCommandTest[app=cli]

callout:mqtt-subscriber[]
callout:mqtt-topic-listen[]
:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin
source:TemperatureListener[app=cli]

callout:mqtt-subscriber[]
callout:mqtt-topic-listen[]

test:MicronautguideCommandTest[app=cli]
:exclude-for-languages:

The MQTT server URI is configured by referencing the properties that were set up for Mosquitto via <<test-resources,Test Resources>>:


:exclude-for-languages:python
resource:application.properties[app=cli,tag=mqtt]
:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin
resource:application.toml[app=cli,tag=mqtt]
:exclude-for-languages:

== Writing an MQTT Subscriber Application

common:cli-or-launch.adoc[]

[source,bash]
----
mn @app:cli-command@ example.micronaut.micronautguide \
    --features=@app:features@ \
    --build=@build@ --lang=@lang@
----

common:build-lang-arguments.adoc[]

common:default-package.adoc[]

Rename this `micronautguide` directory to `app`.

If you use Micronaut Launch, select Micronaut Application as application type and add @app:features-words@ features.

common:diff.adoc[]

diffLink:[app=app]

https://guides.micronaut.io/latest/micronaut-intellij-idea-ide-setup.html[Setup IntelliJ IDEA to develop Micronaut Applications].

=== Configuration

The MQTT server URI is configured by referencing the properties that were set up for Mosquitto via <<test-resources,Test Resources>>:

:exclude-for-languages:python
resource:application.properties[app=app,tag=mqtt]
:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin
resource:application.toml[app=app,tag=mqtt]
:exclude-for-languages:

=== Create Subscriber

source:TemperatureListener[app=app]

callout:mqtt-subscriber[]
callout:mqtt-topic[]

=== Add test

:exclude-for-languages:python
test:SubscriptionTest[app=app]
callout:micronaut-test[]
callout:property[]
callout:requires-property[]
callout:mqtt-publisher[]
callout:mqtt-topic[]
:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin
source:TemperatureClient[app=app]
<1> This bean will only be loaded for the test.
callout:mqtt-publisher[]
callout:mqtt-topic[]

test:SubscriptionTest[app=app]
callout:micronaut-test[]
callout:property[]
:exclude-for-languages:

== Running the Application

=== Run the Subscriber App

common:runapp-instructions.adoc[]

Keep it running. Once you publish a topic with the CLI application, you will see a log entry.

=== Run the CLI

Run the CLI command, which will publish a temperature at startup.

:exclude-for-languages:python

[source, bash]
----
./gradlew run --args="-t 212 -s Fahrenheit"
----

:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin

[source, bash]
----
pyronaut run -- -t 212 -s Fahrenheit
----

:exclude-for-languages:

The subscriber receives the MQTT topic, as you will see in the logs:

[source, bash]
----
12:09:47.280 [MQTT Call: 180d98b5-75b9-41be-a874-295289346592]
    INFO  e.micronaut.TemperatureListener - temperature: 100.00

----

common:graal-with-plugins.adoc[]

:exclude-for-languages:groovy,python

Generate GraalVM native executables for both the CLI and the messaging application, then execute both. Publish a temperature, and you will see it in the subscriber logs.

:exclude-for-languages:


== Next Steps

Read more about https://micronaut-projects.github.io/micronaut-mqtt/latest/guide/[Micronaut MQTT].

common:helpWithMicronaut.adoc[]
