common:header.adoc[]

common:requirements.adoc[]

common:completesolution.adoc[]

common:test-resources-hivemq.adoc[]

== Writing the CLI (Command Line Interface) Application

common:cli-or-launch.adoc[]

[source,bash]
----
mn @cli:cli-command@ example.micronaut.micronautguide \
    --features=@cli:features@ \
    --build=@build@ --lang=@lang@
----

common:build-lang-arguments.adoc[]

common:default-package.adoc[]

Rename this `micronautguide` directory to `cli`.

If you use Micronaut Launch, select Micronaut Application as application type and add @cli:features-words@ features.

diffLink:[app=cli]

common:annotationprocessors.adoc[]

### Create an MqttPublisher

Create an interface to publish MQTT Topics:

source:TemperatureClient[app=cli]
callout:mqtt-publisher[1]
callout:mqtt-topic[2]

### Writing the CLI Command

Create an enum to allow the user to submit temperatures in Celsius or Fahrenheit:

source:Scale[app=cli]

Create a class to show completion candidates:

source:TemperatureScaleCandidates[app=cli]

Replace the command:

source:MicronautguideCommand[app=cli]

callout:picocli-command[1]
callout:picocli-option[2]
callout:picocli-option-required[3]
callout:picocli-completion-candidates-variables[4]
callout:field-injection[5]
<6> Publish the MQTT Topic

Replace the generated test with this:

test:MicronautguideCommandTest[app=cli]

Configure the MQTT server URI in configuration:

resource:application.yml[app=cli,tag=mqtt]

## Writing an MQTT subscriber application

common:cli-or-launch.adoc[]

[source,bash]
----
mn @app:cli-command@ example.micronaut.micronautguide \
    --features=@app:features@ \
    --build=@build@ --lang=@lang@
----

common:build-lang-arguments.adoc[]

common:default-package.adoc[]

If you use Micronaut Launch, select Micronaut Application as application type and add @app:features-words@ features.

diffLink:[app=cli]

common:annotationprocessors.adoc[]

### Configuration

Configure the MQTT server URI in configuration:

resource:application.yml[app=app,tag=mqtt]

### Create Subscriber

source:TemperatureListener[app=app]

callout:mqtt-subscriber[1]
callout:mqtt-topic[2]

== Run both applications

=== Run the Subscriber App

common:runapp-instructions.adoc[]

Keep it running. Once you publish a topic with the CLI application, you will see a log entry.

=== Run the CLI

==== Generate a JAR

common:shade[]

Run the CLI command, which will publish a temperature at startup.

[source, bash]
----
java -jar build/libs/micronautguide-0.1-all.jar -t 212 -s Fahrenheit
12:00:49.668 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [cli]
12:00:50.557 [main] TRACE i.m.m.i.AbstractMqttIntroductionAdvice - Publishing the following message to house/livingroom/temperature
12:00:50.558 [main] TRACE i.m.m.i.AbstractMqttIntroductionAdvice - Qos = 1, Retained = false, Payload = 100.00
Topic published
----

The subscriber receives the MQTT topics, as you will see in the logs:

[source, bash]
----
12:09:47.280 [MQTT Call: 180d98b5-75b9-41be-a874-295289346592]
    INFO  e.micronaut.TemperatureListener - temperature: 100.00

----

common:graal-with-plugins.adoc[]

:exclude-for-languages:groovy

Generate GraalVM native executables for both the CLI and the messaging application, then execute both. Publish a temperature, and you will see it in the subscriber logs.

:exclude-for-languages:


== Next steps

Read more about https://micronaut-projects.github.io/micronaut-mqtt/latest/guide/[Micronaut MQTT].

common:helpWithMicronaut.adoc[]
