micronaut:
  application:
    name: bookinventory
  server:
    port: 8082
endpoints:
  health:
    enabled: true
    sensitive: false
#tag::zipkin[]
otel:
  traces:
    exporter: zipkin
#end::zipkin[]