common:header.adoc[]

common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app-features.adoc[]

=== Dependency

In this guide, to render XML, we use https://micronaut-projects.github.io/micronaut-jackson-xml/latest/guide[Micronaut Jackson XML]. Add the following dependency:

dependency:micronaut-jackson-xml[groupId=io.micronaut.xml]

WARNING: https://micronaut-projects.github.io/micronaut-serialization/latest/guide[Micronaut Serialization] doesn't currently support XML

=== Book Record

Create a record for the XML model.

source:Book[]
callout:introspected[1]
<2> `@JacksonXmlRootElement` annotation defines the name of root element used for the root-level object when serialized.
<3> `@JacksonXmlProperty` annotation provides XML-specific configuration for properties.

=== Book Controller
Create a controller which returns a `Book` instance.

source:BookController[]

callout:controller[number=1,arg0=/book]
callout:produces-xml[2]
callout:get-generic[3]

== Tests
Create a test which verifies tha the controller returns XML.

test:BookControllerTest[]

callout:micronaut-test[1]
callout:http-client[2]
callout:http-request[3]

common:testApp.adoc[]

common:nativetest.adoc[]

common:graal-with-plugins.adoc[]

:exclude-for-languages:groovy

You can execute the `÷books` endpoint exposed by the native executable:

[source, bash]
----
curl localhost:8080/book
----

[source,xml]
----
<book isbn="1491950358"><name>Building Microservices</name></book>
----

:exclude-for-languages:groovy

common:next.adoc[]

Learn more about https://micronaut-projects.github.io/micronaut-jackson-xml/latest/guide/index.html[Micronaut Jackson XML].

common:helpWithMicronaut.adoc[]

https://micronaut-projects.github.io/micronaut-jackson-xml/latest/guide/index.html