common:header-top.adoc[]

== Getting Started

In this guide, you will use Micronaut caching annotations to speed up your application.

common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app.adoc[]

=== Configure the Application

In this sample application, you cache news headlines. Add the https://micronaut-projects.github.io/micronaut-cache/latest/guide/[Micronaut Caffeine Cache] dependency, which adds support for caching with https://github.com/ben-manes/caffeine[Caffeine].

dependency:micronaut-cache-caffeine[groupId=io.micronaut.cache]

:exclude-for-languages:python
Configure your caches in `application.properties`:

resource:application.properties[tag=config]
:exclude-for-languages:
:only-for-languages:python
Configure your caches in `application.toml`:

resource:application.toml[tag=config]
:only-for-languages:

<1> Configure a cache called `headlines`.

TIP: Check the https://micronaut-projects.github.io/micronaut-cache/latest/guide/configurationreference.html#io.micronaut.cache.caffeine.DefaultCacheConfiguration[properties (`maximum-size`, `expire-after-write` and `expire-after-access`)] to configure the size and expiration of your caches. It is important to keep the caches' size under control.

=== Micronaut Cache API

Imagine a service that retrieves headlines for a given month. This operation may be expensive, and you may want to cache it.

source:NewsService[]

callout:singleton[]
<.> Specifies the cache name `headlines` to store cache operation values in.
<.> Indicates a method is cacheable. The cache name `headlines` specified in `@CacheConfig` is used. Since the method has only one parameter, you don't need to specify the `month` `parameters` attribute of the annotation.
<.> Emulate an expensive operation by sleeping for several seconds.
<.> The return value is cached with name `headlines` for the supplied `month`. The method invocation is never skipped even if the cache `headlines` for the supplied `month` already exists.
<.> Method invocation causes the invalidation of the cache `headlines` for the supplied `month`.

TIP: If you don't annotate the class with `@CacheConfig`, specify the cache name in the cache annotations. E.g. `@Cacheable(value = "headlines", parameters = {"month"})`

=== Test the Cache

You can verify that the cache works as expected:

test:NewsServiceTest[]

:exclude-for-languages:python
callout:test-method-order[]
:exclude-for-languages:
callout:micronaut-test[]
<.> Inject `NewsService` bean.
:exclude-for-languages:python
callout:timeout[]
:exclude-for-languages:groovy,python
callout:order[]
:exclude-for-languages:

=== Controller

:exclude-for-languages:python
Create a controller that uses the previous service:
:exclude-for-languages:
:only-for-languages:python
Create a route that uses the previous service:
:only-for-languages:

source:News[]

callout:serdeable[]

source:NewsController[]

:exclude-for-languages:python
callout:controller[arg0=/]
:exclude-for-languages:
:only-for-languages:python
<1> Maps GET requests to `/{month}`.
:only-for-languages:

Add a test:

test:NewsControllerTest[]

:exclude-for-languages:python
<1> Call the endpoint twice and verify with the `@Timeout` annotation that the cache is being used.
:exclude-for-languages:
:only-for-languages:python
<1> Call the endpoint twice and verify that the cached response is reused.
:only-for-languages:

common:runapp.adoc[]

common:graal-with-plugins.adoc[]

:exclude-for-languages:groovy

You should be able to execute this curl request and see results:

[source,bash]
----
curl localhost:8080/NOVEMBER
----

:exclude-for-languages:

== Next Steps

Read about Micronaut https://docs.micronaut.io/latest/guide/#caching[Cache Advice].
Also, check the https://micronaut-projects.github.io/micronaut-cache/latest/guide/[Micronaut Cache] project for more information.

common:helpWithMicronaut.adoc[]
