common:header-top.adoc[]

== Sample Project

You can link:@sourceDir@.zip[download a sample application] with the code examples shown in this article.

== Introduction

Both Spring and Micronaut frameworks are dependency injection engines. In this tutorial, we will manually create a bean, a class managed by the bean context.

== An Interface and an Implementation

With an interface such as:

source:Greeter[app=springboot]

and an implementation such as:

source:HelloGreeter[app=springboot]

We want to be able to inject a bean of the type `Greeter` into our application.

There are several ways to do it. In this tutorial, we will manually instantiate the bean in both frameworks.

== Spring @Configuration

Create a https://docs.spring.io/spring-framework/reference/core/beans/java/configuration-annotation.html[`@Configuration` class] to declare `Greeter` bean through a @Bean-annotated method.

source:GreeterFactory[app=springboot]

callout:spring-at-configuration[]

=== Spring Boot Test

The following test verify it is possible to inject a bean of type `Greeter` in a Spring Boot application.

test:GreeterTest[app=springboot]

callout:spring-boot-test[]
callout:autowired[arg0=Greeter]

== Micronaut @Factory

source:GreeterFactory[app=micronautframework]

callout:at-factory[]

=== Micronaut Test

The following test verify it is possible to inject a bean of type `Greeter` in a Micronaut application.

test:GreeterTest[app=micronautframework]

callout:micronaut-test[]
callout:injection[arg0=Greeter]

== Conclusion

This guide illustrate that the APIs `@Configuration` and `@Factory` of both frameworks are almost identical.


== Next steps

Read more https://guides.micronaut.io/latest/tag-spring_boot_to_micronaut.html[Spring Boot to Micronaut] guides.

common:helpWithMicronaut.adoc[]


