common:header.adoc[]

common:requirements.adoc[]

common:completesolution.adoc[]

common:many-to-many.adoc[]

common:create-app-features.adoc[]

common:default-package.adoc[]

common:diff.adoc[]

common:micronaut-data-jdbc.adoc[]

common:mysql-driver.adoc[]

common:datasource-configuration-mysql.adoc[]

common:liquibase.adoc[]

resource:db/changelog/01-schema.xml[]

=== Entities

==== User

source:UserEntity[]

callout:mapped-entity[]
callout:mapped-entity-id[]
callout:generated-value[]
callout:constraints[]

==== Role

Create `Role` domain class to store authorities within our application.

source:Role[]

callout:mapped-entity[]
callout:mapped-entity-id[]
callout:generated-value[]
callout:constraints[]

==== UserRole

Create a `UserRole` which stores a many-to-many relationship between `User` and `Role`.

source:UserRole[]

callout:mapped-entity[]
callout:embeddedid[]

source:UserRoleId[]

callout:embeddable[]
callout:relation[]

=== Projection

Create `User` record which represents and user and his assigned roles.

source:User[]

callout:introspected[]

=== JDBC Repositories

Create various JDBC Repositories:

==== User Repository

source:UserJdbcRepository[]

callout:jdbcrepository[]
callout:crudrepository[]
callout:at-query[]

==== Role Repository

source:RoleJdbcRepository[]

callout:jdbcrepository[]
callout:crudrepository[]

==== UserRole Repository

source:UserRoleJdbcRepository[]

callout:jdbcrepository[]
callout:crudrepository[]
callout:at-query[]

common:quotedomainclass.adoc[]

=== Test

Add a test that verifies the many-to-many relationship:

test:ManyToManyTest[]

callout:micronaut-test-start-application-false[]

common:testApp.adoc[]

common:nativetest.adoc[]

common:next.adoc[]
