[micronaut.application]
name = "micronautguide"

# tag::static-resources[]
# <1>
[micronaut.router.static-resources.default]
enabled = true
mapping = "/**"
paths = ["classpath:public"]
# end::static-resources[]
