micronaut:
  application:
    name: micronautguide
---
#tag::datasource[]
datasources:
  default:
    driverClassName: org.postgresql.Driver  # <1>
    dialect: POSTGRES # <2>
    schema-generate: NONE # <3>
#end::datasource[]
---
#tag::liquibase[]
liquibase:
  enabled: true
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'
#end::liquibase[]
---
#tag::endpoints[]
endpoints:
  liquibase:
    enabled: true
    sensitive: false
#end::endpoints[]
