[micronaut.application]
name = "micronautguide"

[netty.default.allocator]
max-order = 3

#tag::micronaut-email[]
[micronaut.email.from]
# <1>
email = "${FROM_EMAIL:noreply@test.com}"
# <2>
name = "${FROM_NAME:noreply}"
#end::micronaut-email[]

#tag::smtp[]
[smtp]
# <1>
password = "${SMTP_PASSWORD:password}"
# <2>
user = "${SMTP_USER:user}"
#end::smtp[]

#tag::javamail[]
[javamail.properties.mail.smtp]
port = 587
auth = true
starttls.enable = true
# <1>
host = "${SMTP_HOST:smtp.email.us-ashburn-1.oci.oraclecloud.com}"
#end::javamail[]
