micronaut:
  application:
    name: micronautguide
#tag::cors[]
---
micronaut:
  server:
    cors:
      enabled: true
#end::cors[]
#tag::corsconfigurations[]
      configurations:
        ui:
          allowed-origins:
            - http://127.0.0.1:8000
#end::corsconfigurations[]