micronaut:
  application:
    name: bookinventory
endpoints:
  health:
    enabled: true
    sensitive: false
#tag::otel[]
otel:
  traces:
    exporter: otlp
    propagator: tracecontext, baggage, xray
    exclusions: /health
#end::otel[]
#tag::dynamodb[]
dynamodb:
  table-name: 'bookcatalogue'
#end::dynamodb[]