[micronaut.application]
name = "bookinventory"

[micronaut.server]
port = 8082

[endpoints.health]
enabled = true
sensitive = false

#tag::jaeger[]
[tracing.jaeger]
enabled = true

[tracing.jaeger.sampler]
# <1>
probability = 1
#end::jaeger[]
