micronaut.application.name=micronautguide
#tag::liquibase[]
liquibase.datasources.default.change-log=classpath\:db/liquibase-changelog.xml
#end::liquibase[]
#tag::datasource[]
datasources.default.schema-generate=NONE
# <1>
datasources.default.driver-class-name=oracle.jdbc.OracleDriver
# <2>
datasources.default.db-type=oracle
# <3>
datasources.default.dialect=ORACLE
#end::datasource[]