common:header-top.adoc[]

== Getting Started

In this guide we will generate a client API from an https://www.openapis.org[OpenAPI] definition file.

____
OpenAPI Generator allows generation of API client libraries (SDK generation), server stubs, documentation and configuration automatically given an OpenAPI Spec (both 2.0 and 3.0 are supported).
____

Then we will use the client inside the application.
We will generate the client for link:https://developer.twitter.com/en/docs/twitter-api[Twitter API], however the steps
could easily be replicated with any other API with an OpenAPI definition.

common:requirements.adoc[]

common:completesolution.adoc[]

common:install-openapi-generator.adoc[]

== Generating the Micronaut Client

We will generate a client for link:https://developer.twitter.com/en/docs/twitter-api[Twitter API].

To do this, we will need to download the official Twitter API OpenAPI definition file: link:https://api.twitter.com/2/openapi.json[https://api.twitter.com/2/openapi.json].
Download it as `twitter-api-definition.json` and move into the directory that you intend to use for the project.

To generate the Micronaut client from the JSON definition, open the terminal in the directory where the definition file and
the OpenAPI generator executable are located, and run:

[source,bash]
----
java -jar openapi-generator-cli-5.4.0.jar generate \
    -g java-micronaut-client \# <1>
    -i twitter-api-definition.json \# <2>
    -o ./ \# <3>
    -p apiPackage=example.micronaut.api \# <4>
    -p modelPackage=example.micronaut.model \# <5>
    -p build=@build@ \# <6>
    -p test=junit# <7>
----
<1> Specify that we will use the Java Micronaut client generator.
<2> Specify our OpenAPI definition file as `twitter-api-definition.json`.
<3> Specify the output directory to be the current directory (`./`).
You can specify it to be a different one if you want.
<4> We provide generator-specific properties starting with `-p`.
We want all the api files to be generated in the `example.twitter.api` package.
<5> We want all the models to be in the `example.twitter.model` package.
In this package classes for data models, that are used for communication with server will be generated.
<6> We want to use @build@ as build tool. The supported values are `gradle`, `maven` and `all`.
If nothing is specified, both Maven and Gradle files are generated.
<7> We want to use JUnit 5 for testing. The supported values are `junit` (JUnit 5) and `spock`.
If nothing is specified, `junit` is used by default.

After generation finishes, you should see the following directory structure:
[source,text]
----
./
├── docs
│   └── ... # <1>
├── src/
│   ├── main/
│   │   ├── java/
│   │   │   └── example/twitter/
│   │   │       ├── api # <2>
│   │   │       │   ├── GeneralApi.java
│   │   │       │   ├── SpacesApi.java
│   │   │       │   ├── TweetsApi.java
│   │   │       │   └── UsersApi.java
│   │   │       └── model # <3>
│   │   │           ├── ...
│   │   │           ├── Tweet.java
│   │   │           ├── TweetSearchResponse.java
│   │   │           ├── User.java
│   │   │           └── ...
│   │   └── resources/
│   │       ├── application.yml # <4>
│   │       └── logback.xml
│   └── test/
│       └── java/
│           └── example/twitter/ # <5>
│               ├── api
│               │   ├── GeneralApiTest.java
│               │   ├── SpacesApiTest.java
│               │   ├── TweetsApiTest.java
│               │   └── UsersApiTest.java
│               └── model
│                   └── ...
├── README.md
└── ...
----
<1> The `docs/` directory contains automatically generated Markdown files with documentation about your API.
<2> The `example.twitter.api` package contains API classes.
<3> The `example.twitter.model` package contains data classes, that are used in parameters or bodies of both
requests and responses in the API.
<4> The `application.yml` file contains the configuration of your Micronaut application. We will modify it later.
<5> Templates for tests are generated. Test files for both APIs and models were created.

[NOTE]
====
The definition file is a document describing the Twitter API according to the link:https://swagger.io/specification/[OpenAPI Specification].

If you want to learn about the structure of OpenAPI specification and how to simplify the creation of a Micronaut Server
with it, read the link:https://guides.micronaut.io/latest/micronaut-openapi-generator-server.html["Use OpenAPI Defintion to Generate a Micronaut Server" guide]
or the link:https://swagger.io/docs/specification/about/[OpenAPI guide].
====

As you can see, four API files were generated for the Twitter API.

If you look inside the API files, you will see that method definitions were generated corresponding to different
paths and operations available in the API. Using Micronaut`s features, we will be able to inject a client implementation
of this interface and use it by calling the corresponding methods without the need to worry how client-server communication
is handled.

[NOTE]
=========
If you want to view all the available parameters for micronaut server generator, run
[source,bash]
----
java -jar openapi-generator-cli-5.4.0.jar config-help \
-g java-micronaut-client
----
=========

== Configure Client Authorization

In order to send requests to an API, you might be required to configure Authorization.

=== Create Twitter Development Account

In case of Twitter, we need to configure OAuth2 authorization. You can authorize with an API key
via the OAuth2 authorization code flow or using a Bearer token.

We will use the API key option. To get your API key, you will need to sign up for a Twitter developer account.
To do this, follow the first 2 steps on the
link:https://developer.twitter.com/en/docs/twitter-api/getting-started/getting-access-to-the-twitter-api["Getting Access to the Twitter API"] guide.
Do not forget to save your `API key` and `API secret` values somewhere.

[NOTE]
====
You can read about Twitter OAuth2 authentication in the link:https://developer.twitter.com/en/docs/authentication/oauth-2-0["Authorization" page of Twitter API documentation].
The documentation specifies link:https://developer.twitter.com/en/docs/authentication/oauth-2-0/application-only[authentication with Bearer token]
and link:https://developer.twitter.com/en/docs/authentication/oauth-2-0/bearer-tokens[using an API key].
====

[NOTE]
====
If you forgot to save your `API key` and `API secret`, open the settings for your application (inside project settings)
on the Twitter Developer Portal, find the `Keys and tokens` tab, find the `API key and secret` section and click `Regenerate`
to retrieve a new pair of keys.
====

=== Configure Authorization for Micronaut Client

We will modify the `application.yml` to include the following configuration:
resource:application.yml[tag=authorization]
<1> We add a value to the `miconaut.security.oauth2.clients`. We will add it with the key of `twitter`.
<2> Set the authorization flow to `client_secret_basic`. This authorization was created for applications that need
to access the resources on behalf of itself and requires an `id` and a `secret` parameter, and a token url.
<3> Specify the url for retrieving tokens. We found it in the Twitter documentation.
<4> Specify the `client-id` and `client-secret` parameters. You could directly put your id and secret directly as values
in the configuration, however this highly discouraged due to security concerns. We will point to environment variables
instead.

Before running the application we will need to set the values of `client-id` and `client-secret` using environment
variables. To do it, paste your `API key` and `API secret` into the following command and run in terminal:
[source,bash]
----
export TWITTER_AUTH_CLIENT_ID=XXXXXXXXXXXXXXXXXXXXXXXXX
export TWITTER_AUTH_CLIENT_SECRET=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
----

[NOTE]
Do not forget to add these lines before running any tests or application. If you are using an IDE, there probably should
be an option to add environment variables in the run settings. View the documentation of your specific IDE for details.

Now, the client should authenticate correctly, and we will be able to send requests.

== Testing the Client

You can see that four APIs were generated in the project. These APIs have paths logically distributed between them.
You can look at link:https://developer.twitter.com/en/docs/twitter-api[Twitter API v2] documentation for description on
each of the paths, and notice that the sections are also logically split into `Tweets`, `Users` and `Spaces`, as well.

We will show how we can use the Twitter API by writing some simple tests using the generated Micronaut client.
First, we will use the link:https://developer.twitter.com/en/docs/twitter-api/tweets/counts/introduction[recent tweet counts API]
to get the number of tweets about Toronto in the last 7 days. Open the `TweetsApiTest` and paste the following:

test:../twitter/api/TweetsApiTest[tags=imports|class-begin|test-1|class-end]
<1> Annotating the test with `@MicronautTest` will create a Micronaut context and allows using various Micronaut
features, like injection.
<2> We will inject an implementation of the `TweetsApi` to use in our tests.
<3> Use the `api` to send a request to an API path for counting tweets with a specific query.
We will count tweets that mentioned `"Toronto"`.
<4> We will verify that the data is present. Using manipulations with the generated data models we will calculate
the total number of tweets and verify that there are at least 100 (which reasonably should be always true).

Now, we will test receiving the latest 10 tweets about New York City (NYC). We will use the
link:https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/quick-start[recent tweets lookup API].
To test the data models, we will get multiple properties of the tweet, and also properties of the user
who posted it. We will add the following test to the `TwetsApiTest` class:
test:../twitter/api/TweetsApiTest[tags=test-2]
<1> Set the search query to `"nyc"`.
<2> Expand the query on the `author_id` property to additionally get information about the user based on their id.
You can read about expanding in the link:https://developer.twitter.com/en/docs/twitter-api/expansions[Twitter API expansions documentation page].
<3> Specify the fields we want to get for each tweet.
<4> Specify the fields we want to get for users (authors of tweets).
<5> Retrieve the response from server.
<6> Get all the tweets from the response and verify that some common properties are present.
<7> Get users form a separate property of the response and verify that the information is present.

Finally, we will test getting multiple pages using the same
link:https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/quick-start[recent tweets lookup API]:
test:../twitter/api/TweetsApiTest[tags=test-3]
<1> Retrieve the first 10 tweets that match our query.
<2> Retrieve the next 10 tweets that match the query using the `nextToken` parameter.
<3> Verify that the no tweets on the 2 pages match.

We will now proceed to use the API in a simple application. However, you would probably want to also implement
tests for all other paths of the API, that you were planning to use in your application.

common:testApp-noheader.adoc[]

All the tests should run successfully.

== Using Client in a Controller

We will now write a controller, that will search for most-frequent words in the latest tweets on
a given topic.

=== Creating an Introspected Class

We will first define an object to represent the response. Create a file for `WordFrequency` class, that will have the word
itself, and the number it occurred as properties:
source:model/WordFrequency[]
<1> Annotate the model with the `@Introspected` annotation. This will allow Micronaut to use many features, like
automatically convert it to JSON in response.
<2> Define the 2 required properties and create getters for them.

=== Implementing the Controller

We will create the API of the controller. It will use the generated `TweetApi` client, and the `WordFrequency`
class, which we just created.
source:controller/TwitterFrequentWordsController[tags=imporst|class-start|api|class-end]
<1> Use the Micronaut link:https://docs.micronaut.io/latest/guide/#httpServer[Controller] annotation
to define a controller. The controller will automatically start when Micronaut application is run. Set the controller
to listen for requests on the `/twitter-frequent-words` path.
<2> Use Micronaut's link:https://docs.micronaut.io/latest/guide/#ioc[constructor injection] to inject an implementation
of the `TweetApi`.
<3> Define a get method on the path.
<4> Specify that the method requires 2 parameters: a query to search the tweets by, and the number of most frequent words to
return.
<5> Make a request to the tweeter api and process the data using a function that we will implement next. Note that
no blocking operations should be performed in the method, therefore we manipulate the reactor's link:https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html[Flux]
object and return it as a response.

Now add the method responsible for processing the data to the controller. There is no need to get into the details of its
implementation, but we will leave some description for a curious reader:
source:controller/TwitterFrequentWordsController[tags=method]
<1> Create a `Map` to store the number of occurrences for each of the words.
<2> Split the text of tweets on words (we will split by any non-alphabetic character), filter out all words shorter than
four characters to remove articles and increment the counter for each word in the `Map`.
<3> Sort the words by the number of occurrences, limit the number by certain amount,
and convert the result to a list with instances of `WordFrequency`.

common:runapp.adoc[]

You can send a few requests to the path to test the application. We will use cURL for that.

* The search for `20` most frequent words in tweets about `"Ukraine"` returns words representing
relevant topics at the time (beginning of 2022):
+
[source,bash]
----
curl -i 'localhost:8080/twitter-frequent-words?words-n=20&search-query=Ukraine'
----
+
[source,json]
----
[
  {"word": "ukraine","numberOccurred": 40}, {"word": "https",    "numberOccurred": 15},
  {"word": "russian","numberOccurred": 12}, {"word": "with",     "numberOccurred": 9},
  {"word": "russia", "numberOccurred": 9},  {"word": "invasion", "numberOccurred": 7},
  {"word": "from",   "numberOccurred": 6},  {"word": "india",    "numberOccurred": 5},
  {"word": "that",   "numberOccurred": 5},  {"word": "about",    "numberOccurred": 5},
  {"word": "border", "numberOccurred": 4},  {"word": "army",     "numberOccurred": 4},
  {"word": "putin",  "numberOccurred": 4},  {"word": "people",   "numberOccurred": 4},
  {"word": "forces", "numberOccurred": 4},  {"word": "troops",   "numberOccurred": 4},
  {"word": "their",  "numberOccurred": 4},  {"word": "will",     "numberOccurred": 4},
  {"word": "biden",  "numberOccurred": 4},  {"word": "just",     "numberOccurred": 3}
]
----

* The results of search for `10` most common words in tweets containing substring `"farm"` also seem to be reasonable:
+
[source,bash]
----
curl -i 'localhost:8081/twitter-frequent-words?words-n=10&search-query=farm'
----
+
[source,json]
----
[
  {"word": "farm",      "numberOccurred": 47}, {"word": "workers",   "numberOccurred": 17},
  {"word": "https",     "numberOccurred": 16}, {"word": "hello",     "numberOccurred": 10},
  {"word": "animal",    "numberOccurred": 9},  {"word": "redvelvet", "numberOccurred": 9},
  {"word": "those",     "numberOccurred": 7},  {"word": "their",     "numberOccurred": 7},
  {"word": "temporary", "numberOccurred": 6},  {"word": "revi",      "numberOccurred": 6}
]
----

It is also highly recommended, that you implement tests for all the controllers you write, but we will skip it in
this guide.

common:graal-with-plugins.adoc[]

== Next Steps

=== Learn How to Write OpenAPI Definition and Generate Server Based on It
Read the link:https://guides.micronaut.io/latest/micronaut-openapi-generator-server.html["Use OpenAPI Definition to Generate a Micronaut Server" Guide]
to learn:

* how you can understand OpenAPI definition files and write your own definition files,
* generate server API based on the definitions,
* implement the functionality of the server based on the API and write comprehensive tests utilizing
Micronaut`s features.

=== Learn Micronaut

To learn more about Micronaut framework and its features visit
link:https://micronaut.io/docs/[Micronaut documentation] or read one of the several
link:https://micronaut.io/guides/[Micronaut guides].




