common:header.adoc[]

common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app-features.adoc[]

:exclude-for-languages:python
== OpenPDF

To generate PDFs, we use https://github.com/LibrePDF/OpenPDF[OpenPDF].

____
OpenPDF is a Java library for creating and editing PDF files with a LGPL and MPL open source license. OpenPDF is the LGPL/MPL open source successor of iText, and is based on some forks of iText 4 svn tag. We welcome contributions from other developers. Please feel free to submit pull-requests and bug reports to this GitHub repository.
____

=== OpenPDF Dependency

To use OpenPDF, add the following dependency:

dependency:openpdf[groupId=com.github.librepdf,scope=implementation,version=@openpdfVersion@]
:exclude-for-languages:

:only-for-languages:python
== Python PDF Libraries

Use https://pdfme.readthedocs.io/en/latest/modules/pdf.html[pdfme] to generate the PDF and https://pypdf.readthedocs.io/[pypdf] to verify its text in the test. `pdfme` writes to a file-like object, so the controller can return the generated bytes while Micronaut continues to handle routing, the response, and the blocking executor.

`pdfme` 0.5.0 is MIT-licensed and marked as beta by its project. Review its https://pypi.org/project/pdfme/[release information] before choosing it for production applications. This example creates a text-only document; embedding PNG images requires Pillow.

Add `pdfme==0.5.0` and `pypdf==6.19.0` to `requirements.txt`, then install the dependencies in your application's virtual environment:

[source,bash]
----
pip install -r requirements.txt
----

zipInclude:requirements.txt[]
:only-for-languages:

== Controller

Create a controller that generates and downloads a PDF.

source:PDFController[]
callout:controller[arg0=/pdf]
callout:executes-on[]
callout:get[arg0=download,arg1=/download]
:exclude-for-languages:python
callout:writable[]
:exclude-for-languages:

== Test

Create a test that verifies the controller's download matches the expected text.

test:PDFControllerTest[]

callout:micronaut-test[]
callout:http-client[]

common:testApp.adoc[]

common:runapp.adoc[]

Visit http://localhost:8080/pdf/download and the browser downloads a PDF.

common:next.adoc[]

:exclude-for-languages:python
Learn more about https://github.com/LibrePDF/OpenPDF[OpenPDF].
:exclude-for-languages:
:only-for-languages:python
Learn more about https://pdfme.readthedocs.io/en/latest/modules/pdf.html[pdfme], its https://pypi.org/project/pdfme/[release status], and https://pypdf.readthedocs.io/[pypdf].
:only-for-languages:
