common:header.adoc[]

common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app-features.adoc[]

== OpenPDF

To generate PDFs, we use https://github.com/LibrePDF/OpenPDF[OpenPDF].

____
OpenPDF is a Java library for creating and editing PDF files with a LGPL and MPL open source license. OpenPDF is the LGPL/MPL open source successor of iText, and is based on some forks of iText 4 svn tag. We welcome contributions from other developers. Please feel free to submit pull-requests and bug reports to this GitHub repository.
____

=== OpenPDF Dependency

To use OpenPDF, add the following dependency:

dependency:openpdf[groupId=com.github.librepdf,scope=implementation,version=@openpdfVersion@]

== Controller

Create a controller that generates and downloads a PDF.

source:PDFController[]]
callout:controller[arg0=/pdf]
callout:executes-on[]
callout:get[arg0=download,arg1=/download]
callout:writable[]

== Test

Create a test that verifies the controller's download matches the expected text.

test:PDFControllerTest[]

callout:micronaut-test[]
callout:http-client[]

common:testApp.adoc[]

common:runapp.adoc[]

Visit http://localhost:8080/pdf/download and the browser downloads a PDF.

common:next.adoc[]

Learn more about https://github.com/LibrePDF/OpenPDF[OpenPDF].

common:helpWithMicronaut.adoc[]
