[micronaut.server]
port = -1

[endpoints.health.discovery-client-health]
enabled = false

#tag::eureka[]
[eureka.client]
discovery.enabled = false

[eureka.client.registration]
enabled = false
status = "UP"
#end::eureka[]
