micronaut:
  application:
    name: userecho
---
endpoints:
  health:
    enabled: true
---
#tag::port[]
micronaut:
  server:
    port: 8081 # <1>
#end::port[]
---
#tag::security[]
micronaut:
  security:
    token:
      jwt:
        signatures:
          secret:
            validation: # <2>
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"' # <3>
#end::security[]