#tag::mn[]
# <1>
[micronaut.application]
name = "bookcatalogue"
#end::mn[]

#tag::server[]
[micronaut.server]
port = 8081
#end::server[]

[endpoints.health]
enabled = true
sensitive = false

#tag::eureka[]
[eureka.client.registration]
enabled = true
status = "UP"

[eureka.client]
default-zone = "${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}"
#end::eureka[]
