CREATE TABLE author
(
    id       bigint primary key generated by default as identity,
    username varchar(255)       not null
);

CREATE TABLE to_do
(
    id        bigint primary key generated by default as identity,
    title     varchar(255)       not null,
    completed boolean            not null,
    author_id    bigint REFERENCES author (id)
);
