# tag::testcontainers-jdbc-url[]
[datasources.default]
driver-class-name = "org.testcontainers.jdbc.ContainerDatabaseDriver" # <1>
url = "jdbc:tc:postgresql:15.2-alpine:///db?TC_INITSCRIPT=sql/init-db.sql" # <2>
initialization-fail-timeout = 60000
# end::testcontainers-jdbc-url[]
