# tag::distributedconfiguration[]
[[micronaut.config.import]]
provider = "azure-key-vault" # <1>
vault-url = "https://YOUR_VAULT_NAME.vault.azure.net" # <2>
credential-mode = "environment" # <3>
# end::distributedconfiguration[]

# tag::datasource-secrets[]
[datasources.default]
url = "${JDBC_URL}"
username = "${JDBC-USER}"
password = "${JDBC-PASSWORD}"
# end::datasource-secrets[]
