common:header.adoc[]

== DynamoDB

https://aws.amazon.com/dynamodb/[DynamoDB]

____
DynamoDB is a fast, flexible NoSQL database service for single-digit millisecond performance at any scale
____


common:completesolution.adoc[]

== Writing the Application

=== Create application

common:cli-or-launch.adoc[]

[source,bash]
----
mn @cli-command@ example.micronaut.micronautguide \
              --features=dynamodb \
              --build=@build@ \
              --lang=@lang@
----

common:build-lang-arguments.adoc[]

common:default-package.adoc[]

common:diff-general.adoc[]

=== Dynamo DB Dependencies

To use DynamoDB with the Micronaut framework, your application should have the following dependencies:

:dependencies:
dependency:micronaut-aws-sdk-v2[groupId=io.micronaut.aws,scope=compile]
dependency:dynamodb[groupId=software.amazon.awssdk,scope=compile]
:dependencies:

=== Id Generation

Create an interface to encapsulate id generation.

source:IdGenerator[]

<1> callout:functional-interface[]

common:ksuid.adoc[]

An identifier with a time component is useful when you work with a NoSQL solution such as DynamoDB.

Create a singleton implementation of `IdGenerator`.

source:KsuidGenerator[]

<1> callout:requires-classes[]
<2> callout:singleton[]

=== POJOs

The application contains an interface to mark classes with a unique identifier.

source:Identified[]

Create a POJO to save books to DynamoDB.

source:Book[]

<1> callout:serdeable[]
<2> callout:constraints[]

=== Configuration

Define the name of the DynamoDB table in configuration:


resource:application.properties[tag=dynamodb]

Inject the configuration into the application via a `@ConfigurationProperties` bean.

source:DynamoConfiguration[]

<1> callout:requires-property[]
<2> callout:configuration-properties-interface[]

=== Repository

Create an interface to encapsulate `Book` persistence.

source:BookRepository[]

Create a singleton class to handle common operations with DynamoDB.

source:DynamoRepository[]

And an implementation of `BookRepository`.

source:DefaultBookRepository[]

<1> callout:singleton[]
<2> Paginate instead of using a scan operation.

== Controllers

Create a CRUD controller for `Book`.

source:BooksController[]

<1> callout:executes-on[]
<2> callout:controller[arg0=/books]
<3> callout:constructor-di[arg0=BookRepository]
<4> callout:get[arg0=index,arg1=/]
<5> callout:post[arg0=save,arg1=/]
<6> callout:body-qualifier[]
<7> callout:get[arg0=show,arg1=/{id}]
<8> callout:pathvariable[]
<9> callout:post[arg0=delete,arg1=/]
<10> callout:at-status[]

=== Running the application

Under development and testing, we have https://micronaut-projects.github.io/micronaut-test-resources/latest/guide/#modules-testcontainers[configured Test Resources] to supply the properties `dynamodb-local.host` and `dynamodb-port`.

resource:application.properties[tag=testresources]

<1> The docker image to use for local dynamodb.
<2> The property to bind the container hostname into.
<3> The property to bind the container port into, and the port that should be exposed.

This will start DynamoDB in a container via TestContainers, and inject the properties into your application.

==== Dev default environment

Modify `Application` to use `dev` as a https://docs.micronaut.io/latest/guide/index.html#_default_environment[default environment].

source:Application[]

==== Dev Bootstrap

Create a `StartupEventListener` that is loaded only for the `dev` environment that creates a dynamodb table if one does not already exist.

source:DevBootstrap[]

<1> callout:requires-property[]
<2> callout:requires-env[]
<3> callout:singleton[]

==== Pointing to DynamoDB Local

Add a bean-created listener that points the DynamoDB client to the URL of the DynamoDB local instance.

source:DynamoDbClientBuilderListener[]

<1> callout:requires-property[]
<2> callout:singleton[]
<3> callout:bean-created-event-listener[]
<4> callout:value[]

common:runapp.adoc[]

You should be able to execute the following cURL requests.

[source,bash]
----
curl http://localhost:8080/books
----

[source,json]
----
[]
----

[source,bash]
----
curl -X POST -d '{"isbn":"1680502395","name":"Release It!"}' -H "Content-Type: application/json" http://localhost:8080/books
----

[source,bash]
----
curl http://localhost:8080/books
----

[source,json]
----
[{"id":"2BLCWltdt3gGgSw1qsomXIfXBiX","isbn":"1680502395","name":"Release It!"}]
----

=== Tests

Create a `StartupEventListener` only loaded for the `test` environment which creates the DynamoDB table if it does not exist.

test:TestBootstrap[]

Create a test which verifies the CRUD functionality.

test:BooksControllerTest[]

<1> callout:micronaut-test[]
<2> callout:testcontainers-container[]
<3> callout:test-instance-per-class[]
<4> callout:http-client[]

common:testApp.adoc[]

common:next.adoc[]

Check https://micronaut-projects.github.io/micronaut-aws/latest/guide/[Micronaut AWS] integration.

common:helpWithMicronaut.adoc[]
