micronaut:
  application:
    name: bookinventory
---
#tag::rabbitmq[]
rabbitmq:
  uri: amqp://localhost:5672
#end::rabbitmq[]
---
#tag::port[]
micronaut:
  server:
    port: 8082 # <1>
#end::port[]
---
endpoints:
  health:
    enabled: true