[micronaut.application]
name = "micronautguide"

# tag::datasource[]
[datasources.default]
db-type = "mysql"
dialect = "MYSQL"
driver-class-name = "com.mysql.cj.jdbc.Driver"
# end::datasource[]

# tag::flyway[]
[flyway.datasources.default]
# <1>
enabled = true
# end::flyway[]
