micronaut.email.from.email=test@test.com
micronaut.email.from.name=Email Test
javamail.authentication.password=password
javamail.authentication.username=user
javamail.properties.mail.smtp.host=smtp.com
