micronaut:
  application:
    name: micronautguide
datasources: # <2>
  default:
    url: 'jdbc:h2:mem:flywayDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: 'sa'
    password: ''
    driverClassName: 'org.h2.Driver'
netty:
  default:
    allocator:
      max-order: 3
flyway: # <3>
  datasources:
    default:
      enabled: true