micronaut:
  application:
    name: micronautguide
datasources:
  default:
    url: jdbc:mysql://localhost:3306/db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ''
    schema-generate: CREATE_DROP
    dialect: MYSQL
netty:
  default:
    allocator:
      max-order: 3
#tag::flyway[]
flyway:
  datasources:
    default:
      enabled: true
#end::flyway[]
