include::{commondir}/common-header-top.adoc[]

== Getting Started

In this guide, we will create a Micronaut application written in @language@ and secure it with HTTP Basic Auth.

https://tools.ietf.org/html/rfc7617[RFC7617] defines the "Basic" Hypertext Transfer Protocol (HTTP) authentication scheme, which transmits credentials as user-id/password pairs, encoded using Base64.

include::{commondir}/common-requirements.adoc[]

include::{commondir}/common-completesolution.adoc[]

== Writing the Application

include::{commondir}/common-cli-or-launch.adoc[]

[source,bash]
----
mn create-app --features=security,reactor,graalvm example.micronaut.micronautguide --build=@build@ --lang=@lang@
----

include::{commondir}/common-build-lang-arguments.adoc[]

If you use Micronaut Launch, select "Micronaut Application" as application type and add the `security`, `reactor`, and `graalvm` features.

include::{commondir}/common-default-package.adoc[]

diffLink:[]

include::{commondir}/common-annotationprocessors.adoc[]

=== Authentication Provider

To keep this guide simple, create a naive `AuthenticationProvider` to simulate user's authentication.

source:AuthenticationProviderUserPassword[]

callout:singleton[1]
callout:authentication-provider[2]

=== Controllers

Create `HomeController` which resolves the base URL `/`:

source:HomeController[]

<1> Annotate with `io.micronaut.security.Secured` to configure secured access. The `isAuthenticated()` expression will allow access only to authenticated users.
<2> Annotate with `io.micronaut.http.annotation.Controller` to designate the class as a Micronaut controller.
<3> You can specify the HTTP verb that a controller action responds to. To respond to a GET request, use the `io.micronaut.http.annotation.Get` annotation.
<4> If a user is authenticated, the Micronaut framework will bind the user object to an argument of type `java.security.Principal` (if present).

=== WWW-Authenticate

https://docs.micronaut.io/latest/guide/#replaces[Replace] the default https://docs.micronaut.io/latest/guide/#exceptionHandler[Exception Handler] for `AuthorizationExceptionHandler`, the exception raised when a request is not authorized.

source:DefaultAuthorizationExceptionHandlerReplacement[]

The previous code adds the https://datatracker.ietf.org/doc/html/rfc7235#section-4.1[WWW-Authenticate] header to indicate the authentication scheme.

callout:singleton[1]
<2> Specify that `DefaultAuthorizationExceptionHandlerReplacement` replaces the bean `DefaultAuthorizationExceptionHandler`

=== Tests

Create a test to verify the user authentication flow via Basic Auth.

test:BasicAuthTest[]

callout:micronaut-test[1]
callout:http-client[2]
callout:http-request[3]
<4> If you attempt to access a secured endpoint without authentication, 401 is returned
<5> By using `basicAuth` method, you populate the `Authorization` header with user-id:password pairs, encoded using Base64.
<6> The Micronaut `HttpClient` simplifies parsing the HTTP response payload to Java objects. In this example, we parse the response to `String`.
callout:body-method[7]

=== Use the Micronaut HTTP Client and Basic Auth

If you want to access a secured endpoint, you can also use a Micronaut HTTP Client and supply the Basic Auth as the Authorization header value.

First create a `@Client` with a method `home` which accepts an `Authorization` HTTP Header.

test:AppClient[]

<1> The method consumes plain text, so the Micronaut framework includes the HTTP Header `Accept: text/plain`.
<2> The first character of the parameter name is capitalized and that value (`Authorization`) is used as the HTTP Header name. To change the parameter name, specify the `@Header` annotation value.

Create a test which uses the previous `@Client`

test:BasicAuthClientTest[]

callout:micronaut-test[1]
<2> Inject the `AppClient` bean.
<3> Generate Basic Auth header value and pass it as the parameter value.

include::{commondir}/common-testApp.adoc[]

include::{commondir}/common-runapp.adoc[]

To test the running application, issue a GET request to localhost:8080 with a Basic Authentication header. One way to do this is with curl:

[source,bash]
----
curl -v -u sherlock:password localhost:8080
----

If you open http://localhost:8080 in a browser, a login dialog pops up due to the `WWW-Authenticate` header.

include::{commondir}/common-graal-with-plugins.adoc[]

:exclude-for-languages:groovy

You can invoke the controller exposed by the native image:

[source,bash]
----
curl "http://localhost:8080" -u 'sherlock:password'
----

:exclude-for-languages:

== Next steps

See the https://micronaut-projects.github.io/micronaut-security/latest/guide/[Micronaut security documentation] to learn more.

include::{commondir}/common-helpWithMicronaut.adoc[]
