micronaut.application.name=micronautguide
#tag::mcp[]
micronaut.mcp.server.info.name=Disk Space
micronaut.mcp.server.info.version=0.0.1
# <1>
micronaut.mcp.server.transport=STDIO
#end::mcp[]
#tag::api-weather-gov[]
micronaut.http.services.weather.url=https://api.weather.gov
micronaut.codec.json.additional-types[0]=application/geo+json
#end::api-weather-gov[]