micronaut:
  application:
    name: app
  #tag::oauth2[]
  security:
    authentication: idtoken # <1>
    oauth2:
      clients:
        auth0: # <2>
          client-id: '${OAUTH_CLIENT_ID:xxx}' # <3>
          client-secret: '${OAUTH_CLIENT_SECRET:yyy}' # <4>
          openid:
            issuer: 'https://${OAUTH_DOMAIN:micronautguides.eu.auth0.com}/' # <5>
    endpoints:
      logout:
        get-allowed: true # <6>
#end::oauth2[]
