#tag::object-storage[]
micronaut:
  object-storage:
    aws:
      default:
        bucket: micronaut-guide-object-storage
#end::object-storage[]
  application:
    name: micronautguide
netty:
  default:
    allocator:
      max-order: 3
