micronaut:
  application:
    name: turbo
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:assets"
  security:
    intercept-url-map:
      -
        pattern: "/**"
        access:
          - isAnonymous()
    authentication: session
    redirect:
      unauthorized:
        enabled: false
netty:
  default:
    allocator:
      max-order: 3
