micronaut:
  application:
    name: books
  server:
    port: 8081
endpoints:
  health:
    enabled: true
    sensitive: false
#tag::gorm[]
grails:
  gorm:
    multiTenancy:
      mode: 'DATABASE' # <1>
      tenantResolverClass: 'io.micronaut.multitenancy.gorm.HttpHeaderTenantResolver' # <2>
#end::gorm[]
#tag::datasources[]
hibernate:
  hbm2ddl:
    auto: 'update'
dataSources:
  sherlock:
    url: 'jdbc:h2:mem:sherlockDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: 'sa'
    password: ''
    driverClassName: 'org.h2.Driver'
  watson:
    url: 'jdbc:h2:mem:watsonDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: 'sa'
    password: ''
    driverClassName: 'org.h2.Driver'
#end::datasources[]