micronaut:
  application:
    name: gateway
endpoints:
  health:
    enabled: true
    sensitive: false
---
#tag::multitenancy[]
micronaut:
  multitenancy:
    propagation:
      enabled: true # <1>
      service-id-regex: 'books' # <2>
    tenantresolver:
      cookie:
        enabled: true # <3>
    tenantwriter:
      httpheader:
        enabled: true # <4>
#end::multitenancy[]
---
#tag::http-services[]
micronaut:
  http:
    services:
      books: # <1>
        urls:
          - "http://localhost:8081" # <2>
#end::http-services[]