common:header-top.adoc[]

== Getting Started

This tutorial shows how to generate Java classes from https://json-schema.org/learn/getting-started-step-by-step[JSON Schema] at compile-time using Micronaut JSON Schema.

This guide will generate sources from the JSON Schema used by https://openweathermap.org/current[OpenWeather]'s current weather API. The schema is available at https://json.schemastore.org/openweather.current.json[json.schemastore.org]. We will send a request to the OpenWeather API (which is free access) and validate the response against the generated Java class.

common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app-features.adoc[]

== Generating the Java classes from JSON Schema
:exclude-for-build:maven
Add the Micronaut JSON Schema plugin to your plugins section:

[source, groovy]
.build.gradle
----
plugins {
  id 'io.micronaut.jsonschema' version '4.5.0-SNAPSHOT'
  ...
}
----

And configure your build to generate from a local JSON Schema in your resources folder:

[source, groovy]
.build.gradle
----
micronaut {
  ...
  jsonschema {
    fromFile(file("src/main/resources/openweather.current.json")) {
        outputPackageName.set("com.example.openweather")
    }
 }
}
----

Micronaut JsonSchema generator generates the client code in your build directory and adds it as a source set.
Therefore, you can, for example run `./gradlew compileJava --console=verbose` and see that the sources are generated and compiled:

[source]
----
> Task :generatingSourcesFromOpenweather
...
> Task :compileJava
----

TIP: The Micronaut JSON Schema generator supports a variety of parameters. Please refer to https://micronaut-projects.github.io/micronaut-gradle-plugin/snapshot/#_source_generator_from_micronaut_json_schema[Micronaut JsonSchema Gradle plugin documentation] for all possible options.

After generation finishes, you should see the following directory structure under your `target/generated-sources/jsonschema` directory:

[source]
----
build/generated-sources/jsonschema
└── generatingSourcesFromOpenweather
    └── src
        ├── main
        │   └── java
        │       └── com.example.openweather
        │           └── OpenweatherCurrentWeatherDataApi.java
----

:exclude-for-build:

:exclude-for-build:gradle

Enable the Micronaut JSON Schema generation in your `pom.xml` file, and configure the location to the schema file and desired output package name:

[source, xml]
.pom.xml
----
<properties>
    <micronaut.jsonschema.generator.enabled>true</micronaut.jsonschema.generator.enabled>
    <micronaut.jsonschema.generator.input-file>src/main/resources/openweather.current.json</micronaut.jsonschema.generator.input-url>
    <micronaut.jsonschema.generator.outputPackageName>com.example.openweather</micronaut.jsonschema.generator.outputPackageName>
</properties>
----
Micronaut JsonSchema generator generates the client code in your target directory and compiles it automatically alongside your regular sources.
Therefore, you can run `mvn compile` and see that the sources are generated and compiled.

TIP: The Micronaut JsonSchema generator supports a variety of parameters. Please refer to https://micronaut-projects.github.io/micronaut-maven-plugin/snapshot/examples/jsonschema.html[Micronaut JsonSchema Maven plugin documentation] for all possible options.

After generation finishes, you should see the following directory structure under your `target/generated-sources/jsonschema` directory:

[source]
----
target/generated-sources/jsonschema
└── generatingSourcesFromOpenweather
    └── src
        ├── main
        │   └── java
        │       └── com.example.openweather
        │           └── OpenweatherCurrentWeatherDataApi.java
----

:exclude-for-build:

== Configuring the OpenWeather API client

In order to use the free OpenWeather API, you will need to create an account with OpenWeather and get an API key from Free Access section in this https://openweathermap.org/price[link]. Once you have your API key, you can save the API key from OpenWeather in the `application.properties` file:

resource:application.properties[tag=openweatherconfig]

Feel free to discover types of free API calls available in the https://openweathermap.org/current[OpenWeather API documentation].

We can create a client to interact with the OpenWeather API:


=== Test

Last, let's write a test that verifies the generated JSON Schema matches our expectations:

// test:ProductSchemaTest[]
// callout:micronaut-test[]
// callout:http-client[]
//
// common:json-assert.adoc[]
//
// common:testApp.adoc[]

== Next Steps

Read more about https://micronaut-projects.github.io/micronaut-json-schema/latest/guide/[Micronaut JSON Schema] and https://json-schema.org[JSON Schema].