common:header-top.adoc[]

== Getting Started

This tutorial shows how to generate a Java class from JSON schema at compile-time using Micronaut JSON Schema.
The example shows a JSON Schema, such as the one found in the https://json-schema.org/learn/getting-started-step-by-step[Getting Started Tutorial on the Json Schema Website].

common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app-features.adoc[]

=== JSON Schema dependencies

The `jsonschema` feature adds the following dependencies:

dependency:micronaut-json-schema-processor[groupId=io.micronaut.jsonschema,scope=annotationProcessor]
dependency:micronaut-json-schema-annotations[groupId=io.micronaut.jsonschema]

=== Expose JSON Schema

We can expose the Json Schema generated at compile-time as a static resource with the following configuration:

resource:application.properties[tag=static-resources]

You can test the JSON Schema specification is exposed:

test:JsonSchemaExposedTest[]
callout:micronaut-test[]
callout:http-client[]

=== Test

Last, let's write a test that verifies the generated JSON Schema matches our expectations:

test:ProductSchemaTest[]
callout:micronaut-test[]
callout:http-client[]

common:json-assert.adoc[]

common:testApp.adoc[]

== Next Steps

Read more about https://micronaut-projects.github.io/micronaut-json-schema/latest/guide/[Micronaut JSON Schema] and https://json-schema.org[JSON Schema].