#tag::mn[]
[micronaut.application]
name = "bookinventory"
#end::mn[]

#tag::server[]
[micronaut.server]
port = 8082
#end::server[]

[endpoints.health]
enabled = true
sensitive = false

#tag::oauth2[]
[micronaut.security.token.jwt.signatures.jwks.auth0]
url = "${OAUTH_JWKS:https://micronautguides.eu.auth0.com/.well-known/jwks.json}"
#end::oauth2[]
