common:header.adoc[]

In this guide, you will learn how to use the annotations `@ConfigurationProperties`, `@ConfigurationBuilder`, and `@EachProperty` to consume configured properties in a Micronaut application. These annotations allow declared values to be injected into a bean for use in the application.

common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app-features.adoc[]

== Team Configuration with @ConfigurationProperties

Imagine a feature where you can configure a sports team in a declarative manner. The team has a few attributes like team name, color, and players.


resource:application.properties[tag=teamConfig]

With Micronaut Framework, you can use the `@ConfigurationProperties` annotation to bind the configuration into a bean. Each property that matches the configuration in `application.properties` will call the setter in the bean. The bean will then be available for injection in the application.

source:TeamConfiguration[tags=teamConfigClassNoBuilder|gettersandsetters]

=== Test @ConfigurationProperties

Let's validate that the bean is available in the application context and is created with the values declared in the `application.properties`.

test:TeamConfigurationTest[tag=teamConfigSpecNoBuilder]

<1> Set up configuration properties for the test to use

== Team Admin Builder with @ConfigurationBuilder

The Builder pattern is a great way to build configuration objects incrementally. Read about the Builder pattern in this
https://dzone.com/articles/design-patterns-the-builder-pattern[DZone] article to learn more. Micronaut Framework supports the Builder pattern with `@ConfigurationBuilder`.

Suppose you want to add team administrators to a team. The team administration is composed by using a builder pattern object. You can add a coach, manager, and president to the team.

resource:application.properties[tag=allTeamConfig]

<1> The `manager` property is an example of an element that will be built.

The `TeamAdmin` object abides by the Builder pattern.

source:TeamAdmin[]

<1> `TeamAdmin` is the configuration object that consumes the declared properties.
<2> The builder object is used to incrementally construct the object.
<3> An example of a builder method, where an attribute is set and then the builder itself is returned.
<4> The final `build()` method creates the `TeamAdmin` object.

At the bottom of `TeamConfiguration`, add the inner class `TeamAdmin.Builder` and annotate it with `@ConfigurationBuilder`.
This tells Micronaut Framework that configuration can be read and an object can be constructed using the Builder pattern.

[NOTE]
The builder is used only here, so call `builder.build()` later to get the `TeamAdmin` object. In this guide, the JUnit test calls `builder.build()`.

source:TeamConfiguration[]

callout:serdeable[]
<2> Mark the builder as being ignored during serialization.
<3> `prefixes` tells Micronaut Framework to find methods that are prefixed by `with`; `configurationPrefix` allows the developer to customize the `application.properties` element.
<4> Instantiate the builder object so it can be populated with configuration values.

=== Test @ConfigurationBuilder

Validate that `@ConfigurationBuilder` is applied properly with the following JUnit test. The test format is similar to previous tests.

test:TeamConfigurationTest[tag=teamConfigSpecBuilder]

<1> Properties that will invoke the builder methods on `TeamAdmin.Builder`.
<2> The builder object is now configured, so run `build()` on it to create the `TeamAdmin` object.
<3> Verify the object is created with the `application.properties` properties.

== Stadiums with @EachProperty

Micronaut Framework is also able to read a list of related configurations. Imagine you would like to declare stadiums and their attributes.

resource:application.properties[tag=stadiumConfig]

<1> This element will be the name of the bean. It must be lower kebab-case.

You can use `@EachProperty` to cycle through the configuration and read each nested clause as a bean. The higher-level
property will be parameterized as the name.

source:StadiumConfiguration[]

callout:serdeable[]
<2> Establish the top layer of configuration.
<3> `name` is read from the property key and sent as a parameter to the bean.

=== Test @EachProperty

Validate the configuration with a test. Notice multiple beans are created from the configuration. In a controller, you can
inject a particular `StadiumConfiguration` instance bean by using the `@Named` parameter with a qualifier name.

test:StadiumConfigurationTest[]

<1> Multiple configurations can be declared for the same class.
<2> Since there are multiple beans, a `Qualifier` must be sent to retrieve a bean.

common:runapp.adoc[]

== Controller

Configuration beans can be injected into the application just like any other beans. As a demonstration, create a controller where the beans are constructor injected. The `StadiumConfiguration` class has two instances, so for injection you need to use the `@Named` annotation with a qualifier name to specify the bean.

source:MyController[]

<1> Injection of configuration beans; `@Named` annotation is needed to choose which `StadiumConfiguration` instance is retrieved.

[NOTE]
In the browser go to http://localhost:8080/my/team and http://localhost:8080/my/stadium.

Add test:

test:MyControllerTest[]

common:graal-with-plugins.adoc[]

:exclude-for-languages:groovy

You can invoke the controller exposed by the native executable:

[source, bash]
----
curl http://localhost:8080/my/stadium
curl http://localhost:8080/my/team
----

:exclude-for-languages:

== Next Steps

Visit https://docs.micronaut.io/latest/guide/#config[Micronaut Application Configuration] to learn more.

common:helpWithMicronaut.adoc[]
