= Creating your first Micronaut app

Learn how to create a Hello World Micronaut app with a controller and a functional test.

Authors: Iván López, Sergio del Amo

Micronaut Version: 2.2.2

== Getting Started

In this guide we are going to create a Micronaut app written in Kotlin.

== What you will need

To complete this guide, you will need the following:

* Some time on your hands
* A decent text editor or IDE
* JDK 1.8 or greater installed with `JAVA_HOME` configured appropriately

== Solution

We recommend you to follow the instructions in the next sections and create the app step by step. However, you can go right to the **completed example**.

* link:https://github.com/creating-your-first-micronaut-app/archive/master.zip[Download] and unzip the source

or

* Clone the https://git-scm.com/[Git] repository: `git clone https://github.com/creating-your-first-micronaut-app.git`

Then, `cd` into the `complete` folder which you will find in the root project of the downloaded/cloned project.

== Writing the App

Create an app using the http://docs.micronaut.io/snapshot/guide/index.html#cli[Micronaut Command Line Interface] or with
https://launch.micronaut.io[Micronaut Launch].

`mn create-app example.micronaut.complete --build=maven --lang=kotlin`

NOTE: If you don't specify the `--build` argument, Gradle is used as a build tool. +++<br/>+++ If you don't specify the `--lang` argument, Java is used as a language.

The previous command creates a micronaut app with the default package `example.micronaut` in a folder named `complete`.


include::{commondir}/common-annotationprocessors.adoc[]



=== Application

`Application.kt` is used when running the application via Gradle or via deployment. You can also run the main class directly within your IDE if it is configured correctly.

[source,Kotlin]
.src/main/Kotlin/example/micronaut/Application.kt
----
include::{sourceDir}/creating-your-first-micronaut-app-maven-kotlin/src/main/Kotlin/example/micronaut/Application.kt[]
----

=== Controller

In order to create a microservice that responds with "Hello World" you first need a controller.

Create a Controller:

[source,Kotlin]
.src/main/Kotlin/example/micronaut/HelloController.kt
----
include::{sourceDir}/creating-your-first-micronaut-app-maven-kotlin/src/main/Kotlin/example/micronaut/HelloController.kt[]
----

<1> The class is defined as a controller with the http://docs.micronaut.io/snapshot/api/io/micronaut/http/annotation/Controller.html[@Controller] annotation mapped to the path `/hello`
<2> The http://docs.micronaut.io/snapshot/api/io/micronaut/http/annotation/Get.html[@Get] annotation is used to map the index method to all requests that use an HTTP GET
<3> By default a Micronaut's response uses `application/json` as `Content-Type`. We are returning a String not a JSON object. Because of that, we set it to `text/plain`.
<4> A String "Hello World" is returned as the result

=== Test

Create a test which verifies that when you do a GET request to `/hello` you get `Hello World` as a response:

[source,Kotlin]
.src/test/Kotlin/example/micronaut/HelloControllerTest.kt
----
include::{sourceDir}/creating-your-first-micronaut-app-maven-kotlin/src/test/Kotlin/example/micronaut/HelloControllerTest.kt[]
----

<1> Annotate the class with `@MicronautTest` so Micronaut will initialize the application context and the embedded server.
<2> Inject the `RxHttpClient` bean. It is used the execute an HTTP call to the controller.
<3> Creating HTTP Requests is easy thanks to Micronaut's fluid API.

== Testing the Application

To run the tests:



[source, bash]
----
$ ./mvnw test
----




== Running the Application



To run the application use the `./mvnw mn:run` command which will start the application on port 8080.



== Generate a Micronaut app's Native Image with GraalVM

We are going to use https://www.graalvm.org/[GraalVM], the polyglot embeddable virtual machine, to generate a Native image of our Micronaut application.

Native images compiled with GraalVM ahead-of-time improve the startup time and reduce the memory footprint of JVM-based applications.

=== Native Image generation

The easiest way to install GraalVM is to use https://sdkman.io/[SDKMan.io].

[source, bash]
----
% sdk list java
================================================================================
================================================================================
Available Java Versions
================================================================================
 Vendor        | Use | Version      | Dist    | Status     | Identifier
--------------------------------------------------------------------------------
...
..
.
 GraalVM       |     | 20.3.0.r11   | grl     |            | 20.3.0.r11-grl
               |     | 20.3.0.r8    | grl     |            | 20.3.0.r8-grl
               |     | 20.1.0.r11   | grl     | local only | 20.1.0.r11-grl
               |     | 20.1.0.r8    | grl     | local only | 20.1.0.r8-grl

# For Java 8
$ sdk install java 20.3.0.r8-grl

# For Java 11
$ sdk install java 20.3.0.r11-grl
----

You need to install the native-image component which is not installed by default.

[source, bash]
----
$ gu install native-image
----



To generate a native image using Maven run:

[source, bash]
----
$ ./mvn package -Dpackaging=native-image
----

The native image will be built to `target/application` and can be run with `./target/application`.




You can execute the endpoint exposed by the native image:

[source, bash]
----
$ curl localhost:8080/hello
Hello World
----


== Next steps

Read more about https://micronaut-projects.github.io/micronaut-test/latest/guide/index.html[Micronaut testing].

== Help with Micronaut

++++
<h3 style="color: #333; margin-bottom:25px;"><a href="https://objectcomputing.com/" target="_blank">Object Computing, Inc.</a> (OCI) sponsored the creation of this Guide. A variety of consulting and support services are available.</h3>

<!--[if lte IE 8]>
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2-legacy.js"></script>
<![endif]-->
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2.js"></script>
<script>
  hbspt.forms.create({
	portalId: "4547412",
	formId: "24edfcbb-b6f2-4fcf-af48-35ab6271031e"
});
</script>

<h3 style="color: #333;">OCI is Home to Micronaut.</h3>

<p><a href="https://objectcomputing.com/products/2gm-team" target="_blank">Meet the Team</a></p>
++++