[micronaut.application]
name = "turbo"

[micronaut.router.static-resources.default]
enabled = true
mapping = "/**"
paths = "classpath:assets"

[micronaut.security]
authentication = "session"

[micronaut.security.redirect]
logout = "/"

[micronaut.security.redirect.unauthorized]
enabled = false
url = "/signin"

[[micronaut.security.intercept-url-map]]
pattern = "/**"
access = ["isAnonymous()"]
