#tag::object-storage[]
micronaut:
  object-storage:
    gcp:
      default:
        bucket: micronaut-guide-object-storage
#end::object-storage[]
  application:
    name: micronautguide
netty:
  default:
    allocator:
      max-order: 3
---
#tag::server-max-file-size[]
micronaut:
  server:
    multipart:
      max-file-size: 20971520 # 20 * 1024 * 1024 = 20MB
#end::server-max-file-size[]