common:header.adoc[]

The application uses multiple authentication providers; an LDAP and a database authentication provider.

image:diagram-ldap-authentication.provider.svg[]

common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app-features.adoc[]

common:default-package.adoc[]

common:diff.adoc[]

diffLink:[featureExcludes=spring-security-crypto]

https://guides.micronaut.io/latest/micronaut-intellij-idea-ide-setup.html[Setup IntelliJ IDEA to develop Micronaut Applications].

The generated `application.properties` includes configuration settings that enable security:

resource:application.properties[tag=security]

<1> Set `micronaut.security.authentication` as `bearer`
<2> You can create a SecretSignatureConfiguration named `generator` via configuration as illustrated above. The generator signature is used to sign the issued JWT claims.
<3> Change this to your own secret and keep it safe (do not store this in your VCS)

=== Security LDAP

The Micronaut framework supports authentication with LDAP out of the box.

We will use the open Debian LDAP service for this guide.

Create the configuration properties matching those of the LDAP Server.

resource:application.properties[tag=ldap]

<1> LDAP authentication in the Micronaut framework supports configuration of one or more LDAP servers to authenticate with. You need to name each one. In this tutorial, we use `default`.
<2> Each server has its own settings and can be enabled or disabled.
<3> Sets the manager DN
<4> Sets the manager password.
<5> Sets the base DN to search.
<6> Enable group search.
<7> Sets the base DN to search from.

=== Micronaut Data JDBC

Add https://micronaut-projects.github.io/micronaut-data/latest/guide/#jdbc[Micronaut Data JDBC] dependencies to the project:

:dependencies:

dependency:micronaut-data-processor[groupId=io.micronaut.data,scope=annotationProcessor]
dependency:micronaut-data-jdbc[groupId=io.micronaut.data]
dependency:micronaut-jdbc-hikari[groupId=io.micronaut.sql]
dependency:h2[groupId=com.h2database,scope=runtimeOnly]

:dependencies:

And the database configuration:

resource:application.properties[tag=datasource]

==== Entities

common:quotedomainclass.adoc[]

===== User

Create a `UserState` interface to model the user state.

source:UserState[]

Create `User` domain class to store users within our application.

source:domain/User[]

<1> callout:serdeable[]
<2> callout:mapped-entity[]
<3> callout:mapped-entity-id[]
<4> callout:generated-value[]

===== Role

Create `Role` domain class to store authorities within our application.

source:domain/Role[]

<1> callout:serdeable[]
<2> callout:mapped-entity[]
<3> callout:mapped-entity-id[]
<4> callout:generated-value[]

===== UserRole

Create a `UserRole` which stores a many-to-many relationship between `User` and `Role`.

source:domain/UserRole[]

<1> callout:serdeable[]
<2> callout:mapped-entity[]
<3> callout:embeddedid[]

source:domain/UserRoleId[]

<1> callout:serdeable[]
<2> callout:embeddable[]
<3> callout:creator[]

==== JDBC Repositories

Create various JDBC Repositories:

source:UserJdbcRepository[]

<1> callout:jdbcrepository[]
<2> callout:crudrepository[]

source:RoleJdbcRepository[]

<1> callout:jdbcrepository[]
<2> callout:crudrepository[]

source:UserRoleJdbcRepository[]

<1> callout:jdbcrepository[]
<2> callout:crudrepository[]
<3> callout:at-query[]

=== Password Encoder

Create an interface to handle password encoding:

source:PasswordEncoder[]

To provide an implementation, first include a dependency to https://docs.spring.io/spring-security/site/docs/3.1.x/reference/crypto.html[Spring Security Crypto] to ease password encoding.

Add the dependencies:

:dependencies:

dependency:spring-security-crypto[groupId=org.springframework.security,version=@spring-security-cryptoVersion@]
dependency:jcl-over-slf4j[groupId=org.slf4j]

:dependencies:

Then, write the implementation:

source:BCryptPasswordEncoderService[]

<1> callout:singleton[]

=== Register Service

We will register a user when the application starts up.

Create `RegisterService`

source:RegisterService[]

Update the `Application` class to be an event listener, and use `RegisterService` to create a user:

source:Application[]

<1> callout:server-startup-event[]
<2> callout:constructor-di[arg0=RegisterService]
<3> Register a new user when the application starts.

=== Delegating Authentication Provider

We will set up a https://micronaut-projects.github.io/micronaut-security/latest/api/io/micronaut/security/authentication/AuthenticationProvider.html[AuthenticationProvider] as described in the next diagram.

image::delegating_authentication_provider.svg[]

Next, we create interfaces and implementations for each of the pieces of the previous diagram.

==== User Fetcher

Create an interface to retrieve a `UserState` given a username.

source:UserFetcher[]

Provide an implementation:

source:UserFetcherService[]

<1> callout:singleton[]
<2> `UserJdbcRepository` is injected via constructor injection.

==== Authorities Fetcher

Create an interface to retrieve roles given a username.

source:AuthoritiesFetcher[]

Provide an implementation:

source:AuthoritiesFetcherService[]

<1> callout:singleton[]
<2> `UserRoleJdbcRepository` is injected via constructor injection.

==== Authentication Provider

Create an authentication provider which uses the interfaces you wrote in the previous sections.

source:DelegatingAuthenticationProvider[]

<1> The configured I/O executor service is injected
<2> `subscribeOn` method schedules the operation on the I/O thread pool

IMPORTANT: It is critical that any blocking I/O operations (such as fetching the user from the database in the previous code sample) are offloaded to a separate thread pool that does not block the Event loop.

=== LDAP Authentication Provider test

Create a test to verify an LDAP user can log in.

test:LoginLdapTest[]

<1> callout:micronaut-test[]
<2> callout:http-client[]
<3> Inject the `TokenValidator` bean.
<4> callout:http-request[]
<5> If you attempt to access a secured endpoint without authentication, 401 is returned
<6> Use the `tokenValidator` bean previously injected.

=== Login Testing

Test `/login` endpoint. We verify both LDAP and DB authentication providers work.

test:LoginControllerTest[]

common:testApp.adoc[]

common:runapp.adoc[]

common:next.adoc[]

common:helpWithMicronaut.adoc[]
