common:header.adoc[]

The application uses multiple authentication providers; an LDAP and a database authentication provider.

image:diagram-ldap-authentication.provider.svg[]

common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app-features.adoc[]

common:default-package.adoc[]

common:diff.adoc[]

diffLink:[featureExcludes=spring-security-crypto]

https://guides.micronaut.io/latest/micronaut-intellij-idea-ide-setup.html[Setup IntelliJ IDEA to develop Micronaut Applications].

The generated configuration file includes settings that enable security:

:exclude-for-languages:python
resource:application.properties[tag=security]
:exclude-for-languages:

:only-for-languages:python
resource:application.toml[tag=security]
:only-for-languages:

<1> Set `micronaut.security.authentication` as `bearer`
<2> You can create a SecretSignatureConfiguration named `generator` via configuration as illustrated above. The generator signature is used to sign the issued JWT claims.
<3> Change this to your own secret and keep it safe (do not store this in your VCS)

=== Security LDAP

The Micronaut framework supports authentication with LDAP out of the box.

We will use the open Debian LDAP service for this guide.

Create the configuration properties matching those of the LDAP Server.

:exclude-for-languages:python
resource:application.properties[tag=ldap]
:exclude-for-languages:

:only-for-languages:python
resource:application.toml[tag=ldap]
:only-for-languages:

<1> LDAP authentication in the Micronaut framework supports configuration of one or more LDAP servers to authenticate with. You need to name each one. In this tutorial, we use `default`.
<2> Each server has its own settings and can be enabled or disabled.
<3> Sets the manager DN
<4> Sets the manager password.
<5> Sets the base DN to search.
<6> Enable group search.
<7> Sets the base DN to search from.

=== Micronaut Data JDBC

Add https://micronaut-projects.github.io/micronaut-data/latest/guide/#jdbc[Micronaut Data JDBC] dependencies to the project:

:dependencies:

dependency:micronaut-data-processor[groupId=io.micronaut.data,scope=annotationProcessor]
dependency:micronaut-data-jdbc[groupId=io.micronaut.data]
dependency:micronaut-jdbc-hikari[groupId=io.micronaut.sql]
dependency:h2[groupId=com.h2database,scope=runtimeOnly]

:dependencies:

And the database configuration:

:exclude-for-languages:python
resource:application.properties[tag=datasource]
:exclude-for-languages:

:only-for-languages:python
resource:application.toml[tag=datasource]
:only-for-languages:

==== Entities

common:quotedomainclass.adoc[]

===== User

Create a `UserState` type to model the user state.

source:UserState[]

Create `User` domain class to store users within our application.

source:domain/User[]

callout:serdeable[]
callout:mapped-entity[]
callout:mapped-entity-id[]
callout:generated-value[]

===== Role

Create a `Role` domain class to store authorities within the application.

source:domain/Role[]

callout:serdeable[]
callout:mapped-entity[]
callout:mapped-entity-id[]
callout:generated-value[]

===== UserRole

Create a `UserRole` which stores a many-to-many relationship between `User` and `Role`.

source:domain/UserRole[]

callout:serdeable[]
callout:mapped-entity[]
callout:embeddedid[]

source:domain/UserRoleId[]

callout:serdeable[]
callout:embeddable[]
:exclude-for-languages:python
callout:creator[]
:exclude-for-languages:
:only-for-languages:python
<.> The dataclass constructor provides both embedded ID values.
:only-for-languages:

==== JDBC Repositories

Create the following JDBC repositories:

source:UserJdbcRepository[]

callout:jdbcrepository[]
callout:crudrepository[]

source:RoleJdbcRepository[]

callout:jdbcrepository[]
callout:crudrepository[]

source:UserRoleJdbcRepository[]

callout:jdbcrepository[]
callout:crudrepository[]
callout:at-query[]

=== Password Encoder

Create an interface to handle password encoding:

source:PasswordEncoder[]

To provide an implementation, first include a dependency to https://docs.spring.io/spring-security/site/docs/3.1.x/reference/crypto.html[Spring Security Crypto] to ease password encoding.

Add the dependencies:

:dependencies:

dependency:spring-security-crypto[groupId=org.springframework.security,version=@spring-security-cryptoVersion@]
dependency:jcl-over-slf4j[groupId=org.slf4j]

:dependencies:

Then, write the implementation:

source:BCryptPasswordEncoderService[]

callout:singleton[]

=== Register Service

We will register a user when the application starts up.

Create `RegisterService`

source:RegisterService[]

Update the `Application` class to be an event listener, and use `RegisterService` to create a user:

source:Application[]

callout:server-startup-event[]
callout:constructor-di[arg0=RegisterService]
<.> Register a new user when the application starts.

=== Delegating Authentication Provider

We will set up a https://micronaut-projects.github.io/micronaut-security/latest/api/io/micronaut/security/authentication/AuthenticationProvider.html[AuthenticationProvider] as described in the next diagram.

image::delegating_authentication_provider.svg[]

Next, we create interfaces and implementations for each of the pieces of the previous diagram.

==== User Fetcher

Create an interface to retrieve a `UserState` given a username.

source:UserFetcher[]

Provide an implementation:

source:UserFetcherService[]

callout:singleton[]
<.> `UserJdbcRepository` is injected via constructor injection.

==== Authorities Fetcher

Create an interface to retrieve roles given a username.

source:AuthoritiesFetcher[]

Provide an implementation:

source:AuthoritiesFetcherService[]

callout:singleton[]
<.> `UserRoleJdbcRepository` is injected via constructor injection.

==== Authentication Provider

Create an authentication provider which uses the interfaces you wrote in the previous sections.

source:DelegatingAuthenticationProvider[]

:exclude-for-languages:python
<1> The configured I/O executor service is injected.
<2> The `subscribeOn` method schedules the operation on the I/O thread pool.

IMPORTANT: It is critical that any blocking I/O operations (such as fetching the user from the database in the previous code sample) are offloaded to a separate thread pool that does not block the event loop.
:exclude-for-languages:

:only-for-languages:python
<1> Fetch the user by username using the `UserFetcher`.
<2> Return a successful `AuthenticationResponse` after credentials and account state are validated.
:only-for-languages:

=== LDAP Authentication Provider test

Create a test to verify an LDAP user can log in.

test:LoginLdapTest[]

:exclude-for-languages:python
callout:micronaut-test[]
callout:http-client[]
<.> Inject the `TokenValidator` bean.
callout:http-request[]
<.> If you attempt to access a secured endpoint without authentication, 401 is returned.
<.> Use the `tokenValidator` bean previously injected.
:exclude-for-languages:
:only-for-languages:python
<1> Create a Micronaut test fixture for the application context.
<2> Use `requests.with_context` to send HTTP requests to the running test server.
<3> Send the credentials as a JSON payload to `/login`.
<4> Parse the returned JWT to assert an access token was issued.
:only-for-languages:

=== Login Testing

Test the `/login` endpoint. We verify both LDAP and database authentication providers work.

test:LoginControllerTest[]

common:testApp.adoc[]

common:runapp.adoc[]

common:next.adoc[]

common:helpWithMicronaut.adoc[]
