include::{commondir}/common-header.adoc[]

The application uses multiple authentication providers; an LDAP and a database authentication provider.

image:diagram-ldap-authentication.provider.svg[]

include::{commondir}/common-requirements.adoc[]

include::{commondir}/common-completesolution.adoc[]

== Writing the Application

include::{commondir}/common-cli-or-launch.adoc[]

[source,bash]
----
mn create-app --features=security-jwt,security-ldap example.micronaut.micronautguide --build=@build@ --lang=@lang@
----

include::{commondir}/common-build-lang-arguments.adoc[]

If you use Micronaut Launch, select Micronaut Application as application type and add the `security-jwt` and `security-ldap` features.

include::{commondir}/common-default-package.adoc[]

diffLink:[featureExcludes=spring-security-crypto]

include::{commondir}/common-annotationprocessors.adoc[]

The generated `application.yml` includes configuration settings that enable security:

resource:application.yml[tag=security]

<1> Set `micronaut.security.authentication` as `bearer`
<2> You can create a SecretSignatureConfiguration named `generator` via configuration as illustrated above. The generator signature is used to sign the issued JWT claims.
<3> Change this to your own secret and keep it safe (do not store this in your VCS)

=== Security LDAP

The Micronaut framework supports authentication with LDAP out of the box.

We will use an https://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/[Online LDAP test server] for this guide.

Create several configuration properties matching those of the test LDAP Server.

resource:application.yml[tag=ldap]

<1> LDAP authentication in the Micronaut framework supports configuration of one or more LDAP servers to authenticate with. You need to name each one. In this tutorial, we use `default`.
<2> Each server has its own settings and can be enabled or disabled.
<3> Sets the manager DN
<4> Sets the manager password.
<5> Sets the base DN to search.
<6> Enable group search.
<7> Sets the base DN to search from.

=== GORM

include::{commondir}/common-gorm.adoc[]

Add GORM dependencies to the project:

:dependencies:

dependency:micronaut-hibernate-validator[groupId=io.micronaut.beanvalidation]
dependency:micronaut-hibernate-gorm[groupId=io.micronaut.groovy]
dependency:h2[groupId=com.h2database,scope=runtimeOnly]
dependency:tomcat-jdbc[groupId=org.apache.tomcat,scope=runtimeOnly]

:dependencies:

And the database configuration:

resource:application.yml[tag=datasource]

==== Domain Classes

include::{commondir}/common-quotedomainclass.adoc[]

===== User

Create a `UserState` interface to model the user state.

source:UserState[]

Create `User` domain class to store users within our application.

source:domain/User[]

callout:gorm-entity[1]
callout:gorm-entity-ide[1]

===== Role

Create `Role` domain class to store authorities within our application.

source:domain/Role[]

callout:gorm-entity[1]
callout:gorm-entity-ide[2]

===== UserRole

Create a `UserRole` which stores a many-to-many relationship between `User` and `Role`.

source:domain/UserRole[]

callout:gorm-entity[1]
callout:gorm-entity-ide[2]

==== Data Services

include::{commondir}/common-gormdataservices.adoc[]

Create various GORM Data services:

source:UserGormService[]

callout:gorm-service[1]

source:RoleGormService[]

callout:gorm-service[1]

source:UserRoleGormService[]

callout:gorm-service[1]
<2> GORM allows statically-compiled JPA-QL Queries

=== Password Encoder

Create an interface to handle password encoding:

source:PasswordEncoder[]

To provide an implementation, first include a dependency to https://docs.spring.io/spring-security/site/docs/3.1.x/reference/crypto.html[Spring Security Crypto] to ease password encoding.

Add the dependency:

dependency:spring-security-crypto[groupId=org.springframework.security,version=@spring-security-cryptoVersion@]

Then, write the implementation:

source:BCryptPasswordEncoderService[]

callout:singleton[1]

=== Register Service

We will register a user when the application starts up.

Create `RegisterService`

source:RegisterService[]

Update the `Application` class to be an event listener, and use `RegisterService` to create a user:

source:Application[]

callout:server-startup-event[1]
callout:constructor-di[number=0,arg0=RegisterService]
<3> Register a new user when the application starts.

=== Delegating Authentication Provider

We will set up a http://docs.micronaut.io/snapshot/api/io/micronaut/security/authentication/AuthenticationProvider.html[AuthenticationProvider] a described in the next diagram.

image::delegating_authentication_provider.svg[]

Next, we create interfaces and implementations for each of the pieces of the previous diagram.

==== User Fetcher

Create an interface to retrieve a `UserState` given a username.

source:UserFetcher[]

Provide an implementation:

source:UserFetcherService[]

callout:singleton[1]
<2> `UserGormService` is injected via constructor injection.

==== Authorities Fetcher

Create an interface to retrieve roles given a username.

source:AuthoritiesFetcher[]

Provide an implementation:

source:AuthoritiesFetcherService[]

callout:singleton[1]
<2> `UserRoleGormService` is injected via constructor injection.

==== Authentication Provider

Create an authentication provider which uses the interfaces you wrote in the previous sections.

source:DelegatingAuthenticationProvider[]

<1> The configured I/O executor service is injected
<2> `subscribeOn` method schedules the operation on the I/O thread pool

IMPORTANT: It is critical that any blocking I/O operations (such as fetching the user from the database in the previous code sample) are offloaded to a separate thread pool that does not block the Event loop.

=== LDAP Authentication Provider test

Create a test to verify an LDAP user can log in.

test:LoginLdapTest[]

callout:micronaut-test[1]
callout:http-client[2]
<3> Inject the `TokenValidator` bean.
callout:http-request[4]
<5> If you attempt to access a secured endpoint without authentication, 401 is returned
<6> Use the `tokenValidator` bean previously injected.

=== Login Testing

Test `/login` endpoint. We verify both LDAP and DB authentication providers work.

test:LoginControllerTest[]

include::{commondir}/common-testApp.adoc[]

include::{commondir}/common-runapp.adoc[]

include::{commondir}/common-next.adoc[]

include::{commondir}/common-helpWithMicronaut.adoc[]
