external:micronaut-object-storage-base/start.adoc[]

* A https://cloud.google.com/gcp/[Google Cloud Platform (GCP)] account and a GCP project.


common:jq[]

common:gcp.adoc[]

common:completesolution.adoc[]

common:create-app-features.adoc[]

== Create a bucket

Use the Google Cloud CLI to create a bucket:

[source,bash]
----
gcloud storage buckets create gs://micronaut-guide-object-storage
----

Then, configure the bucket name in `application.properties`:

resource:application.properties[tag=object-storage]

== Controller API

external:micronaut-object-storage-base/controller-api.adoc[]

source:ProfilePicturesController[tags=begin-class|end-class]

callout:controller[arg0=/pictures]
callout:executes-on[]
callout:object-storage-operations[arg0=googlecloud,arg1=GoogleCloudStorageOperations]
callout:object-storage-host-resolver[]

=== Upload endpoint

Implement the upload endpoint by receiving the file from the HTTP client via `CompletedFileUpload`, and the `userId` path
parameter. Upload it to Google Cloud using
https://micronaut-projects.github.io/micronaut-object-storage/latest/api/io/micronaut/objectstorage/googlecloud/GoogleCloudStorageOperations.html[GoogleCloudStorageOperations],
and then return its `ETag` in an HTTP response header to the client:

source:ProfilePicturesController[tags=upload,indent=0]

callout:object-storage-key[]
callout:object-storage-request[]
callout:object-storage-upload-response[arg0=https://cloud.google.com/java/docs/reference/google-cloud-storage/latest/com.google.cloud.storage.Blob,arg1=Blob]
callout:object-storage-location[]
callout:object-storage-response[]

=== Download endpoint

external:micronaut-object-storage-base/download-endpoint.adoc[]

source:ProfilePicturesController[tags=download,indent=0]
<1> The retrieve operation returns an `ObjectStorageEntry`, in this case an
https://micronaut-projects.github.io/micronaut-object-storage/latest/api/io/micronaut/objectstorage/googlecloud/GoogleCloudStorageEntry.html[GoogleCloudStorageEntry],
which allows accessing the Google Cloud-specific
https://cloud.google.com/java/docs/reference/google-cloud-storage/latest/com.google.cloud.storage.Blob[Blob]
callout:object-storage-entry-to-response[arg0=GoogleCloudStorageEntry]
callout:object-storage-etag[]

external:micronaut-object-storage-base/etag.adoc[]

=== Delete endpoint

external:micronaut-object-storage-base/delete-endpoint.adoc[]

common:runapp.adoc[]

common:graal-with-plugins.adoc[]

== Testing

Test the application from the command line.

=== Uploading a profile picture

external:micronaut-object-storage-base/testing-upload.adoc[]

Use the `gcloud` CLI to verify that the file has been uploaded to an Google Cloud bucket:

[source,bash]
----
gcloud storage ls --recursive gs://micronaut-guide-object-storage
----

=== Download a profile picture

external:micronaut-object-storage-base/testing-download.adoc[]

=== Delete a profile picture

external:micronaut-object-storage-base/testing-delete.adoc[]

[source,bash]
----
gcloud storage ls --recursive gs://micronaut-guide-object-storage
----

common:gcp-project-cleanup[]

external:micronaut-object-storage-base/end.adoc[]
* Discover https://cloud.google.com/storage[Google Cloud Storage].
