micronaut:
  application:
    name: micronautguide
---
#tag::datasource[]
datasources:
  default:
    db-type: mysql
    dialect: MYSQL
    driver-class-name: com.mysql.cj.jdbc.Driver
#end::datasource[]
---
#tag::flyway[]
flyway:
  datasources:
    default:
      enabled: true # <1>
#end::flyway[]
test-resources:
  containers:
    mysql:
      image-name: mysql:8.2