micronaut:
  application:
    name: gateway
---
endpoints:
  health:
    enabled: true
---
#tag::port[]
micronaut:
  server:
    port: 8080
#end::port[]
---
#tag::security[]
micronaut:
  security:
    authentication: bearer # <1>
    token:
      jwt:
        signatures:
          secret:
            generator: # <3>
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"' # <4>
#end::security[]
---
#tag::tokenpropagation[]
micronaut:
  security:
    token:
      propagation:
        enabled: true # <1>
        service-id-regex: "userecho" # <2>
#end::tokenpropagation[]
---
#tag::httpservices[]
micronaut:
  http:
    services:
      userecho:
        urls:
          - "http://localhost:8081" # <1>
#end::httpservices[]