micronaut:
  application:
    name: micronautguide
#tag::prometheus[]
---
micronaut:
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
---
#end::prometheus[]