micronaut.application.name=micronautguide
#tag::server[]
micronaut.server.port=8081
#end::server[]
#tag::mcp[]
micronaut.mcp.client.http.diskspace.url=http://localhost:8080/mcp
#end::mcp[]
#tag::ollama[]
langchain4j.ollama.base-url=http://localhost:11434
langchain4j.ollama.model-name=llama3.2
langchain4j.ollama.timeout=5m
#end::ollama[]
