common:header.adoc[]

You will use https://www.mongodb.com[MongoDB] for persistence.

common:requirements.adoc[]
* https://www.docker.io/gettingstarted/#h_installation[Docker] installed to run MongoDB and to run tests using https://www.testcontainers.org[Testcontainers].

common:completesolution.adoc[]

common:create-app-features.adoc[]

=== Dependencies

In this guide, we use the MongoDB Sync driver.

The `mongo-sync` features adds the following dependencies:

:dependencies:

dependency:micronaut-data-document-processor[groupId=io.micronaut.data,scope=annotationProcessor]
dependency:micronaut-data-mongodb[groupId=io.micronaut.data]
dependency:micronaut-mongo-sync[groupId=io.micronaut.mongodb]

:dependencies:

:exclude-for-languages:groovy

=== POJO

Create a `Fruit` POJO:

:exclude-for-languages:

:exclude-for-languages:java

=== POGO

Create a `Fruit` POGO:

:exclude-for-languages:

source:Fruit[]

callout:mapped-entity[1]
callout:mapped-entity-id[2]
callout:constraints[3]

=== Repository

Create a repository interface to encapsulate the CRUD actions for `Fruit`.

source:FruitRepository[]

<1> Annotate with `@MongoRepository`.
<2> Add a finder for finding fruit by a list of names.

=== Service

Create a service `FruitService` as an API to interact with the `Fruit` repository.
This will allow you to keep business logic out of the controller, and to test the controller later without interacting with a real database.

source:FruitService[]

And then create a default implementation of this service.

source:DefaultFruitService[]

callout:singleton[number=1]

=== Controller

Create `FruitController`:

source:FruitController[]

callout:controller[number=1,arg0=/fruits]
callout:executes-on[number=2]
callout:constructor-di[number=3,arg0=FruitService]
callout:get[number=4,arg0=list,arg1=/fruits]
callout:post[number=5,arg0=save,arg1=/fruits]
<6> You can specify the HTTP status code via the `@Status` annotation.
callout:valid[7]
callout:get[number=8,arg0=find,arg1=/fruits/\{id\}]
callout:get[number=9,arg0=findByNameInList,arg1=/fruits/q]
<10> Bind a list of Strings to the query parameter `names`

=== Test

By using the feature `mongo-sync`, the application includes the following test dependencies:

:dependencies:
dependency:junit-jupiter[groupId=org.testcontainers,scope=test]
dependency:mongodb[groupId=org.testcontainers,scope=test]
dependency:testcontainers[groupId=org.testcontainers,scope=test]
:dependencies:

Add a https://docs.micronaut.io/latest/guide/#httpClient[Micronaut declarative HTTP Client] to `src/test` to ease the testing of the application's API.

test:FruitClient[]

We use https://www.testcontainers.org/modules/databases/mongodb/[Testcontainers MongoDB Module] to test the application.

All of the tests will require an existing MongoDB instance for Micronaut Data to connect to.
To facilitate this, create a base test class that handles the start-up and shutdown of MongoDb with TestContainers, and sets our application config to use it.

test:BaseMongoDataTest[]

When the application was created, a test was created for you that tests the application can be started.
Change this test to extend the above base class:

test:MicronautguideTest[]

Then create a test that verifies the validation of the `Fruit` POJO when we create a new entity via `POST`:

test:FruitValidationControllerTest[]

Create a test that checks our controller works against a real MongoDB database:

test:FruitControllerTest[]

And finally, create a test which uses a replacement `FruitService` to test the controller without touching the database:

test:ControllerIsolationTest[]

common:testApp.adoc[]

== Start MongoDB via Docker

You can run MongoDb via Docker:

[source,bash]
----
docker run -ti --rm -p 27017:27017 mongo:5.0.6
----

The application connects to MongoDb, run via Docker, thanks to the following configuration:

resource:application.yml[tag=mongodb]

common:runapp.adoc[]

[source, bash]
----
curl -d '{"name":"Pear"}' \
     -H "Content-Type: application/json" \
     -X POST http://localhost:8080/fruits
----

[source, bash]
----
curl -i localhost:8080/fruits
----

[source]
----
HTTP/1.1 200 OK
date: Wed, 15 Sep 2021 12:40:15 GMT
Content-Type: application/json
content-length: 110
connection: keep-alive

[{"name":"Pear"}]
----

common:next.adoc[]

Read more about the https://micronaut-projects.github.io/micronaut-data/latest/guide/#mongo[integration between the Micronaut Data and MongoDB].

common:helpWithMicronaut.adoc[]
