include::{commondir}/common-header.adoc[]

Nowadays it is pretty usual to have some kind of cron or scheduled task that needs to run every midnight, every hour, a few times a week,...

In this guide you will learn how to use Micronaut capabilities to schedule periodic tasks inside a Micronaut microservice.

include::{commondir}/common-requirements.adoc[]

include::{commondir}/common-completesolution.adoc[]

include::{commondir}/common-create-app.adoc[]

=== Set log level INFO for package demo

In this guide, we will use several log statements to show Job execution.

Add this statement to the end of `logback.xml`:

resource:logback.xml[tag=logger,indent=0]

The above line configures a logger for package `example.micronaut` with log level INFO.

=== Creating a Job

Create the `HelloWorldJob` class:

source:HelloWorldJob[]

callout:singleton[1]
<2> Inject a Logger.
<3> Create trigger every 10 seconds
<4> Create another trigger every 45 seconds with an initial delay of 5 seconds (5000 millis)

:exclude-for-build:maven

Now start the application. Execute the `./gradlew run` command, which will start the application on port 8080.

:exclude-for-build:

:exclude-for-build:gradle

Now start the application. Execute the `./mvnw mn:run` command, which will start the application on port 8080.

:exclude-for-build:

After a few seconds, you will see the following output:

[source, bash]
----
... Simple Job every 10 seconds :15/5/2018 12:48:02 <1>
... Simple Job every 45 seconds :15/5/2018 12:48:07 <2>
... Simple Job every 10 seconds :15/5/2018 12:48:12 <3>
... Simple Job every 10 seconds :15/5/2018 12:48:22
... Simple Job every 10 seconds :15/5/2018 12:48:32
... Simple Job every 10 seconds :15/5/2018 12:48:42
... Simple Job every 45 seconds :15/5/2018 12:48:52 <4>
... Simple Job every 10 seconds :15/5/2018 12:48:52
----

<1> First execution of 10 seconds Job after the application starts
<2> The 45 seconds Job starts 5 seconds after the application starts
<3> Second execution of 10 seconds Job 10 seconds after the first execution
<4> Second execution of 45 seconds Job 45 seconds after the first execution

=== Business logic in dedicated Use Cases

Although the previous example is valid, usually you don't want to put your business logic in a Job. A better approach is
to create an additional bean that the `Job` invokes. This approach decouples your business logic from the scheduling logic.
Moreover, it facilitates testing and maintenance. Let's see an example:

Create the following use case:

source:EmailUseCase[]

And then the Job:

source:DailyEmailJob[]

callout:singleton[1]
<2> Constructor injection.
<3> Trigger the Job once a day at 04:30 AM
<4> Call the injected use case

=== Scheduling a Job Manually

Consider the following scenario. You want to send every user an email two hours after they register on your application and ask them about their experiences during this first interaction.

For this guide, we will schedule a Job to trigger after one minute.

To test it, we will call a new use case named `RegisterUseCase` twice when the application starts.

Modify `Application.@languageextension@`:

source:Application[]

callout:singleton[1]
<2> Listen to the event `ServerStartupEvent`
<3> Constructor injection of `RegisterUseCase`
<4> `onApplicationEvent` is invoked when the application starts

As you see in the previous example, subscribing to an event is as easy as implementing `ApplicationEventListener`.

Create a runnable task `EmailTask.@languageextension@`

source:EmailTask[]

Create `RegisterUseCase.@languageextension@`, which schedules the previous task.

source:RegisterUseCase[]

<1> Constructor injection of `EmailUseCase`
<2> Inject the `TaskScheduler` bean
<3> Create a `Runnable` task
<4> Schedule the task to run a minute from now

If you execute the above code, you will see the Job being executed one minute after we schedule it and with the supplied email address.

[source, bash]
----
INFO  example.micronaut.RegisterUseCase - saving harry@micronaut.example at 15/5/2018 06:25:14
INFO  example.micronaut.RegisterUseCase - saving ron@micronaut.example at 15/5/2018 06:25:34
INFO  example.micronaut.EmailUseCase - Sending email to harry@micronaut.example : Welcome to Micronaut at 15/5/2018 06:26:14
INFO  example.micronaut.EmailUseCase - Sending email to ron@micronaut.example : Welcome to the Micronaut framework at 15/5/2018 06:26:34
----

== Summary

During this guide, we learned how to configure Jobs using the `@Scheduled` annotation using fixedDelay, initialDelay,
and cron, as well as manually configuring Jobs with a `TaskScheduler` and tasks.

include::{commondir}/common-graal-with-plugins.adoc[]

:exclude-for-languages:groovy

Execute the native image, and you will see the log message of the Jobs appear:

[source, bash]
----
$ 10:16:20.803 [pool-2-thread-1] INFO  example.micronaut.HelloWorldJob - Simple Job every 10 seconds: 09/12/2019 10:16:20
$ 10:16:20.806 [main] INFO  example.micronaut.RegisterUseCase - saving harry@micronaut.example at 09/12/2019 10:16:20
$ 10:16:25.804 [pool-2-thread-2] INFO  example.micronaut.HelloWorldJob - Simple Job every 45 seconds: 09/12/2019 10:16:25
$ 10:16:30.807 [pool-2-thread-4] INFO  example.micronaut.HelloWorldJob - Simple Job every 10 seconds: 09/12/2019 10:16:30
----

:exclude-for-languages:

include::{commondir}/common-next.adoc[]

include::{commondir}/common-helpWithMicronaut.adoc[]

