micronaut:
  application:
    name: micronautguide
---
#tag::security[]
micronaut:
  security:
    authentication: session # <1>
    redirect:
      login-success: / # <2>
      login-failure: /login/authFailed #<3>
#end::security[]