:exclude-for-languages:groovy

== Generate a Micronaut Application Native Image with GraalVM

We will use https://www.graalvm.org/[GraalVM], the polyglot embeddable virtual machine, to generate a native image of our Micronaut application.

Compiling native images ahead of time with GraalVM improves startup time and reduces the memory footprint of JVM-based applications.

NOTE: Only Java and Kotlin projects support using GraalVM's `native-image` tool. Groovy relies heavily on reflection, which is only partially supported by GraalVM.

=== Native image generation

include::{commondir}/common-install-graalvm-sdkman.adoc[]

:exclude-for-build:maven

To generate a native image using Gradle run:

[source, bash]
----
$ ./gradlew nativeImage
----

The native image is created in `build/native-image/application` and can be run with `./build/native-image/application`

It is possible to customize the name of the native image or pass additional parameters to GraalVM:

.build.gradle
[source,groovy]
----
nativeImage {
    args('--verbose')
    imageName('mn-graalvm-application') // <1>
}
----
<1> The native image name will now be `mn-graalvm-application`

:exclude-for-build:

:exclude-for-build:gradle

To generate a native image using Maven run:

[source, bash]
----
$ ./mvnw package -Dpackaging=native-image
----

The native image is created in `target/application` and can be run with `./target/application`.

:exclude-for-build:

:exclude-for-languages:
