Micronaut itself does not rely on reflection or dynamic classloading so works automatically with GraalVM native.

First, add Micronaut Graal's annotation processor that helps to handle generating the `reflection-config.json` metadata
that is automatically picked up by the `native-image` tool:

[source,groovy]
.build.gradle
----
dependencies {
...
..
.
include::{sourceDir}/../complete/build.gradle[tag=micronaut-graal]
}
----


> GraalVM Native Image allows you to ahead-of-time compile Java code to a standalone executable, called a native image.
This executable includes the application, the libraries, the JDK and does not run on the Java VM, but includes necessary
components like memory management and thread scheduling from a different virtual machine, called “Substrate VM”. Substrate
VM is the name for the runtime components (like the deoptimizer, garbage collector, thread scheduling etc.). The resulting
program has faster startup time and lower runtime memory overhead compared to a Java VM.

We need to add a dependency to `svm`:

[source,groovy]
.build.gradle
----
dependencies {
...
..
.
include::{sourceDir}/../complete/build.gradle[tag=svm]
}
----

To simplify building the image you need to create a `native-image.properties` file.
The convention is to use the folder `src/main/resources/META-INF/native-image` and then a folder following the maven coordinates of the application. For our example `example.micronaut/micronautguide`.

Add a `native-image.properties` inside  `src/main/resources/META-INF/native-image/example.micronaut/micronautguide` folder.

[source,groovy]
.src/main/resources/META-INF/native-image/example.micronaut/micronautguide/native-image.properties
----
include::{sourceDir}/../complete/src/main/resources/META-INF/native-image/example.micronaut/micronautguide/native-image.properties[]
----

- The `-H:Name` argument specifies the name of the native image that will be generated.
- The `-H:Class` argument specifies the entry point of your application (the class that defines a static void main method.
