:exclude-for-languages:groovy

== Generate a Micronaut Application Native Image with GraalVM

We will use https://www.graalvm.org/[GraalVM], the polyglot embeddable virtual machine, to generate a native image of our Micronaut application.

Compiling native images ahead of time with GraalVM improves startup time and reduces the memory footprint of JVM-based applications.

NOTE: Only Java and Kotlin projects support using GraalVM's `native-image` tool. Groovy relies heavily on reflection, which is only partially supported by GraalVM.

=== Native image generation

include::{commondir}/common-install-graalvm-sdkman.adoc[]

:exclude-for-build:maven

To generate a native image using Gradle, run:

[source, bash]
----
$ ./gradlew nativeCompile
----

The native image is created in `build/native/nativeCompile` directory and can be run with `./build/native/nativeCompile/application`.

It is possible to customize the name of the native image or pass additional parameters to GraalVM:

.build.gradle
[source,groovy]
----
graalvmNative {
    binaries {
        main {
            imageName.set('mn-graalvm-application') // <1>
            buildArgs.add('--verbose') // <2>
        }
    }
}
----
<1> The native image name will now be `mn-graalvm-application`
<2> It is possible to pass extra arguments to build the native image

:exclude-for-build:

:exclude-for-build:gradle

To generate a native image using Maven run:

[source, bash]
----
$ ./mvnw package -Dpackaging=native-image
----

The native image is created in `target/application` and can be run with `./target/application`.

:exclude-for-build:

:exclude-for-languages:
