:exclude-for-languages:groovy

== Generate a Micronaut app's Native Image with GraalVM

We will use https://www.graalvm.org/[GraalVM], the polyglot embeddable virtual machine, to generate a Native image of our Micronaut application.

Native images compiled with GraalVM ahead-of-time to improve the startup time and reduce the memory footprint of JVM-based applications.

NOTE: Use of GraalVM's `native-image` tool is only supported in Java and Kotlin projects. Groovy relies heavily on
reflection which is only partially supported by GraalVM.

=== Native Image generation

The easiest way to install GraalVM is to use https://sdkman.io/[SDKMan.io].

[source, bash]
----
# For Java 8
$ sdk install java 21.1.0.r8-grl

# For Java 11
$ sdk install java 21.1.0.r11-grl
----

You need to install the `native-image` component which is not installed by default.

[source, bash]
----
$ gu install native-image
----

:exclude-for-build:maven

To generate a native image using Gradle run:

[source, bash]
----
$ ./gradlew nativeImage
----

The native image is created in `build/native-image/application` and can be run with `./build/native-image/application`

It is possible to customize the name of the native image or pass additional parameters to GraalVM:

.build.gradle
[source,groovy]
----
nativeImage {
    args('--verbose')
    imageName('mn-graalvm-application') // <1>
}
----
<1> The native image name will now be `mn-graalvm-application`

:exclude-for-build:

:exclude-for-build:gradle

To generate a native image using Maven run:

[source, bash]
----
$ ./mvnw package -Dpackaging=native-image
----

The native image is created in `target/application` and can be run with `./target/application`.

:exclude-for-build:

:exclude-for-languages:
