== Installing Micronaut

=== SDKMan

http://sdkman.io['sdkman'] is a popular command line utility for installing and managing Micronaut installations
 (as well as other JVM frameworks and languages). Install `sdkman` by running the following command in your Unix terminal:

[source, bash]
----
$ curl -s "https://get.sdkman.io" | bash
----

Once the installation is complete, install the latest version of Micronaut (this guide uses 1.0.0.M1):

[source, bash]
----
$ sdk install micronaut 1.0.0.M1
----

`sdkman` will prompt you to choose whether to set this version as the default (choose 'yes').

[source, bash]
----
$ mn --version

| Micronaut Version: 1.0.0.M1
| JVM Version: 1.8.0_77
----

NOTE: If you are running Windows, there is a clone project of `sdkman` available that follows the same conventions. You can download it from https://github.com/flofreud/posh-gvm[https://github.com/flofreud/posh-gvm]


=== Download from Micronaut.io

This is not the recommend way to install Micronaut, but here are the manual installation steps, if the above methods fails.

Download the Grails binary package from https://micronaut.io/download.html[https://micronaut.io]. Unpack the package in a convenient directory.

[source, bash]
----
$ unzip ~/Downloads/micronaut-1.0.0.M1.zip
----

Edit your `.bashrc` (most Linux flavors) or `.bash_profile` file with the following environment variables (add these to the end of the file)

Set the `MICRONAUT_HOME` environment variable to the location where you extracted the zip

[source, bash]
----
export MICRONAUT_HOME=/path/to/micronaut-1.0.0.M1
----

On Windows you can create an environment variable under `My Computer/Advanced/Environment Variables`

Now add the Grails `bin` directory to your `PATH` variable:

[source, bash]
----
export MICRONAUT_HOME=/path/to/micronaut-1.0.0.M1
export PATH="$PATH:$MICRONAUT_HOME/bin
----

Again, on Windows you will need to modify the `Path` environment variable under `My Computer/Advanced/Environment Variables`

You should now be able to type `mn --version` in the terminal window and verify that Grails has been installed successfully:

[source, bash]
----
$ mn --version

| Micronaut Version: 1.0.0.M1
| JVM Version: 1.8.0_77
----
