micronaut:
  application:
    name: complete
---
#tag::security[]
micronaut:
  security:
    authentication: cookie # <1>
    redirect:
      login-failure: /login/authFailed  # <2>
    token:
      jwt:
        signatures:
          secret:
            generator:  # <3>
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"' # <4>
#end::security[]
