external:micronaut-email/header.adoc[]

external:micronaut-email/controller.adoc[]

external:micronaut-email/configuration.adoc[]

=== AWS SES

____
Amazon Simple Email Service (Amazon SES) is a cloud-based email sending service designed to help digital marketers and application developers send marketing, notification, and transactional emails. It is a reliable, cost-effective service for businesses of all sizes that use email to keep in contact with their customers.
____

==== Dependency

Because we added `email-ses` feature, the application contains the following dependency:

dependency:micronaut-email-ses[groupId=com.micronaut.email]

=== Micronaut AWS SDK v2

Micronaut Amazon SES integration uses https://micronaut-projects.github.io/micronaut-aws/latest/guide/#sdkv2[Micronaut AWS SDK v2 integration].

Because we added `aws-v2-sdk` feature, the application contains the following dependency:

dependency:micronaut-aws-sdk-v2[groupId=io.micronaut.aws]

Read about:

* https://micronaut-projects.github.io/micronaut-aws/latest/guide/#awsCredentials[Supplying AWS Credentials].
* Select https://micronaut-projects.github.io/micronaut-aws/latest/guide/#awsRegionSelection[AWS Region Selection]
* https://micronaut-projects.github.io/micronaut-aws/latest/guide/#ses[SES beans]

external:micronaut-email/test.adoc[]

=== Running the Application

==== From email address

Change the property `mail.email.from.email` to match your Amazon SES verified sender.

==== Supply AWS Credentials

An easy way to https://micronaut-projects.github.io/micronaut-aws/latest/guide/#awsCredentials[supply AWS Credentials] is to define the following environment variables:

[source, bash]
----
export AWS_ACCESS_KEY_ID=xxx
export AWS_SECRET_ACCESS_KEY=xxx
----

==== Run

common:runapp-instructions.adoc[]

==== Invoke

[source, bash]
----
curl -d '{"to":"john@micronaut.example"}'
     -H "Content-Type: application/json"
     -X POST http://localhost:8080/mail/send
----

external:micronaut-email/next.adoc[]

common:helpWithMicronaut.adoc[]
