micronaut:
  application:
    name: micronautguide
  http:
    client:
      read-timeout: 120s
#tag::db[]
db:
  name: 'fruit'
  collection: 'fruit'
#end::db[]
# Required for pre TestResources 1.1
test-resources:
  containers:
    mongodb:
      image-name: mongo:5