micronaut:
  application:
    name: micronautguide
---
#tag::mongodb[]
mongodb:
  uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
#end::mongodb[]
---
#tag::db[]
db:
  name: 'fruit'
  collection: 'fruit'
#end::db[]
