common:header.adoc[]

common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app-features.adoc[]

=== Properties

Create a default `messages.properties` file:

resource:i18n/messages.properties[]

Create a `messages_es.properties` file for Spanish locale:

resource:i18n/messages_es.properties[]

=== Message Source

Create a `MessageSource` that uses the previous properties files:

source:MessageSourceFactory[]

callout:factory[]
callout:singleton[]

=== Controller

source:HelloWorldController[]

:exclude-for-languages:python

callout:controller[arg0=/]
callout:constructor-di[arg0=LocalizedMessageSource]
callout:produces[]
<4> https://docs.micronaut.io/latest/api/io/micronaut/context/LocalizedMessageSource.html[LocalizedMessageSource] contains methods to fetch a message with a code, a default message, or variables.

:exclude-for-languages:

:only-for-languages:python

<1> Inject a bean of type `LocalizedMessageSource`.
<2> Set the response content-type to `TEXT_PLAIN`.
<3> The https://docs.micronaut.io/latest/api/io/micronaut/http/annotation/Get.html[@Get] annotation maps the function to an HTTP GET request.
<4> https://docs.micronaut.io/latest/api/io/micronaut/context/LocalizedMessageSource.html[LocalizedMessageSource] contains methods to fetch a message with a code, a default message, or variables.

:only-for-languages:

=== Tests

test:HelloWorldControllerTest[]

callout:micronaut-test[]
callout:http-client[]
callout:http-request[]

common:testApp.adoc[]

== Learn More

The application changes the locale with the `Accept-Language` HTTP header. Learn more about https://docs.micronaut.io/latest/guide/#localeResolution[Locale Resolution].
