common:header.adoc[]

common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app-features.adoc[]

=== Properties

Create a default `messages.properties` file:

resource:i18n/messages.properties[]

Create a `messages_es.properties` file for Spanish locale:

resource:i18n/messages_es.properties[]

=== Message Source

Create a `MessageSource` that uses the previous properties files:

source:MessageSourceFactory[]

<1> callout:factory[]
<2> callout:singleton[]

=== Controller

source:HelloWorldController[]

<1> callout:controller[arg0=/]
<2> callout:constructor-di[arg0=LocalizedMessageSource]
<3> callout:produces[]
<4> https://docs.micronaut.io/latest/api/io/micronaut/context/LocalizedMessageSource.html[LocalizedMessageSource] contains methods to fetch a message with a code, a default message, or variables.

=== Tests

test:HelloWorldControllerTest[]

<1> callout:micronaut-test[]
<2> callout:http-client[]
<3> callout:http-request[]

common:testApp.adoc[]

== Learn More

The application changes the locale with the `Accept-Language` HTTP Header. Learn more about https://docs.micronaut.io/latest/guide/#localeResolution[Locale Resolution].
