micronaut.application.name=micronautguide
#tag::liquibase[]
liquibase.datasources.default.change-log=classpath\:db/liquibase-changelog.xml
#end::liquibase[]
#tag::datasource[]
datasources.default.schema-generate=NONE
datasources.default.url=jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE ALIAS IF NOT EXISTS H2GIS_SPATIAL FOR "org.h2gis.functions.factory.H2GISFunctions.load"\\;CALL H2GIS_SPATIAL()
datasources.default.username=sa
datasources.default.password=
# <1>
datasources.default.driver-class-name=org.h2.Driver
# <2>
datasources.default.db-type=h2
# <3>
datasources.default.dialect=H2
#end::datasource[]
