micronaut.application.name=micronautguide
micronaut.security.authentication=cookie
micronaut.security.token.refresh.cookie.enabled=false
micronaut.security.token.jwt.signatures.secret.generator.secret="${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"
micronaut.security.intercept-url-map[0].pattern=/**
micronaut.security.intercept-url-map[0].http-method=GET
micronaut.security.intercept-url-map[0].access[0]=isAnonymous()
micronaut.security.intercept-url-map[1].pattern=/**
micronaut.security.intercept-url-map[1].http-method=POST
micronaut.security.intercept-url-map[1].access[0]=isAnonymous()
graphql.graphiql.enabled=true
