common:header.adoc[]

common:google-cloud-registry.adoc[]

The docker image runs a https://www.graalvm.org/reference-manual/native-image/[GraalVM Native Executable] of the Micronaut application.

> Develop and deploy highly scalable containerized applications on a fully managed serverless platform.

common:gcp-deploy-requirements2content.adoc[]

== Docker Push Native

Before attempting to push the image, make sure you run GraalVM JDK.

common:install-graalvm-sdkman.adoc[]

Push the Docker image of your application to https://cloud.google.com/container-registry[Google Cloud Container Registry].

:exclude-for-build:

:exclude-for-build:maven

Modify your Gradle build and configure the

[source,groovy]
----
...
..
.
dockerBuildNative {
    images = ["gcr.io/micronaut-guides-xxxxxx/micronautguide:latest"]
}
----

:exclude-for-build:

common:docker-push-native-gradle.adoc[]

:exclude-for-build:gradle

[source, bash]
----
./mvnw deploy \
     -Dpackaging=docker-native \
     -Djib.to.image=gcr.io/micronaut-guides-xxxxxx/micronautguide:latest
----

:exclude-for-build:

The previous URL uses the pattern: `gcr.io/micronaut-guides-xxxxxx/micronautguide:latest`. Change it to use your Project ID.

You get an output such as:

[source, bash]
----
....
..
.
Pushing image 'gcr.io/micronaut-guides-xxxxxx/micronautguide:latest'.
----

== Google Cloud Run Deploy

You can deploy to Google Cloud Run via the CLI. Use the value you configured in your build as the image argument's value.

[source, bash]
----
gcloud run deploy \
    --image=gcr.io/micronaut-guides-xxxxxx/micronautguide:latest \
    --platform managed \
    --allow-unauthenticated
----

common:google-cloud-run-deploy-plain.adoc[]

== Next steps

You will probably want to deploy to Google Cloud Run from your CI server. https://launch.micronaut.io[Micronaut Launch] contains feature https://micronaut.io/launch?type=DEFAULT&features=github-workflow-google-cloud-run-graalvm[github-workflow-google-cloud-run-graalvm], which adds a https://github.com/features/actions[GitHub Actions] Workflow that deploys a GraalVM Native executable of a Micronaut application to Google Cloud Run from Google Container Registry.

common:google-cloud-run-next.adoc[]