#tag::mn[]
# <1>
[micronaut.application]
name = "bookinventory"
#end::mn[]

#tag::server[]
# <1>
[micronaut.server]
port = 8082
#end::server[]

[endpoints.health]
enabled = true
sensitive = false

#tag::consul[]
[consul.client.registration]
enabled = true

[consul.client]
default-zone = "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
#end::consul[]
