common:header.adoc[]

common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app-features.adoc[]

common:micronaut-views-thymeleaf.adoc[]

=== API Response

For this guide, we will use a publicly available REST API https://jsonplaceholder.typicode.com/[jsonplaceholder.typicode.com] as a 3rd party *Photo API*.

Create a `Photo` type to map the API response:

source:Photo[]

callout:serdeable[]
callout:reflective-access[]

:exclude-for-languages:python
Thymeleaf accesses `Photo` via reflection. By adding the `@ReflectiveAccess` annotation, the Micronaut Graal annotation processor generates the necessary reflection metadata to generate a Native Image with https://graalvm.org[GraalVM].
:exclude-for-languages:

:exclude-for-languages:java
Thymeleaf accesses `Photo` via reflection. By adding the `@ReflectiveAccess` annotation, the application enables reflective access to the `Photo` type.
:exclude-for-languages:

=== HTTP Client

Add a https://docs.micronaut.io/latest/guide/#httpClient[Micronaut declarative HTTP Client]:

source:PhotosClient[]

callout:client[]
callout:get[arg0=findById,arg1=/photos/{id}]
callout:pathvariable[]

=== HTTP Client Configuration

We used `photos` as the HTTP Client identifier.

Configure the `micronaut.http.services.photos.url` to point the client identifier to https://jsonplaceholder.typicode.com/[jsonplaceholder.typicode.com]

:exclude-for-languages:python
resource:application.properties[tag=clienturl]
:exclude-for-languages:

:exclude-for-languages:java
resource:application.toml[tag=clienturl]
:exclude-for-languages:

=== Controller

Create a controller, which invokes the declarative HTTP client:

source:PhotosController[]

callout:controller[arg0=/photos]
callout:constructor-di[arg0=PhotosClient]
callout:produces-html[]
callout:executes-on[]
callout:view[]
callout:get[arg0=findById,arg1=/photos/{id}]
callout:pathvariable[]

=== Thymeleaf template

:exclude-for-languages:python
Create a Thymeleaf template in `src/main/resources/views/photos/show.html`:
:exclude-for-languages:

:exclude-for-languages:java
Create a Thymeleaf template in `config/views/photos/show.html`:
:exclude-for-languages:

resource:views/photos/show.html[]

=== Tests

Write a test that verifies the application renders the HTML page.

test:PhotosControllerTest[]

callout:micronaut-test[]
callout:http-client[]

common:testApp.adoc[]

:exclude-for-languages:python
common:nativetest.adoc[]
:exclude-for-languages:

common:next.adoc[]

Read more about https://micronaut-projects.github.io/micronaut-views/latest/guide/[Micronaut Views].

common:helpWithMicronaut.adoc[]
