common:header.adoc[]

common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app-features.adoc[]

common:micronaut-views-thymeleaf.adoc[]

=== API Response

For this guide, we will use a publicly available REST API https://jsonplaceholder.typicode.com/[jsonplaceholder.typicode.com] as a 3rd party *Photo API*.

Create a `Photo` record to map the API response:

source:Photo[]

<1> callout:serdeable[]
<2> callout:reflective-access[]

Thymeleaf accesses `Photo` via reflection. By adding the `@ReflectiveAccess` annotation, the Micronaut Graal annotation processor generates the necessary reflection metadata to generate a Native Image with https://graalvm.org[GraalVM].

=== HTTP Client

Add a https://docs.micronaut.io/latest/guide/#httpClient[Micronaut declarative HTTP Client]:

source:PhotosClient[]

<1> callout:client[]
<2> callout:get[arg0=findById,arg1=/photos/{id}]
<3> callout:pathvariable[]

=== HTTP Client Configuration

We used `photos` as the HTTP Client identifier.

Configure the `micronaut.http.services.photos.url` to point the client identifier to https://jsonplaceholder.typicode.com/[jsonplaceholder.typicode.com]

resource:application.properties[tag=clienturl]

=== Controller

Create a controller, which invokes the declarative HTTP client:

source:PhotosController[]

<1> callout:controller[arg0=/photos]
<2> callout:constructor-di[arg0=PhotosClient]
<3> callout:produces-html[]
<4> callout:executes-on[]
<5> callout:view[]
<6> callout:get[arg0=findById,arg1=/photos/{id}]
<7> callout:pathvariable[]

=== Thymeleaf template

Create a Thymeleaf template in `src/main/resources/views/photos/show.html`:

resource:views/photos/show.html[]

=== Tests

Write a test that verifies the application renders the HTML page.

test:PhotosControllerTest[]

<1> callout:micronaut-test[]
<2> callout:http-client[]

common:testApp.adoc[]

common:nativetest.adoc[]

common:next.adoc[]

Read more about https://micronaut-projects.github.io/micronaut-views/latest/guide/[Micronaut Views].

common:helpWithMicronaut.adoc[]