# tag::client[]
[micronaut.ssl]
# <1>
port = -1

# <2>
[micronaut.http.client.ssl.key-store]
path = "classpath:ssl/client.p12"
# <3>
password = "secret"
# <4>
type = "PKCS12"

[micronaut.http.client.ssl]
# <5>
insecure-trust-all-certificates = true
# end::client[]

[micronaut.server.ssl.key-store]
password = "secret"

[micronaut.server.ssl.trust-store]
password = "secret"
