micronaut:
  application:
    name: bookcatalogue
endpoints:
  health:
    enabled: true
    sensitive: false
#tag::jaeger[]
otel:
  traces:
    exporter: otlp
  exporter:
    otlp:
      endpoint: http://localhost:4317 # Jaeger supports OTLP directly. The default port for OTLP/gRPC is 4317
#end::jaeger[]
