common:header.adoc[]

common:requirements.adoc[]

common:oracle-cloud-account.adoc[]

common:oracle-cloud-cli.adoc[]

== Oracle Cloud Vault

https://docs.oracle.com/en-us/iaas/Content/KeyManagement/Concepts/keyoverview.htm[Oracle Cloud Vault] lets you securely store and retrieve secrets such as passwords or other information that shouldn't be accessible in cleartext.

In this guide we'll use Vault to store database connection information for a Micronaut application that uses MySQL, and use the Micronaut support for Oracle Cloud to make the process seamless.

== The Application

Download the complete solution of the guideLink:micronaut-data-jdbc-repository[Access a database with Micronaut Data JDBC] guide. You will use the sample application as a starting point.

== Creating an Oracle Cloud Vault

We'll do the work of creating the vault with the Oracle Cloud CLI. See the https://docs.oracle.com/en-us/iaas/tools/oci-cli/3.7.1/oci_cli_docs/cmdref/kms.html[Vault CLI command reference] for more information.

NOTE: If you prefer to use the Oracle Cloud web console to create the vault, follow the steps in the "Using Oracle Cloud Vault" section of the guideLink:micronaut-oracle-autonomous-db[Access an Oracle Autonomous Database] guide.

There are three required parameters for the create command; compartment OCID, display name, and vault type.

common:oracle-cloud-compartment-id.adoc[]

=== Create the Vault

Choose a display name (1-100 characters) and a vault type, either `DEFAULT` or `VIRTUAL_PRIVATE`. We recommend that you choose `DEFAULT` to avoid the cost of a virtual private vault.

Run the https://docs.oracle.com/en-us/iaas/tools/oci-cli/3.7.1/oci_cli_docs/cmdref/kms/management/vault/create.html[create command] with the compartment OCID, display name, and vault type substituted:

[source,bash]
----
oci kms management vault create -c $C \
    --display-name mn_guide_vault \
    --vault-type DEFAULT
----

The response should look like this:

[source,json]
----
{
  "data": {
    "compartment-id": "ocid1.tenancy.oc1..aaaaaaaaixksuiqo3rx6...",
    "crypto-endpoint": null,
    "defined-tags": {},
    "display-name": "mn_guide_vault",
    "freeform-tags": {},
    "id": "ocid1.vault.oc1.iad.b5re3....abuwcljryp5dmxbu3si7...",
    "is-primary": true,
    "lifecycle-state": "CREATING",
    "management-endpoint": null,
    "replica-details": null,
    "restored-from-vault-id": null,
    "time-created": "2022-04-05T12:35:22.665000+00:00",
    "time-of-deletion": null,
    "vault-type": "DEFAULT",
    "wrappingkey-id": ""
  },
  "etag": "b577fd72830444583aa6..."
}
----

Save the vault OCID from the `id` property in the response; this is the unique identifier for your vault and you'll need it later.

==== Create a Master Encryption Key

Next we need to https://docs.oracle.com/en-us/iaas/Content/KeyManagement/Tasks/managingkeys.htm[create a Master Encryption Key].

For this we need the management endpoint URL that wasn't available yet in the response from the vault `create` command. Run the https://docs.oracle.com/en-us/iaas/tools/oci-cli/2.9.4/oci_cli_docs/cmdref/kms/management/vault/get.html[get command] with the vault OCID substituted:

[source,bash]
----
oci kms management vault get --vault-id ocid1.vault.oc1.iad.b5re3....abuwcljryp5dmxbu3si7...
----

The response should look like this:

[source,json]
----
{
  "data": {
    "compartment-id": "ocid1.tenancy.oc1..aaaaaaaaixksuiqo3rx6...",
    "crypto-endpoint": "https://b5re3...-crypto.kms.us-ashburn-1.oraclecloud.com",
    ...,
    "display-name": "mn_guide_vault",
    "freeform-tags": {},
    "id": "ocid1.vault.oc1.iad.b5re3....abuwcljryp5dmxbu3si7...",
    "is-primary": true,
    "lifecycle-state": "ACTIVE",
    "management-endpoint": "https://b5re3...-management.kms.us-ashburn-1.oraclecloud.com",
    ...
  },
  "etag": "b577fd72830444583aa6..."
}
----

It will take a few minutes for the vault to finish provisioning. Re-run the `get` command until the value of `lifecycle-state` is `ACTIVE`. The URL is available in the `management-endpoint` property.

Choose a name for the key, e.g., "mn-guide-encryption-key", and a "Protection Mode", either to `SOFTWARE` or `HSM`. We recommend that you choose `SOFTWARE` to avoid the cost of using a hardware security module (HSM). You also need to decide on a key shape algorithm and key length; for this guide we'll use `AES` and a key length of 32 (256 bits).

Run the https://docs.oracle.com/en-us/iaas/tools/oci-cli/3.7.1/oci_cli_docs/cmdref/kms/management/key/create.html[create command] with the compartment OCID, display name, protection mode, key shape, and management endpoint substituted:

[source,bash]
----
oci kms management key create -c $C \
    --display-name mn-guide-encryption-key \
    --protection-mode SOFTWARE \
    --key-shape '{"algorithm":"AES","length":"32"}' \
    --endpoint https://b5re3...-management.kms.us-ashburn-1.oraclecloud.com
----

NOTE: If you use Windows, escape the inner double quotes in the value for `key-shape`: `'{\"algorithm\":\"AES\",\"length\":\"32\"}`

The response should look like this:

[source,json]
----
{
  "data": {
    "compartment-id": "ocid1.tenancy.oc1..aaaaaaaaixksuiqo3rx6...",
    "current-key-version": "ocid1.keyversion.oc1.iad.b5re3.....awegmjgzmniaa.abuwc...",
    "defined-tags": {},
    "display-name": "mn-guide-encryption-key",
    "freeform-tags": {},
    "id": "ocid1.key.oc1.iad.b5re3.....abuwcljrcuie7t6gctc6...",
    "is-primary": true,
    "key-shape": {
      "algorithm": "AES",
      "curve-id": null,
      "length": 32
    },
    "lifecycle-state": "CREATING",
    "protection-mode": "SOFTWARE",
    "replica-details": null,
    "restored-from-key-id": null,
    "time-created": "2022-04-05T13:31:33.634000+00:00",
    "time-of-deletion": null,
    "vault-id": "ocid1.vault.oc1.iad.b5re3....abuwcljryp5dmxbu3si7..."
  },
  "etag": "e9fedb409a0edf1a2453..."
}
----

== Using Vault with Micronaut

=== micronaut-oraclecloud-vault Dependency

The https://micronaut-projects.github.io/micronaut-oracle-cloud/latest/guide/#vault[micronaut-oracle-cloud] subproject provides integration between Micronaut apps and Oracle Cloud, including using Vault as a distributed configuration source. Add a dependency to your build for the `micronaut-oraclecloud-vault` library to add Vault support:

dependency:micronaut-oraclecloud-vault[groupId=io.micronaut.oraclecloud]

=== Configuration changes

==== bootstrap.yml

Create `src/main/resources/bootstrap.yml` with just the `micronaut.application.name` property:

[source,yaml]
.src/main/resources/bootstrap.yml
----
micronaut:
  application:
    name: micronautguide
----

and delete the `micronaut.application.name` property from `application.yml` so it's only declared once:

[source,yaml]
.src/main/resources/application.yml
----
micronaut:
  executors:
    io:
      type: fixed
      nThreads: 75
datasources:
  default:
    url: ${JDBC_URL:`jdbc:mysql://localhost:3306/db`}
    username: ${JDBC_USER:root}
    password: ${JDBC_PASSWORD:}
    dialect: MYSQL
    driverClassName: ${JDBC_DRIVER:com.mysql.cj.jdbc.Driver}
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      enabled: true
----

==== bootstrap-oraclecloud.yml

Then create `src/main/resources/bootstrap-oraclecloud.yml` with the following content:

[source,yaml]
.src/main/resources/bootstrap-oraclecloud.yml
----
micronaut:
  config-client:
    enabled: true
oci:
  config:
    instance-principal:
      enabled: true # <1>
  vault:
    config:
      enabled: true
    vaults:
      - ocid: # <2>
        compartment-ocid: # <3>
----

<1> We'll use https://micronaut-projects.github.io/micronaut-oracle-cloud/latest/guide/#instance-principals[Instance Principal authentication] to allow the Micronaut application to access Vault
<2> Set the value of the `ocid` property with the vault OCID unique identifier you saved when creating the vault.
<3> Set the value of the `compartment-ocid` property with the OCID unique identifier of the compartment where you created the vault and secrets

== MySQL Database

Use the guideLink:micronaut-cloud-database-oracle[Deploy a Micronaut MySQL Database Application to Oracle Cloud] guide to create a MySQL database; follow the steps in the "Creating a MySQL DB System at Oracle Cloud" section.

== Deploying the Application

Use the guideLink:micronaut-oracle-cloud[Deploy a Micronaut application to Oracle Cloud] guide to create a compute instance and deploy the application to it; follow the steps in the "Create an Oracle Cloud Compute Instance" and "Deploy to Oracle Cloud" sections up to the step where you start the application. We need to connect the application to the MySQL database before starting it up.

NOTE: When creating the compute VM at Oracle Cloud, use the same subnet as the one where you created the MySQL database, otherwise the application will not be able to access the database.

== Configuring MySQL Access

Use the guideLink:micronaut-cloud-database-oracle[Deploy a Micronaut MySQL Database Application to Oracle Cloud] guide to configure access to the MySQL database; follow the steps in the "Configure MySQL" section. You will need the private IP address of the VM, the MySQL private IP address, and the admin username and password you chose when creating the database.

== Creating Secrets

In the guideLink:micronaut-data-jdbc-repository[Access a database with Micronaut Data JDBC] guide, the values for the JDBC URL, database username and password, and the JDBC driver class are "externalized" properties with default values:

[source,yaml]
.application.yml
----
datasources:
  default:
    url: ${JDBC_URL:`jdbc:mysql://localhost:3306/db`}
    username: ${JDBC_USER:root}
    password: ${JDBC_PASSWORD:}
    dialect: MYSQL
    driverClassName: ${JDBC_DRIVER:com.mysql.cj.jdbc.Driver}
----

The guide recommends that you set environment variables to override the default values, but in this guide we'll go a step further and store some of those values in our Oracle Cloud Vault. We'll leave the default for the driver class, but create vault secrets for `JDBC_USER`, `JDBC_PASSWORD`, and `JDBC_URL`.

=== JDBC_USER

The first secret will be for the database username, so the secret name will be `JDBC_USER`.

Secret values must be Base64-encoded. You can encode the value programmatically, e.g., `Base64.getEncoder().encodeToString("the value")`, or use an online tool such as https://www.base64encode.org/.

Run the https://docs.oracle.com/en-us/iaas/tools/oci-cli/3.7.1/oci_cli_docs/cmdref/vault/secret/create-base64.html[create-base64 command] with the compartment OCID, encryption key OCID, vault OCID, secret name, and Base64-encoded secret value substituted. If you used `guide_user` as the username, the Base64-encoded value will be `Z3VpZGVfdXNlcg==`

[source,bash]
----
oci vault secret create-base64 -c $C \
    --key-id ocid1.key.oc1.iad.b5re3.....abuwcljrcuie7t6gctc6... \
    --vault-id ocid1.vault.oc1.iad.b5re3....abuwcljryp5dmxbu3si7... \
    --secret-name JDBC_USER \
    --secret-content-content Z3VpZGVfdXNlcg==
----

Note that running that command will leave the Base64-encoded value in your shell history. To avoid this, you can create a JSON file containing the parameters and pass that as an argument to the command.

To use this approach, create a file like this with values substituted, and save it as key.json:

[source,json]
----
{
   "compartmentId": "ocid1.compartment.oc1..aaaaaaaarkh3s2wcxbbm...",
   "keyId": "ocid1.key.oc1.iad.b5re3.....abuwcljrcuie7t6gctc6...",
   "vaultId": "ocid1.vault.oc1.iad.b5re3....abuwcljryp5dmxbu3si7...",
   "secretName": "JDBC_USER",
   "secretContentContent": "Z3VpZGVfdXNlcg=="
}
----

and run this `create-base64` command instead:

[source,bash]
----
oci vault secret create-base64 --from-json file://key.json
----

With either approach the response should look like this:

[source,json]
----
{
  "data": {
    "compartment-id": "ocid1.compartment.oc1..aaaaaaaarkh3s2wcxbbm...",
    "current-version-number": 1,
    "description": null,
    "freeform-tags": {},
    "id": "ocid1.vaultsecret.oc1.iad.amaaaaaafzr7royabqgz...",
    "key-id": "ocid1.key.oc1.iad.b5re3.....abuwcljrcuie7t6gctc6...",
    "lifecycle-details": null,
    "lifecycle-state": "CREATING",
    "metadata": null,
    "secret-name": "JDBC_USER",
    "secret-rules": null,
    "time-created": "2022-04-05T14:16:17.458000+00:00",
    "time-of-current-version-expiry": null,
    "time-of-deletion": null,
    "vault-id": "ocid1.vault.oc1.iad.b5re3....abuwcljryp5dmxbu3si7..."
  },
  "etag": "f1f1f91fc7008ccce876..."
}
----

=== JDBC_PASSWORD

Create a second secret with the name `JDBC_PASSWORD`. The value will be the Base64-encoded database user password you chose earlier.

=== JDBC_URL

Create a third secret with the name `JDBC_URL`. The URL will be `jdbc:mysql://<MySQL IP address>:3306/micronaut` with the private IP address of your MySQL database substituted. Set the value of the secret as the Base64-encoded URL value.

== Instance Principal authentication

We'll use https://micronaut-projects.github.io/micronaut-oracle-cloud/latest/guide/#instance-principals[Instance Principal authentication] to allow the Micronaut application to retrieve secrets from Vault. To use this, we need to create a dynamic group and add a policy statement granting permission.

NOTE: If you prefer to use the Oracle Cloud web console to create the dynamic group and policy statements, follow the steps in the "Instance Principal authentication" section of the guideLink:micronaut-oracle-cloud-streaming[Oracle Cloud Streaming and the Micronaut Framework - Event-Driven Applications at Scale] guide.

=== Dynamic Group

Choose a group name, e.g., "mn-guide-dg", and a matching rule, i.e., the logic that will be used to determine group membership. We'll make the rule fairly broad - use `ALL {instance.compartment.id = 'ocid1.compartment.oc1..aaaaaaaarkh3s2wcxbbm...'}` replacing `ocid1.compartment.oc1..aaaaaaaarkh3s2wcxbbm...` with the compartment OCID:

Run the https://docs.oracle.com/en-us/iaas/tools/oci-cli/2.9.2/oci_cli_docs/cmdref/iam/dynamic-group/create.html[create command] with the compartment OCID substituted:

[source,bash]
----
oci iam dynamic-group create \
   --name mn-guide-dg \
   --description mn-guide-dg \
   --matching-rule "ALL {instance.compartment.id = 'ocid1.compartment.oc1..aaaaaaaarkh3s2wcxbbm...'}"
----

The response should look like this:

[source,json]
----
{
  "data": {
    "compartment-id": "ocid1.tenancy.oc1..aaaaaaaaud4g4e5ovjaw...",
    "defined-tags": {},
    "description": "mn-guide-dg",
    "freeform-tags": {},
    "id": "ocid1.dynamicgroup.oc1..aaaaaaaatjclr6ne7q2i...",
    "inactive-status": null,
    "lifecycle-state": "ACTIVE",
    "matching-rule": "ALL {instance.compartment.id = 'ocid1.compartment.oc1..aaaaaaaarkh3s2wcxbbm...'}",
    "name": "mn-guide-dg",
    "time-created": "2022-04-06T02:33:00.571000+00:00"
  },
  "etag": "70443ddd9daf8d841399..."
}
----

Save the value for `compartment-id` from the response; we'll need it in the next step to create the policy.

See the https://docs.oracle.com/en-us/iaas/Content/Identity/Tasks/managingdynamicgroups.htm[Dynamic Group docs] for more information.

=== Dynamic Group Policy Statements

Next, create the policy granting read access to Vault.

We'll create the policy in the root compartment, i.e., the tenancy, so we'll use the tenancy OCID saved from the dynamic group creation response.

Run the https://docs.oracle.com/en-us/iaas/tools/oci-cli/2.9.2/oci_cli_docs/cmdref/iam/policy/create.html[create command] with the tenancy OCID substituted:

[source,bash]
----
oci iam policy create -c ocid1.tenancy.oc1..aaaaaaaaud4g4e5ovjaw... \
    --name mn-guide-policy \
    --description mn-guide-policy \
    --statements '["allow dynamic-group mn-guide-dg to read secret-family in tenancy"]'
----

The response should look like this:

[source,json]
----
{
  "data": {
    "compartment-id": "ocid1.tenancy.oc1..aaaaaaaaud4g4e5ovjaw...",
    "defined-tags": {},
    "description": "mn-guide-policy",
    "freeform-tags": {},
    "id": "ocid1.policy.oc1..aaaaaaaau7uhwxr3ynlr...",
    "inactive-status": null,
    "lifecycle-state": "ACTIVE",
    "name": "mn-guide-policy",
    "statements": [
      "allow dynamic-group mn-guide-dg to read secret-family in tenancy"
    ],
    "time-created": "2022-04-06T03:48:23.662000+00:00",
    "version-date": null
  },
  "etag": "60c9d220133f315bb11c..."
}
----

== Start the application

Finally, start the application. From the SSH session into your VM, run:

[source,bash]
----
java -jar application.jar
----

Verify that the application is working correctly with some cURL commands.

Create a genre by running

[source,bash]
----
curl -X POST http://[VM IP Address]:8080/genres \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{ "name": "music" }'
----

The response should look like this:

[source,json]
----
{"id":1,"name":"music"}
----

List all genres by running

[source,bash]
----
curl http://[VM IP Address]:8080/genres/list
----

The response should look like this:

[source,json]
----
[{"id":1,"name":"music"}]
----

common:next.adoc[]

Read more about the https://micronaut-projects.github.io/micronaut-oracle-cloud/latest/guide/[Micronaut Oracle Cloud] integration.
