common:header.adoc[]

common:costs-gcloud.adoc[]

common:requirements.adoc[]
* You need a https://cloud.google.com/gcp/[Google Cloud Platform (GCP)] account and a GCP project.

common:gcp-cloudsql.adoc[]

common:completesolution.adoc[]

common:create-app-features.adoc[]

common:gcp.adoc[]

common:gcp-billing.adoc[]

== Dependency

dependency:mysql-socket-factory[groupId=com.google.cloud.sql,version=@mysqlSocketFactoryVersion@]

== Data Source Configuration

source:GoogleCloudSqlSetup[]

callout:singleton[1]

== Google Cloud Run Deploy

You can deploy to Google Cloud Run via the CLI. Use the value you configured in your build as the image argument's value.

[source, bash]
----
gcloud run deploy \
    --image=gcr.io/micronaut-guides-xxxxxx/micronautguide:latest \
    --platform managed \
    --execution-environment=gen2 \
    --allow-unauthenticated
----

common:google-cloud-run-deploy-json.adoc[]

== Cleanup

common:gcloud-run-services-delete[]

common:gcloud-delete-project[]

== Next steps

Read more about:

common:crac-next.adoc[]
common:google-cloud-run-next.adoc[]

common:helpWithMicronaut.adoc[]
