micronaut:
  application:
    name: complete
---
#tag::security[]
micronaut:
  application:
    name: micronautguide
  security:
    authentication: bearer # <1>
    token:
      jwt:
        signatures:
          secret:
            generator: # <2>
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"' # <3>
#end::security[]
---
#tag::ldap[]
micronaut:
  security:
    ldap:
      default: # <1>
        context:
          server: 'ldaps://db.debian.org'  # <2>
          managerDn: 'cn=read-only-admin,dc=debian,dc=org'  # <3>
          managerPassword: 'password'  # <4>
        search:
          base: "dc=debian,dc=org"  # <5>
        groups:
          enabled: true  # <6>
          base: "dc=debian,dc=org" # <7>
#end::ldap[]
---
#tag::datasource[]
dataSource:
  url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  driverClassName: org.h2.Driver
  username: sa
  password: ''
  pooled: true
  jmxExport: true
hibernate:
  hbm2ddl:
    auto: update
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
#end::datasource[]
