micronaut:
  application:
    name: bookrecommendation
endpoints:
  health:
    enabled: true
    sensitive: false
#tag::otel[]
otel:
  traces:
    exporter: otlp
    propagator: tracecontext, baggage, xray
    exclusions: /health
#end::otel[]
---
micronaut:
  http:
    services:
      bookcatalogue:
        url: 'http://localhost:8081'
      bookinventory:
        url: 'http://localhost:8082'