= @guideTitle@

@guideIntro@

Authors: @authors@

Micronaut Version: @micronaut@

include::{commondir}/common-gettingStarted.adoc[]

include::{commondir}/common-requirements.adoc[]

include::{commondir}/common-completesolution.adoc[]

include::{commondir}/common-create-app.adoc[]


=== Application

`Application.@languageextension@` is used when running the application via Gradle or via deployment. You can also run the main class directly within your IDE if it is configured correctly.

source:Application[]

=== Controller

In order to create a microservice that responds with "Hello World" you first need a controller.

Create a Controller:

source:HelloController[]

<1> The class is defined as a controller with the https://docs.micronaut.io/latest/api/io/micronaut/http/annotation/Controller.html[@Controller] annotation mapped to the path `/hello`
<2> The https://docs.micronaut.io/latest/api/io/micronaut/http/annotation/Get.html[@Get] annotation is used to map the index method to all requests that use an HTTP GET
<3> By default a Micronaut's response uses `application/json` as `Content-Type`. We are returning a String not a JSON object. Because of that, we set it to `text/plain`.
<4> A String "Hello World" is returned as the result

=== Test

Create a test which verifies that when you do a GET request to `/hello` you get `Hello World` as a response:

test:HelloControllerTest[]

<1> Annotate the class with `@MicronautTest` so Micronaut will initialize the application context and the embedded server.
<2> Inject the `RxHttpClient` bean. It is used the execute an HTTP call to the controller.
<3> Creating HTTP Requests is easy thanks to Micronaut's fluid API.

include::{commondir}/common-testApp.adoc[]

include::{commondir}/common-runapp.adoc[]

include::{commondir}/common-graal-with-plugins.adoc[]

:exclude-for-languages:groovy

You can execute the endpoint exposed by the native image:

[source, bash]
----
$ curl localhost:8080/hello
Hello World
----

:exclude-for-languages:

== Next steps

Read more about https://micronaut-projects.github.io/micronaut-test/latest/guide/index.html[Micronaut testing].

include::{commondir}/common-helpWithMicronaut.adoc[]
