common:header.adoc[]

common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app.adoc[]

=== Application

`Application.@languageextension@` is used when running the application via Gradle or via deployment. You can also run the main class directly within your IDE if it is configured correctly.

source:Application[]

=== Controller

In order to create a microservice that responds with "Hello World" you first need a controller.

Create a Controller:

source:HelloController[]

callout:controller[number=1,arg0=/hello]
callout:get[number=2,arg0=index,arg1=/hello]
callout:text-plain[3]
<4> A String "Hello World" is returned as the result

=== Test

Create a test to verify that when you make a GET request to `/hello` you get `Hello World` as a response:

test:HelloControllerTest[]

callout:micronaut-test[1]
callout:http-client[2]
callout:http-request[3]

common:testApp.adoc[]

common:runapp.adoc[]

common:graal-with-plugins.adoc[]

:exclude-for-languages:groovy

You can execute the endpoint exposed by the native image:

[source, bash]
----
curl localhost:8080/hello
----

[source]
----
Hello World
----

:exclude-for-languages:

== Next steps

Read more about https://micronaut-projects.github.io/micronaut-test/latest/guide/[Micronaut testing].

common:helpWithMicronaut.adoc[]
