[micronaut.application]
name = "micronautguide"

[datasources.default]
db-type = "oracle"
dialect = "ORACLE"
driver-class-name = "oracle.jdbc.OracleDriver"
schema-generate = "CREATE_DROP"

[test-resources.containers.oracle]
image-name = "gvenzl/oracle-free:23-slim-faststart"
startup-timeout = "600s"
