micronaut:
  server:
    port: 8081 # <1>

datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE # <2>
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: none
    dialect: H2

kafka:
  bootstrap:
    servers: localhost:9092 # <3>

flyway:
  datasources:
    default:
      locations:
        - classpath:db/migration/h2 # <4>
