micronaut:
  application:
    name: reactivehibernate
---
netty:
  default:
    allocator:
      max-order: 3
---
#tag::application[]
application:
  max: 50
#end::application[]
---
#tag::jpa[]
jpa:
  default:
    reactive: true
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        show_sql: true
        connection:
          url: jdbc:mysql://localhost:3306/mysql # Use JDBC style url
          username: root
          password: pass
#end::jpa[]