micronaut:
  application:
    name: reactivehibernate
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    reactive: true
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        connection:
          url: jdbc:mysql://localhost:3306/mysql # Use JDBC style url
          username: root
          password: pass
