= @guideTitle@

@guideIntro@

Authors: @authors@

Micronaut Version: @micronaut@

In this guide, we will add git commit info to your Micronaut build artifacts and running application. There are many benefits of keeping your commit info handy:

* Commit info is encapsulated within the built artifacts

* Fast authoritative means of identifying what specific code is running in an environment

* This solution doesn't rely on external tracking mechanisms

* Transparency and reproducibility when investigating issues

include::{commondir}/common-gettingStarted.adoc[]

include::{commondir}/common-requirements.adoc[]

include::{commondir}/common-completesolution.adoc[]

NOTE: Before running the downloaded project, follow the steps described in the *Initialize Git Repository* section below.

include::{commondir}/common-create-app.adoc[]

== Initialize Git Repository

The project aims to demonstrate how to provide Git commit information to the
`/info` endpoint and in order for that to work the project needs to be in a Git repository.  After creating the project, initialize a Git repository from the root of the newly created project:

[source,bash]
----
$ cd micronautguide
$ git init
$ git add .
$ git commit -a "Initial project"
----

== Management

Inspired by Spring Boot and Grails, the Micronaut management dependency adds support for monitoring of your application via endpoints: special URIs that return details about the health and state of your application.

To use the management features described in this section, add the dependency on your classpath.

dependency:micronaut-management[]

== Info endpoint

> The info endpoint returns static information from the state of the application. The info exposed can be provided by any number of "info sources".

Enable the info endpoint:

resource:application.yml[tag=endpoints]

:exclude-for-build:maven

== Gradle Git Properties Plugin

:exclude-for-build:
:exclude-for-build:gradle

== Maven Git Commit Id Plugin

:exclude-for-build:

If a `git.properties` file is available on the classpath, the http://docs.micronaut.io/latest/api/io/micronaut/management/endpoint/info/source/GitInfoSource.html[GitInfoSource] will expose the values in that file under the `git` key. Generation of a `git.properties` file will need to be configured as part of your build.

:exclude-for-build:maven

For example, you may choose to use the https://plugins.gradle.org/plugin/com.gorylenko.gradle-git-properties[Gradle Git Properties] plugin. The plugin provides a task named `generateGitProperties` responsible for the `git.properties` file generation. It is automatically invoked upon the execution of the `classes` task. You can find the generated file in the directory `build/resources/main`.

Modify `build.gradle` file to add the plugin:

[source,groovy]
.build.gradle
----
plugins {
  id "com.gorylenko.gradle-git-properties" version "@gradle-git-propertiesVersion@"
}
----

:exclude-for-build:

:exclude-for-build:gradle

For example, you may choose to use the https://github.com/git-commit-id/git-commit-id-maven-plugin[Maven Git Commit Id Plugin] plugin. The plugin provides a goal named `git-commit-id:revision` responsible for the `git.properties` file generation. It is automatically invoked upon the execution of the `classes` goal. You can find the generated file in the directory `target/classes`.

Modify `pom.xml` file to add the plugin:

[source,xml]
.pom.xml
----
<properties>
   ...
   <gitCommitIdPlugin.version>@git-commit-id-pluginVersion@</gitCommitIdPlugin.version>
</properties>

...

rocker:gitCommitIdPlugin[]
----

:exclude-for-build:

== Test

Create a JUnit test to verify that when you make a GET request to `/info` you get a payload such as:

[source, json]
----
{
  "git": {
    "dirty": "true",
    "commit": {
      "id": "7368906193527fbf2b45f1ed5b08c56631f5b155",
      "describe": "7368906-dirty",
      "time": "1527429126",
      "message": {
        "short": "Initial version",
        "full": "Initial version"
      },
      "user": {
        "name": "sdelamo",
        "email": "sergio.delamo@softamo.com"
      }
    },
    "branch": "master"
  }
}
----

Create a JUnit test to verify the behaviour:

test:InfoTest[]

<1> Annotate the class with `@MicronautTest` to let Micronaut start the embedded server and inject the beans. More info: https://micronaut-projects.github.io/micronaut-test/latest/guide/index.html[https://micronaut-projects.github.io/micronaut-test/latest/guide/index.html].
<2> Inject the `HttpClient` bean in the application context.
<3> Creating HTTP Requests is easy thanks to Micronaut's fluid API.
<4> Use `.body()` to retrieve the parsed payload.

include::{commondir}/common-testApp.adoc[]

include::{commondir}/common-runapp.adoc[]

include::{commondir}/common-graal-with-plugins.adoc[]

:exclude-for-languages:groovy

Annotate the `Application` class with `@Introspected`. This won't be necessary in a real world application because there
will be Micronaut beans defined (something annotated with `@Singleton`, `@Controller`,...), but for this case we need to
annotate a class so the visitor that generates the GraalVM `resource-config.json` file is triggered:

source:Application[]

The `git.properties` file that is generated by the `gradle-git-properties` plugin
will not be accessible from the native image unless access to the file is
configured in `resource-config.json`:

resource:META-INF/native-image/resource-config.json[]

You can execute the `info` endpoint exposed by the native image:

[source, bash]
----
curl localhost:8080/info

{"git":{"dirty":"true","total":{"commit":{"count":"45"}},"build":{"host":"Sergios-iMac-Pro.local","time":"2019-12-09T09:35:30+0100","user":{"name":"Sergio del Amo","email":"sergio.delamo@softamo.com"},"version":"0.1"},"commit":{"time":"2019-12-09T09:30:41+0100","id":"af3cff433d247fd4c2d8c54ae200108e98adfb2a","message":{"short":"add help section","full":"add help section\n"},"user":{"name":"Sergio del Amo","email":"sergio.delamo@softamo.com"}},"remote":{"origin":{"url":"git@github.com:micronaut-guides/adding-commit-info.git"}},"branch":"master"}}%
----

:exclude-for-languages:

include::{commondir}/common-next.adoc[]

include::{commondir}/common-helpWithMicronaut.adoc[]
