common:header-top.adoc[]

== Getting Started

In this guide, we will demonstrate Micronaut https://docs.micronaut.io/latest/guide/#transfers[file transfer] capabilities by creating an application which downloads an Excel file containing a list of books.

https://guides.micronaut.io/latest/micronaut-intellij-idea-ide-setup.html[Setup IntelliJ IDEA to develop Micronaut Applications].

common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app.adoc[]

== Writing the App

=== Books

Create `Book` POJO:

source:Book[]

Create an interface to encapsulate Book retrieval.

source:BookRepository[]

Create a bean which implements the previous interface:

source:BookRepositoryImpl[]

callout:singleton[1]

=== Spreadsheet Builder

Add a dependency to https://spreadsheet.dsl.builders/[Spreadsheet builder]
____
Spreadsheet builder provides convenient way how to read and create MS Excel OfficeOpenXML Documents (XSLX) focus not only on content side but also on easy styling.
____

dependency:spreadsheet-builder-poi:2.2.1[groupId=builders.dsl]

=== Excel Creation

Create a interface to encapsulate Excel generation:

source:BookExcelService[]

<1> `SystemFile` is specified as the return type of a route execution to indicate the given file should be downloaded by the client instead of displayed.

Externalize your styles configuration into a class implementing `builders.dsl.spreadsheet.builder.api.Stylesheet` interface to maximize code reuse.

source:BookExcelStylesheet[]

Create a bean which generates the Excel file.

source:BookExcelServiceImpl[]]

callout:singleton[1]

=== Controller

common:micronaut-views-thymeleaf.adoc[]

Create a controller:

source:HomeController[]

callout:controller[number=1,arg0=/]
<2> Constructor injection
<3> Use `@View` annotation to specify which template to use to render the response.
<4> You can specify the HTTP verb that a controller action responds to. To respond to a GET request, use `io.micronaut.http.annotation.Get`
<5> `SystemFile` is specified as the return type of a route execution to indicate the given file should be downloaded by the client instead of displayed.

The previous controller index method renders a simple view with a link to download the Excel file:

resource:views/index.html[]

=== Tests

Often, file transfers remain untested in many applications. In this section, you will see how easy is to test that the
file downloads but also that the downloaded file contents match our expectations.

Create a test to verify the Excel file is downloaded and the content matches our expectations.

test:DownloadExcelTest[]

callout:micronaut-test[1]
callout:http-client[2]
callout:http-request[3]
<4> Use `.body()` to retrieve the excel bytes.

common:testApp.adoc[]

common:runapp.adoc[]

== Next Steps

Read more about Micronaut https://docs.micronaut.io/latest/guide/#transfers[File Transfers] support.

common:helpWithMicronaut.adoc[]
