common:header-top.adoc[]

common:requirements.adoc[]

common:completesolution.adoc[]

== Composite Pattern

A common pattern while developing Micronaut applications is to create an ordered functional interface. Often, you want to evaluate every implementation in order.
By combining the `@Primary` annotation and the injection of a collection of beans of a particular type, you achieve this pattern easily in a Micronaut application.

Imagine you want to create an API to resolve a color:

source:ColorFetcher[]

<1> callout:functional-interface[]
<2> callout:ordered[]

== Http Header

You may write an implementation which searches for a color in an HTTP Header.

source:HttpHeaderColorFetcher[]

<1> callout:singleton[]
<2> callout:override-get-order[]

== Path

You could have another naive implementation which uses the HTTP Request's path.

source:PathColorFetcher[]

<1> callout:singleton[]
<2> callout:override-get-order[]

== Controller

If you create a controller which injects via constructor injection a bean of type `ColorFetcher`,
you will get the following exception:

[source,bash]
----
Message: Multiple possible bean candidates found:
[example.micronaut.PathColorFetcher,
example.micronaut.HttpHeaderColorFetcher]
Path Taken: new ColorController(ColorFetcher colorFetcher)
--> new ColorController([ColorFetcher colorFetcher])
io.micronaut.context.exceptions.DependencyInjectionException:
Failed to inject value for parameter [colorFetcher]
of class: example.micronaut.ColorController
----

source:ColorController[]

<1> callout:controller[arg0=/color]
<2> callout:constructor-di[arg0=ColorFetcher]
<3> callout:text-plain[]
<4> callout:get[arg0=mint,arg1=/mint]
<5> callout:request-controller-method-parameter[]

=== Primary

Create a new implementation of `ColorFetcher`. It traverses every other implementation of `ColorFetcher` in order.

source:CompositeColorFetcher[]

<1> callout:primary[]
<2> callout:singleton[]
<3> `ColorFetcher` implements `Ordered`. Because of that, you can inject an ordered list of beans of type `ColorFetcher`. You get every bean of type `ColorFetcher` but `CompositeColorFetcher`.

You can test that `CompositeColorFetcher` is primary bean of type `ColorFetcher`.

test:CompositeColorFetcherTest[]

<1> callout:micronaut-test-start-application-false[]

Moreover, you can test the previous controller with:

test:ColorControllerTest[]

<1> callout:micronaut-test[]
<2> callout:http-client[]

== Next Steps

- Read more about https://docs.micronaut.io/latest/guide/#_primary_and_secondary_beans[Primary and Secondary Beans].

The Composite pattern is used in several places within the framework. For example:

- https://docs.micronaut.io/latest/api/io/micronaut/discovery/CompositeDiscoveryClient.html[CompositeDiscoveryClient]
- https://docs.micronaut.io/latest/api/io/micronaut/http/server/util/locale/CompositeHttpLocaleResolver.html[CompositeHttpLocaleResolver]
- https://docs.micronaut.io/latest/api/io/micronaut/runtime/context/CompositeMessageSource.html[CompositeMessageSource]

common:helpWithMicronaut.adoc[]
