# tag::security[]
[micronaut.security]
# <1>
authentication = "bearer"

[micronaut.security.token.jwt.signatures.secret.generator]
# <2>
secret = "${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"
# end::security[]

# tag::refresh[]
[micronaut.security.token.jwt.generator.refresh-token]
# <1>
secret = "${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"
# end::refresh[]

[micronaut.application]
name = "micronautguide"

# tag::datasources[]
[datasources.default]
password = ""
url = "jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
username = "sa"
driver-class-name = "org.h2.Driver"
schema-generate = "CREATE_DROP"
dialect = "H2"
# end::datasources[]
