common:header.adoc[]

common:requirements.adoc[]

common:completesolution.adoc[]

https://docs.oracle.com/en/database/oracle/oracle-database/26/ddscg/configure-oracle-deep-data-security-sample-application.html[Configure Oracle Deep Data Security for a Sample Application]

== Run Oracle Database via Docker

```
docker run -d --name micronaut-deep-data-security -p 1521:1521 -p 2484:2484 -e ORACLE_PASSWORD='YourStrongPassword1' -v oracle-free-data:/opt/oracle/oradata gvenzl/oracle-free:23.26.2-full
```


=== Generate Wallets and Certificates

Generate the https://docs.oracle.com/en/database/oracle/oracle-database/26/ddscg/generate-wallets-and-certificates-springboot.html[Wallets and Certificates] as described in the tutorial in the  https://docs.oracle.com/en/database/oracle/oracle-database/26/ddscg/generate-wallets-and-certificates-springboot.html[Oracle Deep Data Security Guide]. But instead of creating them in `/u01/app/oracle/wallets/server`. We will create it them in `$HOME/wallets/server` -  `/opt/oracle/wallets/server`

1. Connect to the container:

```
docker exec -it spring-deep-data-security bash
```

2. Create a directory for the server wallet.

```
mkdir -p $HOME/wallets/server
```

Create the server wallet (identity) and a self-signed certificate.

```
orapki wallet create -wallet /u01/app/oracle/wallets/server -pwd <wallet_password> -auto_login
orapki wallet add -wallet /u01/app/oracle/wallets/server -dn "CN=<your-vm-fqdn>,O=Oracle,C=US" -keysize 2048 -self_signed -validity 3650 -pwd <wallet_password>
````

For this demo, instead of `<your-vm-fqdn>`, we use `localhost`.

Enter the `<wallet_password>`. For example, use `WalletPass123!` instead of `<wallet_password>`.

=== Configure Database Network Settings

https://docs.oracle.com/en/database/oracle/oracle-database/26/ddscg/configure-database-network-settings.html[Configure the database listener and network layer] to accept secure TCPS connections on port 2484 and enable token-based authentication. Both configurations use the server wallet you created in the previous section.

Connect to the container:

```
docker exec -it spring-deep-data-security bash
```

1. Configure the database listener.

a. Go to the database network configuration directory.

```
cd $ORACLE_HOME/network/admin
```

b. Open `listener.ora` in a text editor.

Add or update the wallet location and the TCPS address as shown below and save the file.
Use the database server’s fully qualified domain name for HOST. For this demo, I used `0.0.0.0`

```
WALLET_LOCATION = (SOURCE = (METHOD = FILE) (METHOD_DATA = (DIRECTORY = /opt/oracle/wallets/server)))

TLS_CLIENT_AUTHENTICATION = FALSE

LISTENER =
 (DESCRIPTION_LIST =
  (DESCRIPTION =
   (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC_FOR_FREE))
   (ADDRESS = (PROTOCOL = TCP)(HOST = 0.0.0.0)(PORT = 1521))
   (ADDRESS = (PROTOCOL = TCPS)(HOST = 0.0.0.0)(PORT = 2484))
  )
 )

DEFAULT_SERVICE_LISTENER = FREE
```

2. Configure network and token authentication (`sqlnet.ora`).
This step enables token-based authentication and directs the database network layer to the server wallet for TLS.
In $ORACLE_HOME/network/admin, open sqlnet.ora.

```
NAMES.DIRECTORY_PATH = (EZCONNECT, TNSNAMES)
# See https://github.com/gvenzl/oci-oracle-xe/issues/43
DISABLE_OOB=ON
BREAK_POLL_SKIP=1000

# --- Authentication ---
SQLNET.AUTHENTICATION_SERVICES = (BEQ, TOKENAUTH)

# --- TLS Configuration ---
TLS_CLIENT_AUTHENTICATION = FALSE
TLS_SERVER_DN_MATCH = TRUE

# Prevents conflicts between Native Encryption and TLS
SQLNET.IGNORE_ANO_ENCRYPTION_FOR_TCPS = TRUE

WALLET_LOCATION = (SOURCE = (METHOD = FILE) (METHOD_DATA = (DIRECTORY = /opt/oracle/wallets/server)))
```


Generate the https://docs.oracle.com/en/database/oracle/oracle-database/26/ddscg/generate-wallets-and-certificates-springboot.html[Wallets and Certificates] as described in the tutorial in the  https://docs.oracle.com/en/database/oracle/oracle-database/26/ddscg/generate-wallets-and-certificates-springboot.html[Oracle Deep Data Security Guide]





common:create-app-features.adoc[]

=== DTOs

source:dto/EmployeeDto[]
callout:serdeable[]

source:dto/SalaryAggregates[]
callout:serdeable[]

source:dto/SalarySummaryDto[]
callout:serdeable[]

=== Entities

source:domain/EmployeeEntity[]

callout:mapped-entity[]
callout:mapped-entity-id[]
callout:mapped-property[]

=== Repositories

source:repository/EmployeeRepository[]

callout:jdbcrepository[]
callout:crudrepository[]
callout:at-query[]

=== Services

source:services/EmployeeService[]

callout:singleton[]
callout:injection[arg0=EmployeeRepository]

=== Controller

source:api/HomeController[]

callout:controller[arg0=/]
callout:injection[arg0=EmployeeService]
callout:secured-anonymous[]
callout:view[]
callout:get[arg0=index,arg1=/]
callout:executes-on[]
<7> Bind Authenticated user
