common:header-top.adoc[]

== Sample Project

You can link:@sourceDir@.zip[download a sample application] with the code examples shown in this article.

== Introduction

Micronaut features an extensible bean scoping mechanism based on https://javax-inject.github.io/javax-inject/[JSR-330]. 


== Scenario

To talk about the different types of scopes, we use the following scenario. 

A `@Controller` which injects two collaborators. 

source:singleton/RobotController[tags=imports|controller|clazz]

Each collaborator has an injection endpoint for a bean of type `Robot`

source:singleton/RobotFather[]

source:singleton/RobotMother[]

Let's discuss how the application behaves depending on the scope used for the bean of type `Robot`.

== Singleton

source:singleton/Robot[]

test:SingletonScopeTest[]
callout:micronaut-test[1]
callout:http-client[2]

== Prototype

source:prototype/Robot[]

test:PrototypeScopeTest[]
callout:micronaut-test[1]
callout:http-client[2]

== Request

source:request/Robot[]

test:RequestScopeTest[]
callout:micronaut-test[1]
callout:http-client[2]

== Refreshable

source:refreshable/Robot[]

test:RefreshableScopeTest[]
callout:property[1]
callout:micronaut-test[2]
callout:http-client[3]

== Next steps

Read more about https://docs.micronaut.io/latest/guide/#scopes[Scopes] in the Micronaut Framework.

common:helpWithMicronaut.adoc[]
