common:header-top.adoc[]

== Sample Project

You can link:@sourceDir@.zip[download a sample application] with the code examples in this article.

== Introduction

Micronaut features an extensible bean scoping mechanism based on https://javax-inject.github.io/javax-inject/[JSR-330]. 


== Scenario

We use the following scenario to talk about the different types of scopes.

The following `@Controller` injects two collaborators. 

source:singleton/RobotController[tags=pkg|imports|controller|clazz]

Each collaborator has an injection endpoint for a bean of type `Robot`.

source:singleton/RobotFather[]

source:singleton/RobotMother[]

Let's discuss how the application behaves depending on the scope used for the bean of type `Robot`.

== Singleton

**Singleton scope indicates only one instance of the bean will exist**. 

To define a singleton, annotate a class with `jakarta.inject.Singleton` at the class level. 

The following class creates a unique identifier in the constructor. This identifier allows us to identify how many   `Robot` instances are used. 

source:singleton/Robot[tags=pkg|clazz]
callout:singleton[1]

=== Singleton Test

The following test verifies `@Singleton` behaviour. 
  
test:SingletonScopeTest[tags=imports|testheaders|test]
callout:micronaut-test[1]
callout:http-client[2]
<3> The same instance fulfills both injection points at `RobotFather` and `RobotMother`. 
<4> Same instance is used upon subsequent requests.

== Prototype

**Prototype scope indicates that a new instance of the bean is created each time it is injected**

Let's use `@Prototype` instead of `@Singleton`. 

source:prototype/Robot[]
callout:prototype[1]

=== Prototype Tests

The following test verifies the behavior of `Prototype` scope. 

test:PrototypeScopeTest[tags=imports|testheader|test]
callout:micronaut-test[1]
callout:http-client[2]
<3> A new instance is created to fulfill each injection point. Two instances - one for `RobotFather` and another for `RobotMother`. 
<4> Instances remain upon subsequent requests.

== Request

**@RequestScope scope is a custom scope that indicates a new instance of the bean is created and associated with each HTTP request**

source:request/Robot[]
callout:request-scope[1]
callout:request-aware[2]

=== Request Tests

The following test verifies the behavior of `@RequestScope` scope. 

test:RequestScopeTest[tags=imports|testheader|test]
callout:micronaut-test[1]
<3> Both injection points, `RobotFather` and `RobotMother`, are fulfilled with the same instance of `Robot`. An instance associated with the HTTP Request. 
<4> Both injection points are fulfilled with the new instance of `Robot`.


== Refreshable

**https://docs.micronaut.io/latest/guide/#refreshable[Refreshable scope] is a custom scope that allows a bean's state to be refreshed via the https://docs.micronaut.io/latest/guide/#refreshEndpoint[/refresh endpoint].**

source:refreshable/Robot[]

=== Refreshable Tests

The following test enables the https://docs.micronaut.io/latest/guide/#refreshEndpoint[refresh endpoint] and verifies the behavior of `@Refreshable`

test:RefreshableScopeTest[tags=imports|testheader|test]
callout:property[1]
callout:micronaut-test[2]
callout:http-client[3]
<3> The same instance fulfills both injection points at `RobotFather` and `RobotMother`. 
<4> Hitting the refresh endpoint, publishes a https://docs.micronaut.io/latest/api/io/micronaut/runtime/context/scope/refresh/RefreshEvent.html[RefreshEvent], which invalidates the instance of `Robot`. A new instance of `Robot` is created the next time the object is requested.  

== @Context

TODO 

== @Bean

TODO 

== Other scopes

Micronaut Framework ships with other built-in Scopes: 

=== @Infrastructure

https://docs.micronaut.io/latest/api/io/micronaut/context/annotation/Infrastructure.html[@Infrastructure] scope represents a bean that cannot be overridden or replaced using `@Replaces` because it is critical to the functioning of the system.

=== @ThreadLocal

https://docs.micronaut.io/latest/api/io/micronaut/runtime/context/scope/ThreadLocal.html[@ThreadLocal] scope is a custom scope that associates a bean per thread via a ThreadLocal

Read more about https://docs.micronaut.io/latest/guide/#scopes[Scopes] in the Micronaut Framework.

common:helpWithMicronaut.adoc[]
