common:header.adoc[]

common:requirements.adoc[]
* An https://aws.amazon.com/[AWS account] with:
** An IAM user with enough permissions to create and manage a queue instances in SQS.
** The AWS CLI configured to use the IAM user above.

common:completesolution.adoc[]

common:create-app-features.adoc[]

== Create an application
Let’s create a set of components that will use the https://micronaut-projects.github.io/micronaut-jms/latest/guide/[Micronaut JMS] to send and receive messages from https://docs.aws.amazon.com/it_it/AWSSimpleQueueService/latest/APIReference/Welcome.html[AWS SQS]

____
Amazon SQS is a reliable, highly-scalable hosted queue for storing messages as they travel between applications or microservices. Amazon SQS moves data between distributed application components and helps you decouple these components.
____

=== Configuration

Enable JMS SQS integration:

resource:application.properties[]

=== Creating a JMS Producer

Create a JMS Producer interface.

source:DemoProducer[]

<1> The `JMSProducer` annotation defines this interface as a client that sends messages.
<2> The `@Queue` annotation indicates which queue the message should be published to.
<3> The `send` method accepts a single parameter which is the payload of a message.

=== Creating a JMS Consumer

Create a JMS Consumer class.

source:DemoConsumer[]

<1> The `@JMSListener` defines the bean as a message listener.
<2> The `@Queue` annotation indicates which queue to subscribe to.
<3> The `receive` method accepts a single parameter which is the payload of a message.

=== Creating a Controller

Let’s create a Controller with an endpoint that we will call to verify that message has been sent by the JMS Producer (`DemoProducer`) and then finally received and consumed by the JMS Consumer (`DemoConsumer`).

source:DemoController[]

<1> callout:controller[arg0=/]
<2> callout:constructor-di[arg0=DemoProducer]
<3> Maps a `GET` request to `/demo` path, which attempts to publish a message to a SQS queue instance.
<4> Calls `send` method on `DemoProducer` instances providing the message payload.

== Testing

common:localstack.adoc[]

common:localstack-dependencies.adoc[]

First, we create a configuration properties object to encapsulate the configuration of the SQS client, which we will provide via LocalStack.

test:SqsConfig[]

<1> callout:configuration-properties[]

Create a `BeanCreatedEventListener` to override the SQS client endpoint with the LocalStack endpoint.

test:SqsClientBuilderListener[]

<1> callout:singleton[]
<2> callout:bean-created-event-listener[]
<3> callout:constructor-di[arg0=SqsConfig]

Create a `BeanCreatedEventListener` to create a SQS queue named `demo_queue`.

test:SqsClientCreatedEventListener[]

<1> callout:singleton[]
<2> callout:bean-created-event-listener[]

Create a test using the https://java.testcontainers.org/modules/localstack/[Testcontainers LocalStack] module to start a LocalStack container and verify that the message has been sent and received.

test:MicronautguideTest[]

<1> callout:micronaut-test[]
<2> callout:test-instance-per-class[]
<3> callout:test-property-provider[]

common:aws.adoc[]

== Creating a queue instance in Amazon Simple Queue Service (Amazon SQS)

You will create a queue with the AWS CLI. See the https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sqs/index.html[AWS CLI `sqs` command] for more information.

=== Create a queue instance

[source,bash]
----
aws sqs create-queue --queue-name demo_queue
----
Copy and save the response of the command. You will need the `QueueUrl` to delete the queue after you finish with it.

== Running the Application

With almost everything in place, you can start the application and try it out. First, set environment variables to configure the queue connection. Then you can start the app.

Create environment variables for `AWS_ACCESS_KEY_ID`, and `AWS_SECRET_ACCESS_KEY`, as defined in https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/credentials-chain.html[AWS SDK Java v2 - Credential settings retrieval order]:

[source,bash]
----
export AWS_ACCESS_KEY_ID=<the access key from the AWS configuration step>
export AWS_SECRET_ACCESS_KEY=<the secret key from the AWS configuration step>
----

[NOTE]
.Windows System
====
Command Prompt:: Change '*export*' to '*set*'
+
Example: `set AWS_ACCESS_KEY_ID=aws_access_key`

PowerShell:: Change '*export* ' to '*$*' and use quotes around the value
+
Example: `$AWS_ACCESS_KEY_ID="aws_access_key"`
====

common:runapp-instructions.adoc[]

You can test the application in a web browser or with cURL.

Run from a terminal window to publish and consume a message:

[source, bash]
----
curl "http://localhost:8080/demo"
----

=== Stopping the Instance and cleaning up

Once you are done with this guide, you can stop/delete the AWS resources created to avoid incurring unnecessary charges.

[source,bash]
----
aws sqs delete-queue --queue-url <QUEUE_URL>
----
Replace the `<QUEUE_URL>` placeholder with a queue URL value returned from the `create-queue` command.

common:graal-with-plugins.adoc[]

:exclude-for-languages:groovy

Start the native executable and execute the same cURL request as before.

:exclude-for-languages:

common:next.adoc[]

Read more about https://micronaut-projects.github.io/micronaut-jms/latest/guide/[Micronaut JMS].

Discover https://aws.amazon.com/sqs/[Amazon Simple Queue Service (SQS)].
