common:header.adoc[]

:exclude-for-languages:kotlin
You are going to use https://docs.oracle.com/en/java/javase/17/language/records.html[Record Classes] in a Micronaut application.

____
Record classes, which are a special kind of class, help to model plain data aggregates with less ceremony than normal classes.

A record declaration specifies in a header a description of its contents; the appropriate accessors, constructor, equals, hashCode, and toString methods are created automatically. A record's fields are final because the class is intended to serve as a simple "data carrier."
____
:exclude-for-languages:

:exclude-for-languages:java
You are going to use https://kotlinlang.org/docs/data-classes.html[Kotlin Data Classes] in a Micronaut application.

____
Kotlin data classes help to model plain data aggregates with less ceremony than normal classes.

A data class primary constructor declares the data it contains; equals, hashCode, toString, and component functions are created automatically.
____
:exclude-for-languages:

common:requirements.adoc[]

common:completesolution.adoc[]

common:cli-or-launch.adoc[]

common:create-app-features.adoc[]

[source,bash]
----
mn @cli-command@ \
   example.micronaut.micronautguide \
   --features=data-jdbc,postgres,liquibase \
   --build=@build@ \
   --lang=@lang@ \
----


common:build-lang-arguments.adoc[]

common:default-package.adoc[]

NOTE: If you use https://launch.micronaut.io[Micronaut Launch], select "Micronaut Application" as application type and add `postgres`, `data-jdbc`, and `liquibase` as features.

https://guides.micronaut.io/latest/micronaut-intellij-idea-ide-setup.html[Setup IntelliJ IDEA to develop Micronaut Applications].

:exclude-for-languages:kotlin
=== Immutable Configuration with Java Records
:exclude-for-languages:
:exclude-for-languages:java
=== Immutable Configuration with Kotlin Data Classes
:exclude-for-languages:

source:ValueAddedTaxConfiguration[]

callout:configuration-properties[]

Write a test:

test:ValueAddedTaxConfigurationTest[]

callout:property[]
callout:micronaut-test-start-application-false[]

=== Database Migration with Liquibase

We need a way to create the database schema. For that, we use
https://micronaut-projects.github.io/micronaut-liquibase/latest/guide/[Micronaut integration with Liquibase].

Add the following snippet to include the necessary dependencies:

dependency:micronaut-liquibase[groupId=io.micronaut.liquibase]

Configure the database migrations directory for http://www.liquibase.org[Liquibase] in `application.properties`.


resource:application.properties[tag=liquibase]

Create the following files with the database schema creation and a book:

resource:db/liquibase-changelog.xml[]

resource:db/changelog/01-create-books-schema.xml[]

resource:db/changelog/02-insert-book.xml[]

During application startup, http://www.liquibase.org[Liquibase] executes the SQL file, creates the schema needed for the application and inserts one book.

:exclude-for-languages:kotlin
=== Mapped Entities with Java Records
:exclude-for-languages:
:exclude-for-languages:java
=== Mapped Entities with Kotlin Data Classes
:exclude-for-languages:

Create a Micronaut Data Mapped Entity

source:Book[]

callout:mapped-entity[]
<.> The primary key is annotated with `@Id`. It is an assigned primary key.
callout:constraints[]
<.> Annotate `about` with `@Nullable`, since it is optional.

:exclude-for-languages:kotlin
=== Projections with Java Records
:exclude-for-languages:
:exclude-for-languages:java
=== Projections with Kotlin Data Classes
:exclude-for-languages:

:exclude-for-languages:kotlin
Create a record to project some data from the `book` table. For example, exclude the `about` field.
:exclude-for-languages:
:exclude-for-languages:java
Create a data class to project some data from the `book` table. For example, exclude the `about` field.
:exclude-for-languages:

source:BookCard[]

callout:serdeable[]
callout:constraints[]

:exclude-for-languages:kotlin
Create a https://micronaut-projects.github.io/micronaut-data/latest/guide/#dbcRepositories[Repository], which uses the previous Java record as a DTO projection.
:exclude-for-languages:
:exclude-for-languages:java
Create a https://micronaut-projects.github.io/micronaut-data/latest/guide/#dbcRepositories[Repository], which uses the previous Kotlin data class as a DTO projection.
:exclude-for-languages:

source:BookRepository[]

callout:jdbcrepository[]
callout:crudrepository[]
callout:dto-projection[]

:exclude-for-languages:kotlin
=== JSON serialization with Java Records
:exclude-for-languages:
:exclude-for-languages:java
=== JSON serialization with Kotlin Data Classes
:exclude-for-languages:

:exclude-for-languages:kotlin
Create a Java record to represent a JSON response:
:exclude-for-languages:
:exclude-for-languages:java
Create a Kotlin data class to represent a JSON response:
:exclude-for-languages:

source:BookForSale[]

callout:serdeable[]
callout:constraints[]

Create a Controller that uses the previous record:

source:BookController[]

callout:controller[arg0=/books]
callout:constructor-di[arg0=BookRepository]
callout:executes-on[]
callout:get[arg0=index,arg1='/']
:exclude-for-languages:kotlin
<.> Return a Java record, and the application responds with the JSON representation of the object.
:exclude-for-languages:
:exclude-for-languages:java
<.> Return a Kotlin data class, and the application responds with the JSON representation of the object.
:exclude-for-languages:

=== Create a Test

Create a test:

test:BookControllerTest[]

callout:property[]
callout:micronaut-test-transactional-false[]
callout:http-client[]
<.> Multiline string
callout:binding-json-array[]

common:test-resources-postgres.adoc[]

== Datasource configuration

Although the URL is configured automatically via <<test-resources,Test Resources>>, we must configure the PostgreSQL driver and dialect in `application.properties`:

resource:application.properties[tag=datasource]

<1> Use PostgreSQL driver.
<2> Configure the PostgreSQL dialect.
<3> You handle database migrations via Liquibase

common:testApp.adoc[]

== Running the application

Set up the environment variable to configure the VAT percentage.

Configure
[source,bash]
----
export VAT_PERCENTAGE=20
----

common:runapp-instructions.adoc[]

You can run a cURL command to test the application:

[source, bash]
----
curl http://localhost:8080/books
----

[source,json]
----
[{"isbn":"0321601912","title":"Continuous Delivery","price":47.99}]
----

common:graal-with-plugins.adoc[]

You can run a cURL command to test the application:

[source, bash]
----
curl http://localhost:8080/books
----

[source,json]
----
[{"isbn":"0321601912","title":"Continuous Delivery","price":47.99}]
----

You receive an empty array because there are no books in the database. You can create a Liquibase changelog to add seed data.

common:next.adoc[]

common:helpWithMicronaut.adoc[]
