include::{commondir}/common-header.adoc[]

You are going to use https://docs.oracle.com/en/java/javase/16/language/records.html[Record Classes] in a Micronaut Application.

____
Record classes, which are a special kind of class, help to model plain data aggregates with less ceremony than normal classes.

A record declaration specifies in a header a description of its contents; the appropriate accessors, constructor, equals, hashCode, and toString methods are created automatically. A record's fields are final because the class is intended to serve as a simple "data carrier".
____

include::{commondir}/common-requirements.adoc[]

include::{commondir}/common-completesolution.adoc[]

include::{commondir}/common-cli-or-launch.adoc[]

[source,bash]
----
mn create-app --jdk=17 \
   example.micronaut.micronautguide \
   --features=data-jdbc,postgres,liquibase \ 
   --build=@build@ \
   --lang=@lang@ \
----


NOTE: To use Java records, specify JDK 17 when you create the application

include::{commondir}/common-build-lang-arguments.adoc[]

include::{commondir}/common-default-package.adoc[]

NOTE: If you use https://launch.micronaut.io[Micronaut Launch], select "Micronaut Application" as application type and add the `postgres`, `data-jdbc` and `liquibase` as features.

include::{commondir}/common-annotationprocessors.adoc[]

=== Immutable Configuration with Java Records

source:ValueAddedTaxConfiguration[]

callout:configuration-properties[1]

Write a test:

test:ValueAddedTaxConfigurationTest[]

callout:property[1]
callout:micronaut-test-start-application-false[2]


=== Database Migration with Liquibase

We need a way to create the database schema. For that, we use
https://micronaut-projects.github.io/micronaut-liquibase/latest/guide/[Micronaut integration with Liquibase].

Add the following snippet to include the necessary dependencies:

dependency:micronaut-liquibase[groupId=io.micronaut.liquibase]

Configure the database migrations directory for http://www.liquibase.org[Liquibase] in `application.yml`.

resource:application.yml[tag=liquibase]

Create the following files with the database schema creation:

resource:db/liquibase-changelog.xml[] 

resource:db/changelog/01-create-books-schema.xml[] 

During application startup, http://www.liquibase.org[Liquibase] executes the SQL file and create the schema needed for the application.

=== Mapped Entities with Java Records

Create a Micronaut Data Mapped Entity

source:Book[]

callout:mapped-entity[1]
<2> The primary key is annotated with `@Id` and `@GeneratedValue`. Since records are immutable constructor arguments that are generated values need to be marked as @Nullable
callout:constraints[3]
<4> Annotate `about` with `@Nullable` since it is optional.

=== Projections with Java Records

Create a record to project some data from the `book` table. For example, exclude the `about` field.

source:BookCard[]

callout:introspected[1]
callout:constraints[2]

Create a https://micronaut-projects.github.io/micronaut-data/latest/guide/#dbcRepositories[Repository] which uses the previous Java record as a DTO projection.

source:BookRepository[]

callout:jdbcrepository[1]
callout:crudrepository[2]
callout:dto-projection[3]

=== JSON serialization with Java Records

Create a Java record to represent a JSON response: 

source:BookForSale[]

callout:introspected[1]
callout:constraints[2]

Create a Controller which uses the previous record: 

source:BookController[]

callout:controller[number=1,arg0=/books]
callout:constructor-di[number=2,arg0=BookRepository]
callout:get[number=3,arg0=index,arg1='/']
<4> Respond a Java Record and the application responds JSON representation of the object

=== Testing with PostgreSQL with TestContainers

We use https://www.testcontainers.org/modules/databases/postgres/[Test Containers] to test against a PostgreSQL database. 

Add the following snippet to include the necessary test container dependencies:

:dependencies:
dependency:postgresql[groupId=org.testcontainers,scope=testImplementation]
dependency:testcontainers[groupId=org.testcontainers,scope=testImplementation]
:dependencies:

Configure the default datasource to use the PostgreSQL database provided by TestContainers for the test environment:

testResource:application-test.yml[]

=== Create a Test

Create a test:

test:BookControllerTest[]

callout:property[1]
callout:micronaut-test-transactional-false[2]
callout:http-client[3]
<4> Multiline string 
<5> The generated value needs to be marked as `@Nullable` and, thus, you pass `null` to instantiate the Java Record.
callout:binding-json-array[6]

=== Running the application

include::{commondir}/common-run-postgres-with-docker.adoc[]

Set up the following environment variables to connect to the PostgreSQL database you started with Docker.

resource:application.yml[tag=datasource]

<1> The JDBC url matches the database name you used in the previous command.
<2> Driver and dialect are configured to use PostgreSQL.
<3> You handle database migrations via Liquibase 

[source,bash]
----
export DATASOURCES_DEFAULT_USERNAME=dbuser
export DATASOURCES_DEFAULT_PASSWORD=theSecretPassword
export VAT_PERCENTAGE=20
----

Configure your default datasource to use PostgreSQL database you started with Docker:

include::{commondir}/common-runapp-instructions.adoc[]

You can run a cURL command to test the application:

[source, bash]
----
$ curl http://localhost:8080/books
[]
----

You receive an empty array, because there are no books in the database. You can create a liquibase changelog to add seed data.

include::{commondir}/common-graal-with-plugins.adoc[]

You can run a cURL command to test the application:

[source, bash]
----
$ curl http://localhost:8080/books
[]
----

You receive an empty array, because there are no books in the database. You can create a liquibase changelog to add seed data.

include::{commondir}/common-next.adoc[]

include::{commondir}/common-helpWithMicronaut.adoc[]

