common:header.adoc[]

This guide will demonstrate how to use https://cloud.google.com/secret-manager/docs/overview[Google Secret Manager] to store the configurations for a Micronaut Data JDBC application.

Instead of storing the database url, username and password in plan text or environment variables. A secret manager provides a convenient way to stores API keys, passwords, certificates, and other sensitive data while improving security.

common:requirements.adoc[]
* A https://cloud.google.com/gcp/[Google Cloud Platform (GCP)] account and a GCP project.

common:costs-gcloud.adoc[]

common:gcp.adoc[]

== Creating the Application

Download the complete solution of the guideLink:micronaut-data-jdbc-repository[Access a database with Micronaut Data JDBC] guide.

This guide is a companion to either the above guide or the guideLink:micronaut-cloud-database-google[Connect a Micronaut Data JDBC Application to a Google MySQL Database].

== Dependencies

=== Update the Application to use Google's Secret Manager

The https://micronaut-projects.github.io/micronaut-gcp/latest/guide/#secretManager[micronaut-gcp] subproject provides integration between Micronaut apps and the Google Cloud, including using Secret Manager as a distributed configuration source.

Add the following dependency to your build:

dependency:micronaut-gcp-secret-manager[groupId=io.micronaut.gcp]

NOTE: Native compile requires a supplemental library. See https://micronaut-projects.github.io/micronaut-gcp/latest/guide/#nativeImage[Micronaut GCP: Generating Native Executables] for instructions on adding it to your build.

The Micronaut Framework reads distributed configurations, like secrets, at start-up, but needs to be instructed to do so.

== Distributed Configuration

common:enable-distributed-configuration.adoc[]

== Google's Secret Manager

=== Move JDBC URL, username and password from the Application Configurations

Create a file named `datasource-info.yml` in the project root directory, or elsewhere on your filesystem, to contain the JDBC connection information.

[TIP]
====
Do not add this file to source control, since it contains sensitive information.
====

Add the following:

[,yml]
.datasource-info.yml
----
datasources:
  default:
    url: <JDBC_URL>
    username: <USER_NAME>
    password: <USER_PASSWORD>
----

==== Examples of datasource-info.yml:

.Docker MySQL configurations example for guideLink:micronaut-data-jdbc-repository[Access a database with Micronaut Data JDBC]
[%collapsible]
====
[,yml]
----
datasources:
  default:
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: ''
----
====
.Google Cloud MySQL configurations example for guideLink:micronaut-cloud-database-google[Connect a Micronaut Data JDBC Application to a Google MySQL Database]
[%collapsible]
====
[,yml]
----
datasources:
  default:
    url: jdbc:mysql://34.xxx.xxx.65:3306/demo
    username: jdbcUser
    password: userSecretPassword
----
====

=== Clean up of the Application Configurations

Remove the following from the `application.yml`.

[,diff]
.src/main/resources/application.yml
----
- micronaut:
-  application:
-    name: micronautguide

datasources:
  default:
-    url: ${JDBC_URL:`jdbc:mysql://localhost:3306/db`}
-    username: ${JDBC_USER:root}
-    password: ${JDBC_PASSWORD:}
    dialect: MYSQL
    driverClassName: ${JDBC_DRIVER:com.mysql.cj.jdbc.Driver}

flyway:
  datasources:
    default:
      enabled: true
----

=== Add Configurations to Google Secret Manager

Add the new `datasource-info.yml` configuration file to the secret manager.

[,bash]
----
gcloud secrets create application \
  --data-file=path/to/datasource-info.yml
----

[NOTE]
====
You might be prompted to enable the Google SQL Admin API

[source, bash]
----
API [secretmanager.googleapis.com] not enabled on project [<project-id>].

Would you like to enable and retry (this will take a few minutes)? (y/N)?
----
====

See https://micronaut-projects.github.io/micronaut-gcp/latest/guide/#secretManager[Google Cloud Secret Manager Support's] "Configuration file resolution" section for other built-in and manual configured ways that configurations files can be named other than `application` as above.

=== Stand Alone Secret (Optional)

There are many cases where you might just need a secret (key and value) in your application. Helpful if something changes often or is different per environment.

With Google Secret Manager you can:

. Create a file that just contains the password, like above.
. Use the Google Cloud Console to add the secret.
. Add a secret directly on the command line, but this is discouraged because the plaintext will appear in your shell history.

For this example, let's move the user's password to its own secret, using option 3.

On Linux and Mac:
[,bash,options="nowrap"]
----
printf "<PASSWORD>" | gcloud secrets create jdbc_password --data-file=-
----

On Windows:
[,bash,options="nowrap"]
----
Write-Output "<PASSWORD>" | gcloud secrets create my-secret --data-file=-
----

[WARNING]
====
All line breaks and leading and trailing whitespace are stripped from the secret at runtime.
====

Add the following to the `bootstrap.yml`

resource:bootstrap.yml[tag=optional]

This is needed, because Google's Secret Manager does not offer a hierarchical approach. Therefor we need to tell the application which keys to read.

The secret `jdbc_password` will me mapped to the property `sm.jdbc.password`. And can be used like `@Property(name="sm.jdbc.password")` within the application.

Update the `datasource-info.yml` file to:

[,yml]
.datasource-info.yml
----
datasources:
  default:
    url: <JDBC_URL>
    username: <USER_NAME>
    password: ${sm.jdbc.password}
----

Finally, update the secret.

[,bash]
----
gcloud secrets versions add application \
  --data-file=path/to/datasource-info.yml
----

=== Fix Test Configurations

Distributed configurations have a higher precedence (priority) than application configurations found in application_<env>.yml. Meaning if we tested the application now, the datasource configuration in Google's Secret Manager would be used and not the Test Container configuration in application_test.yml.

With Secret Manager: :: Add `application-test.yml` to secret manager:
+
[,bash]
----
gcloud secrets create application_test \
  --data-file=src/test/resources/application-test.yml
----

Without Secret Manager: :: Create a `bootstrap-test.yml` file or rename `application_test.yml` to `bootstrap-test.yml` and add:
+
[,yml]
.src/test/resources/bootstrap_test.yml
----
micronaut:
  config-client:
    enabled: false
----

== Running the Application

common:runapp-instructions.adoc[]

common:gcp-default-credentials.adoc[]

You can test the application in a web browser or with cURL.

Run from a terminal window to create a `Genre`:

[source, bash]
----
curl -X "POST" "http://localhost:8080/genres" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{ "name": "music" }'
----

and run this to list the genres:

[source, bash]
----
curl http://localhost:8080/genres/list
----

common:gcp-project-cleanup.adoc[]

external:micronaut-cloud-database-base/end.adoc[]

Read more about https://micronaut-projects.github.io/micronaut-gcp/latest/guide/[Micronaut GCP] integration.



