common:header.adoc[]

This guide will demonstrate how to use https://cloud.google.com/secret-manager/docs/overview[Google Secret Manager] to store the configurations for a Micronaut Data JDBC application.

Instead of storing the database url, username and password in plan text or environment variables. A secret manager provides a convenient way to stores API keys, passwords, certificates, and other sensitive data while improving security.

common:requirements.adoc[]
* A https://cloud.google.com/gcp/[Google Cloud Platform (GCP)] account and a GCP project.

common:costs-gcloud.adoc[]

common:gcp.adoc[]

== Creating the Application

This guide is a continuation of the guideLink:micronaut-cloud-database-google[Connect a Micronaut Data JDBC Application to a Google MySQL Database] guide. Rather than storing the JDBC URL, user's name and password in environment variables as described in the "Running the Application" section. This will show you how to configure and store them in Google's Secret Manager.

== Google's Secret Manager

=== Update the Application to use Google's Secret Manager

First, add the following dependency to the build.

dependency:micronaut-gcp-secret-manager[groupId=io.micronaut.gcp]

:dependencies:

#N.b.: Currently, Native Image compiles fails currently without `nativeImageCompileOnly("com.google.cloud:native-image-support:0.12.10")` - working on a fix#

The Micronaut Framework reads distributed configurations, like secrets, at start-up, but needs to be instructed to do so.

This is accomplished by creating a `bootstrap.yml` file in the `resources` directory and adding the following:

resource:bootstrap.yml[tag=required]
. Moved from `src/main/resources/application.yml`
. Enables the distributed configurations

=== Move JDBC URL, username and password from the Application Configurations

Create a file named `datasource-info.yml` in the project root directory, or elsewhere on your filesystem, to contain the JDBC connection information.

[TIP]
====
Do not add this file to source control, since it contains sensitive information.
====

Add the following:

[,yml]
.datasource-info.yml
----
datasources:
  default:
    url: <JDBC_URL>
    username: <USER_NAME>
    password: <USER_PASSWORD>
----

Where `JDBC_URL`, `USER_NAME` and `USER_PASSWORD` would have been the values stored as environment variables in the guideLink:micronaut-cloud-database-google[Connect a Micronaut Data JDBC Application to a Google MySQL Database] guide.

=== Clean up of the Application Configurations

Remove the following from the `application.yml`.

[,diff]
.src/main/resources/application.yml
----
- micronaut:
-  application:
-    name: micronautguide

datasources:
  default:
-    url: ${JDBC_URL:`jdbc:mysql://localhost:3306/db`}
-    username: ${JDBC_USER:root}
-    password: ${JDBC_PASSWORD:}
    dialect: MYSQL
    driverClassName: ${JDBC_DRIVER:com.mysql.cj.jdbc.Driver}

flyway:
  datasources:
    default:
      enabled: true
----

=== Add Configurations to Google Secret Manager

Add the new `datasource-info.yml` configuration file to the secret manager.

[,bash]
----
gcloud secrets create application \
  --data-file=path/to/datasource-info.yml
----

[NOTE]
====
You might be prompted to enable the Google SQL Admin API

[source, bash]
----
API [secretmanager.googleapis.com] not enabled on project [<project-id>].

Would you like to enable and retry (this will take a few minutes)? (y/N)?
----
====

=== Stand Alone Secret (Optional)

There are many cases where you might just need a secret (key and value) in your application. Helpful if something changes often or is different per environment.

With Google Secret Manager you can:

. Create a file that just contains the password, like above.
. Use the Google Cloud Console to add the secret.
. Add a secret directly on the command line, but this is discouraged because the plaintext will appear in your shell history.

For this example, let's move the user's password to its own secret, using option 3.

On Linux and Mac:
[,bash,options="nowrap"]
----
printf "<PASSWORD>" | gcloud secrets create jdbc_password --data-file=-
----

On Windows:
[,bash,options="nowrap"]
----
Write-Output "<PASSWORD>" | gcloud secrets create my-secret --data-file=-
----

[CAUTION]
====
PowerShell will add a newline to the resulting secret.

It does not cause an issue in the case, but might in others.
====

Add the following to the `bootstrap.yml`

resource:bootstrap.yml[tag=optional]

This is needed, because Google's Secret Manager does not offer a hierarchical approach. Therefor we need to tell the application which keys to read.

The secret `jdbc_password` will me mapped to the property `sm.jdbc.password`. And can be used like `@Property(name="sm.jdbc.password")` within the application.

Update the `datasource-info.yml` file to:

[,yml]
.datasource-info.yml
----
datasources:
  default:
    url: <JDBC_URL>
    username: <USER_NAME>
    password: ${sm.jdbc.password}
----

Finally, update the secret.

[,bash]
----
gcloud secrets versions add application \
  --data-file=path/to/datasource-info.yml
----

== Running the Application

common:runapp-instructions.adoc[]

[NOTE]
====
You might get this error message: +
"Message: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information."

If you are developing locally you can do:
[,bash]
----
gcloud auth application-default login
----
Otherwise, follow the instructions in the link above.
====

You can test the application in a web browser or with cURL.

Run from a terminal window to create a `Genre`:

[source, bash]
----
curl -X "POST" "http://localhost:8080/genres" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{ "name": "music" }'
----

and run this to list the genres:

[source, bash]
----
curl http://localhost:8080/genres/list
----

== Stopping the Instance

[source, bash]
----
gcloud sql instances patch micronaut-guides-mysql \
  --activation-policy=NEVER
----

common:gcp-project-cleanup.adoc[]

external:micronaut-cloud-database-base/end.adoc[]

Read more about https://micronaut-projects.github.io/micronaut-gcp/latest/guide/[Micronaut GCP] integration.



