common:header.adoc[]

This guide demonstrates how to use https://cloud.google.com/secret-manager/docs/overview[Google Secret Manager] to store the configuration for a Micronaut Data JDBC application.

Instead of storing the database URL, username, and password in plaintext or environment variables, use a secret manager. A secret manager provides a convenient way to store API keys, passwords, certificates, and other sensitive data while improving security.

common:requirements.adoc[]
* A https://cloud.google.com/gcp/[Google Cloud Platform (GCP)] account and a GCP project.

common:costs-gcloud.adoc[]

common:gcp.adoc[]

== Creating the Application

Download the complete solution of the guideLink:micronaut-data-jdbc-repository[Access a database with Micronaut Data JDBC] guide.

This guide is a companion to either the above guide or the guideLink:micronaut-cloud-database-google[Connect a Micronaut Data JDBC Application to a Google MySQL Database].

== Dependencies

=== Update the Application to use Google's Secret Manager

The https://micronaut-projects.github.io/micronaut-gcp/latest/guide/#secretManager[micronaut-gcp] subproject provides integration between Micronaut apps and the Google Cloud, including using Secret Manager as a distributed configuration source.

Add the following dependency to your build:

dependency:micronaut-gcp-secret-manager[groupId=io.micronaut.gcp]

:exclude-for-languages:python
NOTE: Native compile requires a supplemental library. See https://micronaut-projects.github.io/micronaut-gcp/latest/guide/#nativeImage[Micronaut GCP: Generating Native Executables] for instructions on adding it to your build.
:exclude-for-languages:

Micronaut Framework reads distributed configuration, such as secrets, at startup, but needs to be instructed to do so.

== Distributed Configuration

common:enable-distributed-configuration.adoc[]

== Google's Secret Manager

=== Move JDBC URL, username, and password from the application configuration

Create a file named `datasource-info.yml` in the project root directory, or elsewhere on your filesystem, to contain the JDBC connection information.

[TIP]
====
Do not add this file to source control, since it contains sensitive information.
====

Add the following:

[,yml]
.datasource-info.yml
----
datasources:
  default:
    url: <JDBC_URL>
    username: <USER_NAME>
    password: <USER_PASSWORD>
----

==== Examples of datasource-info.yml

.Docker MySQL configuration example for guideLink:micronaut-data-jdbc-repository[Access a database with Micronaut Data JDBC]
[%collapsible]
====
[,yml]
----
datasources:
  default:
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: ''
----
====
.Google Cloud MySQL configuration example for guideLink:micronaut-cloud-database-google[Connect a Micronaut Data JDBC Application to a Google MySQL Database]
[%collapsible]
====
[,yml]
----
datasources:
  default:
    url: jdbc:mysql://34.xxx.xxx.65:3306/demo
    username: jdbcUser
    password: userSecretPassword
----
====

=== Clean up the application configuration

:only-for-languages:python

Keep the datasource dialect, driver, and Flyway settings in `config/application.toml`. Do not put database credentials in source control. In `config/application-cloud.toml`, replace `YOUR_PROJECT_ID` with your Google Cloud project ID; the importer reads the `application` secret as a YAML configuration document.

:only-for-languages:

:exclude-for-languages:python

Remove the following from the `application.properties`.

[,diff]
.src/main/resources/application.properties
----
- micronaut.application.name=micronautguide
- datasources.default.url=${JDBC_URL:`jdbc:mysql://localhost:3306/db`}
- datasources.default.username=${JDBC_USER:root}
- datasources.default.password=${JDBC_PASSWORD:}
datasources.default.dialect=MYSQL
datasources.default.driver-class-name=${JDBC_DRIVER:com.mysql.cj.jdbc.Driver}
flyway.datasources.default.enabled=true
----

:exclude-for-languages:

=== Add Configurations to Google Secret Manager

Add the new `datasource-info.yml` configuration file to the secret manager.

[,bash]
----
gcloud secrets create application \
  --data-file=path/to/datasource-info.yml
----

[NOTE]
====
You might be prompted to enable the Google Secret Manager API:

[source, bash]
----
API [secretmanager.googleapis.com] not enabled on project [<project-id>].

Would you like to enable and retry (this will take a few minutes)? (y/N)?
----
====

See the "Configuration file resolution" section of https://micronaut-projects.github.io/micronaut-gcp/latest/guide/#secretManager[Google Cloud Secret Manager Support] for the built-in and manually configured ways that configuration files can use names other than `application`.

=== Standalone Secret (Optional)

:exclude-for-languages:python

In many cases, you might need only a secret key and value in your application. This is helpful when something changes often or differs per environment.

With Google Secret Manager you can:

. Create a file that just contains the password, like above.
. Use the Google Cloud Console to add the secret.
. Add a secret directly on the command line, but this is discouraged because the plaintext will appear in your shell history.

For this example, let's move the user's password to its own secret, using option 3.

On Linux and Mac:
[,bash,options="nowrap"]
----
printf "<PASSWORD>" | gcloud secrets create jdbc_password --data-file=-
----

On Windows:
[,bash,options="nowrap"]
----
Write-Output "<PASSWORD>" | gcloud secrets create my-secret --data-file=-
----

[WARNING]
====
All line breaks and leading and trailing whitespace are stripped from the secret at runtime.
====

Add the following to the `bootstrap.properties`

resource:bootstrap.properties[tag=optional]

This is needed because Google Secret Manager does not offer a hierarchical approach. Therefore, you need to tell the application which keys to read.

The secret `jdbc_password` will be mapped to the property `sm.jdbc.password` and can be used with `@Property(name="sm.jdbc.password")` within the application.

Update the `datasource-info.yml` file to:

[,yml]
.datasource-info.yml
----
datasources:
  default:
    url: <JDBC_URL>
    username: <USER_NAME>
    password: ${sm.jdbc.password}
----

Finally, update the secret.

[,bash]
----
gcloud secrets versions add application \
  --data-file=path/to/datasource-info.yml
----

:exclude-for-languages:

:only-for-languages:python

To keep a password in a separate secret, store a configuration document rather than a raw scalar. Create `jdbc-password.toml` outside source control:

[,toml]
.jdbc-password.toml
----
[sm.jdbc]
password = "<USER_PASSWORD>"
----

Upload the document without putting the password in shell history:

[,bash]
----
gcloud secrets create jdbc_password --data-file=path/to/jdbc-password.toml
----

Append this import to `config/application-cloud.toml`, replacing the project identifier:

[,toml]
----
[[micronaut.config.import]]
provider = "gcp-secret-manager"
path = "jdbc_password"
project-id = "YOUR_PROJECT_ID"
format = "toml"
----

The document supplies `sm.jdbc.password`. Set `datasources.default.password` in `datasource-info.yml` to `${sm.jdbc.password}`, then update the `application` secret with `gcloud secrets versions add application --data-file=path/to/datasource-info.yml`.

The configuration importer reads structured configuration documents; it does not map a raw single-value secret using the legacy `gcp.secret-manager.keys` setting.

:only-for-languages:

=== Fix Test Configurations

:only-for-languages:python

The sample's local tests activate the `test` environment, not `cloud`, so Micronaut Test Resources supplies MySQL without accessing Google Secret Manager. Do not activate `cloud` for these tests. To verify the cloud integration, configure Application Default Credentials, activate `cloud`, and exercise the same `/genres` operations against the remote database.

:only-for-languages:

:exclude-for-languages:python

Distributed configuration has a higher precedence than application configuration found in `application_<env>.properties`. If you tested the application now, the data source configuration in Google Secret Manager would be used instead of the Testcontainers configuration in `application_test.properties`.

With Secret Manager: :: Add `application-test.properties` to secret manager:
+
[,bash]
----
gcloud secrets create application_test \
  --data-file=src/test/resources/application-test.properties
----

Without Secret Manager: :: Create a `bootstrap-test.properties` file or rename `application_test.properties` to `bootstrap-test.properties` and add:
+
[,properties]
.src/test/resources/bootstrap_test.properties
----
micronaut.config-client.enabled=true
----

:exclude-for-languages:

== Running the Application

:exclude-for-languages:python
common:runapp-instructions.adoc[]
:exclude-for-languages:

common:gcp-default-credentials.adoc[]

:only-for-languages:python

Activate the cloud configuration after configuring credentials and uploading the secret. On Linux and macOS:

[,bash]
----
export MICRONAUT_ENVIRONMENTS=cloud
pyronaut run
----

On Windows PowerShell:

[,powershell]
----
$env:MICRONAUT_ENVIRONMENTS = "cloud"
pyronaut run
----

:only-for-languages:

You can test the application in a web browser or with cURL.

Run from a terminal window to create a `Genre`:

[source, bash]
----
curl -X "POST" "http://localhost:8080/genres" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{ "name": "music" }'
----

and run this to list the genres:

[source, bash]
----
curl http://localhost:8080/genres/list
----

common:gcp-project-cleanup.adoc[]

external:micronaut-cloud-database-base/end.adoc[]

Read more about https://micronaut-projects.github.io/micronaut-gcp/latest/guide/[Micronaut GCP] integration.
