[micronaut.application]
name = "micronautguide"

# tag::jinja[]
[micronaut.views.jinja]
default-extension = "html"
# end::jinja[]

# tag::webjars[]
[micronaut.router.static-resources.webjars]
paths = "classpath:/META-INF/resources/webjars"
mapping = "/webjars/**"
# end::webjars[]
