external:micronaut-openapi-base/openapi-intro.adoc[]

== Micronaut OpenAPI Asciidoc

Micronaut OpenAPI provides a dependency to generate the OpenAPI documentation in https://asciidoc.org/[Asciidoc].

=== Micronaut OpenAPI Asciidoc dependency

Add the following dependency:

dependency:micronaut-openapi-adoc[groupId=io.micronaut.openapi,scope=annotationProcessor]

=== OpenAPI Asciidoc Generated Test

An OpenAPI specification as Asciidoc is generated at compile-time. You can test it as follows:

test:OpenApiAsciidocGeneratedTest[]
callout:micronaut-test-start-application-false[]

external:micronaut-openapi-base/homecontroller.adoc[]

The hidden path is not included in the asciidoc file:

test:HomeControllerHiddenAsciidocTest[]

:leveloffset: -1

common:testApp.adoc[]

common:runapp.adoc[]

If you go to `http://localhost:8080`, you will see the Asciidoc version of the compile-time generated OpenAPI Specification

common:graalvm-resource-config.adoc[]

common:graal-with-plugins.adoc[]

If you go to `http://localhost:8080`, you will see the Asciidoc version of the compile-time generated OpenAPI Specification

common:next.adoc[]

common:helpWithMicronaut.adoc[]
