micronaut:
  application:
    name: bookrecommendation
endpoints:
  health:
    enabled: true
    sensitive: false
#tag::zipkin[]
tracing:
  zipkin:
    http:
      url: http://localhost:9411
    enabled: true
    sampler:
      probability: 1 # <1>
#end::zipkin[]