# tag::distributedconfiguration[]
[[micronaut.config.import]]
provider = "gcp-secret-manager" # <1>
path = "application" # <2>
project-id = "YOUR_PROJECT_ID" # <3>
format = "yml"
# end::distributedconfiguration[]
