= @guideTitle@

@guideIntro@

Authors: @authors@

Micronaut Version: @micronaut@

include::{commondir}/common-gettingStarted.adoc[]

include::{commondir}/common-requirements.adoc[]

include::{commondir}/common-completesolution.adoc[]

include::{commondir}/common-create-app.adoc[]

== Code

=== JSON Web Key Generation

Create an interface to encapsulate the contract to generate a https://datatracker.ietf.org/doc/html/rfc7517[JWK (JSON Web Key)]

source:JsonWebKeyGenerator[]

To generate a JWK, use https://connect2id.com/products/nimbus-jose-jwt[Nimbus JOSE + JWT], an open source Java library to generate JSON Web Tokens (JWT).

Add the following dependency:

dependency:nimbus-jose-jwt[groupId=com.nimbusds,version=@nimbus-jose-jwtVersion@]

Create an implementation of `JsonWebKeyGenerator`

source:RS256JsonWebKeyGenerator[]

<1> Annotate the class with `@Singleton` to register it in the application context.


include::{commondir}/common-testApp.adoc[]

include::{commondir}/common-runapp.adoc[]

include::{commondir}/common-graal-with-plugins.adoc[]

:exclude-for-languages:groovy

TODO describe how you consume the endpoints exposed by the native image with curl

:exclude-for-languages:

TODO Use the generic next step

include::{commondir}/common-next.adoc[]

TODO or a personalized guide for the guide:

== Next steps

TODO: link to the documentation modules you used in the guide

include::{commondir}/common-helpWithMicronaut.adoc[]