= @guideTitle@

@guideIntro@

Authors: @authors@

Micronaut Version: @micronaut@

== Getting Started

In this guide, we will create a Micronaut application written in @language@ to consume the GitHub API with the Micronaut HTTP Client.

include::{commondir}/common-requirements.adoc[]

include::{commondir}/common-completesolution.adoc[]

include::{commondir}/common-create-app.adoc[]

=== GitHub API

In this guide, you will consume the https://docs.github.com/en/rest[GitHub API] from a Micronaut application.

In particular, we consume the https://docs.github.com/en/rest/reference/repos#list-releases[List releases] endpoint.

____
This returns a list of releases, which does not include regular Git tags that have not been associated with a release.
____

This API resource can be consumed by both authenticated and anonymous clients.

Initially, you will consume it anonymously, later we will discuss authentication.

Modify `src/main/resources/application.yml` to create some configuration parameters.

resource:application.yml[tag=githubconfig]

To encapsulate type-safe configuration retrieval, we use a https://docs.micronaut.io/latest/guide/index.html#configurationProperties[`@ConfigurationProperties`] object:

source:GithubConfiguration[]

In this guide, you will fetch https://github.com/micronaut-projects/micronaut-core/releases[Micronaut Core releases].

To consume the GitHub API, you will use Micronaut HTTP Client.

=== Low Level Client

Initially, you will create a Bean which uses the low-level Client API.

Create a POJO to parse the JSON response into an object:

source:GithubRelease[]

Create `GithubLowLevelClient`:

source:GithubLowLevelClient[]

<1> Use `jakarta.inject.Singleton` to designate a class as a singleton.
<2> Inject `HttpClient` via constructor injection.
<3> Inject the previously defined configuration parameters.
<4> Creating HTTP Requests is easy thanks to Micronaut's fluid API.
<5> GitHub API requires to set the `User-Agent` header.
<6> GitHub encourages to explicitly request the version 3 via the `Accept` header. With `@Header`, you add the `Accept: application/vnd.github.v3+json` HTTP header to every request.
<7> Use `retrieve` to perform an HTTP request for the given request object and convert the full HTTP response's body into the specified type. e.g. `List<GithubRelease>`.

NOTE: Instead of `retrieve` we could have used `jsonStream`. You can use `jsonStream()` to stream arrays of type `application/json` or
JSON streams of type `application/x-json-stream`. If we use `retrieve`, such as in the previous code listing, the operation will not block.
However, it will not return until all the data has been received from the server. In the case of a JSON array that would be the whole array.
However, if you are interested in just the first element of the array, `jsonStream` provides a better alternative since it starts streaming data from the server without needing the whole response.
For example, `jsonStream().firstElement()` will only parse the first item in a JSON array. Hence it is more efficient.

=== Declarative Client

It is time to take a look at Micronaut's support for declarative clients via the Client annotation.

Create `GithubApiClient` which clearly illustrates how a declarative Micronaut HTTP Client, which is generated at compile-time, simplifies our code.

source:GithubApiClient[]

<1> URL of the remote service
<2> GitHub API requires to set the `User-Agent` header.
<3> GitHub encourages to explicitly request the version 3 via the `Accept` header. With `@Header`, you add the `Accept: application/vnd.github.v3+json` HTTP header to every request.
<4> You can use configuration parameter interpolation when you define the path of the GET endpoint.
<5> You can return any reactive type of any implementation (RxJava, Reactor...), but it's better to use the Reactive Streams public interfaces like `Publisher`.

=== Controller

Create a Controller. It uses both (low-level and declarative clients). It showcases several Micronaut's capabilities.

* Micronaut supports any framework that implements Reactive Streams, including RxJava, and Reactor. Thus, you can easily and efficiently
compose multiple HTTP client calls without blocking (which will limit the throughput and scalability of your application).
* Micronaut enables you to consume/produce https://docs.micronaut.io/latest/guide/index.html#clientStreaming[JSON Streams].

source:GithubController[]

<1> The class is defined as a controller with the @api@/io/micronaut/http/annotation/Controller.html[@Controller] annotation mapped to the path `/github`.
<2> Inject beans via constructor injection.
<3> The @api@/io/micronaut/http/annotation/Get.html[@Get] annotation maps the index method to all requests that use an HTTP GET
<4> The `releasesWithLowLevelClient` returns a Maybe which may or may not emit an item. If an item is not emitted a 404 is returned.
<5> In order to do JSON streaming you can declare a controller method that returns a `application/x-json-stream` of JSON objects.
<6> You can return any reactive type of any implementation (RxJava, Reactor...), but it's better to use the Reactive Streams public interfaces like `Publisher`.

=== Tests

Create a test to verify that both clients work as expected, and the controller echoes the output of the GitHub API in a Reactive way.

test:GithubControllerTest[]

<1> Annotate the class with `@MicronautTest` to let Micronaut starts the embedded server and inject the beans. More info: https://micronaut-projects.github.io/micronaut-test/latest/guide/index.html[https://micronaut-projects.github.io/micronaut-test/latest/guide/index.html].
<2> Inject the `StreamingHttpClient` bean in the application context.
<3> Sometimes, receiving just the object is not enough, and you need information about the response. In this case, instead of `retrieve` you should use the `exchange` method.
<4> Micronaut makes it easy to parse JSON into Java objects.
<5> Use `status` to check the HTTP status code.
<6> Use `.body()` to retrieve the parsed payload.
<7> Use the `jsonStream` method, which returns a `Publisher`, to consume the endpoint which generates a JSON Stream.

include::{commondir}/common-testApp.adoc[]

== HTTP Client Filter

Often, you need to include the same HTTP headers or URL parameters in a set of requests against a third-party API or when
calling another Microservice. To simplify this, Micronaut includes the ability to define `HttpClientFilter` classes that
are applied to all matching HTTP clients.

For a real world example, let us provide GitHub Authentication via an `HttpClientFilter`. Follow the steps in
https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token[to create you own Personal Token].
Then you can use those credentials to access the GitHub API
https://docs.github.com/en/rest/overview/other-authentication-methods#via-oauth-and-personal-access-tokens[using Basic Auth].

Create a Filter:

source:GithubFilter[]

<1> Supply the pattern you want to match to the `@Filter` annotation.
<2> Micronaut will not load the Bean unless configuration properties are set.
<3> Constructor injection of the configuration parameters.
<4> Enhance every request sent to GitHub API providing Basic Authentication.

=== Configuration Parameters

Add your GitHub `username` and `token` to `src/main/resource/application.yml`

[source, yaml]
----
github:
  organization: micronaut-projects
  repo: micronaut-core
  username: yourgithubusername
  token: xxxxxxxxxxxx
----

Add to `src/main/resources/logback.xml`, a logger to see Micronaut's HTTP client output.

[source, xml]
----
<logger name="io.micronaut.http.client" level="TRACE"/>
----

If you run again the tests, you will see the that the Filter is invoked and HTTP Basic Auth is used against GitHub API.

[source, bash]
-----
13:09:56.662 [default-nioEventLoopGroup-1-4] DEBUG i.m.h.client.netty.DefaultHttpClient - Sending HTTP GET to https://api.github.com/repos/micronaut-projects/micronaut-core/releases
13:09:56.663 [default-nioEventLoopGroup-1-4] TRACE i.m.h.client.netty.DefaultHttpClient - User-Agent: Micronaut HTTP Client
13:09:56.663 [default-nioEventLoopGroup-1-4] TRACE i.m.h.client.netty.DefaultHttpClient - Accept: application/json
13:09:56.663 [default-nioEventLoopGroup-1-4] TRACE i.m.h.client.netty.DefaultHttpClient - Authorization: Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
13:09:56.664 [default-nioEventLoopGroup-1-4] TRACE i.m.h.client.netty.DefaultHttpClient - host: api.github.com
-----

include::{commondir}/common-graal-with-plugins.adoc[]

== Next steps

Visit https://docs.micronaut.io/latest/guide/index.html#httpClient[Micronaut HTTP Client documentation] to learn more.

include::{commondir}/common-helpWithMicronaut.adoc[]

