common:header-top.adoc[]

== Getting Started

In this guide, we will create a Micronaut application written in @language@ to consume the GitHub API with the Micronaut HTTP Client.

common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app-features.adoc[]

=== Dependency

To use the https://docs.micronaut.io/snapshot/guide/#nettyHttpClient[Micronaut HTTP Client based on Netty], add the following dependency:

dependency:micronaut-http-client[groupId=io.micronaut]

To use the https://docs.micronaut.io/snapshot/guide/#jdkHttpClient[Micronaut HTTP Client based on Java HTTP Client], add the following dependency:

dependency:micronaut-http-client-jdk[groupId=io.micronaut]

=== GitHub API

In this guide, you will consume the https://docs.github.com/en/rest[GitHub API] from a Micronaut application.

In this guide, you will fetch https://github.com/micronaut-projects/micronaut-core/releases[Micronaut Core releases] via the https://docs.github.com/en/rest/reference/repos#list-releases[List releases] endpoint.

____
This returns a list of releases, which does not include regular Git tags that have not been associated with a release.
____

This API resource can be consumed by both authenticated and anonymous clients. Initially, you will consume it anonymously, later we will discuss authentication.

:exclude-for-languages:python

Create a record to parse the JSON response into an object:

:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin

Create a dataclass to parse the JSON response into an object:

:exclude-for-languages:

source:GithubRelease[]

=== Configuration

:exclude-for-languages:python

Modify `src/main/resources/application.properties` to create some configuration parameters.

resource:application.properties[tag=githubconfig]

:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin

Modify `config/application.toml` to create some configuration parameters.

resource:application.toml[tag=githubconfig]

:exclude-for-languages:

To encapsulate type-safe configuration retrieval, we use a https://docs.micronaut.io/latest/guide/#configurationProperties[`@ConfigurationProperties`] object:

source:GithubConfiguration[]

==== JSON Codec Configuration

Add configuration to treat `application/vnd.github.v3+json` as JSON.

:exclude-for-languages:python

resource:application.properties[tag=jsoncodec]

:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin

resource:application.toml[tag=jsoncodec]

:exclude-for-languages:

==== HTTP Client Service Configuration

Add configuration to associate a service identifier to the GitHub API URL.

:exclude-for-languages:python

resource:application.properties[tag=githubapi]

:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin

resource:application.toml[tag=githubapi]

:exclude-for-languages:

=== Low Level Client

Initially, you will create a Bean which uses the low-level Client API.

Create `GithubLowLevelClient`:

source:GithubLowLevelClient[]

callout:singleton[]
:exclude-for-languages:python
<.> Inject `HttpClient` via constructor injection. The `@Client` `id` member uses `github`; the service identifier set in the configuration.
<.> Inject the previously defined configuration parameters.
:exclude-for-languages:
:exclude-for-languages:java,groovy,kotlin
<.> Inject `HttpClient` into an annotated class attribute. The `@Client` `id` member uses `github`; the service identifier set in the configuration.
<.> Inject the previously defined configuration parameters into an annotated class attribute.
:exclude-for-languages:
callout:http-request[]
<.> GitHub API requires to set the `User-Agent` header.
<.> GitHub encourages to explicitly request the version 3 via the `Accept` header. With `@Header`, you add the `Accept: application/vnd.github.v3+json` HTTP header to every request.
<.> Use `retrieve` to perform an HTTP request for the given request object and convert the full HTTP response's body into the specified type. e.g. `List<GithubRelease>`.

=== Declarative Client

It is time to take a look at support for declarative clients via the Client annotation.

Create `GithubApiClient` which clearly illustrates how a declarative Micronaut HTTP Client, which is generated at compile-time, simplifies our code.

source:GithubApiClient[]

<.> URL of the remote service
<.> GitHub API requires to set the `User-Agent` header.
<.> GitHub encourages to explicitly request the version 3 via the `Accept` header. With `@Header`, you add the `Accept: application/vnd.github.v3+json` HTTP header to every request.
<.> You can use configuration parameter interpolation when you define the path of the GET endpoint.
callout:singleresult[]
<.> You can return any reactive type of any implementation (RxJava, Reactor...), but it's better to use the Reactive Streams public interfaces like `Publisher`.

=== Controller

:exclude-for-languages:python

Create a Controller. It uses both (low-level and declarative clients). The Micronaut framework supports Reactive Streams implementations such as https://micronaut-projects.github.io/micronaut-rxjava3/latest/guide/[RxJava] or https://micronaut-projects.github.io/micronaut-reactor/latest/guide/[Project Reactor]. Thus, you can efficiently compose multiple HTTP client calls without blocking (which will limit the throughput and scalability of your application).

:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin

Create route functions. They use both low-level and declarative clients. The Micronaut framework supports Reactive Streams implementations such as https://micronaut-projects.github.io/micronaut-rxjava3/latest/guide/[RxJava] or https://micronaut-projects.github.io/micronaut-reactor/latest/guide/[Project Reactor]. Thus, you can efficiently compose multiple HTTP client calls without blocking (which will limit the throughput and scalability of your application).

:exclude-for-languages:

source:GithubController[]

:exclude-for-languages:python
callout:controller[arg0=/github]
<.> Inject beans via constructor injection.
<.> The @api@/io/micronaut/http/annotation/Get.html[@Get] annotation maps the `index` method to all requests that use an HTTP GET
callout:singleresult[]
callout:get[arg0=fetchReleases,arg1=/releases]
:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin
<.> Inject beans into annotated module variables.
<.> The @api@/io/micronaut/http/annotation/Get.html[@Get] annotation maps the route function to an HTTP GET request.
callout:singleresult[]
<.> The @api@/io/micronaut/http/annotation/Get.html[@Get] annotation maps the `fetch_releases` route function to `/github/releases`.
<.> Return the `Publisher` from the declarative client.
:exclude-for-languages:

=== Tests

We will mock the GitHub API with some releases

NOTE: Here we only show a single release.
      You can add more entries to the file if you want to test with multiple releases.

:exclude-for-languages:python

[source, json]
.src/test/resources/single-release.json
----
include::{sourceDir}/micronaut-http-client/@sourceDir@/src/test/resources/single-release.json[]
----

:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin

[source, json]
.tests-config/releases.json
----
include::{sourceDir}/micronaut-http-client/@sourceDir@/tests-config/single-release.json[]
----

:exclude-for-languages:

Create a test to verify that both clients work as expected, and the controller echoes the output of the GitHub API in a Reactive way.

test:GithubControllerTest[]

callout:spec-name[]
callout:mock-http-server[arg0=GitHub]
:exclude-for-languages:python
<.> Create a sample `single-release.json` file in the `src/test/resources` directory. To get some test data, call the GitHub API with curl or provide a release entry yourself.
<.> Sometimes, receiving just the object is not enough, and you need information about the response. In this case, instead of `retrieve` you should use the `exchange` method.
callout:binding-json-array[]
<.> Use `status` to check the HTTP status code.
callout:body-method[]
:exclude-for-languages:
:exclude-for-languages:java,groovy,kotlin
<.> Create a sample `releases.json` file in the `tests-config` directory. To get some test data call GitHub API with curl or provide a few entries yourself.
<.> Use `requests.with_context(my_context)` to call the application under test with a context-bound HTTP client.
<.> Decode the JSON response body into a Python list.
<.> Use `status_code` to check the HTTP status code.
<.> Validate the response body.
:exclude-for-languages:


common:testApp.adoc[]

== HTTP Client Filter

Often, you need to include the same HTTP headers or URL parameters in a set of requests against a third-party API or when calling another Microservice. To simplify this, the Micronaut framework includes the ability to define `HttpClientFilter` classes that are applied to all matching HTTP clients.

For a real world example, let us provide GitHub Authentication via an `HttpClientFilter`. Follow the steps in
https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token[to create your own Personal Token].
Then you can use those credentials to access the GitHub API
https://docs.github.com/en/rest/overview/other-authentication-methods#via-oauth-and-personal-access-tokens[using Basic Auth].

Create a Filter:

source:GithubFilter[]

callout:client-filter[]
:exclude-for-languages:kotlin
<.> The Micronaut framework will not load the bean unless configuration properties are set.
:exclude-for-languages:

:exclude-for-languages:java,groovy
<.> Kotlin doesn't support runtime repeatable annotations (see https://youtrack.jetbrains.com/issue/KT-12794[KT-12794]. We use a custom condition to enable the bean where appropriate.
:exclude-for-languages:

:exclude-for-languages:python
<.> Constructor injection of the configuration parameters.
:exclude-for-languages:
:exclude-for-languages:java,groovy,kotlin
<.> Inject the configuration parameters into an annotated class attribute.
:exclude-for-languages:
callout:request-filter[]
<.> Enhance every request sent to GitHub API providing Basic Authentication.

:exclude-for-languages:java,groovy,python

Create a custom Condition:

source:GithubFilterCondition[]

<1> Implement Micronaut `Condition`.
<2> Get the `GithubConfiguration` bean from the application context.
<3> Only return `true` when the `token` and the `username` exist.

:exclude-for-languages:

=== Configuration Parameters

:exclude-for-languages:python

Add your GitHub `username` and `token` to `src/main/resources/application.properties`

[source, properties]
----
github.organization=micronaut-projects
github.repo=micronaut-core
github.username=yourgithubusername
github.token=xxxxxxxxxxxx
----

:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin

Add your GitHub `username` and `token` to `config/application.toml`

[source, toml]
----
[github]
organization = "micronaut-projects"
repo = "micronaut-core"
username = "yourgithubusername"
token = "xxxxxxxxxxxx"
----

:exclude-for-languages:

:exclude-for-languages:python

Add a logger to `src/main/resources/logback.xml` to see the HTTP client output.

:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin

Configure logging in `src/main.py` to see the HTTP client output. The Pyronaut logging module applies this Python logging configuration through Logback.

:exclude-for-languages:

:exclude-for-languages:python

[source, xml]
----
<logger name="io.micronaut.http.client" level="TRACE"/>
----

:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin

zipInclude:src/main.py[tag=logging]

:exclude-for-languages:

If you run again the tests, you will see the that the Filter is invoked and HTTP Basic Auth is used against GitHub API.

[source, bash]
-----
13:09:56.662 [default-nioEventLoopGroup-1-4] DEBUG i.m.h.client.netty.DefaultHttpClient - Sending HTTP GET to https://api.github.com/repos/micronaut-projects/micronaut-core/releases
13:09:56.663 [default-nioEventLoopGroup-1-4] TRACE i.m.h.client.netty.DefaultHttpClient - User-Agent: Micronaut HTTP Client
13:09:56.663 [default-nioEventLoopGroup-1-4] TRACE i.m.h.client.netty.DefaultHttpClient - Accept: application/json
13:09:56.663 [default-nioEventLoopGroup-1-4] TRACE i.m.h.client.netty.DefaultHttpClient - Authorization: MASKED
13:09:56.664 [default-nioEventLoopGroup-1-4] TRACE i.m.h.client.netty.DefaultHttpClient - host: api.github.com
-----

common:graal-with-plugins.adoc[]

== Next Steps

Visit https://docs.micronaut.io/latest/guide/#httpClient[Micronaut HTTP Client documentation] to learn more.

common:helpWithMicronaut.adoc[]
