[micronaut.application]
name = "micronautguide"

# tag::datasource[]
[datasources.default]
schema-generate = "none"
db-type = "postgres"
dialect = "POSTGRES"
driver-class-name = "org.postgresql.Driver"
initialization-fail-timeout = 60000
# end::datasource[]
