[micronaut.application]
name = "micronautguide"

# tag::static-resources[]
[micronaut.router.static-resources.jsonschema]
mapping = "/schemas/**"
paths = "classpath:META-INF/schemas"
# end::static-resources[]
