= @guideTitle@

@guideIntro@

Authors: @authors@

Micronaut Version: @micronaut@

include::{commondir}/common-gettingStarted.adoc[]

include::{commondir}/common-requirements.adoc[]

include::{commondir}/common-completesolution.adoc[]

== Writing the App

include::{commondir}/common-cli-or-launch.adoc[]

[source,bash]
----
mn create-app example.micronaut.micronautguide --feature=azure-function --build=@build@ --lang=@lang@
----

include::{commondir}/common-build-lang-arguments.adoc[]

include::{commondir}/common-default-package.adoc[]

NOTE: If you use https://launch.micronaut.io[Micronaut Launch], select "Micronaut Application" as application type and add the `azure-function` feature.

include::{commondir}/common-annotationprocessors.adoc[]


== Azure CLI

Install https://docs.microsoft.com/en-us/cli/azure/[Azure CLI]

> Azure  CLI  is a set of commands used to create and manage Azure resources. The Azure CLI is available across Azure services and is designed to get you working quickly with Azure, with an emphasis on automation.

== Azure Functions Core Tools

Install the https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=macos%2Ccsharp%2Cbash#install-the-azure-functions-core-tools[Azure Functions Core Tools]

> Azure  Function Core Tools includes a version of the same runtime that powers Azure Functions runtime that you can run on your local development computer. It also provides commands to create functions, connect to Azure, and deploy function projects.

== Function

The created application contains class which extends `AzureHttpFunction`

source:Function[]

When you write a Micronaut Azure HTTP function, you will write your application as you will normally do when developing outside of Azure functions. That it is to say, you will create routes with classes annotated with `@Controller`. The above class bridges both worlds. It adapts from an Azure to a Micronaut HTTP Request, and based on the route, it delegates to the appropriate Micronaut's controller.

== Controller

The generated application contains a `Controller` which exposes two routes (`GET` and `POST`):

source:MicronautguideController[]

* The class is defined as a controller with the https://docs.micronaut.io/latest/api/io/micronaut/http/annotation/Controller.html[@Controller] annotation mapped to the path `/micronautguide`
* The https://docs.micronaut.io/latest/api/io/micronaut/http/annotation/Get.html[@Get] annotation is used to map the `index` method to all requests that use an HTTP GET.
* By default a Micronaut's response uses `application/json` as `Content-Type`. `index` method returns a String not a JSON object. Because of that, we set the response content-type to `text/plain` with the `@Produces` annotation.
* The https://docs.micronaut.io/latest/api/io/micronaut/http/annotation/Post.html[@Post] annotation is used to map the `postMethod` method to all requests that use an HTTP GET.
* `@Introspected` annotation generates bean meta-information at compile time.

== Tests

The generated application contains a test which shows how to write a Micronaut Azure HTTP Function tests.

test:MicronautguideFunctionTest[]

* Instantiating the function starts the Micronaut's application context.

include::{commondir}/common-testApp.adoc[]

== Running the Application

:exclude-for-build:maven

To run the application use the `./gradlew azureFunctionsRun` command which will start the application on port 8080.

:exclude-for-build:

:exclude-for-build:gradle

To run the application use the `./mvnw package azure-functions:run` command which will start the application on port 8080.

:exclude-for-build:

You can invoke the GET route:

[source,bash]
----
curl -i localhost:7071/api/micronautguide
HTTP/1.1 200 OK
Date: Sat, 08 May 2021 03:55:11 GMT
Content-Type: text/plain
Server: Kestrel
Transfer-Encoding: chunked

Example Response
----

or the POST route:

[source,bash]
----
curl -i -d '{"name":"John Snow"}' -H "Content-Type: application/json" -X POST http://localhost:7071/api/micronautguide
HTTP/1.1 200 OK
Date: Sat, 08 May 2021 03:57:56 GMT
Content-Type: application/json
Server: Kestrel
Transfer-Encoding: chunked

{"returnMessage":"Hello John Snow, thank you for sending the message"}
----

== Next steps

Read more about:

* https://micronaut-projects.github.io/micronaut-azure/latest/guide/[Micronaut Azure] integration.
* https://github.com/Azure/azure-functions-java-library[Library for Azure Java Functions]
* https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-java[Azure functions for Java developers]

include::{commondir}/common-helpWithMicronaut.adoc[]