=== Deleting the project

The easiest way to eliminate billing is to delete the project you created for the tutorial.

[WARNING]
====
Deleting a project has the following consequences:

- If you used an existing project, you'll also delete any other work you've done in the project.

- You can't reuse the project ID of a deleted project. If you created a custom project ID that you plan to use in the future, you should delete the resources inside the project instead. This ensures that URLs that use the project ID, such as an appspot.com URL, remain available.

- If you are exploring multiple tutorials and quickstarts, reusing projects instead of deleting them prevents you from exceeding project quota limits.
====

==== Via the CLI

To delete the project using the Cloud SDK, run the following command, replacing `YOUR_PROJECT_ID` with the project ID:

[source,bash]
----
gcloud projects delete YOUR_PROJECT_ID
----

==== Via the Cloud Platform Console

In the Cloud Platform Console, https://console.cloud.google.com/iam-admin/projects[go to the Projects page].

In the project list, select the project you want to delete and click Delete project. After selecting the checkbox next to the project name, click `Delete project`

In the dialog, type the project ID, and then click Shut down to delete the project.

Deleting or turning off specific resources

You can individually delete or turn off some of the resources that you created during the tutorial.
