== Google Cloud Platform

Signup for the https://console.cloud.google.com/[Google Cloud Platform]

=== Cloud SDK

Install the https://cloud.google.com/sdk/docs/install[Cloud SDK CLI] for your operating system.

Cloud SDK includes the `gcloud` command-line tool. Run the `init` command in your terminal:

[source,bash]
----
gcloud init
----

Log in to your Google Cloud Platform:

[source,bash]
----
gcloud auth login
----

=== Google Cloud Platform Project

Create a new project with a unique name (replace `xxxxxx` with alphanumeric characters of your choice):

[source,bash]
----
gcloud projects create micronaut-guides-xxxxxx
----

NOTE: In GCP, project ids are globally unique, so the id you used above is the one you should use in the rest of this guide.

Change your project:

[source,bash]
----
gcloud config set project micronaut-guides-xxxxxx
----

If you forget the project id, you can list all projects:

[source,bash]
----
gcloud projects list
----

=== Enable billing

Ensure you have a billing account created, and if not create one via the https://console.cloud.google.com/billing[Google Cloud Platform Console].

To get a list of your billing accounts, run:

[source,bash]
----
❯ gcloud beta billing accounts list
ACCOUNT_ID            NAME                  OPEN   MASTER_ACCOUNT_ID
XXXXXX-XXXXXX-XXXXXX  My Billing Account    True
----

You can then attach a billing account to your project:

[source,bash]
----
gcloud beta billing projects link micronaut-guides-xxxxxxx --billing-account=XXXXXX-XXXXXX-XXXXXX
----