:exclude-for-languages:groovy

== Generate Micronaut Application Native Executables with GraalVM

We will use https://www.graalvm.org/[GraalVM], an advanced JDK with ahead-of-time Native Image compilation, to generate a native executable of this Micronaut application.

Compiling Micronaut applications ahead of time with GraalVM significantly improves startup time and reduces the memory footprint of JVM-based applications.

NOTE: Only Java and Kotlin projects support using GraalVM's `native-image` tool. Groovy relies heavily on reflection, which is only partially supported by GraalVM.

=== Native Executable Generation

common:install-graalvm-sdkman.adoc[]

:exclude-for-build:maven

To generate native executables for each application using Gradle, run:

[source, bash]
----
./gradlew nativeCompile
----

The native executables are created in `build/native/nativeCompile` directory and can be run with `build/native/nativeCompile/micronautguide`.

It is possible to customize the name of a native executable or pass additional parameters to GraalVM:

.build.gradle
[source,groovy]
----
graalvmNative {
    binaries {
        main {
            imageName.set('mn-graalvm-application') // <1>
            buildArgs.add('-Ob') // <2>
        }
    }
}
----
<1> The native executable name will now be `mn-graalvm-application`
<2> It is possible to pass extra build arguments to `native-image`. For example, `-Ob` enables the quick build mode.

:exclude-for-build:

:exclude-for-build:gradle

To generate native executables for each application using Maven, run:

[source, bash]
----
./mvnw package -Dpackaging=native-image
----

The native executable is created in the `target` directory and can be run with `target/micronautguide`.

It is possible to customize the name of the native executable or pass additional build arguments using the https://graalvm.github.io/native-build-tools/latest/maven-plugin.html[Maven plugin for GraalVM Native Image building]. Declare the plugin as following:

.pom.xml
[source,xml]
----
<plugin>
    <groupId>org.graalvm.buildtools</groupId>
    <artifactId>native-maven-plugin</artifactId>
    <version>0.10.3</version>
    <configuration>
        <!--  <1> -->
        <imageName>mn-graalvm-application</imageName>
        <buildArgs>
          <buildArg>-Ob</buildArg> <2>
        </buildArgs>
    </configuration>
</plugin>
----
<1> The native executable name will now be `mn-graalvm-application`.
<2> It is possible to pass extra build arguments to `native-image`. For example, `-Ob` enables the quick build mode.

:exclude-for-build:

:exclude-for-languages:
