> Develop and deploy highly scalable containerized applications on a fully managed serverless platform.

common:requirements.adoc[]
* You need a https://cloud.google.com/gcp/[Google Cloud Platform (GCP)] account and a GCP project.
* A computer with x86_64 architecture.

WARNING: The CRaC JDK currently requires that you are using a machine with x86_64 architecture. If you are using a different architecture, you cannot currently build a CRaC checkpointed application.

common:completesolution.adoc[]

common:create-app-features.adoc[]

external:distribution-base/hellocontroller.adoc[]

test:HelloControllerTest[]

common:gcp.adoc[]

=== Enable the Google Cloud Container Registry API

We need somewhere to store our docker images, so we need to enable the Google Cloud Container Registry API for your project via the Google Cloud CLI:

[source, bash]
----
gcloud services enable containerregistry.googleapis.com
----

=== Configure Google Cloud Docker

Run `auth configure-docker` via the Google Cloud CLI:

[source, bash]
----
> gcloud auth configure-docker
----

[source, bash]
----
Adding credentials for all GCR repositories.
WARNING: A long list of credential helpers may cause delays running 'docker build'. We recommend passing the registry name to configure only the registry you are using.
After update, the following will be written to your Docker config file
 located at [~/.docker/config.json]:
 {
  "credHelpers": {
    "gcr.io": "gcloud",
    "marketplace.gcr.io": "gcloud",
    "eu.gcr.io": "gcloud",
    "us.gcr.io": "gcloud",
    "staging-k8s.gcr.io": "gcloud",
    "asia.gcr.io": "gcloud"
  }
}
----