:exclude-for-languages:groovy

== Python Runtime Compilation

When using the GraalVM JDK, Python code executed with the GraalPy engine is just-in-time compiled.
With other JDKs, the Python code is interpreted, resulting in reduced performance.

The easiest way to install https://www.graalvm.org[GraalVM] on Linux or Mac is to use https://sdkman.io/[SDKMan.io].

[source, bash]
.Java 23
----
sdk install java 23-graal
----

For installation on Windows, or for a manual installation on Linux or Mac, see the https://www.graalvm.org/latest/docs/getting-started/[GraalVM Getting Started] documentation.

The previous command installs Oracle GraalVM, which is free to use in production and free to redistribute, at no cost, under the https://www.oracle.com/downloads/licenses/graal-free-license.html[GraalVM Free Terms and Conditions].

Alternatively, you can use the https://github.com/graalvm/graalvm-ce-builds/releases/[GraalVM Community Edition]:

[source, bash]
.Java 23
----
sdk install java 23-graalce
----

== Generate a Micronaut Application Native Executable with GraalVM

Starting with GraalVM for JDK 23, Micronaut applications that use GraalPy or any Truffle language can be compiled into native executables using GraalVM Native Image.

Compiling Micronaut applications ahead of time with GraalVM significantly improves startup time and reduces
the memory footprint of JVM-based applications.

=== Native Image Configuration
GraalVM Native Image compilation requires metadata to correctly run code that uses https://www.graalvm.org/latest/reference-manual/native-image/metadata/#dynamic-proxy[dynamic proxies].

Create a proxy configuration file:
resource:META-INF/native-image/proxy-config.json[]

=== Native Executable Generation

:exclude-for-build:gradle
To generate a native executable using Maven, run:

[source, bash]
----
./mvnw package -Dpackaging=native-image
----

The native executable is created in the _target_ directory and can be run with `./target/micronautguide`.

:exclude-for-build:

:exclude-for-build:maven
To generate a native executable using Gradle, run:

[source, bash]
----
./gradlew nativeCompile
----

The native executable is created in `build/native/nativeCompile` directory and can be run with `build/native/nativeCompile/micronautguide`.

:exclude-for-build: