=== Micronaut Test Resources Goals

https://melix.github.io/blog/2022/08/micronaut-test-resources.html[Micronaut Test Resources aims to achieve the following goals]:

____
> * **zero-configuration**: without adding any configuration, test resources should be spawned and the application configured to use them. Configuration is only required for advanced use cases.
> * **classpath isolation**: use of test resources shouldn’t leak into your application classpath, nor your test classpath
> * **compatible with GraalVM native**: if you build a native binary, or run tests in native mode, test resources should be available
> * **easy to use**: the Micronaut build plugins for Gradle and Maven should handle the complexity of figuring out the dependencies for you
> * **extensible**: you can implement your own test resources, in case the built-in ones do not cover your use case
> * **technology agnostic**: while lots of test resources use Testcontainers under the hood, you can use any other technology to create resources
____
