=== Enable Distributed Configuration

Create a `bootstrap.properties` file in the `resources` directory to https://docs.micronaut.io/latest/guide/#bootstrap[enable distributed configuration].
Add the following:

resource:bootstrap.properties[tag=distributedconfiguration]

<1> Set the application name in `bootstrap.properties` instead of `application.properties` so that it is available when reading configuration from distributed sources.
properties
<2> Set `micronaut.config-client.enabled=true` which is used to read and resolve configuration from distributed sources.

=== Clean up Application Configuration

If `application.properties` sets `micronaut.application.name`, remove it. You moved it to `bootstrap.properties`.

[,diff]
.src/main/resources/application.properties
----
micronaut.application.name=micronautguide
----

=== Disable Distributed Configuration for Test

You can disable distributed configuration in a test by annotating a test with:

[source, java]
----
@Property(name = "micronaut.config-client.enabled", value = StringUtils.FALSE)
@MicronautTest
----