== Installing OpenAPI Generator

To use OpenAPI Generator we need to https://github.com/OpenAPITools/openapi-generator#1---installation[install OpenAPI Generator CLI].

We will use the jar option. https://github.com/OpenAPITools/openapi-generator#13---download-jar[Download it] and store it in the directory that you want to use for this project.

Next, open terminal in the same directory. To verify that generator works correctly run the `help` command:
[source,bash]
----
java -jar openapi-generator-cli-XXX.jar help
----

It should provide a description and a list of commands.

[NOTE]
===============================
All the options for installation are given at the https://openapi-generator.tech/docs/installation["CLI Installation" guide on the OpenAPI Generator website].

In particular:

* run `brew install openapi-generator` for Homebrew installation,
* or read the link:https://openapi-generator.tech/docs/installation/#bash-launcher-script["Bash Launcher Script" section]
to set up a bash script with automatic updates

If you installed the generator with a package manager or bash launcher script, simply run
[source,bash]
----
openapi-generator-cli help
----
===============================

NOTE: You can also use the https://openapi-generator.tech/docs/online[OpenAPI Generator Online Service] but its usage
is not covered by this guide.