// Define this variable if need mysql:
// :database:mysql

=== Database Migration with Flyway

We need a way to create the database schema. For that, we use
https://micronaut-projects.github.io/micronaut-flyway/latest/guide/[Micronaut integration with Flyway].

http://www.flyway.org[Flyway] automates schema changes significantly simplifying schema management tasks, like migrating, rolling-back and reproducing in multiple environments.

Add the following snippet to include the necessary dependencies:

:dependencies:
dependency:micronaut-flyway[groupId=io.micronaut.flyway]
ifeval::["{database}" == "mysql"]
dependency:flyway-mysql[groupId=org.flywaydb,scope=runtimeOnly]
endif::[]
:dependencies:

We will enable Flyway in the `application.yml` and configure it to perform migration on one of the defined data sources.

resource:application.yml[tag=flyway]

<1> Enable Flyway for the `default` datasource.

NOTE: Configuring multiple data sources is as simple as enabling Flyway for each of them. You can also specify folders that will be used for migrating each datasource. Find out more in the https://micronaut-projects.github.io/micronaut-flyway/latest/guide/[Micronaut Flyway documentation].

Flyway migration will be automatically triggered before Micronaut application starts. Flyway will read migration commands in the `resources/db/migration/` directory, execute them if necessary and verify the configured data source is consistent with them.

Create the following migration files with the database schema creation:
