micronaut:
  application:
    name: bookinventory
endpoints:
  health:
    enabled: true
    sensitive: false
#tag::jaeger[]
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 1 # <1>
#end::jaeger[]