micronaut:
  application:
    name: demo
  jms:
    sqs:
      enabled: true
aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_KEY}
netty:
  default:
    allocator:
      max-order: 3
