micronaut:
  application:
    name: micronautguide
netty:
  default:
    allocator:
      max-order: 3
#tag::tracing[]
tracing:
  zipkin:
    enabled: true # <1>
    sampler:
      probability: 1 # <2>
#end::tracing[]