include::{commondir}/common-header.adoc[]

The application exposes some REST endpoints and stores data in a MySQL database using Micronaut Data JDBC.

== What you will need

To complete this guide, you will need the following:

* Some time on your hands
* A decent text editor or IDE
* JDK 1.8 or greater installed with `JAVA_HOME` configured appropriately
* https://www.docker.io/gettingstarted/#h_installation[Docker] installed to run MySQL and for running tests, using https://www.testcontainers.org[Testcontainers].

include::{commondir}/common-completesolution.adoc[]

== Writing the Application

include::{commondir}/common-cli-or-launch.adoc[]

:exclude-for-languages:groovy
[source,bash]
----
mn create-app --features=data-jdbc,flyway,jdbc-hikari,mysql,testcontainers,graalvm example.micronaut.micronautguide --build=@build@ --lang=@lang@
----
:exclude-for-languages:

:exclude-for-languages:java,kotlin
[source,bash]
----
mn create-app --features=data-jdbc,flyway,jdbc-hikari,mysql,testcontainers example.micronaut.micronautguide --build=@build@ --lang=@lang@
----
:exclude-for-languages:

include::{commondir}/common-build-lang-arguments.adoc[]

:exclude-for-languages:groovy
If you use Micronaut Launch, select Micronaut Application as application type and add the `data-jdbc`, `flyway`, `jdbc-hikari`, `mysql`, `testcontainers` and `graalvm` features.
:exclude-for-languages:

:exclude-for-languages:java,kotlin
If you use Micronaut Launch, select Micronaut Application as application type and add the `data-jdbc`, `flyway`, `jdbc-hikari`, `mysql` and `testcontainers` features.
:exclude-for-languages:

include::{commondir}/common-default-package.adoc[]

include::{commondir}/common-annotationprocessors.adoc[]

=== Data Source configuration

Add the following dependencies:

Define the datasource in `src/main/resources/application.yml`.

resource:application.yml[tag=datasource]

=== DB Schema

We need a way to create the database schema. For that we will use
https://micronaut-projects.github.io/micronaut-flyway/latest/guide/[Micronaut integration with Flyway].

Configure the database migrations directory for Flyway in `application.yml`.

resource:application.yml[tag=flyway]

Create the file `V1__schema.sql` with the database schema creation:

resource:db/migration/V1__schema.sql[]

During application startup, Flyway will execute the SQL file and create the schema needed for the application.

=== Domain

Create the domain entities:

source:domain/Genre[]

TIP: You could use a https://micronaut-projects.github.io/micronaut-data/latest/guide/#sqlAnnotations[subset of supported JPA annotations] instead by including the following `compileOnly` scoped dependency: `jakarta.persistence:jakarta.persistence-api`.

=== Repository Access

Next, create a repository interface to define the operations to access the database. Micronaut Data will implement the interface at compilation time:

source:GenreRepository[]

callout:jdbcrepository[1]
<2> `Genre`, the entity to treat as the root entity for the purposes of querying, is established either from the method signature or from the generic type parameter specified to the `GenericRepository` interface.

The repository extends from `PageableRepository`. It inherits the hierarchy `PageableRepository` -> `CrudRepository` -> `GenericRepository`.

|===
|Repository | Description

|`PageableRepository`
| A repository that supports pagination. It provides `findAll(Pageable)` and `findAll(Sort)`.

|`CrudRepository`
| A repository interface for performing CRUD (Create, Read, Update, Delete). It provides methods such as `findAll()`, `save(Genre)`, `deleteById(Long)`, and `findById(Long)`.

|`GenericRepository`
| A root interface that features no methods but defines the entity type and ID type as generic arguments.

|===

=== Controller

include::{commondir}/common-validation.adoc[]

Create a class to encapsulate the Update operations:

source:GenreUpdateCommand[]

callout:introspected[1]

Create `GenreController`, a controller that exposes a resource with the common CRUD operations:

source:GenreController[]

callout:executes-on[1]
callout:controller[number=2,arg0=/genres]
callout:constructor-di[number=3,arg0=GenreRepository]
<4> Maps a `GET` request to `/genres/{id}`, which attempts to show a genre. This illustrates the use of a URL path variable.
<5> Returning an empty optional when the genre doesn't exist makes the Micronaut framework respond with 404 (not found).
<6> Maps a `PUT` request to `/genres`, which attempts to update a genre.
<7> Adds `@Valid` to any method parameter that requires validation. Use a POJO supplied as a JSON payload in the request to populate command.
<8> It is easy to add custom headers to the response.
<9> Maps a `GET` request to `/genres/list`, which returns a list of genres. This mapping illustrates URL parameters being mapped to a single POJO.
<10> You can bind `Pageable` as a controller method argument. Check the examples in the following test section and read the https://micronaut-projects.github.io/micronaut-data/latest/guide/configurationreference.html#io.micronaut.data.runtime.config.DataConfiguration.PageableConfiguration[Pageable configuration] options. For example, you can configure the default page size with the configuration property `micronaut.data.pageable.default-page-size`.
<11> Maps a `POST` request to `/genres`, which attempts to save a genre.
<12> Maps a `POST` request to `/ex`, which generates an exception.
<13> Maps a `DELETE` request to `/genres/{id}`, which attempts to remove a genre. This illustrates the use of a URL path variable.

=== Writing Tests

Create a test to verify the CRUD operations:

test:GenreControllerTest[]

callout:micronaut-test[1]
callout:http-client[2]
callout:http-request[3]
<4> If you care just about the object in the response, use `retrieve`.
<5> Sometimes, receiving just the object is not enough, and you need information about the response. In this case, instead of `retrieve`, use the `exchange` method.

To configure the MySQL Testcontainer, create `application-test.yml` in the test's resources folder.

testResource:application-test.yml[]


include::{commondir}/common-testApp.adoc[]

== Running the Application

Execute the following command to run a MySQL container:

[source,bash]
----
docker run -it --rm \
	-p 3306:3306 \
	-e MYSQL_DATABASE=db \
	-e MYSQL_ALLOW_EMPTY_PASSWORD=yes \
	mysql:8
----

include::{commondir}/common-runapp-instructions.adoc[]

Save one genre, and your `genre` table will now contain an entry.

[source, bash]
----
curl -X "POST" "http://localhost:8080/genres" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{ "name": "music" }'
----

include::{commondir}/common-graal-with-plugins.adoc[]

:exclude-for-languages:groovy

You can execute the `genres` endpoints exposed by the native image. For example:

[source, bash]
----
 curl localhost:8080/genres/list
----

:exclude-for-languages:

== Next steps

Read more about https://micronaut-projects.github.io/micronaut-data/latest/guide/[Micronaut Data].

include::{commondir}/common-helpWithMicronaut.adoc[]
