micronaut:
  application:
    name: micronautguide
---
#tag::datasource[]
datasources:
  default:
    dialect: MYSQL
    driverClassName: ${JDBC_DRIVER:com.mysql.cj.jdbc.Driver}
#end::datasource[]
---
#tag::flyway[]
flyway:
  datasources:
    default:
      enabled: true # <1>
#end::flyway[]
---
#tag::assets[]
micronaut:
  router:
    static-resources:
      assets:
        paths: 'classpath:assets'
        mapping: '/assets/**'
#end::assets[]