micronaut:
  application:
    name: micronautguide
---
#tag::config[]
micronaut:
  caches:
    headlines: # <1>
      charset: 'UTF-8'
#end::config[]
---
#tag::hazelcast[]
hazelcast:
  client:
    network:
      addresses:
        - '192.168.4.67:5701'
#end::hazelcast[]