common:header.adoc[]

common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app-features.adoc[]

:leveloffset: +1

common:openapi-dependencies.adoc[]

== Latest Guide Controller

First, let's create a controller that exposes the https://guides.micronaut.io[Micronaut Guides] information.

=== Guides Model

We support different build tools per guide:

source:BuildTool[]

A guide may be written in multiple languages:

source:Language[]

Thus, we have several options per guide:

source:Option[]
callout:serdeable[]
callout:constraints[]

The following type represents a Micronaut Guide:

source:Guide[]
callout:serdeable[]
callout:constraints[]
callout:swagger-schema[]

=== Controller

Let's create a controller for which we will generate an OpenAPI Specification at build time.

source:LatestGuidesController[]

We could test such a controller with:

test:LatestGuidesControllerTest[]

callout:micronaut-test[]
callout:http-client[]

== @OpenAPIDefinition

The Micronaut OpenAPI integration requires a class to be annotated with `@OpenAPIDefinition`. Modify the application class and annotate it.

source:Application[]

== OpenAPI Generated at Compile Time

By adding the `@OpenAPIDefinition` annotation to `Application`, an OpenAPI specification is generated at compile time. You can test it as follows:

test:OpenApiGeneratedTest[]
callout:micronaut-test-start-application-false[]

== Expose the OpenAPI Specification

We can expose the OpenAPI specification generated at compile time as a static resource with the following configuration:

resource:application.properties[tag=static-resources-swagger]

You can test that the OpenAPI specification is available:

test:OpenApiExposedTest[]
callout:micronaut-test[]
callout:http-client[]
