micronaut:
  application:
    name: micronautguide
  security:
    authentication: idtoken # <1>
    oauth2:
      clients:
        micronaut: # <2>
          client-id: ${OAUTH_CLIENT_ID:xxx} # <3>
          client-secret: ${OAUTH_CLIENT_SECRET:yyy} # <3>
          openid:
            issuer: ${OAUTH_ISSUER:zzz} # <3>
    endpoints:
      logout:
        enabled: true
        get-allowed: true # <4>
netty:
  default:
    allocator:
      max-order: 3
