[micronaut.security.oauth2]
enabled = false

[micronaut.security.oauth2.clients.keycloak]
enabled = false

[micronaut.security.oauth2.clients.default]
enabled = false

[micronaut.security.jwks]
enabled = false

[micronaut.security.openid-configuration]
enabled = false
