common:header-top.adoc[]

== Sample Project

You can link:@sourceDir@.zip[download a sample application] with the code examples in this article.

== Introduction

This guide is the sixth tutorial of https://guides.micronaut.io/latest/tag-building_a_rest_api.html[Building a Rest API] - a series of tutorials comparing how to develop a REST API with Micronaut Framework and Spring Boot.

In this tutorial, we secure the API via https://en.wikipedia.org/wiki/Basic_access_authentication[basic authentication].
Only users with the role `SAAS_SUBSCRIPTION_OWNER` can access the endpoints.
Each subscription is associated with a user. Authenticated users can only access their own subscriptions.

== Dependencies

=== Spring Boot

In the Spring boot application, add https://docs.spring.io/spring-security/reference/getting-spring-security.html[Spring Boot Starter Security] dependency:

dependency:spring-boot-starter-security[groupId=org.springframework.boot]

=== Micronaut Security

In the Micronaut application, add https://micronaut-projects.github.io/snapshot/4.7.0/guide/[Micronaut Security] and https://docs.spring.io/spring-security/site/docs/5.0.x/reference/html/crypto.html[Spring Security Crypto]. We use the latter to encrypt the user's password using BCrypt.

:dependencies:

dependency:micronaut-security[groupId=io.micronaut.security]
dependency:spring-security-crypto[groupId=org.springframework.security,version=@spring-security-cryptoVersion@]

:dependencies:

== Entity

We add an `owner` property to the `SaasSubscription` entity. The `owner` is the unique identity of user person who created and can manage a subscription.


=== Spring Boot

source:SaasSubscription[app=springboot]

=== Micronaut Framework

source:SaasSubscription[app=micronautframework]

callout:serdeable[]
callout:mapped-entity[]
callout:mapped-entity-id[]
callout:generated-value[]

== Repository

We need to modify the repositories to add methods leveraging the `owner` property.

=== Spring Boot

source:SaasSubscriptionRepository[app=springboot]

callout:crudrepository[]
callout:spring-boot-paging-and-sorting-repository[]

=== Micronaut Framework

source:SaasSubscriptionRepository[app=micronautframework]

callout:jdbcrepository[]
callout:pageable-repository[]

== Security Configuration

Two sample users will be able to authenticate: `sarah1` and `john-owns-no-subscriptions`. Only the former has the role `SAAS_SUBSCRIPTION_OWNER`.

=== Spring Boot

The following class configures Spring Security for the application:

source:SecurityConfig[app=springboot]

callout:spring-boot-configuration[]
<2> Create a bean of type `PasswordEncoder`
<3> Create a bean of type `SecurityFilterChain` to configure Spring Security's filter chain.
<4> All HTTP requests to `/subscriptions/**` endpoints are required to be authenticated using HTTP Basic Authentication security (username and password). They do not require CSRF security.
<5> Create a bean of type `UserDetails`.
<6> `InMemoryUserDetailsManager` is a test-only Service that Spring security provides as a way to provide user authentication and authorization information.

=== Micronaut Framework

In Micronaut Security, https://micronaut-projects.github.io/micronaut-security/snapshot/guide/#basicAuth[Basic authentication] is enabled by default.
Micronaut Security attempts to authenticate the supplied credentials against every bean of type `AuthenticationProvider`.
Write the following authentication provider singleton which authenticates the same sample users as we did in the Spring Boot application.

source:AppAuthenticationProvider[app=micronautframework]

callout:singleton[]

== Controllers

NOTE: Both frameworks allow you to bind the authenticated user to a controller method parameter of type `java.security.Principal`.

The controllers use the methods added to the repositories.

=== Spring Boot

source:SaasSubscriptionController[app=springboot]

callout:spring-boot-rest-controller[]
callout:spring-boot-request-mapping[]
callout:constructor-di[arg0=SaasSubscriptionRepository]
callout:spring-boot-get-mapping[arg0=findById,arg1=/subscriptions/{id}]
callout:spring-boot-path-variable[]
callout:principal[]

=== Micronaut Framework

NOTE: The application endpoints are only accessible to users with role `SAAS_SUBSCRIPTION_OWNER`. The Micronaut application annotates every controller with `@Secured("SAAS_SUBSCRIPTION_OWNER")`. The Spring Boot application specifies the role requirement in the `SecurityConfig.java` file.

source:SaasSubscriptionController[app=micronautframework]

callout:controller[arg0=/subscriptions]
callout:secured-roles[]
callout:constructor-di[arg0=SaasSubscriptionRepository]
callout:get[arg0=findById,arg1=/subscriptions/{id}]
callout:pathvariable[]
callout:principal[]
callout:http-response[]

== Tests

In this tutorial, we use https://joel-costigliola.github.io/assertj/[AssertJ] in the tests.

=== Database Schema

The database schema should add `owner` column.

testResource:schema.sql[app=springboot]

=== Tests Seed Data

The seed data inserts entries with different owners.

testResource:data.sql[app=springboot]

=== Spring Boot Test

The following tests shows that you can use the method `TestRestTemplate::withBasicAuth` to supply basic authentication credentials.

test:SecurityTest[app=springboot]

callout:spring-boot-test[]
callout:autowired[arg0=TestRestTemplate]
callout:spring-boot-test-rest-template[]
<4> basic authentication for `sarah1`.

=== Micronaut Test

The following tests shows that you can use the method `MutableHttpRequest::basicAuth` to supply basic authentication credentials.

test:SecurityTest[app=micronautframework]

callout:micronaut-test[]
callout:http-client[]
callout:http-client-response-exception[]

== Conclusion

As you see in this tutorial, securing a REST API with basic authentication is straightforward in both Micronaut and Spring Boot.
Security configuration differs between both frameworks but the coding experience of accessing the authenticated user as a Controller method parameter of type `java.security.Principal` is identical.

== Next Steps

Learn more about https://micronaut-projects.github.io/micronaut-security/snapshot/guide/[Micronaut Security]
