[micronaut.application]
name = "micronautguide"

# tag::allTeamConfig[]
# tag::teamConfig[]
[team]
name = "Steelers"
color = "Black"
player-names = ["Mason Rudolph", "James Connor"]
# end::teamConfig[]

# <1>
[team.team-admin]
manager = "Nirav Assar"
coach = "Mike Tomlin"
president = "Dan Rooney"
# end::allTeamConfig[]

# tag::stadiumConfig[]
# <1>
[stadium.coors]
city = "Denver"
size = 50000

[stadium.pnc]
city = "Pittsburgh"
size = 35000
# end::stadiumConfig[]
