micronaut.application.name=micronautguide

#tag::datasource[]
# <1>
datasources.default.driver-class-name=oracle.jdbc.OracleDriver
# <2>
datasources.default.db-type=oracle
# <3>
datasources.default.dialect=ORACLE
#end::datasource[]

#tag::cache[]
# <1>
micronaut.oracle.cache.datasource=default
# <2>
micronaut.oracle.cache.prefix=MN
# <3>
micronaut.caches.headlines.expire-after-write=10m
# <4>
micronaut.caches.headlines.cleanup-interval=1m
#end::cache[]

#tag::testresources[]
test-resources.containers.oracle.image-name=gvenzl/oracle-free
test-resources.containers.oracle.image-tag=latest
test-resources.containers.oracle.startup-timeout=600s
#end::testresources[]
