== Getting Started

include::{commondir}/common-micronautonex.adoc[]

In this guide we are going to create a Micronaut app written in Java.

=== What you will need

=== Solution

include::{commondir}/common-completesolution.adoc[]


== Writing the App

include::{commondir}/common-create-app-java.adoc[]

:exclude-for-languages:groovy

include::{commondir}/common-annotationprocessors.adoc[]

:exclude-for-languages:

=== Application

`Application.@languageextension@` is used when running the application via Gradle or via deployment. You can also run the main class directly within your IDE if it is configured correctly.

[source,@language@]
.src/main/@language@/example/micronaut/Application.@languageextension@
----
include::{sourceDir}/@sourceDir@/src/main/@language@/example/micronaut/Application.@languageextension@[]
----

=== Controller

In order to create a microservice that responds with "Hello World" you first need a controller.

Create a Controller:

[source,@language@]
.src/main/@language@/example/micronaut/HelloController.@languageextension@
----
include::{sourceDir}/@sourceDir@/src/main/@language@/example/micronaut/HelloController.@languageextension@[]
----

<1> The class is defined as a controller with the http://docs.micronaut.io/snapshot/api/io/micronaut/http/annotation/Controller.html[@Controller] annotation mapped to the path `/hello`
<2> The http://docs.micronaut.io/snapshot/api/io/micronaut/http/annotation/Get.html[@Get] annotation is used to map the index method to all requests that use an HTTP GET
<3> By default a Micronaut's response uses `application/json` as `Content-Type`. We are returning a String not a JSON object. Because of that, we set it to `text/plain`.
<4> A String "Hello World" is returned as the result

=== Test

Create a test which verifies that when you do a GET request to `/hello` you get `Hello World` as a response:

[source,@language@]
.src/test/@language@/example/micronaut/HelloControllerTest.@languageextension@
----
include::{sourceDir}/@sourceDir@/src/test/@language@/example/micronaut/HelloController@testsuffix@.@languageextension@[]
----

<1> Annotate the class with `@MicronautTest` so Micronaut will initialize the application context and the embedded server.
<2> Inject the `RxHttpClient` bean. It is used the execute an HTTP call to the controller.
<3> Creating HTTP Requests is easy thanks to Micronaut's fluid API.

== Testing the Application

include::{commondir}/common-testApp.adoc[]

== Running the Application

include::{commondir}/common-runapp.adoc[]

:exclude-for-languages:groovy

== Generate a Micronaut app's Native Image with GraalVM

dependency:micronaut-graal[scope="annotationProcessor"]

include::{commondir}/common-graal.adoc[]

=== Micronaut + GraalVM changes

include::{commondir}/common-graal-setup.adoc[]

=== Native Image generation

include::{commondir}/common-graal-install.adoc[]

include::{commondir}/common-graal-nativeimage.adoc[]

You can execute the endpoint exposed by the native image:

[source, bash]
----
$ curl localhost:8080/hello
Hello World
----

=== Native Image generation with Docker

include::{commondir}/common-graal-docker.adoc[]

:exclude-for-languages:

== Next steps

Read more about https://micronaut-projects.github.io/micronaut-test/latest/guide/index.html[Micronaut testing].

== Help with Micronaut

include::{commondir}/common-helpWithMicronaut.adoc[]