common:header.adoc[]

common:requirements.adoc[]

common:completesolution.adoc[]

== One-to-Many Relationship

In this tutorial, you develop a one-to-many relationship, as illustrated in the following tables.

.Table: Contact
[cols="1,1,1", options="header"]
|===
| id | first_name | last_name
| 1  | Sergio       | del Amo
|===

.Table: Phone
[cols="1,1,1", options="header"]
|===
| id | phone       | contact_id
| 1  | +14155552671 | 1
| 2  | +442071838750 | 1
|===

common:create-app-features.adoc[]

common:datasource-header.adoc[]

:exclude-for-languages:python

resource:application.properties[tag=datasource]

:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin

resource:application.toml[tag=datasource]

:exclude-for-languages:

:exclude-for-languages:python
common:liquibase.adoc[]

:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin

=== Database Migration with Liquibase

We need a way to create the database schema. For that, we use
https://micronaut-projects.github.io/micronaut-liquibase/latest/guide/[Micronaut integration with Liquibase].

Add the following snippet to include the necessary dependencies:

dependency:micronaut-liquibase[groupId=io.micronaut.liquibase]

Configure the database migrations directory for http://www.liquibase.org[Liquibase] in `application.toml`.

resource:application.toml[tag=liquibase]

Create the following files with the database schema creation:

:exclude-for-languages:

resource:db/changelog/01-schema.xml[]

== Entities

Create an entity mapping the table `contact`:

source:ContactEntity[]
callout:mapped-entity[]
callout:mapped-entity-id[]
callout:generated-value[]
callout:nullable-record-id[]
callout:relation[]

Create an entity mapping the table `phone`:

source:PhoneEntity[]
callout:mapped-entity[]
callout:mapped-entity-id[]
callout:generated-value[]
callout:nullable-record-id[]
callout:relation[]

== Projections

Create one projection to return a complete view, phones included, of the contact:

source:ContactComplete[]
callout:introspected[]

Create one projection to preview a contact, no phones:

source:ContactPreview[]
callout:introspected[]

== Repositories

source:PhoneRepository[]
callout:jdbcrepository[]
callout:crudrepository[]

source:ContactRepository[]
callout:jdbcrepository[]
callout:crudrepository[]
callout:join-left-fetch[arg0=phones]
callout:at-query[]


== Tests

The following tests illustrate the association queries:

test:ContactRepositoryTest[]
callout:micronaut-test-transactional-false[]
callout:injection[arg0=ContactRepository]
callout:injection[arg0=PhoneRepository]

common:testApp.adoc[]

common:nativetest.adoc[]

common:next.adoc[]

Read more about https://micronaut-projects.github.io/micronaut-data/latest/guide/[Micronaut Data].

common:helpWithMicronaut.adoc[]
