common:completesolution.adoc[]

common:create-app-features.adoc[]

=== Metrics Configuration

Several groups of metrics are enabled by default; these include system metrics (JVM info, uptime, etc.), as well as metrics tracking web requests, DataSource activity, and others. Overall metrics can be enabled or disabled, and groups can be individually enabled or disabled in configuration.

Add the following to `application.yml`:

common:yaml-dependency.adoc[]

resource:application.yml[tag=metrics]

<1> Change to `false` to disable all metrics, e.g., per-environment
<2> These default to `true` and are only here for convenience, to be able to disable a subset of metrics

=== Custom Metrics

If the built-in metrics aren't enough, you can easily add custom metrics with the following annotations.

@Timed:: Creates a `Timer` metric that contains the total time, max time and count.

@Counted:: Creates a `Counter` metric that only contains a count.

If you want to create your own gauge, you can inject `io.micrometer.core.instrument.MeterRegistry` to your bean.

=== Data Source Metrics

`DataSource` metrics are enabled by default if you use the HikariCP (the default), Tomcat JDBC, or Commons DBCP connection pool.

common:flyway.adoc[]

resource:db/migration/V1__schema.sql[]

During application startup, Flyway will execute the SQL file and create the schema needed for the application.

=== Domain

Create a `Book` domain class that uses https://micronaut-projects.github.io/micronaut-data/latest/guide/#sql[Micronaut Data JDBC]:

source:Book[]
callout:mapped-entity[1]
callout:mapped-entity-id[2]
callout:generated-value[3]

=== BookRepository

Next, create the `BookRepository` interface to define database operations. Micronaut Data will implement the interface at compilation time:

source:BookRepository[]
callout:jdbcrepository[1]
<2> Specifies that `Book` is the root entity, and the primary key type is `Long`.

=== Data populator class

Create a `DataPopulator` class to create some example database entries when the application starts:

source:DataPopulator[]

callout:singleton[1]
callout:constructor-di[number=2,arg0=BookRepository]
callout:event-listener[3]
callout:transactional[4]

=== BookController

Create `BookController` to access `Book` instances (and trigger JDBC metric data):

source:BookController[]
callout:controller[number=1,arg0=/books]
callout:executes-on[2]
callout:constructor-di[number=3,arg0=BookRepository]
<4> Maps a `GET` request to `/books`, which returns a list of `Book`
<5> Creates a `Timer` metric with the given name. If the name is omitted, defaults to `method.timed`.
<6> Maps a `GET` request to `/books/{isbn}`, which attempts to show a `Book`. This illustrates the use of a URL path variable.
<7> Creates a `Counter` metric with the given name. If the name is omitted, defaults to the `method.counted`.

=== Custom Metrics

To see custom metrics in action, create a service that periodically retrieves the current Bitcoin price in USD using REST.

==== Model

We'll need a data class to represent the REST response. Create the `BitcoinPrice` class:

source:crypto/BitcoinPrice[]

callout:introspected[1]

==== Kucoin Declarative HTTP Client

Create declarative Micronaut HTTP Client interface that will be implemented at compile time:

source:crypto/PriceClient[]

callout:client[1]

==== HTTP Service Configuration

Modify `application.yml` to configure the URL for the `kucoin` Service ID:

resource:application.yml[tag=http-services]

<1> The ID we used with `@Client`
<2> The URL for the `kucoin` service

==== Service

Create a `CryptoService` class that uses `PriceClient` and updates three custom meters:

source:crypto/CryptoService[]
callout:singleton[1]
<2> Use constructor injection to inject `PriceClient`, `MeterRegistry`, and `ObjectMapper` beans
<3> Create a `Counter` to track the total number of updates
<4> Create a `Timer` to track the total time performing updates
<5> Create a `Gauge` to track the most recent update
<6> Use the `Scheduled` annotation to configure regular updates
<7> Update the `Timer`
<8> Increment the `Counter`
<9> Update the `Gauge` with the latest price

== Testing the Application

Create the `src/test/resources/application-test.yml` configuration file for tests.

testResource:application-test.yml[]

<1> Disable crypto price lookups with a long initial delay

Create a test class to verify metrics functionality:

test:MetricsTest[]
callout:micronaut-test[1]
<2> Inject the `MeterRegistry` bean
<3> Inject the `LoggingSystem` bean
callout:http-client[4]

Create an additional test class to verify the custom metrics:

test:CryptoUpdatesTest[]

The previous test creates two Micronaut embedded servers. One mocks the `kucoin` API, the other is our application. The test uses `@Requires` to conditionally load a controller only for the `kucoin` bean context.
We used an identifier with `@Client`, which makes it easy to point our HTTP client to the mock server.

=== Running the tests

common:testApp-noheader.adoc[]

== Running the Application

common:runapp-instructions.adoc[]

Alternately, to make the Bitcoin price update occur more frequently to see the effects on metrics, start the application with a config override to update every five seconds:

:exclude-for-build:maven

[source,bash]
----
./gradlew run --args="-crypto.updateFrequency=5s"
----

:exclude-for-build:
:exclude-for-build:gradle

[source,bash]
----
./mvnw mn:run -Dmn.appArgs="-crypto.updateFrequency=5s"
----

:exclude-for-build:

You can retrieve a list of known metrics using cURL:

[source,bash]
----
curl localhost:8080/metrics
----

The response should look like this:

[source,json]
----
{
  "names": [
    "bitcoin.price.checks",
    "bitcoin.price.latest",
    "bitcoin.price.time",
    "executor",
    "executor.active",
    "executor.completed",
    "executor.pool.core",
    "executor.pool.max",
    "executor.pool.size",
    "executor.queue.remaining",
    "executor.queued",
    "hikaricp.connections",
    "hikaricp.connections.acquire",
    "hikaricp.connections.active",
    ...
    "jvm.threads.peak",
    "jvm.threads.states",
    "logback.events",
    "process.cpu.usage",
    "process.files.max",
    "process.files.open",
    "process.start.time",
    "process.uptime",
    "system.cpu.count",
    "system.cpu.usage",
    "system.load.average.1m"
  ]
}
----

After the application has been running for a bit and has made a few Bitcoin price checks, we can view the related metric values:

[source,bash]
----
curl localhost:8080/metrics/bitcoin.price.latest
----

[source,json]
----
{
  "measurements": [{ "statistic": "VALUE", "value": 29659.0 } ],
  "name": "bitcoin.price.latest"
}
----

[source,bash]
----
curl localhost:8080/metrics/bitcoin.price.checks
----

[source,json]
----
{
  "measurements": [{ "statistic": "COUNT", "value": 5.0 } ],
  "name": "bitcoin.price.checks"
}
----

[source,bash]
----
curl localhost:8080/metrics/bitcoin.price.time
----

[source,json]
----
{
  "baseUnit": "seconds",
  "measurements": [
    { "statistic": "COUNT",      "value": 5.0 },
    { "statistic": "TOTAL_TIME", "value": 2.525546791 },
    { "statistic": "MAX",        "value": 0.851958216 }
  ],
  "name": "bitcoin.price.time"
}
----

common:graal-with-plugins.adoc[]

:exclude-for-languages:groovy

Start the native image and run the cURL commands above to see that the application works the same way as before, with faster startup and response times.

:exclude-for-languages: