common:header.adoc[]

We'll use https://micronaut-projects.github.io/micronaut-micrometer/latest/guide/[Micronaut Micrometer] to expose application metric data with https://micrometer.io/[Micrometer].

common:requirements.adoc[]

common:completesolution.adoc[]

== Writing the Application

common:cli-or-launch.adoc[]

[source,bash]
----
mn @cli-command@ example.micronaut.micronautguide \
    --features=data-jdbc,flyway,management,graalvm \
    --build=@build@ --lang=@lang@
----

common:build-lang-arguments.adoc[]

common:default-package.adoc[]

If you use Micronaut Launch, select Micronaut Application as application type and add `data-jdbc`, `flyway`, `management`, and `graalvm` features.

diffLink:[featureExcludes=micronaut-micrometer-core]

common:annotationprocessors.adoc[]

=== Dependencies

Add a dependency for `micronaut-micrometer-core` to add core Micrometer support:

dependency:micronaut-micrometer-core[groupId=io.micronaut.micrometer]

=== Metrics Configuration

Several groups of metrics are enabled by default; these include system metrics (JVM info, uptime, etc.) as well as metrics tracking web requests, DataSource activity, and others. Overall metrics can be enabled or disabled, and groups can be individually enabled or disabled in configuration.

Add the following to `application.yml`:

resource:application.yml[tag=metrics]
<1> Change to `false` to disable all metrics, e.g., per-environment
<2> Uncomment this section to send metrics to https://micronaut-projects.github.io/micronaut-micrometer/latest/guide/#metricsAndReporters[one of the many supported registries]. Note that you also need to add a build dependency for the registry, e.g., `micronaut-micrometer-registry-atlas`
<3> Change to `false` to disable sending to Atlas
<4> Metrics are initially configured to update every minute. See https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#parse-java.lang.CharSequence-[java.time.Duration#parse(CharSequence)]
<5> These default to `true` and are only here for convenience, to be able to disable a subset of metrics

=== Database Access

`DataSource` metrics are enabled by default if you use the HikariCP (the default), Tomcat JDBC, or Commons DBCP connection pool. Create a `Book` domain class that uses https://micronaut-projects.github.io/micronaut-data/latest/guide/#sql[Micronaut Data JDBC]:

source:Book[]
callout:mapped-entity[1]
callout:mapped-entity-id[2]
callout:generated-value[3]

=== BookRepository

Next, create the `BookRepository` interface to define database operations. Micronaut Data will implement the interface at compilation time:

source:BookRepository[]
callout:jdbcrepository[1]
<2> Specifies that `Book` is the root entity and the primary key type is `Long`.

=== Data populator class

Create a `DataPopulator` class to create some example database entries when the application starts:

source:DataPopulator[]

callout:singleton[1]
callout:requires-not-env-test[2]
callout:constructor-di[number=3,arg0=BookRepository]
callout:event-listener[4]

=== BookController

Create `BookController` to access `Book` instances (and trigger JDBC metric data):

source:BookController[]
callout:controller[number=1,arg0=/books]
callout:executes-on[2]
callout:constructor-di[number=3,arg0=BookRepository]
<4> Maps a `GET` request to `/books`, which returns a list of `Book`
<5> Maps a `GET` request to `/books/{isbn}`, which attempts to show a `Book`. This illustrates the use of a URL path variable.

=== CryptoService

To see custom metrics in action, create a service that periodically retrieves the current Bitcoin price in USD using REST.

We'll need a data class to represent the REST response. Create the `BitcoinPrice` class:

source:crypto/BitcoinPrice[]

callout:introspected[1]

=== Kucoin HTTP Client

Create declarative Micronaut HTTP Client interface that will be implemented at compile time:

source:crypto/PriceClient[]

Configure the URLs for the Service ID `kucoin`.
Modify `application.yml`

resource:application.yml[tag=http-services]

<1> Same ID we used with `@Client`
<2> URL where the `books` service will reside.

Create the `CryptoService` class which uses `PriceClient` and updates three custom meters:

source:crypto/CryptoService[]
callout:singleton[1]
<2> Use constructor injection to inject `PriceClient`, `MeterRegistry`, and `ObjectMapper` beans
<3> Create a `Counter` to track the total number of updates
<4> Create a `Timer` to track the total time performing updates
<5> Create a `Gauge` to track the most recent update
<6> Use the `Scheduled` annotation to configure regular updates
<7> Update the `Timer`
<8> Increment the `Counter`
<9> Update the `Gauge` with the latest price

=== Database Migration with Flyway

To keep things simple, we're using an in-memory https://www.h2database.com/html/main.html[H2] database.

https://micronaut-projects.github.io/micronaut-flyway/latest/guide/[Micronaut Flyway] will manage database migrations; enable Flyway migrations by adding this to your `application.yml`:

resource:application.yml[tag=flyway]
<1> Enable Flyway for the `default` datasource.

At startup, any migration scripts in the `resources/db/migration` directory that haven't run yet will be run. Create the following migration file to create the `book` database table:

resource:db/migration/V1__schema.sql[]

== Testing the Application

Create `application-test.yml` to disable sending metrics to Atlas (if you enabled it) during tests, and to disable crypto price lookups:

testResource:application-test.yml[]
<1> Disable sending metrics to Atlas
<2> Disable crypto price lookups with a long initial delay

Create the `MetricsTest` class to test metrics functionality:

test:MetricsTest[]
callout:micronaut-test[1]
<2> Inject the `MeterRegistry` bean
<3> Inject the `LoggingSystem` bean
callout:http-client[4]

Create the `CryptoUpdatesTest` to test the custom metric:

test:CryptoUpdatesTest[]

common:testApp-noheader.adoc[]

== Running the Application

Before starting the application, if you're exporting metrics to an external registry be sure the registry is available.

common:runapp-instructions.adoc[]

Alternately, to make the Bitcoin price update occur more frequently to see the effects on metrics, start the application with a config override to update every five seconds:

:exclude-for-build:maven

[source,bash]
----
./gradlew run --args="-crypto.updateFrequency=5s"
----

:exclude-for-build:
:exclude-for-build:gradle

[source,bash]
----
./mvnw mn:run -Dmn.appArgs="-crypto.updateFrequency=5s"
----

:exclude-for-build:

You can retrieve a list of known metrics using cURL:

[source,bash]
----
curl localhost:8080/metrics
----

The response should look like this:

[source,json]
----
{
  "names": [
    "bitcoin.price.checks",
    "bitcoin.price.latest",
    "bitcoin.price.time",
    "executor",
    "executor.active",
    "executor.completed",
    "executor.pool.core",
    "executor.pool.max",
    "executor.pool.size",
    "executor.queue.remaining",
    "executor.queued",
    "hikaricp.connections",
    "hikaricp.connections.acquire",
    "hikaricp.connections.active",
    ...
    "jvm.threads.peak",
    "jvm.threads.states",
    "logback.events",
    "process.cpu.usage",
    "process.files.max",
    "process.files.open",
    "process.start.time",
    "process.uptime",
    "system.cpu.count",
    "system.cpu.usage",
    "system.load.average.1m"
  ]
}
----

After the application has been running for a bit and has made a few Bitcoin price checks, we can view the related metric values:

[source,bash]
----
curl localhost:8080/metrics/bitcoin.price.latest
----

[source,json]
----
{
  "measurements": [{ "statistic": "VALUE", "value": 29659.0 } ],
  "name": "bitcoin.price.latest"
}
----

[source,bash]
----
curl localhost:8080/metrics/bitcoin.price.checks
----

[source,json]
----
{
  "measurements": [{ "statistic": "COUNT", "value": 5.0 } ],
  "name": "bitcoin.price.checks"
}
----

[source,bash]
----
curl localhost:8080/metrics/bitcoin.price.time
----

[source,json]
----
{
  "baseUnit": "seconds",
  "measurements": [
    { "statistic": "COUNT",      "value": 5.0 },
    { "statistic": "TOTAL_TIME", "value": 2.525546791 },
    { "statistic": "MAX",        "value": 0.851958216 }
  ],
  "name": "bitcoin.price.time"
}
----

common:graal-with-plugins.adoc[]

:exclude-for-languages:groovy

Start the native image and run the cURL commands above to see that the application works the same way as before, with faster startup and response times.

:exclude-for-languages:

== Next steps

See the https://micronaut-projects.github.io/micronaut-micrometer/latest/guide/[Micronaut Micrometer documentation] to learn about the various metrics, configuration options, and supported registries.
