micronaut.server.port=3000
micronaut.application.name=micronautguide
# Datasource
datasources.default.db-type=oracle
datasources.default.dialect=ORACLE
datasources.default.driver-class-name=oracle.jdbc.OracleDriver
datasources.default.schema-generate=NONE
# Security
micronaut.security.endpoints.logout.get-allowed=true
