# OAUTH
micronaut.security.authentication=idtoken
micronaut.security.oauth2.clients.entraid.client-id=${HRAPP_CLIENT_ID}
micronaut.security.oauth2.clients.entraid.client-secret=${HRAPP_CLIENT_SECRET}
micronaut.security.oauth2.clients.entraid.openid.issuer=https://login.microsoftonline.com/${HRAPP_TENANT_ID}/v2.0/

# OJDBC Extensions
datasources.default.data-source-properties.oracle.jdbc.provider.endUserSecurityContext=ojdbc-provider-micronaut-end-user-security-context
datasources.default.data-source-properties.oracle.jdbc.provider.endUserSecurityContext.clientId=${HRAPP_CLIENT_ID}
datasources.default.data-source-properties.oracle.jdbc.provider.endUserSecurityContext.clientSecret=${HRAPP_CLIENT_SECRET}
datasources.default.data-source-properties.oracle.jdbc.provider.endUserSecurityContext.tokenUrl=https://login.microsoftonline.com/${HRAPP_TENANT_ID}/oauth2/v2.0/token
datasources.default.data-source-properties.oracle.jdbc.provider.endUserSecurityContext.scope=${HRAPP_SCOPE}

# Oracle JDBC
datasources.default.data-source-properties.oracle.net.wallet_location=${ORACLE_WALLET_TRUSTSTORE}
datasources.default.data-source-properties.oracle.jdbc.clientId=${HRAPP_CLIENT_ID}
datasources.default.data-source-properties.oracle.jdbc.clientSecret=${HRAPP_CLIENT_SECRET}
datasources.default.data-source-properties.oracle.jdbc.tokenAuthentication=AZURE_SERVICE_PRINCIPAL
datasources.default.data-source-properties.oracle.jdbc.tenantId=${HRAPP_TENANT_ID}
datasources.default.data-source-properties.oracle.jdbc.azureDatabaseApplicationIdUri=${DB_APP_ID_URI}

# Datasource
datasources.default.jdbc-url=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=tcps)(HOST=localhost)(PORT=2484))(SECURITY=(TLS_SERVER_CERT_DN="CN=localhost,O=Oracle,C=US")(TOKEN_AUTH=AZURE_SERVICE_PRINCIPAL)(AZURE_DB_APP_ID_URI=${DB_APP_ID_URI})(TENANT_ID=${HRAPP_TENANT_ID}))(CONNECT_DATA=(SERVICE_NAME=freepdb1)))
