micronaut:
  application:
    name: micronautguide
---
#tag::datasource[]
r2dbc:
  datasources:
    default:
      url: ${R2DBC_URL:`r2dbc:mysql://localhost:3306/db`}
      username: ${JDBC_USER:root}
      password: ${JDBC_PASSWORD:}
      schema-generate: CREATE_DROP
      dialect: MYSQL
datasources:
  default:
    url: ${JDBC_URL:`jdbc:mysql://localhost:3306/db`}
    username: ${JDBC_USER:root}
    password: ${JDBC_PASSWORD:}
    dialect: MYSQL
    driverClassName: ${JDBC_DRIVER:com.mysql.cj.jdbc.Driver}
#end::datasource[]
---
#tag::flyway[]
flyway:
  datasources:
    default:
      enabled: true # <1>
#end::flyway[]