micronaut:
  application:
    name: micronautguide
---
#tag::datasource[]
r2dbc:
  datasources:
    default:
      dialect: MYSQL
datasources:
  default:
    dialect: MYSQL
#end::datasource[]
---
#tag::flyway[]
flyway:
  datasources:
    default:
      enabled: true # <1>
#end::flyway[]
test-resources:
  containers:
    mysql:
      image-name: mysql:8.2