micronaut:
  application:
    name: micronautguide
  executors:
    io:
      type: fixed
      nThreads: 75 # <1>
flyway:
  datasources:
    default:
      enabled: true
datasources:
  default:
    ocid: # <1>
    walletPassword: # <2>
    username: micronautdemo
    password: # <3>
oci:
  config:
    profile: DEFAULT # <4>
