micronaut.application.name=micronautguide
test-resources.containers.oracle.startup-timeout=600s
# <1>
micronaut.executors.io.nThreads=75
flyway.datasources.default.enabled=true
# <2>
oci.config.profile=DEFAULT
datasources.default.dialect=ORACLE
datasources.default.db-type=oracle
datasources.default.driver-class-name=oracle.jdbc.OracleDriver
# <3>
#datasources.default.ocid=
# <4>
#datasources.default.walletPassword=
#datasources.default.username=micronautdemo
# <5>
#datasources.default.password=
