micronaut:
  application:
    name: gateway
---
endpoints:
  health:
    enabled: true
---
#tag::port[]
micronaut:
  server:
    port: 8080
#end::port[]
---
#tag::security[]
micronaut:
  security:
    authentication: bearer # <1>
    token:
      jwt:
        signatures:
          secret:
            generator: # <2>
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"' # <3>
#end::security[]
---
#tag::httpservices[]
micronaut:
  http:
    services:
      userecho: # <1>
        urls:
          - "http://localhost:8081" # <2>
#end::httpservices[]