common:header.adoc[]

You are going to deploy a Docker Image containing a CRaC enabled JDK and a pre-warmed, checkpointed Micronaut application to https://cloud.google.com/run[Google Cloud Run].

common:cloudrun.adoc[]

common:docker-crac.adoc[]

== Docker Push

common:google-cloud-registry.adoc[]

:exclude-for-build:

:exclude-for-build:maven

Modify your Gradle build and configure the image name for the `dockerBuildCrac` task:

[source,groovy]
----
tasks.named("dockerBuildCrac") {
    images = ["gcr.io/micronaut-guides-xxxxxxx/micronautguide:latest"]
}
----

:exclude-for-build:

:exclude-for-build:maven

[source, bash]
----
./gradlew dockerPushCrac
----

:exclude-for-build:
:exclude-for-build:gradle

[source, bash]
----
./mvnw deploy \
     -Dpackaging=docker-crac \
     -Djib.to.image=gcr.io/micronaut-guides-xxxxxxx/micronautguide:latest
----

:exclude-for-build:

NOTE: In the image name above, `micronaut-guides-xxxxxxx` should be replaced by your project name you created earlier in the guide.

You get an output such as:

[source, bash]
----
Pushing image 'gcr.io/micronaut-guides-xxxxxxx/micronautguide:latest'.
----

common:google-cloud-run-deploy.adoc[]

== Cleanup

We should then remove the resources we created in this guide to avoid incurring extra charges.

=== Google Cloud Run Delete

Delete the Google Cloud Run service with the https://cloud.google.com/sdk/gcloud/reference/run/services/delete[google cloud run services delete] command.

[source, bash]
----
gcloud run services delete micronautguide
----

=== Google Cloud Project deletion

Delete the project you created as part of this guide with.

[source, bash]
----
gcloud projects delete micronaut-guides-xxxxxx
----

== Next steps

Read more about:

common:google-cloud-run-next.adoc[]
common:crac-next.adoc[]

common:helpWithMicronaut.adoc[]
