common:header-top.adoc[]

== Getting Started

In this guide, we will write an OpenAPI definition file and then use it to generate a Java Micronaut server API with OpenAPI Generator.

Then we will add internal logic to the API and test our implementation.

=== What OpenAPI Is

The link:https://oai.github.io/Documentation/start-here.html[OpenAPI Specification] defines a format for uniquely describing REST APIs that is both human- and machine-readable. Later in this guide, we will discover the structure of documents in the OpenAPI format. We will also create such a document for our desired API. Note that we will refer to the document describing our API as an **API definition** file.

=== Advantages Of OpenAPI

* It provides a unique way of describing a REST API that is easy to understand and modify. It is the most broadly adopted industry standard for describing new APIs and has the most developed tooling ecosystem.
* You can generate interactive documentation and client implementations from the same definition file in numerous languages.
* You can use the same definition file to generate a server template. The template will include client-server communication specifics based on your API definition. It removes the need for developers to write extensive documentation about each possible path and parameter for the APIs - most can be described in the definition file. This prevents incompatibility issues between the client and server sides which might be caused by ill-communication.
+
NOTE: The internal server logic cannot be generated from a definition file and needs to be implemented manually based on the generated server template. The reason for this is very simple: there cannot be a unified way of describing all the possible server implementations.

=== What The OpenAPI Generator Is

____
OpenAPI Generator allows the generation of API client libraries (SDK generation), server stubs, documentation, and configuration automatically given an OpenAPI Spec (both 2.0 and 3.0 are supported).
____

=== What You Will Learn

* You will discover the general structure of a document in the OpenAPI format and a definition file in this format describing the desired API for our custom server.
* You will learn to use the link:https://openapi-generator.tech/[OpenAPIGenerator] to generate Micronaut code in Java for the server application. We will extend the code by implementing internal logic and testing it.
* You will learn how to use Micronaut Data JDBC to connect to a MySQL database from our application to store and retrieve data. You will complement the application with tests.

=== Solution

We recommend that you follow the instructions in the next sections and create the application step by step. However, you can directly get the complete solution by downloading and unzipping link:@sourceDir@.zip[@sourceDir@.zip].

common:requirements.adoc[]

== Installing OpenAPI Generator

To use OpenAPI Generator we need to https://github.com/OpenAPITools/openapi-generator#1---installation[install OpenAPI Generator CLI].

We will use the jar option. https://github.com/OpenAPITools/openapi-generator#13---download-jar[Download it] and store it in the directory that you want to use for this project.

Next, open the terminal in the same directory. To verify that generator works correctly, run the `help` command:
[source,bash]
----
java -jar openapi-generator-cli-XXX.jar help
----

It should provide a description and a list of commands.

[NOTE]
===============================
All the options for installation are given at the https://openapi-generator.tech/docs/installation["CLI Installation" guide on the OpenAPI Generator website].

In particular:

* run `brew install openapi-generator` for Homebrew installation,
* or read the link:https://openapi-generator.tech/docs/installation/#bash-launcher-script["Bash Launcher Script" section]
to set up a bash script with automatic updates

If you installed the generator with a package manager or bash launcher script, simply run
[source,bash]
----
openapi-generator-cli help
----
===============================

NOTE: You can also use the https://openapi-generator.tech/docs/online[OpenAPI Generator Online Service] but its usage is not covered by this guide.


== Creating The API Definition File

We will now create a definition file that will describe our server API, including the available paths and operations.

The definition file must be in the OpenAPI format. The document must have a specific structure. link:https://oai.github.io/Documentation/specification.html["OpenAPI Specification" guide] describes it with more detail. We will write sections of the definition document based on the specification.

//NOTE: You can get the complete version of the config file
//that we are about to create here:
//link:{sourceDir}@sourceDir@/library-definition.yaml[library-definition.yaml].
//However, we do recommend you to look through each of its sections for better understanding.

OpenAPI generator supports `.yaml` and `.json` file formats for the definition file. We will use YAML due to its simplicity and human readability.

In the directory where you downloaded the OpenAPI generator CLI, create a file named `library-definition.yaml` and open it in your favourite text editor.

=== Describing General Server Info

We will first provide general server information in the definition file. Paste the following text to the file:

resource:library-definition.yaml[tag=info]

<1> The version that will be used for parsing.
<2> The info object contains general information about the API like a short description and license. In this case, we will be creating a website for a library.
<3> Tags will be used to logically structure different paths.

NOTE: If you are new to OpenAPI, you might be interested in reading the link:https://swagger.io/docs/specification/about/[OpenAPI guide] or the link:https://swagger.io/specification/[OpenAPI 3.0.0 specification] after you finish this guide.

=== Defining Paths And Operations

The paths section of the definition is described in the link:https://oai.github.io/Documentation/specification-paths.html["API Endpoints" OpenAPI Guide], but can also be understood from a few examples. This section defines paths and various operations (like `GET`, `PUT`, and `POST`) available on these paths.

We will proceed by defining a path that is supposed to be used for searching books in our library. The parameters that we will define in the definition will be used to narrow the search results.

Paste the following to our file:

resource:library-definition.yaml[tags=paths|search]

<1> We define the `GET` operation on the `/search` path.
<2> We use the `books` tag that we previously defined. Note that for each tag a controller will be generated that will implement its operations.
<3> The `search` operation id will be used as method name for the given path.
<4> We define two parameters of type string that the user should supply in the query.
<5> Validation can be used on parameters. In this case book name must contain at least three characters.
<6> The `responses` object describes the response codes that can be produced. It also defines the structure of body if any.
<7> In case of correct request we define the body to contain a list of `BookInfo` objects. The schema for the book info object will be defined later in `components/schemas` section of definition.
<8> The `"400"` status code will be produced by Micronaut in case of bad request, like an incorrect type supplied or failed validation. Even though Micronaut handles it automatically and no implementation is needed on our side, we add it for a complete API specification.

NOTE: You can read more about parameter descriptions in the
link:https://swagger.io/docs/specification/describing-parameters/["Describing Parameters" OpenAPI guide].
All the available types and their validations are described in
link:https://swagger.io/docs/specification/data-models/data-types/["Data Models (Schemas)" OpenAPI guide].

We will define another path with a `POST` operation, that is supposed to be used to add info about a book in our library. In this case the request will contain a body with all the book information:

resource:library-definition.yaml[tag=add]

<1> We define the `POST` method for the `/add` path, and add the same tag `books` to it.
<2> We specify that a body is required and what are the supported content-types for it. (in this case only `application/json`, but multiple can be allowed).
<3> We write that `BookInfo` object is required to be in the request body. We reference the same `BookInfo` schema that we will define next.

NOTE: To read more about body definitions, see the
link:https://swagger.io/docs/specification/describing-request-body/["Describing Request Body" OpenAPI guide].

=== Defining Schemas

Schemas are required whenever a parameter, request body or a response body we want to describe needs to be an object. In that case we add a schema that defines all the properties of the object. You can find out about the format for schemas in the link:https://oai.github.io/Documentation/specification-content.html["Content of Message Bodies" OpenAPI Guide].

We will add schemas to our definition file:

resource:library-definition.yaml[tag=components]

<1> We define the `BookInfo` schema inside then `components/schemas` section. From this schema a Java class will be generated with the same `BookInfo` class name.
<2> We define all the properties of `BookInfo`, including required validation on them (In this case, it is minimal length requirement on one string and a regex pattern on another). An abbreviated form is used for some YAML lists and dictionaries to reduce the number of rows and simplify readability.
<3> We reference another schema to be used as a property.
<4> We define `BookAvailability` schema to be an enum with three available values. A Java `BookAvailability` class will be generated with given enum values based on our definition.

As you can see schemas can be defined as enums when they can only be assigned a finite number of values. Also, you can reference other schemas as properties of a schema.

NOTE: You can read more about writing schemas in the
link:https://swagger.io/docs/specification/data-models/["Data Models (Schemas)" OpenAPI guide].

Save the file and proceed to the next part of the guide.
//Altogether it should look like this: link:@sourceDir@/library-definition.yaml[library-definition.yaml].

== Generating Server API From The OpenAPI Definition

Now we will generate server API files from our definition. The generated server code will be in Java and will use the Micronaut features for client-server communication.
Open the terminal in the same directory as `library-definition.yaml` file and run the following command:

[source,bash]
----
java -jar openapi-generator-cli-XXX.jar generate \
    -g java-micronaut-server \# <1>
    -i library-definition.yaml \# <2>
    -o ./ \# <3>
    -p controllerPackage=example.micronaut.controller \# <4>
    -p modelPackage=example.micronaut.model \# <5>
    -p build=@build@ \# <6>
    -p test=junit# <7>
----
<1> Specify that we will use Java Micronaut server generator.
<2> Specify our OpenAPI definition file as `library-definition.yaml` which we just created.
<3> Specify the output directory to be the current directory (`./`).
You can specify it to be a different one if you want (e.g. `library-server`).
<4> We provide generator-specific properties starting with `-p`.
We want all the controllers to be generated in the `example.micronaut.controller` package.
<5> We want all the models (data models, like `BookInfo`) to be in `example.micronaut.model` package.
<6> We want to use @build@ as build tool. The supported values are `gradle`, `maven` and `all`.
If nothing is specified, both Maven and Gradle files are generated.
<7> We want to use JUnit 5 for testing. The supported values are `junit` (JUnit 5) and `spock`.
If nothing is specified, `junit` is used by default.

//[WARNING]
//=========
//If you are using Windows command prompt, run:
//=========
//[source,bash]
//----
//java -jar openapi-generator-cli-XXX.jar generate -g java-micronaut-server -i library-definition.yaml -o ./ -p controllerPackage=example.micronaut.controller -p modelPackage=example.micronaut.model -p build=@build@ -p test=junit
//----

[NOTE]
=========
If you want to view all the available parameters for micronaut server generator, run
[source,bash]
----
java -jar openapi-generator-cli-XXX.jar config-help \
    -g java-micronaut-server
----
=========

[NOTE]
=========
If you plan to change the definition file and regenerate files, consider setting the `-p generateControllerAsAbstract=true`
parameter (we don't recommend doing it during this guide, though). In this case an abstract class will be generated
for the API, while all the logic needs to be implemented in a different class (that extends the API abstract class).
This way your changes won't be overwritten by generation, but the API will be updated.
=========

After running, the OpenAPI generator CLI will output information about generated files. Now you can open the directory in your favorite IDE or text editor.

You should see the following directory structure:

[source,text]
----
./
├── docs
│   └── ... # <1>
├── src/
│   ├── main/
│   │   ├── java/
│   │   │   └── example/micronaut/
│   │   │       ├── Application.java # <2>
│   │   │       ├── controller
│   │   │       │   └── BooksController.java # <3>
│   │   │       └── model
│   │   │           ├── BookAvailability.java # <4>
│   │   │           └── BookInfo.java
│   │   └── resources/
│   │       ├── application.yml # <5>
│   │       └── logback.xml
│   └── test/
│       └── java/
│           └── example/micronaut/ # <6>
│               ├── controller
│               │   └── BooksControllerTest.java
│               └── model
│                   ├── BookAvailabilityTest.java
│                   └── BookInfoTest.java
├── README.md
└── ...
----
<1> The `docs/` directory contains automatically generated Markdown files with documentation about your API.
<2> Starts the Micronaut server with detected controllers.
<3> The `BooksController` is generated based on paths with `books` tag. It is generated in the package we specified
for controllers earlier.
<4> Two files are generated in the `models/` directory based on schemas we provided in the definition.
<5> Config file for Micronaut is generated with a default value for server port and other parameters.
<6> Tests are generated for all the controllers and models.

== Application Structure

To better understand the Micronaut Application we want to develop, let's first look at the schematic of the whole application:

image::openapi-generator/server-component-scheme.svg[]

<1> The controller will receive client requests utilizing Micronaut server features.
<2> The controller will call repository methods responsible for interaction with the database.
<3> The repository methods will be implemented utilizing Micronaut JDBC, and will send queries to the database.
<4> The files we generated with OpenAPI generator include Micronaut features responsible for server-client communication, like parameter and body binding, and JSON conversion.

== Data Storage And Access With MySQL and JDBC

We will use MySQL database to store and access data. This will ensure that stored data is persistent between the server runs and can be easily accessed and modified by multiple instances of our application.

Before implementing any server logic we need to create a database and configure connection to it. We will use Flyway to set up the database schema and JDBC for accessing the data.

common:data-jdbc-mysql-configuration[]

// Define the database variable that will be used in the snippet

:database: mysql
common:flyway.adoc[]

resource:db/migration/V1__schema.sql[]

The SQL commands in the migration will create the `book` table with `id` and four columns describing its properties, and populate the table with three sampe rows.

=== Creating a MappedEntity

To retrieve objects from the database you need to define a class annotated with https://micronaut-projects.github.io/micronaut-data/latest/api/io/micronaut/data/annotation/MappedEntity.html[@MappedEntity]. Instances of the class will represent a single row retrieved from the database in a query.

We will now create `BookEntity` class. We will be retrieving data from the `book` table and therefore class properties match columns in the table. Note that special annotations are added on the property corresponding to the primary key of the table.

source:BookEntity[]

callout:mapped-entity[1]
callout:mapped-entity-id[2]

=== Writing a Repository

common:jdbc-repository-intro[]

source:BookRepository[]

callout:jdbcrepository[1]
<2> `BookEntity`, the entity to treat as the root entity for the purposes of querying, is established either from the method signature or from the generic type parameter specified to the `GenericRepository` interface.
callout:jpa-specification-executor[3]
callout:jpa-specification-findall[4]

In the above code snippet we extended the `JpaSpecificationExecutor` interface to define a `findAll` method that supports `Predicate` as argument, which allows to modify the operations performed during runtime. We will now create a factory class for creating predicates that we plan to use in our application:

source:BookSpecifications[]

== Writing the Controller Logic

If you look inside the generated `BookInfo.java` file, you can see the class that was generated with all the parameters
based on our definition. Notice that the constructor signature has two parameters, which were defined as `required` in the
YAML definition file:

[source,java]
----
    public BookInfo(String name, BookAvailability availability);
----

Along with that it has getters and setters for parameters and Jackson serialization annotations.

=== Implementing Controller Methods

Now open `BooksController`. Thanks to the https://docs.micronaut.io/latest/guide/#httpServer[@Controller] annotation an instance of the class will be initialized when Micronaut application starts and corresponding method will be called when there is a request. The class should also have two methods named the same as the operations we created in the definition file. The methods have Micronaut framework annotations describing the required API. We will now write their bodies.

Using the Inversion of Control principle we will inject `BookRepository` so it can be used in the methods. When initializing the controller, Micronaut will automatically provide an instance of the repository as a constructor argument:
source:controller/BooksController[tag=inject,indent=0]
callout:constructor-di[number=1,arg0=BookRepository]

Next, keeping all the generated annotations, add this implementation for the `search` method:

source:controller/BooksController[tag=search,indent=0]
callout:executes-on[1]
<2> Define the `searchEntities` method that will manage the different combinations of desired search parameters.
<3> Use the predicate we previously defined to search for substring in one column
<4> Use the Criteria API to build a query for combined search in the 2 columns during runtime.
<5> Map the `BookEntity` instances to the desired return type.

Finally, we will implement the `addBook` method:
source:controller/BooksController[tag=addBook,indent=0]
callout:executes-on[1]
callout:at-status[2]
<3> Call the repository method that will add an entry to the table.

common:runapp.adoc[]

You can send a few requests to the paths to test the application. We will use cURL for that.

* The search for book names, that have `"Guide"` as substring should return 2 `BookInfo` objects:
+
[source,bash]
----
curl "localhost:8080/search?book-name=Guide"
----
+
[source,bash]
----
[{"name":"The Hitchhiker's Guide to the Galaxy","availability":"reserved","author":"Douglas Adams"},
{"name":"Java Guide for Beginners","availability":"available"}]
----

* The search for a substring `"Gu"` in name will return a `"Bad Request"` error, since we have defined the `book-name` parameter to
have at least three characters:
+
[source,bash]
----
curl -i "localhost:8080/search?book-name=Gu"
----
+
[source,bash]
----
HTTP/1.1 400 Bad Request
Content-Type: application/json
date: ****
content-length: 180
connection: keep-alive

{"message":"Bad Request","_embedded":{"errors":[{"message":"bookName: size must be between 3 and 2147483647"}]},
"_links":{"self":{"href":"/search?book-name=Gu","templated":false}}}
----

* Addition of a new book should not result in errors:
+
[source,bash]
----
curl -i -d '{"name": "My book", "availability": "available"}' \
  -H 'Content-Type: application/json' -X POST localhost:8080/add
----
+
[source,bash]
----
HTTP/1.1 200 OK
date: Tue, 1 Feb 2022 00:01:57 GMT
Content-Type: application/json
content-length: 0
connection: keep-alive
----
You can then verify that the addition was successful by performing another search.

== Testing the Application

common:testcontainers-mysql.adoc[]

=== Testing Models

As we have noticed previously, some files were generated as templates for tests.
We will implement tests for models inside these files. Their main purpose will be to verify that we correctly described
our API in the YAML file, and therefore the generated files behave as expected.

We will begin by writing tests for the required properties of `BookInfo` object.
Define the following imports:
test:model/BookInfoTest[tag=imports]

Add the following methods inside the `BookInfoTest` class:
test:model/BookInfoTest[tag=requiredProperties]
<1> Instruct Micronaut to inject an instance of the link:https://docs.micronaut.io/latest/guide/#beanValidation[Validator].
`Validator` will automatically validate parameters and response bodies annotated with `@Valid` in the controller.
We will use it test the validations manually.
<2> Verify that the validator doesn't produce any violations on a correct `BookInfo` instance.
<3> Verify that `null` value is not allowed for the `name` property, since the property is marked as required.
<4> Perform the same tests for the required `availability` property.

We will then write similar test for other properties:
test:model/BookInfoTest[tag=otherProperties]
<1> Verify that there are no violations for both `null` or `"Lewis Carol"` used as a value for the `author` property.
<2> Verify that there is a violation in case the name is too short (at least tree characters are required).
<3> Verify that there are no violations for valid values of the `ISBN` property.
<4> Verify that there is a violation in case the value doesn't match the required pattern (A space is present).

Finally, we will test JSON serialization and parsing by writing a simple controller and client:
test:model/BookInfoTest[tags=annotations|jsonSerialization]
<1> Create a simple controller that will respond to requests on the `/bookinfo` path.
<2> Specify the `spec.name` property for this test class.
<3> Use the link:https://docs.micronaut.io/latest/guide/#metaScopes[Requires] annotation to specify that
this controller will only be used if the `spec.name` property is set to `BookInfoTest`. This will prevent the controller
from running during other tests.
<4> Define a `GET` method that will return a `BookInfo` object in the `application/json` format.
<5> Create a test that will send a request to the server and verify that the response matches the desired object
(This means that both serialization and parsing work correctly).

Similarly, we can implement tests for the `BookAvailability` class. The details are not shown in this guide.

=== Testing the Controller

We will write test for the two paths of `BookController`.

If you open the `BooksControllerTest`, you can see that templates of tests were generated for both paths with examples of requests to corresponding paths. The templates can be used to simplify and speed up test writing.

We will simply replace the contents of the file:

test:controller/BooksControllerTest[]

callout:micronaut-test[1]
callout:http-client[2]
callout:http-request[3]
<4> Verify that addition of book info was successful by checking the status code.
callout:binding-json-array[5]
callout:body-method[6]
<7> Verify that there are exactly two books with `"Guide"` substring in title.

common:testApp-noheader.adoc[]

All the tests should run successfully.

common:graal-with-plugins.adoc[]

== Next steps

=== Learn More

Read OpenAPI and Micronaut documentation and guides:

* https://www.openapis.org[OpenAPI]
* https://openapi-generator.tech[OpenAPI Generator]
* Definition files generation from annotated controllers with link:https://micronaut-projects.github.io/micronaut-openapi/latest/guide[Micronaut OpenAPI]
* link:https://micronaut-projects.github.io/micronaut-data/latest/guide[Micronaut Data]

=== Add Security

We could have defined our security requirements by adding a security schema to the `library-definition.yaml` file.
For example, we will add HTTP Basic authentication:

[source,yaml]
----
paths:
  /search:
    # ... #
  /add:
    post:
      # ... #
      security:
        - MyBasicAuth: [] # <2>
components:
  schemas:
    # ... #
  securitySchemes:
    MyBasicAuth: # <1>
      type: http
      scheme: basic
----
<1> Define a security schema inside the `components/securitySchemes`. We want to use Basic auth for authentication.
<2> Add the schema to the paths that you want to secure. In this case we want to restrict access to
adding books into our library.

NOTE: You can read more about describing various authentication in the
link:https://swagger.io/docs/specification/authentication/["Authentication and Authorization" OpenAPI guide].

The generator will then annotate such endpoints with the
link:https://micronaut-projects.github.io/micronaut-security/latest/guide/#secured[Secured] annotation accordingly:

[source,java]
----
@Secured(SecurityRule.IS_AUTHENTICATED)
public Mono<Object> addBook( /* ... */ ){ /* ... */ }
----

You will then need to implement an
link:https://micronaut-projects.github.io/micronaut-security/latest/guide/#authenticationProviders[AuthenticationProvider]
that satisfies your needs. If you want to finish implementing the basic authentication, continue to the
link:https://guides.micronaut.io/latest/micronaut-security-basicauth.html[Micronaut Basic Auth guide] and replicate
steps to create the `AuthenticationProvider` and appropriate tests.

NOTE: You can also read link:https://micronaut-projects.github.io/micronaut-security/latest/guide/[Micronaut Security documentation]
or link:https://micronaut.io/guides[Micronaut guides] about security to learn more about
the supported Authorization strategies.

=== Generate Micronaut Client

You can generate a Micronaut client based on the same `library-definition.yaml` file.

Run the following in terminal to create client in the `library-client` directory:

[source,bash]
----
java -jar openapi-generator-cli-XXX.jar generate \
    -g java-micronaut-client \
    -i library-definition.yaml \
    -o library-client \
    -p apiPackage=example.micronaut.api \
    -p modelPackage=example.micronaut.model \
    -p build=@build@ \
    -p test=junit
----

=== Add Server URL Information

If you have your server running, you can add your website URL to it in the YAML definition file:
[source,yaml]
----
# ... #
servers:
  - url: 'http://my.website.com'
----

=== Generate User-Friendly Documentation

You can generate documentation in html file inside the `html-docs/` directory by running
[source,bash]
----
java -jar openapi-generator-cli-XXX.jar generate \
    -g html2 \
    -i library-definition.yaml \
    -o html-docs
----
