/*
 * Library
 * This is a library API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package example.micronaut.controller

//tag::package[]
//package example.micronaut.controller
//end::package[]

//tag::import[]
import example.micronaut.BookEntity
import example.micronaut.BookRepository
import example.micronaut.api.BooksApi
import example.micronaut.model.BookInfo
import groovy.transform.CompileStatic
import io.micronaut.core.annotation.NonNull
import io.micronaut.core.util.StringUtils
import io.micronaut.http.annotation.Controller
import io.micronaut.scheduling.TaskExecutors
import io.micronaut.scheduling.annotation.ExecuteOn
//end::import[]

//tag::clazz[]
@CompileStatic
@Controller
class BooksController implements BooksApi {
//end::clazz[]

    //tag::inject[]
    private final BookRepository bookRepository // <1>

    BooksController(BookRepository bookRepository) { // <1>
        this.bookRepository = bookRepository
    }
    //end::inject[]

    //tag::addBook[]
    @Override
    @ExecuteOn(TaskExecutors.BLOCKING)
    void addBook(BookInfo bookInfo) {
        bookRepository.save(bookInfo.getName(), // <3>
                bookInfo.getAvailability(),
                bookInfo.getAuthor(),
                bookInfo.getIsbn())
    }
    //end::addBook[]

    //tag::search[]
    @Override
    @ExecuteOn(TaskExecutors.BLOCKING) // <1>
    List<BookInfo> search(
            String bookName,
            String authorName) {
        searchEntities(bookName, authorName)
                .collect { BookEntity entity -> map(entity) } // <5>
    }

    private BookInfo map(BookEntity entity) {
        BookInfo book = new BookInfo(entity.name, entity.availability)
        book.setIsbn(entity.isbn)
        book.setAuthor(entity.author)
        book
    }

    @NonNull
    private List<BookEntity> searchEntities(String name, String author) { // <2>
        if (StringUtils.isEmpty(name) && StringUtils.isEmpty(author)) {
            return bookRepository.findAll()
        } else if (StringUtils.isEmpty(name)) {
            return bookRepository.findAllByAuthorContains(author) // <3>
        } else if (StringUtils.isEmpty(author)) {
            return bookRepository.findAllByNameContains(name)
        }
        bookRepository.findAllByAuthorContainsAndNameContains(author, name) // <4>
    }
    //end::search[]
//tag::footer[]
}
//end::footer[]
