common:header.adoc[]

common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app-features.adoc[]

common:micronaut-views-thymeleaf.adoc[]

== Controller

Create a controller that responds with HTML or JSON depending on the request `Accept` HTTP header.

source:MessageController[]
callout:controller[arg0=/]
<.> Use the `@Produces` annotation to indicate the possible response content types. It matches the `Accept` header of the request, as you will see in the test.
callout:get-generic[]
callout:http-request-method-parameter[]

For HTML, the previous controller uses a Thymeleaf view:

resource:views/message.html[]

== Test

Write a test that verifies the response content type depending on the request `Accept` HTTP header.

test:MessageControllerTest[]
callout:micronaut-test[]
callout:http-client[]
callout:http-request[]

common:testApp.adoc[]

common:nativetest.adoc[]

common:next.adoc[]

Read more about https://micronaut-projects.github.io/micronaut-views/latest/guide/[Micronaut Views].

common:helpWithMicronaut.adoc[]
