common:header.adoc[]

common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app-features.adoc[]

common:micronaut-views-thymeleaf.adoc[]

== Controller

Create a controller that responds HTML or JSON depending on the request Accept HTTP Header.

source:MessageController[]

<1> callout:controller[arg0=/]
<2> Use the `@Produces` annotation to indicate the possible response's content type. It matches the `Accept` header of the request, as you will see in the test.
<3> callout:get-generic[]
<4> callout:http-request-method-parameter[]

In case of HTML, the previous controller uses a Thymeleaf view:

resource:views/message.html[]

== Test

Write a test verifying the response content type depending on the request Accept HTTP Header.

test:MessageControllerTest[]

<1> callout:micronaut-test[]
<2> callout:http-client[]
<3> callout:http-request[]

common:testApp.adoc[]

common:nativetest.adoc[]

common:next.adoc[]

Read more about https://micronaut-projects.github.io/micronaut-views/latest/guide/[Micronaut Views].

common:helpWithMicronaut.adoc[]