common:header.adoc[]

common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app-features.adoc[]

:exclude-for-languages:python

common:micronaut-views-thymeleaf.adoc[]

:exclude-for-languages:

:only-for-languages:python

== Views

The `views-jinjava` feature configures Micronaut Views' https://micronaut-projects.github.io/micronaut-views/latest/guide/#jinjava[Jinjava integration] to render Jinja templates. The Python routes below supply the template model as a dictionary.

Configure the renderer to use HTML files for the Jinja templates:

resource:application.toml[tag=jinja]

:only-for-languages:

== Controller

Create a controller that responds with HTML or JSON depending on the request `Accept` HTTP header.

source:MessageController[]

:exclude-for-languages:python

callout:controller[arg0=/]
<.> Use the `@Produces` annotation to indicate the possible response content types. It matches the `Accept` header of the request, as you will see in the test.
callout:get-generic[]
callout:http-request-method-parameter[]

:exclude-for-languages:

:only-for-languages:python

<1> Declare a Micronaut controller for `/`.
<2> Declare the JSON response type on the route. Micronaut selects the matching route using the request's `Accept` header.
<3> Return a Python dictionary, which Micronaut serializes as JSON.
<4> For the HTML route, `@View` renders the dictionary with the `message.html` Jinja template. No manual header parsing or response wrapper is needed.

:only-for-languages:

:exclude-for-languages:python

For HTML, the previous controller uses a Thymeleaf view:

resource:views/message.html[]

:exclude-for-languages:

:only-for-languages:python

For HTML, the previous controller uses a Jinja template. The `e` filter escapes the message for HTML:

resource:views/message.html[]

:only-for-languages:

== Test

Write a test that verifies the response content type depending on the request `Accept` HTTP header.

test:MessageControllerTest[]

:exclude-for-languages:python
callout:micronaut-test[]
callout:http-client[]
callout:http-request[]
:exclude-for-languages:

:only-for-languages:python
<.> Create a Micronaut test fixture for the application under test.
<.> Use `requests.with_context(my_context)` to call the application under test with a context-bound HTTP client.
<.> Send requests with explicit `Accept` headers.
:only-for-languages:

common:testApp.adoc[]

common:nativetest.adoc[]

common:next.adoc[]

Read more about https://micronaut-projects.github.io/micronaut-views/latest/guide/[Micronaut Views].
