common:header-top.adoc[]

== Getting Started

In this guide, we will create three microservices that will communicate with each other with https://www.rabbitmq.com/[RabbitMQ] using the request-response pattern with https://micronaut-projects.github.io/micronaut-rabbitmq/latest/guide/#rpc[RPC]
_(Remote Procedure Call)_.

____
RabbitMQ is an open-source message-broker software that originally implemented the Advanced Message Queuing Protocol (AMQP)
and has since been extended with a plug-in architecture to support Streaming Text Oriented Messaging Protocol (STOMP),
Message Queuing Telemetry Transport (MQTT), and other protocols.
____

common:requirements.adoc[]

common:completesolution.adoc[]

== Writing the Application

Let's describe the microservices you will build through the guide.

* `bookcatalogue` - This returns a list of books. It uses a domain consisting of a book name and an ISBN.

* `bookinventory` - This exposes an endpoint to check whether a book has sufficient stock to fulfill an order. It uses a domain consisting of a stock level and an ISBN.

* `bookrecommendation` - This consumes previous services and exposes an endpoint that recommends book names that are in stock.

https://guides.micronaut.io/latest/micronaut-intellij-idea-ide-setup.html[Setup IntelliJ IDEA to develop Micronaut Applications].

common:test-resources-rabbitmq.adoc[]

=== Catalogue microservice

Create the `bookcatalogue` microservice using the https://docs.micronaut.io/latest/guide/#cli[Micronaut Command Line Interface] or with https://launch.micronaut.io[Micronaut Launch].

[source,bash]
----
mn @bookcatalogue:cli-command@ --features=rabbitmq,graalvm example.micronaut.bookcatalogue --build=@build@ --lang=@lang@
----

common:build-lang-arguments.adoc[]

If you use Micronaut Launch, select Micronaut Application as application type and add the `rabbitmq` and `graalvm` features.

The previous command creates a directory named `bookcatalogue` and a Micronaut application inside it with default package `example.micronaut`.

diffLink:[app=bookcatalogue]

==== Create RabbitMQ exchange, queue, and binding

Before being able to send and receive messages using RabbitMQ, it is necessary to define the exchange, queue, and binding.
One option is to create them directly in the RabbitMQ Admin UI available on http://localhost:15672.
Use `guest` for both username and password.

Another option is to create them programmatically. Create the class `ChannelPoolListener.java`:

source:ChannelPoolListener[app=bookcatalogue]

<1> Define an exchange named `micronaut`. From the producer point of view, everything is sent to the exchange with the
appropriate routing key.
<2> Define a queue named `inventory`. The consumer will listen for messages in that queue.
<3> Define a binding between the exchange and the queue using the routing key `books.inventory`.
<4> Define a queue named `catalogue`. The consumer will listen for messages in that queue.
<5> Define a binding between the exchange and the queue using the routing key `books.catalogue`.

NOTE: In this Catalogue Microservice, the only necessary element is the `catalogue` queue, but it is a good practice to define
all the elements in the same file and share the file between all the projects.

==== Create consumer

Create a `BookCatalogueService` class to handle incoming RPC requests into the `bookcatalogue` microservice:

source:BookCatalogueService[app=bookcatalogue]

<1> Annotate the class with `@RabbitListener` to indicate that this bean will consume messages from RabbitMQ.
<2> Annotate the method with `@Queue`. This listener will listen to messages in the `catalogue` queue.

The previous service responds a `List<Book>`. Create the `Book` POJO:

source:Book[app=bookcatalogue]

=== Inventory microservice

Create the `bookinventory` microservice using the https://docs.micronaut.io/latest/guide/#cli[Micronaut Command Line Interface] or with https://launch.micronaut.io[Micronaut Launch].

[source,bash]
----
mn @bookinventory:cli-command@ --features=rabbitmq,graalvm example.micronaut.bookinventory --build=@build@ --lang=@lang@
----

common:build-lang-arguments.adoc[]

If you use Micronaut Launch, select Micronaut Application as application type and add the `rabbitmq` and `graalvm` features.

The previous command creates a directory named `bookinventory` and a Micronaut application inside it with default package `example.micronaut`.

diffLink:[app=bookinventory]

The previous command creates a directory named `bookinventory` and a Micronaut application inside it with default package `example.micronaut`.

==== Create RabbitMQ exchange, queue and binding

Copy the `ChannelPoolListener` class you created in the `bookcatalogue` microservice to `bookinventory/src/main/@lang@/example/micronaut/bookcatalogue`.

==== Create consumer

Create a `BookInventoryService` class to handle incoming RPC requests into the `bookinventory` microservice:

source:BookInventoryService[app=bookinventory]

<1> Annotate the class with `@RabbitListener` to indicate that this bean will consume messages from RabbitMQ.
<2> Annotate the method with `@Queue`. This listener will listen to messages in `inventory` queue.

The previous service uses `BookInventory` POJO. Create it:

source:BookInventory[app=bookinventory]

=== Recommendation microservice

Create the `bookrecommendation` microservice using the https://docs.micronaut.io/latest/guide/#cli[Micronaut Command Line Interface] or with https://launch.micronaut.io[Micronaut Launch].

[source,bash]
----
mn @bookrecommendation:cli-command@ --features=rabbitmq,reactor,graalvm example.micronaut.bookrecommendation --build=@build@ --lang=@lang@
----

common:build-lang-arguments.adoc[]

If you use Micronaut Launch, select Micronaut Application as application type and add the `rabbitmq`, `reactor`, and `graalvm` features.

The previous command creates a directory named `bookrecommendation` and a Micronaut application inside it with default package `example.micronaut`.

diffLink:[app=bookrecommendation]

==== Create RabbitMQ exchange, queue and binding

Copy the `ChannelPoolListener` class you created in the `bookcatalogue` microservice to `bookrecommendation/src/main/java/example/micronaut/bookcatalogue`.

==== Create clients

Let's create two interfaces to send messages to RabbitMQ. The Micronaut framework will implement the interfaces at compilation time.
Create `CatalogueClient`:

source:CatalogueClient[app=bookrecommendation]

<1> Send the messages to exchange `micronaut`.
<2> Set the `replyTo` property to `amq.rabbitmq.reply-to`. This is a special queue that always exists and does not need
to be created. That is why we did not create the queue in the `ChannelInitializer`. RabbitMQ uses that queue in a
special way, and setting the value of the property `replyTo` to that queue will enable this call as an RPC one. RabbitMQ
will create a temporary queue for the callback.
<3> Set the routing key.
<4> Define the method that will "mirror" the one in the consumer. Keep in mind that in the consumer, it is not possible to
return a reactive type, but on the client side it is. Also, it is necessary to send something, even if it's not
used in the consumer.

Create `InventoryClient.java`:

source:InventoryClient[app=bookrecommendation]

<1> Send the messages to exchange `micronaut`.
<2> Set the `replyTo` property to `amq.rabbitmq.reply-to`.
<3> Set the routing key.
<4> Define the method that will "mirror" the one in the consumer. As we did with `CatalogueClient`, we use a reactive
type to wrap the result.

==== Create the controller

Create a Controller that injects both clients.

source:BookController[app=bookrecommendation]

callout:controller[number=1,arg0=/books]
<2> Clients are injected via constructor injection
callout:get[number=3,arg0=index,arg1=/books]

The previous controller returns a `Publisher<BookRecommendation>`. Create the `BookRecommendation` POJO:

source:BookRecommendation[app=bookrecommendation]

== RabbitMQ and the Micronaut Framework

As <<Test Resources,mentioned above>> a shared dockerized instance of RabbitMQ will be started automatically when you run the application, however if you want to start your own instance of RabbitMQ, you have a few options:

=== Install RabbitMQ via Docker

The fastest way to start using https://hub.docker.com/_/rabbitmq/[RabbitMQ is via Docker]:

[source,bash]
----
docker run --rm -it \
        -p 5672:5672 \
        -p 15672:15672 \
        rabbitmq:3.8.12-management
----

=== Alternative methods

Alternatively you can https://www.rabbitmq.com/download.html[install and run a local RabbitMQ instance].

== Running the Application

Configure `bookinventory` to run on port 8082:

common:yaml-dependency.adoc[]

resource:application.yml[app=bookinventory,tag=port]

Run `bookinventory` microservice:

:exclude-for-build:maven

[source,bash]
.bookinventory
----
./gradlew run
----

[source]
----
13:30:22.426 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 742ms. Server Running: 1 active message listeners.
----

:exclude-for-build:

:exclude-for-build:gradle

[source,bash]
.bookinventory
----
./mvnw mn:run
----

[source]
----
13:30:22.426 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 742ms. Server Running: 1 active message listeners.
----

:exclude-for-build:

Configure `bookcatalogue` to run on port 8081:

resource:application.yml[app=bookcatalogue,tag=port]

Run `bookcatalogue` microservice:

:exclude-for-build:maven

[source,bash]
.bookcatalogue
----
./gradlew run
----

[source]
----
13:31:19.887 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 949ms. Server Running: 1 active message listeners.
----

:exclude-for-build:

:exclude-for-build:gradle

[source,bash]
.bookcatalogue
----
./mvnw mn:run
----

[source]
----
13:31:19.887 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 949ms. Server Running: 1 active message listeners.
----

:exclude-for-build:

Configure `bookrecommendation` to run on port 8080:

resource:application.yml[app=bookrecommendation,tag=port]

NOTE: 8080 is the default port if you don't specify `micronaut.server.port` property

Run `bookrecommendation` microservice:

:exclude-for-build:maven

[source,bash]
.bookrecommendation
----
./gradlew run
----

[source]
----
13:32:06.045 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 959ms. Server Running: http://localhost:8080
----

:exclude-for-build:

:exclude-for-build:gradle

[source,bash]
.bookrecommendation
----
./mvnw mn:run
----

[source]
----
13:32:06.045 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 959ms. Server Running: http://localhost:8080
----

:exclude-for-build:

You can run a `curl` command to test the whole application:

[source, bash]
----
curl http://localhost:8080/books
----

[source,json]
----
[{"name":"Building Microservices"}]
----

common:graal-with-plugins.adoc[]

:exclude-for-languages:groovy

Start the native executables for the two microservices and run the same `curl` request as before to check that everything works with GraalVM.

:exclude-for-languages:

== Next Steps

Read more about https://micronaut-projects.github.io/micronaut-rabbitmq/latest/guide/#rpc[RabbitMQ RPC Support] in the Micronaut framework.
