[micronaut.application]
name = "micronautguide"

# tag::mcp[]
[micronaut.mcp.server.info]
name = "Weather"
version = "0.0.1"

[micronaut.mcp.server]
# <1>
transport = "HTTP"
# end::mcp[]

# tag::api-weather-gov[]
[micronaut.http.services.weather]
url = "https://api.weather.gov"

[micronaut.codec.json]
additional-types = ["application/geo+json"]
# end::api-weather-gov[]
