micronaut:
  application:
    name: micronautguide
#tag::oauth2[]
---
micronaut:
  security:
    authentication: idtoken # <1>
    oauth2:
      clients:
        google: # <2>
          client-id: '${OAUTH_CLIENT_ID:xxx}'  # <3>
          client-secret: '${OAUTH_CLIENT_SECRET:yyy}' # <4>
          openid:
            issuer: 'https://accounts.google.com' # <5>
    endpoints:
      logout:
        get-allowed: true # <6>
#end::oauth2[]
