micronaut:
  application:
    name: micronautguide
---
#tag::datasource[]
datasources:
  default:
    dialect: MYSQL
    driverClassName: com.mysql.cj.jdbc.Driver
#end::datasource[]
---
#tag::flyway[]
flyway:
  datasources:
    default:
      enabled: true # <1>
#end::flyway[]