micronaut:
  application:
    name: bookcatalogue
endpoints:
  health:
    enabled: true
    sensitive: false
---
#tag::oauth2[]
micronaut:
  security:
    token:
      jwt:
        signatures:
          jwks:
            auth0:
              url: 'https://cognito-idp.${COGNITO_REGION:us-east-1}.amazonaws.com/${COGNITO_POOL_ID:us-east-1_blablabla}/.well-known/jwks.json'
#end::oauth2[]