common:header.adoc[]

common:requirements.adoc[]

== Create an Application

common:cli-or-launch.adoc[]

[source,bash]
----
mn @cli-command@ example.micronaut.micronautguide --build=@build@ --lang=@lang@
----

common:build-lang-arguments.adoc[]

common:default-package.adoc[]

== Introduction

:exclude-for-languages:python

To distribute a self-contained Micronaut application that can be run from the command line, you can generate a fat JAR or uber JAR. A fat JAR combines the project's dependency classes and resources into a single output JAR: an executable JAR.

If you use https://launch.micronaut.io[Micronaut Launch] or the Micronaut CLI to generate a Micronaut application, the application's build contains everything you need to produce an executable JAR.

:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin

To distribute a self-contained Pyronaut application that can be run from the command line, you can generate a Python wheel. The wheel contains the processed application classes, resources, and a console script launcher for the application.

If you use Micronaut Launch or the Micronaut CLI to generate a Pyronaut application, the application's configuration contains everything you need to produce a wheel.

:exclude-for-languages:

== Main Class

:exclude-for-languages:python

The generated application contains an `Application` class, the entry point of the Micronaut application. It also has the build configuration to define that class as the application's main class.

:exclude-for-build:maven

The https://micronaut-projects.github.io/micronaut-gradle-plugin/latest/[Micronaut Gradle Plugin] implicitly applies the https://docs.gradle.org/current/userguide/application_plugin.html[Gradle Application Plugin].

The application contains the only mandatory configuration for the Application plugin: the specification of the main class:

:exclude-for-build:

common:mainclass.adoc[]

:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin

The generated application contains a `main.py` script, the entry point of the Pyronaut application.

zipInclude:src/main.py[]

:exclude-for-languages:

:exclude-for-languages:python

external:distribution-base/hellocontroller.adoc[]

:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin

== Controller

The generated application contains classless route functions that respond to HTTP requests:

zipInclude:src/example/micronaut/controller.py[]

:exclude-for-languages:

:exclude-for-languages:python

== Generate Executable JAR

:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin

== Generate Distribution Wheel

:exclude-for-languages:python

:exclude-for-build:maven

The application applies the https://gradleup.com/shadow/[Shadow Gradle plugin]. You can use its task `shadowJar` to generate an executable JAR.

:exclude-for-build:

common:executable-jar.adoc[]

:exclude-for-build:gradle

The Micronaut Maven Plugin supports different `<packaging>` types. The previous command does not specify a packaging type, so it uses `jar`, the default packaging type. The command produces a runnable fat JAR.

The Micronaut Maven Plugin delegates to the `maven-shade-plugin` to produce a JAR file. The `io.micronaut:micronaut-parent POM` defines the Maven Shade Plugin configuration, and the defaults should be enough. Refer to the https://maven.apache.org/plugins/maven-shade-plugin/[Maven Shade Plugin documentation] to customize how to produce the executable JAR.

:exclude-for-build:

:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin

For Pyronaut, use the `pyronaut build` command to produce a wheel:

[source,bash]
----
pyronaut build
----

The command runs production configuration validation, installs dependencies, processes the application sources, and writes the wheel to the `dist/` directory.

:exclude-for-languages:

:exclude-for-languages:python

== Run the Executable JAR

:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin

== Run the Wheel

:exclude-for-languages:python

Run the application packaged as a JAR file:

common:executable-jar-run.adoc[]

:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin

Install the wheel and run the generated console script printed by `pyronaut build`. The generated guide project uses `default`:

[source,bash]
----
python -m pip install dist/*.whl
default
----

:exclude-for-languages:

:exclude-for-languages:python

== Time To First Request

=== Script

Use the following script to measure time to first request of a single output JAR.

resource:../../../ttfr.sh[]

=== Measurement

[source, bash]
----
:exclude-for-build:maven
./ttfr.sh -j build/libs/micronautguide-0.1-all.jar
:exclude-for-build:
:exclude-for-build:gradle
./ttfr.sh -j target/micronautguide-0.1.jar
:exclude-for-build:
 __  __ _                                  _
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v3.8.4)

16:00:32.037 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 439ms. Server Running: http://localhost:8080
0.734 seconds
----

:exclude-for-languages:

common:next.adoc[]

Learn more about https://guides.micronaut.io/latest/micronaut-docker-image.html[how to build a Docker Image of your Micronaut application].

common:helpWithMicronaut.adoc[]
