#tag::mn[]
micronaut:
  application:
    name: bookrecommendation # <1>
  server:
    port: 8080 # <2>
#end::mn[]
#tag::eureka[]
eureka:
  client:
    registration:
      enabled: true
    defaultZone: "${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}"
#end::eureka[]
endpoints:
  health:
    enabled: true
    sensitive: false