include::{commondir}/common-header.adoc[]

include::{commondir}/common-requirements.adoc[]

include::{commondir}/common-completesolution.adoc[]

include::{commondir}/common-cli-or-launch.adoc[]

[source,bash]
----
mn create-app
   example.micronaut.micronautguide \
   --features=data-jdbc,postgres,liquibase \ 
   --build=@build@ \
   --lang=@lang@ \
----


include::{commondir}/common-build-lang-arguments.adoc[]

include::{commondir}/common-default-package.adoc[]

NOTE: If you use https://launch.micronaut.io[Micronaut Launch], select "Micronaut Application" as application type and add `postgres`, `data-jdbc`, and `liquibase` as features.

include::{commondir}/common-annotationprocessors.adoc[]

=== Create Entity

Create a `@MappedEntity` to save persons. Initially, consider name and age required. Use `int` primitive for the age.

source:Person[tags=clazz|ageint|gettersetters]

callout:mapped-entity[1]
callout:mapped-entity-id[2]
callout:generated-value[3]
callout:version-optimistic-locking[4]

=== Database Migration with Liquibase

We need a way to create the database schema. For that, we use
https://micronaut-projects.github.io/micronaut-liquibase/latest/guide/[Micronaut integration with Liquibase].

Add the following snippet to include the necessary dependencies:

dependency:micronaut-liquibase[groupId=io.micronaut.liquibase]

Configure the database migrations directory for http://www.liquibase.org[Liquibase] in `application.yml`.

resource:application.yml[tag=liquibase]

Create the following files with the database schema creation:

resource:db/liquibase-changelog.xml[]

resource:db/changelog/01-create-person.xml[]

During application startup, http://www.liquibase.org[Liquibase] executes the SQL file and creates the schema needed for the application.

If you check the database schema, there are three tables:

- `databasechangelog`
- `databasechangeloglock`

The tables `databasechangelog` and `databasechangeloglock` are used by Liquibase to keep track of database migrations.

The `person` table looks like:

|===
|Column | Nullable

|`id`
|NO

|`version`
|NO

|`name`
|NO

|`age`
|NO
|===

=== Drop Not Null Constraint

Applications change. Make `age` optional:

source:Person[tags=nullableage]

Add a new changeset to drop the null constraint:

resource:db/liquibase-changelog.xml[]

resource:db/changelog/02-nullable-age.xml[]

After the changeset, the `person` table looks like:

|===
|Column | Nullable

|`id`
|NO

|`version`
|NO

|`name`
|NO

|`age`
|YES
|===

== Liquibase

To enable the Liquibase endpoint, add the `management` dependency on your classpath.

dependency:micronaut-management[]

Enable the Liquibase endpoint:

resource:application.yml[tag=endpoints]

include::{commondir}/common-testcontainers-postgres.adoc[]

=== Test

Create a test that invokes the Liquibase endpoint

test:LiquibaseEndpointTest[]

callout:micronaut-test[1]
callout:http-client[2]

=== Running the application

include::{commondir}/common-run-postgres-with-docker.adoc[]

Set up the following environment variables to connect to the PostgreSQL database you started with Docker.

resource:application.yml[tag=datasource]

<1> The JDBC URL matches the database name you used in the previous command.
<2> Use PostgreSQL driver.
<3> Configure the PostgreSQL dialect.
<3> You handle database migrations via Liquibase 

[source,bash]
----
export DATASOURCES_DEFAULT_USERNAME=dbuser
export DATASOURCES_DEFAULT_PASSWORD=theSecretPassword
export VAT_PERCENTAGE=20
----

Configure your default datasource to use the PostgreSQL database you started with Docker:

include::{commondir}/common-runapp-instructions.adoc[]

You can run a cURL command to test the application:

[source, bash]
----
$ curl http://localhost:8080/liquibase
----

You will see information about migrations.

include::{commondir}/common-graal-with-plugins.adoc[]

You can run a cURL command to test the application:

[source, bash]
----
$ curl http://localhost:8080/liquibase
----

You will see information about migrations.

include::{commondir}/common-next.adoc[]

Check https://micronaut-projects.github.io/micronaut-liquibase/latest/guide/[Micronaut Liquibase] integration.

include::{commondir}/common-helpWithMicronaut.adoc[]

