common:header.adoc[]

common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app-features.adoc[]

== Logback

Configure https://logback.qos.ch[Logback] to log the package `example.micronaut` with `TRACE` level.

[source, xml]
----
<configuration>
    ...
    <logger name="example.micronaut" level="TRACE"/>
</configuration>

----

== ServerFilter

Create a filter which logs the non-sensitive HTTP Request headers.

source:LoggingHeadersFilter[]

callout:server-filter-match-all[]
callout:at-request-filter[]
callout:filter-implementing-order[]

== Controller

Create a controller which responds a JSON object: `{"message":"Hello World"}`.

source:HelloController[]

callout:controller[arg0=/]
callout:get-generic[]
callout:json-bydefault[]

common:runapp.adoc[]

[source,bash]
----
curl localhost:8080 -H "X-Request-Id: 1234"
----

You will see in the logs:

[source, bash]
----
... TRACE e.micronaut.LoggingHeadersFilter - Host: localhost:8080
... TRACE e.micronaut.LoggingHeadersFilter - User-Agent: curl/8.4.0
... TRACE e.micronaut.LoggingHeadersFilter - Accept: */*
... TRACE e.micronaut.LoggingHeadersFilter - X-Request-Id: 1234
----

== Tests

common:logback-test.adoc[]

=== Write tests

Create a `MemoryAppender` to ease testing.

test:MemoryAppender[]

Create a test that verifies the filter logs HTTP header. It masks sensitive HTTP headers.

test:HelloControllerTest[]
callout:micronaut-test[]
callout:http-client[]

common:testApp.adoc[]

common:next.adoc[]

Learn more about https://docs.micronaut.io/latest/guide/#filtermethods[Filter Methods].

common:helpWithMicronaut.adoc[]


