common:header.adoc[]

The https://datatracker.ietf.org/doc/html/rfc6455[WebSocket Protocol] allows for web browsers to establish interactive sessions with a server that are event-driven. This technology is ideal for applications that need state changes without the overhead and latency of polling the server. The article https://www.linode.com/docs/guides/introduction-to-websockets/["Introduction to WebSockets"] explains the benefits of WebSocket in more depth along with a discussion of the client-side WebSocket API.

This guide will take you through the creation of an event-driven chat application utilizing Mircronaut WebSocket.

common:completesolution.adoc[]

common:create-app-features.adoc[]

=== The chat functionality
source:ChatWebSocket[]

<1> Create the WebSocket along with path parameters for the topic and username
<2> The WebSocket broadcaster which is set from the contructor where the broadcaster is injected
<3> Event for when a client opens a WebSocket connection
<4> Event for when a client sends a message using WebSocket
<5> Event for when a client closes a WebSocket connection

=== Tests

Add a test for the resource:

== Next steps

Read more about:

- https://jakarta.ee/specifications/websocket/[Jakarta WebSocket Specifications]
