[micronaut.server]
port = -1

#tag::consul[]
[consul.client]
enabled = false
health-check = false

[consul.client.registration]
enabled = false

[endpoints.health.discovery-client-health]
enabled = false
#end::consul[]
