common:header.adoc[]

== REST-assured

In this guide, you will test a Micronaut application using https://rest-assured.io[REST-assured].

____
Testing and validating REST services in Java is harder than in dynamic languages such as Ruby and Groovy. REST Assured brings the simplicity of using these languages into the Java domain, and the Micronaut Test REST Assured module makes it easier to integrate the https://rest-assured.io[REST-assured] library. Using it eliminates the need to hard code the version, and simplifies test fixtures by supporting injection of `RequestSpecification` into test fields or method parameters (parameters are only supported with JUnit 5):
____


common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app.adoc[]

external:hello-base/hellocontroller.adoc[]

== Dependencies

To use https://rest-assured.io[REST-assured], add the following dependency on the Micronaut Test REST-assured module:

dependency:micronaut-test-rest-assured[groupId=io.micronaut.test,scope=test]

== Test

test:HelloControllerTest[]

callout:micronaut-test[1]
<2> Inject an instance of `RequestSpecification`.
<3> Micronaut Test sets the embedded server port on `spec`, so it's unnecessary to inject `EmbeddedServer` and retrieve it explicitly.

common:testApp.adoc[]

common:next.adoc[]

Learn more about https://micronaut-projects.github.io/micronaut-test/latest/guide/[Micronaut Test].

common:helpWithMicronaut.adoc[]
