micronaut:
  application:
    name: bookcatalogue
endpoints:
  health:
    enabled: true
    sensitive: false
#tag::otel[]
otel:
  traces:
    exporter: otlp
    propagator: tracecontext, baggage, xray
    exclusions: /health
#end::otel[]
netty:
  default:
    allocator:
      max-order: 3
#tag::dynamodb[]
dynamodb:
  table-name: 'bookcatalogue'
#end::dynamodb[]
#tag::testresources[]
test-resources:
  containers:
    dynamodb:
      image-name: amazon/dynamodb-local # <1>
      hostnames:
        - dynamodb-local.host # <2>
      exposed-ports:
        - dynamodb-local.port: 8000 # <3>
#end::testresources[]
