common:header-top.adoc[]

== Getting Started

In this guide, you will learn how to test your application's behavior when a user with specific roles is authenticated.

common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app-features.adoc[]

=== Controller

Given a controller that returns a different output depending on whether the user has a certain role or not:

source:PlanController[]

callout:controller[arg0=/]
callout:produces[]
callout:secured-is-authenticated[]
callout:get[arg0=index,arg1=/plan]
<.> You can bind `Authentication` as a parameter in a controller method.

=== Tests

==== Test authentication required

You can write tests to verify the behavior of the controller.

The following test verifies that authentication is required to access the endpoint:

test:PlanControllerRequiresAuthenticationTest[]

callout:micronaut-test[]
callout:http-client[]

==== Test behavior with an authenticated user without roles

The following test verifies how the controller behaves when the authenticated user lacks the `ROLE_EVIL_MASTERMIND` role:

test:PlanControllerAuthenticatedTest[]
callout:spec-name[]
callout:micronaut-test[]
callout:http-client[]

==== Test behavior with an authenticated user with a role

The following test verifies how the controller behaves when the authenticated user has the `ROLE_EVIL_MASTERMIND` role:

test:PlanControllerAuthenticatedWithRolesTest[]

callout:spec-name[]
callout:micronaut-test[]
callout:http-client[]

common:testApp.adoc[]

== Next Steps

See the https://micronaut-projects.github.io/micronaut-security/latest/guide/[Micronaut security documentation] to learn more.

common:helpWithMicronaut.adoc[]