[micronaut.application]
name = "micronautguide"

# <1>
[micronaut.security.x509]
enabled = true

# <2>
[micronaut.ssl]
enabled = true

[micronaut.server.ssl]
# <3>
client-authentication = "want"

# <4>
[micronaut.server.ssl.key-store]
path = "classpath:ssl/keystore.p12"
# <5>
password = ""
# <6>
type = "PKCS12"

# <7>
[micronaut.server.ssl.trust-store]
path = "classpath:ssl/truststore.jks"
# <8>
password = ""
# <9>
type = "JKS"
