[micronaut.application]
name = "micronautguide"

#tag::liquibase[]
[liquibase.datasources.default]
change-log = "classpath:db/liquibase-changelog.xml"
#end::liquibase[]

#tag::datasource[]
[datasources.default]
schema-generate = "NONE"
# <1>
driver-class-name = "oracle.jdbc.OracleDriver"
# <2>
db-type = "oracle"
# <3>
dialect = "ORACLE"
#end::datasource[]
