common:header.adoc[]

You use https://flywaydb.org/documentation/[Flyway]:

____
Flyway is an open-source database migration tool. It strongly favors simplicity and convention over configuration.
____

common:requirements.adoc[]

common:completesolution.adoc[]

common:cli-or-launch.adoc[]

[source,bash]
----
mn create-app example.micronaut.micronautguide \
   --features=data-jdbc,mysql,flyway \
   --build=@build@ --lang=@lang@
----

common:build-lang-arguments.adoc[]

common:default-package.adoc[]

NOTE: If you use https://launch.micronaut.io[Micronaut Launch], select "Micronaut Application" as application type and add `mysql`, `data-jdbc`, and `flyway` as features.

https://guides.micronaut.io/latest/micronaut-intellij-idea-ide-setup.html[Setup IntelliJ IDEA to develop Micronaut Applications].

=== Create Entity

Create a `@MappedEntity` to save persons. Initially, consider name and age required. Use `int` primitive for the age.

source:Person[tags=clazz1|ageint|clazz2]

callout:mapped-entity[1]
callout:mapped-entity-id[2]
callout:generated-value[3]
callout:version-optimistic-locking[4]

common:flyway.adoc[]

resource:db/migration/V1__create-person.sql[]

During application startup, https://www.flywaydb.org[Flyway] executes the SQL file and creates the schema needed for the application.

If you check the database schema, there are two tables:

- `person`
- `flyway_scheme_history`

Flyway uses the table `flyway_scheme_history` to keep track of database migrations.

The `person` table looks like:

|===
|Column | Nullable

|`id`
|NO

|`version`
|NO

|`name`
|NO

|`age`
|NO
|===

=== Drop Not Null Constraint

Applications change. Make `age` optional:

source:Person[tags=nullableage]

Add a new migration to drop the null constraint:

resource:db/migration/V2__nullable-age.sql[]

After the migration, the `person` table looks like:

|===
|Column | Nullable

|`id`
|NO

|`version`
|NO

|`name`
|NO

|`age`
|YES
|===

== Flyway endpoint

To enable the Flyway endpoint, add the `management` dependency on your classpath.

dependency:micronaut-management[]

Enable the Flyway endpoint:

common:yaml-dependency.adoc[]

resource:application.yml[tag=endpoints]

=== Test

Create a test that invokes the Flyway endpoint.

test:FlywayEndpointTest[]

callout:micronaut-test[1]
callout:http-client[2]

common:test-resources-mysql-datasource.adoc[]

common:testApp.adoc[]

common:runapp.adoc[]

You can run a cURL command to test the application:

[source, bash]
----
curl http://localhost:8080/flyway
----

You will see information about migrations.

common:graal-with-plugins.adoc[]

You can run a cURL command to test the application:

[source, bash]
----
curl http://localhost:8080/flyway
----

You will see information about migrations.

common:next.adoc[]

Check https://micronaut-projects.github.io/micronaut-flyway/latest/guide/[Micronaut Flyway] integration.

Learn more about https://flywaydb.org[Flyway].

common:helpWithMicronaut.adoc[]
