micronaut.application.name=micronautguide
#tag::liquibase[]
liquibase.datasources.default.change-log=classpath\:db/liquibase-changelog.xml
#end::liquibase[]
#tag::datasource[]
datasources.default.schema-generate=NONE
# <1>
datasources.default.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
# <2>
datasources.default.db-type=mssql
# <3>
datasources.default.dialect=SQL_SERVER
#end::datasource[]
#tag::testresources[]
test-resources.containers.mssql.accept-license=true
test-resources.containers.mssql.startup-timeout=600s
#end::testresources[]
