CREATE OR REPLACE JSON RELATIONAL DUALITY VIEW STUDENT_VIEW AS
SELECT JSON {
    '_id': TBL_STUDENT.id,
    'name': TBL_STUDENT.name WITH UPDATE,
    'classes': [
        SELECT JSON {
            'id': TBL_STUDENT_CLASSES.id
        }
        FROM TBL_STUDENT_CLASSES
        WITH INSERT UPDATE DELETE
        WHERE TBL_STUDENT.id = TBL_STUDENT_CLASSES.student_id
    ]
}
FROM TBL_STUDENT WITH UPDATE INSERT DELETE;