micronaut:
  server:
    port: 8080 # <1>
---
#tag::httpservices[]
micronaut:
  http:
    services:
      bookcatalogue:
        url: 'http://localhost:8081'
      bookinventory:
        url: 'http://localhost:8082'
#end::httpservices[]    