micronaut:
  application:
    name: bookrecommendation # <1>
endpoints:
  health:
    enabled: true
    sensitive: false
---
#tag::oauth2[]
micronaut:
  security:
    oauth2:
      clients:
        cognito: # <1>
          client-id: '${OAUTH_CLIENT_ID:xxx}' # <2>
          client-secret: '${OAUTH_CLIENT_SECRET:yyy}' # <3>
          grant-type: client_credentials # <4>
          token:
            url: '${OAUTH_TOKEN_URL:`https://micronautguide.auth.us-east-1.amazoncognito.com/oauth2/token`}' # <5>
            auth-method: client_secret_basic # <6>
          client-credentials:
            service-id-regex: 'bookcatalogue|bookinventory' # <7>
            scope: 'example.micronaut.books/books.read' # <8>
            
#end::oauth2[]