micronaut:
  application:
    name: micronautguide
---
#tag::datasource[]
datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
#end::datasource[]
---
#tag::flyway[]
flyway:
  datasources:
    default:
      enabled: true # <1>
#end::flyway[]