micronaut:
  application:
    name: bookcatalogue
  server:
    port: 8081
endpoints:
  health:
    enabled: true
    sensitive: false
#tag::zipkin[]
otel:
  traces:
    exporter: zipkin
#end::zipkin[]
