common:header-top.adoc[]

== Getting Started

In this guide, you will create a Micronaut application written in @language@ with https://www.graalvm.org/[GraalVM] support.

common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app-features.adoc[]

=== Service

Create a `Conference` type:

source:Conference[]

callout:serdeable[]

Create a service:

source:ConferenceService[]

callout:singleton[]
<.> Return a random conference.

=== Controller

Create a controller with a method that returns a `Conference`. Micronaut Framework will convert it automatically to JSON in the
response:

source:ConferenceController[]

callout:controller[arg0=/conferences]
<.> Constructor injection.
callout:get[arg0=index,arg1=/random]
<.> Return a `Conference`.

common:graal-with-plugins.adoc[]

:exclude-for-languages:java,groovy,kotlin

== Generate a Pyronaut Application Native Executable with GraalVM

We will use https://www.graalvm.org/[GraalVM], an advanced JDK with ahead-of-time Native Image compilation, to generate a native executable of this Pyronaut application.

Compiling Pyronaut applications ahead of time with GraalVM improves startup time and reduces the memory footprint.

=== GraalVM Installation

common:install-graalvm-sdkman.adoc[]

=== Native Executable Generation

To generate a native executable using Pyronaut, run:

[source,bash]
----
pyronaut build --native
----

The native executable is created in the pass:[__pyronaut__/native] directory.

:exclude-for-languages:

:exclude-for-languages:python

=== Creating a Native Executable Inside Docker

The output following this approach is a Docker image that runs the native executable of your application. You don't need to install any additional dependencies.

:exclude-for-build:maven

.Building a GraalVM native executable with Gradle
[source,bash]
----
./gradlew dockerBuildNative
----

:exclude-for-build:

:exclude-for-build:gradle

.Building a GraalVM native executable with Maven
[source,bash]
----
./mvnw package -Dpackaging=docker-native
----

:exclude-for-build:

:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin

=== Creating a Native Executable Inside Docker

The output following this approach is a Docker image that runs the native executable of your application. You don't need to install any additional dependencies.

.Building a GraalVM native executable with Pyronaut
[source,bash]
----
pyronaut build --native --docker
----

:exclude-for-languages:

=== Running the Native Executable

Execute the application by either running the executable or starting the Docker container.

.Executing the native executable
[source,bash]
----
10:29:46.845 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 12ms. Server Running: http://localhost:8080
----

You can see that the application starts in only 12 ms.

=== Sending a Request

Start the application either using Docker or the native executable. You can run a few cURL requests to test the application:

[source,bash]
----
time curl localhost:8080/conferences/random
----

[source]
----
{"name":"Greach"}
real    0m0.016s
user    0m0.005s
sys     0m0.004s
----

[source,bash]
----
time curl localhost:8080/conferences/random
----

[source]
----
{"name":"GR8Conf EU"}
real    0m0.014s
user    0m0.005s
sys     0m0.004s
----

== Next Steps

Read more about https://docs.micronaut.io/latest/guide/#graal[Micronaut support for GraalVM].

:exclude-for-languages:python

Take a look at the https://github.com/micronaut-projects/micronaut-gradle-plugin[Micronaut Gradle plugin] and https://micronaut-projects.github.io/micronaut-maven-plugin/latest/[Micronaut Maven Plugin] documentation.

:exclude-for-languages:

common:helpWithMicronaut.adoc[]
