= @guideTitle@

@guideIntro@

Authors: @authors@

Micronaut Version: @micronaut@

include::{commondir}/common-gettingStarted.adoc[]

In this guide, we are going to create a Micronaut application with https://www.graalvm.org/[GraalVM] support.

include::{commondir}/common-requirements.adoc[]

include::{commondir}/common-completesolution.adoc[]

include::{commondir}/common-create-app.adoc[]

=== Service

Create a POJO `Conference`:

source:Conference[]

<1> Annotate the class with @api@/io/micronaut/core/annotation/Introspected.html[`@Introspected`]
to generate `BeanIntrospection` metadata at compilation time. This information is used to the render the POJO as json using Jackson
without using reflection.

Create a Service:

source:ConferenceService[]

<1> Use `javax.inject.Singleton` to designate a class a a singleton.
<2> Return a random conference.

=== Controller

Create a Controller with a method that returns a `Conference`. Micronaut will convert it automatically to JSON in the
response:

source:ConferenceController[]

<1> The class is defined as a controller with the `@Controller` annotation mapped to the path `/conferences`.
<2> Constructor injection
<3> The `@Get` annotation is used to map the index method to all requests that use an HTTP GET
<4> Return a `Conference`.

include::{commondir}/common-graal-with-plugins.adoc[]

=== Creating native image inside Docker

The output following this approach is a docker image that runs the native image of your application. You don't need to install
any additional dependency.

:exclude-for-build:maven

.Building Graal native image
[source,bash]
----
$ ./gradlew dockerBuildNative
----

:exclude-for-build:

:exclude-for-build:gradle

.Building Graal native image with Maven
[source,bash]
----
$ ./mvnw package -Dpackaging=docker-native
----

:exclude-for-build:

:exclude-for-languages:

=== Running the native image

Execute the application either by running the executable or starting the docker container.

.Executing the native image
[source,bash]
----
10:29:46.845 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 12ms. Server Running: http://localhost:8080
----

We can see that the application starts in only 12ms.

=== Sending a request

Start the application either using Docker or the native executable. You can run a few cURL requests to test the application:

[source,bash]
----
complete $ time curl localhost:8080/conferences/random
{"name":"Greach"}
real    0m0.016s
user    0m0.005s
sys     0m0.004s

complete $ time curl localhost:8080/conferences/random
{"name":"GR8Conf EU"}
real    0m0.014s
user    0m0.005s
sys     0m0.004s

----

NOTE: For more information about the new plugins take a look at the https://github.com/micronaut-projects/micronaut-gradle-plugin[Micronaut Gradle plugin]
and https://micronaut-projects.github.io/micronaut-maven-plugin/latest/index.html[Micronaut Maven Plugin] documentation.

== Next steps

Read more about https://docs.micronaut.io/latest/guide/index.html#graal[GraalVM Support] inside Micronaut.

include::{commondir}/common-helpWithMicronaut.adoc[]
