common:header-top.adoc[]

== Getting Started

In this guide, we will create a Micronaut application written in @language@ with https://www.graalvm.org/[GraalVM] support.

common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app-features.adoc[]

=== Service

Create a POJO `Conference`:

source:Conference[]

callout:serdeable[1]

Create a Service:

source:ConferenceService[]

callout:singleton[1]
<2> Return a random conference.

=== Controller

Create a Controller with a method that returns a `Conference`. The Micronaut framework will convert it automatically to JSON in the
response:

source:ConferenceController[]

callout:controller[number=1,arg0=/conferences]
<2> Constructor injection
callout:get[number=3,arg0=index,arg1=/random]
<4> Return a `Conference`.

common:graal-with-plugins.adoc[]

=== Creating native executable inside Docker

The output following this approach is a Docker image that runs the native executable of your application. You don't need to install any additional dependencies.

:exclude-for-build:maven

.Building GraalVM native executable
[source,bash]
----
./gradlew dockerBuildNative
----

:exclude-for-build:

:exclude-for-build:gradle

.Building GraalVM native executable with Maven
[source,bash]
----
./mvnw package -Dpackaging=docker-native
----

:exclude-for-build:

:exclude-for-languages:

=== Running the native executable

Execute the application by either running the executable or starting the Docker container.

.Executing the native executable
[source,bash]
----
10:29:46.845 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 12ms. Server Running: http://localhost:8080
----

We can see that the application starts in only 12ms.

=== Sending a request

Start the application either using Docker or the native executable. You can run a few cURL requests to test the application:

[source,bash]
----
time curl localhost:8080/conferences/random
----

[source]
----
{"name":"Greach"}
real    0m0.016s
user    0m0.005s
sys     0m0.004s
----

[source,bash]
----
time curl localhost:8080/conferences/random
----

[source]
----
{"name":"GR8Conf EU"}
real    0m0.014s
user    0m0.005s
sys     0m0.004s
----

== Next steps

Read more about https://docs.micronaut.io/latest/guide/#graal[GraalVM Support] inside the Micronaut framework.

Take a look at the https://github.com/micronaut-projects/micronaut-gradle-plugin[Micronaut Gradle plugin] and https://micronaut-projects.github.io/micronaut-maven-plugin/latest/[Micronaut Maven Plugin] documentation.

common:helpWithMicronaut.adoc[]
