[micronaut.application]
name = "micronautguide"

# <1>
[micronaut.security]
authentication = "idtoken"

# <2>
# <3>
[micronaut.security.oauth2.clients.micronaut]
client-id = "${OAUTH_CLIENT_ID:xxx}"
# <3>
client-secret = "${OAUTH_CLIENT_SECRET:yyy}"
# <3>
[micronaut.security.oauth2.clients.micronaut.openid]
issuer = "${OAUTH_ISSUER:https://idcs.example.identity.oraclecloud.com/}"

[micronaut.security.endpoints.logout]
enabled = true
# <4>
get-allowed = true

[netty.default.allocator]
max-order = 3
