common:header.adoc[]

common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app-features.adoc[]

:leveloffset: +1

common:openapi-dependencies.adoc[]

== Latest Guide Controller

First, let's create a controller that exposes the https://guides.micronaut.io[Micronaut Guides] information.

=== Guides Model

We support different build tools per guide:

source:BuildTool[]

A guide may be written in multiple languages:

source:Language[]

Thus, we have several options per guide:

source:Option[]
callout:serdeable[1]
callout:constraints[2]

The following Java record represents a Micronaut Guide:

source:Guide[]
callout:serdeable[1]
callout:constraints[2]
callout:swagger-schema[3]

=== Controller

Let's create a controller for which we will generate an OpenAPI Specification at build time.

source:LatestGuidesController[]

We could test such a controller with:

test:LatestGuidesControllerTest[]

callout:micronaut-test[1]
callout:http-client[2]

== @OpenApiSpecification

The Micronaut OpenAPI integration requires a class to be annotated with `@OpenApiSpecification`. Modify `Application.java` and annotate it.

source:Application[]

== OpenAPI Generated at compile-time

By adding the `@OpenApiSpecification` annotation to `Application`, an OpenAPI specification is generated at compile-time. You can test it as follows:

test:OpenApiGeneratedTest[]
callout:micronaut-test-start-application-false[1]

== Expose the OpenAPI Specification

We can expose the OpenAPI specification generated at compile-time as a static resource with the following configuration:

resource:application.properties[tag=static-resources-swagger]

You can test the OpenAPI specification is available:

test:OpenApiExposedTest[]
callout:micronaut-test[1]
callout:http-client[2]

== Swagger UI

To simplify the visualization of the OpenAPI specification, we are going to use https://swagger.io/tools/swagger-ui/[Swagger UI]

____
Swagger UI allows anyone — be it your development team or your end consumers — to visualize and interact with the API’s resources without having any of the implementation logic in place. It’s automatically generated from your OpenAPI (formerly known as Swagger) Specification, with the visual documentation making it easy for back end implementation and client side consumption.
____

To generate Swagger-UI HTML, create an `openapi.properties` file in the root of your project and add:

[source, properties]
----
swagger-ui.enabled=true
----

You can write a test to verify that Swagger-UI HTML is generated at compile-time.

test:SwaggerUiGeneratedTest[]
callout:micronaut-test-start-application-false[1]

== Expose Swagger-UI

We can expose the Swagger-UI HTML generated at compile-time as a static resource with the following configuration:

resource:application.properties[tag=swagger-ui]

You can test the Swagger-UI is available:

test:SwaggerUiTest[]
callout:micronaut-test[1]
callout:http-client[2]

== Home Controller

Next, create a controller that redirects to the swagger-ui endpoint.

source:HomeController[]
callout:controller[number=1,arg0=/]
callout:get-generic[number=2]
callout:swagger-hidden[3]

Write a test that verifies the redirection and checks that the endpoint is not included in the OpenAPI specification:

test:HomeControllerTest[]
callout:property[1]
callout:micronaut-test[2]
callout:http-client[3]
<4> The root endpoint is not included in the OpenAPI specification.

:leveloffset: -1

common:testApp.adoc[]

common:runapp.adoc[]

If you go to `http://localhost:8080`, you will see the SwaggerUI visualization of the compile-time generated OpenAPI Specification

common:graal-with-plugins.adoc[]

If you go to `http://localhost:8080`, you will see the SwaggerUI visualization of the compile-time generated OpenAPI Specification

common:next.adoc[]

common:helpWithMicronaut.adoc[]
