common:header.adoc[]

common:requirements.adoc[]

common:completesolution.adoc[]

== OAuth 2.0 Dependency

To use OAuth 2.0 integration, add the next dependency:

dependency:micronaut-security-oauth2[groupId=io.micronaut.security]

== Micronaut Discovery client

Add the next dependency:

dependency:micronaut-discovery-client[groupId=io.micronaut.discovery]

== Bootstrap.yml

To enable distributed configuration a src/main/resources/bootstrap.yml configuration file must be created:

resource:bootstrap.yml[]

<1> Set the application name in `bootstrap.yml` instead of `application.yml` so that its value is available for Bootstrap Context compatible beans.
<2> Enable `micronaut.config-client.enabled`
<3> Enable Hashicorp Vault client and configure its uri.

== Controller

Create a controller which exposes the value read from AWS Secrets Manager.

source:ClientIdController[]

== Logs

Add the following configuration to `src/main/resources/logback.xml` to get a more verbose output when the app startsup:

[source, xml]
----
<logger name="io.micronaut.discovery.vault" level="TRACE"/>
----

== Start Vault via Docker

[source, bash]
----
docker run --cap-add=IPC_LOCK -d --name=dev-vault vault
----

The above runs a completely in-memory Vault server, which is useful for development but should not be used in production.

common:runapp.adoc[]

You should see traces such as:

```
TODO
```

[source, bash]
----
curl localhost:8080
XXXX
----

common:graal-with-plugins.adoc[]

common:next.adoc[]

Read about https://aws.amazon.com/secrets-manager/[AWS Secrets Manager]

common:helpWithMicronaut.adoc[]