micronaut.application.name=micronautguide
#tag::liquibase[]
liquibase.datasources.default.change-log=classpath\:db/liquibase-changelog.xml
#end::liquibase[]
#tag::datasource[]
datasources.default.schema-generate=NONE
# <1>
datasources.default.driver-class-name=org.postgresql.Driver
# <2>
datasources.default.db-type=postgres
# <3>
datasources.default.dialect=POSTGRES
#end::datasource[]
#tag::testresources[]
test-resources.containers.postgres.image-name=postgis/postgis
test-resources.containers.postgres.image-tag=17-3.5
test-resources.containers.postgres.startup-timeout=600s
#end::testresources[]
