external:micronaut-object-storage-base/start.adoc[]

common:oracle-cloud-account.adoc[]
common:oracle-cloud-cli.adoc[]

common:jq[]

common:completesolution.adoc[]

common:create-app-features.adoc[]

== Create a bucket

common:oracle-cloud-compartment-id.adoc[]

=== Use the CLI to create the bucket

[source,bash]
----
oci os bucket create --compartment-id $C --name micronaut-guide-object-storage
----

We can also use the CLI to get the Object Storage namespace:

[source,bash]
----
export OCI_NS=$(oci os ns get | jq -r '.data')
----

Then, configure the bucket name and namespace in `application.yml`:

common:yaml-dependency.adoc[]

resource:application.yml[tag=object-storage]

== Controller API

external:micronaut-object-storage-base/controller-api.adoc[]

source:ProfilePicturesController[tags=begin-class|end-class]

callout:controller[number=1,arg0=/pictures]
callout:executes-on[2]
callout:object-storage-operations[number=3,arg0=oraclecloud,arg1=OracleCloudStorageOperations]
callout:object-storage-host-resolver[4]

=== Upload endpoint

Implement the upload endpoint by receiving the file from the HTTP client via `CompletedFileUpload`, and the `userId` path
parameter. Upload it to Oracle Cloud using
https://micronaut-projects.github.io/micronaut-object-storage/latest/api/io/micronaut/objectstorage/oraclecloud/OracleCloudStorageOperations.html[OracleCloudStorageOperations],
and then return its `ETag` in an HTTP response header to the client:

source:ProfilePicturesController[tags=upload,indent=0]

callout:object-storage-key[1]
callout:object-storage-request[2]
callout:object-storage-upload-response[number=3,arg0=https://docs.oracle.com/en-us/iaas/tools/java/2.44.0/com/oracle/bmc/objectstorage/responses/PutObjectResponse.html,arg1=PutObjectResponse]
callout:object-storage-location[4]
callout:object-storage-response[5]

=== Download endpoint

external:micronaut-object-storage-base/download-endpoint.adoc[]

source:ProfilePicturesController[tags=download,indent=0]
<1> The retrieve operation returns an `ObjectStorageEntry`, in this case an
https://micronaut-projects.github.io/micronaut-object-storage/latest/api/io/micronaut/objectstorage/oraclecloud/OracleCloudStorageEntry.html[OracleCloudStorageEntry],
which allows accessing the Oracle Cloud-specific
https://docs.oracle.com/en-us/iaas/tools/java/2.44.0/com/oracle/bmc/objectstorage/responses/GetObjectResponse.html[GetObjectResponse]
callout:object-storage-entry-to-response[number=2,arg0=OracleCloudStorageEntry]
callout:object-storage-etag[3]

external:micronaut-object-storage-base/etag.adoc[]

=== Delete endpoint

external:micronaut-object-storage-base/delete-endpoint.adoc[]

common:runapp.adoc[]

common:graal-with-plugins.adoc[]

== Testing

Test the application from the command line.

=== Uploading a profile picture

external:micronaut-object-storage-base/testing-upload.adoc[]

Use the `oci` CLI to verify that the file has been uploaded to an Oracle Cloud bucket:

[source,bash]
----
oci os object list --bucket-name micronaut-guide-object-storage
----

=== Download a profile picture

external:micronaut-object-storage-base/testing-download.adoc[]

=== Delete a profile picture

external:micronaut-object-storage-base/testing-delete.adoc[]

[source,bash]
----
oci os object list --bucket-name micronaut-guide-object-storage
----

=== Cleanup

Remove the bucket from Oracle Cloud to not leave stale resources:

[source,bash]
----
oci os bucket delete --bucket-name micronaut-guide-object-storage
----

external:micronaut-object-storage-base/end.adoc[]
* Discover https://www.oracle.com/cloud/storage/object-storage/[Oracle Cloud Infrastructure (OCI) Object Storage].
