micronaut:
  application:
    name: complete
#tag::datasource[]
datasources:
  default:
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driverClassName: org.h2.Driver
#end::datasource[]
#tag::flyway[]
flyway:
  datasources:
    default:
      locations: classpath:databasemigrations
#end::flyway[]