name: Guides CI
on:
  push:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
  pull_request:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
jobs:
  build-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build Guide
        run: ./gradlew creatingYourFirstMicronautAppBuild
      - id: set-mavenmatrix
        run: echo "::set-output name=mavenmatrix::[creating-your-first-micronaut-app-maven-groovy,creating-your-first-micronaut-app-maven-java,creating-your-first-micronaut-app-maven-kotlin]"
      - id: set-gradlematrix
        run: echo "::set-output name=gradlematrix::[creating-your-first-micronaut-app-gradle-groovy,creating-your-first-micronaut-app-gradle-java,creating-your-first-micronaut-app-gradle-kotlin]"
    outputs:
      gradlematrix: ${{ steps.set-matrix.outputs.gradlematrix }}
      mavenmatrix: ${{ steps.set-matrix.outputs.mavenmatrix }}
  maven-test-jdk8:
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_project: ${{needs.build-matrix.outputs.mavenmatrix}}
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build with Maven
        run: |
          cd "build/code/creating-your-first-micronaut-app/$test_project"
          ./mvnw test
  gradle-test-jdk8:
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_project: ${{needs.build-matrix.outputs.gradlematrix}}
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build with Gradle
        run: |
          cd "build/code/creating-your-first-micronaut-app/$test_project"
          ./gradlew test