name: Guides CI
on:
  push:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
  pull_request:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
jobs:
  matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build Guide
        run: ./gradlew creatingYourFirstMicronautAppBuild
      - id: set-mavenmatrix
        echo "::set-output name=mavenmatrix::{\"testproject\":[\"creating-your-first-micronaut-app-maven-groovy\",\"creating-your-first-micronaut-app-maven-java\",\"creating-your-first-micronaut-app-maven-kotlin\"]}"
      - id: set-gradlematrix
        echo "::set-output name=gradlematrix::{\"testproject\":[\"creating-your-first-micronaut-app-gradle-groovy\",\"creating-your-first-micronaut-app-gradle-java\",\"creating-your-first-micronaut-app-gradle-kotlin\"]}"
    outputs:
      gradlematrix: ${{ steps.set-matrix.outputs.gradlematrix }}
      mavenmatrix: ${{ steps.set-matrix.outputs.mavenmatrix }}
  check-matrix:
    runs-on: ubuntu-latest
    needs: matrix
    steps:
      - name: Install json2yaml
        run: |
          sudo npm install -g json2yaml

      - name: Check matrix definition
        run: |
          matrix='${{ needs.matrix.outputs.gradlematrix }}'
          echo $matrix
          echo $matrix | jq .
          echo $matrix | json2yaml
  maven-test-jdk:
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{needs.matrix.outputs.mavenmatrix}}
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build with Maven
        run: |
          cd "build/code/creating-your-first-micronaut-app/$testproject"
          ./mvnw test
  gradle-test-jdk:
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{needs.matrix.outputs.gradlematrix}}
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build with Gradle
        run: |
          cd "build/code/creating-your-first-micronaut-app/$testproject"
          ./gradlew test