name: Test micronaut-database-authentication-provider
on:
  push:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
    paths: ["version.txt","guides/micronaut-database-authentication-provider/**"]
  pull_request:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
    paths: ["version.txt","guides/micronaut-database-authentication-provider/**"]
jobs:
  maven-test:
    if: ${{ false }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["8","11","17"]
        testproject: []
    env:
      JDK_VERSION:  ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build Projects
        run: ./gradlew micronautDatabaseAuthenticationProviderGenerateProjects
      - name: Build with Maven
        run: 'cd build/code/micronaut-database-authentication-provider/${{ matrix.testproject }};export AWS_ACCESS_KEY_ID=XXX;export AWS_SECRET_ACCESS_KEY=YYY;export AWS_REGION=us-east-1;./mvnw test'
  gradle-test:
    if: ${{ true }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["8","11","17"]
        testproject: ["micronaut-database-authentication-provider-gradle-groovy"]
    env:
      JDK_VERSION: ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build Projects
        run: ./gradlew micronautDatabaseAuthenticationProviderGenerateProjects
      - name: Build with Gradle
        run: 'cd build/code/micronaut-database-authentication-provider/${{ matrix.testproject }};export AWS_ACCESS_KEY_ID=XXX;export AWS_SECRET_ACCESS_KEY=YYY;export AWS_REGION=us-east-1;./gradlew test'
