name: Test micronaut-oracle-function
on:
  push:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
    paths: ["version.txt","guides/micronaut-oracle-function/**"]
  pull_request:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
    paths: ["version.txt","guides/micronaut-oracle-function/**"]
jobs:
  maven-test:
    if: ${{ true }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["11","17"]
        testproject: ["micronaut-oracle-function-maven-java","micronaut-oracle-function-maven-groovy","micronaut-oracle-function-maven-kotlin"]
    env:
      JDK_VERSION:  ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build Projects
        run: ./gradlew micronautOracleFunctionGenerateProjects
      - name: Build with Maven
        run: 'cd build/code/micronaut-oracle-function/${{ matrix.testproject }};./mvnw test'
  gradle-test:
    if: ${{ true }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["11","17"]
        testproject: ["micronaut-oracle-function-gradle-java","micronaut-oracle-function-gradle-groovy","micronaut-oracle-function-gradle-kotlin"]
    env:
      JDK_VERSION: ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build Projects
        run: ./gradlew micronautOracleFunctionGenerateProjects
      - name: Build with Gradle
        run: 'cd build/code/micronaut-oracle-function/${{ matrix.testproject }};./gradlew test'
