name: Test creating-your-first-micronaut-app
on:
  push:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
    paths: ["version.txt","guides/creating-your-first-micronaut-app/**","guides/hello-base/**"]
  pull_request:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
    paths: ["version.txt","guides/creating-your-first-micronaut-app/**","guides/hello-base/**"]
jobs:
  maven-test:
    if: ${{ true }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["8","11","17"]
        testproject: ["creating-your-first-micronaut-app-maven-java","creating-your-first-micronaut-app-maven-groovy","creating-your-first-micronaut-app-maven-kotlin"]
    env:
      JDK_VERSION:  ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build Projects
        run: ./gradlew creatingYourFirstMicronautAppGenerateProjects
      - name: Build with Maven
        run: 'cd build/code/creating-your-first-micronaut-app/${{ matrix.testproject }};export AWS_ACCESS_KEY_ID=XXX;export AWS_SECRET_ACCESS_KEY=YYY;export AWS_REGION=us-east-1;./mvnw test'
  gradle-test:
    if: ${{ true }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["8","11","17"]
        testproject: ["creating-your-first-micronaut-app-gradle-java","creating-your-first-micronaut-app-gradle-groovy","creating-your-first-micronaut-app-gradle-kotlin"]
    env:
      JDK_VERSION: ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build Projects
        run: ./gradlew creatingYourFirstMicronautAppGenerateProjects
      - name: Build with Gradle
        run: 'cd build/code/creating-your-first-micronaut-app/${{ matrix.testproject }};export AWS_ACCESS_KEY_ID=XXX;export AWS_SECRET_ACCESS_KEY=YYY;export AWS_REGION=us-east-1;./gradlew test'
