name: Test micronaut-java-records
on:
  schedule:
    - cron: '0 5 * * 1-5'
jobs:
  maven-test:
    if: ${{ true }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["17"]
        testproject: ["micronaut-java-records-maven-java"]
    env:
      JDK_VERSION:  ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Use next snapshot patch version
        run: ./increment_version.sh -p
      - name: Build Projects
        run: ./gradlew micronautJavaRecordsGenerateProjects
      - name: Build with Maven
        run: 'cd build/code/micronaut-java-records/${{ matrix.testproject }};./mvnw test'
  gradle-test:
    if: ${{ true }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["17"]
        testproject: ["micronaut-java-records-gradle-java"]
    env:
      JDK_VERSION: ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Use next snapshot patch version
        run: ./increment_version.sh -p
      - name: Build Projects
        run: ./gradlew micronautJavaRecordsGenerateProjects
      - name: Build with Gradle
        run: 'cd build/code/micronaut-java-records/${{ matrix.testproject }};./gradlew test'

