name: Test micronaut-rabbitmq
on:
  push:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
    paths: ["version.txt","guides/micronaut-rabbitmq/**"]
  pull_request:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
    paths: ["version.txt","guides/micronaut-rabbitmq/**"]
jobs:
  maven-test:
    if: ${{ true }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["8","11","17"]
        testproject: ["micronaut-rabbitmq-maven-java/books","micronaut-rabbitmq-maven-java/analytics","micronaut-rabbitmq-maven-groovy/books","micronaut-rabbitmq-maven-groovy/analytics","micronaut-rabbitmq-maven-kotlin/books","micronaut-rabbitmq-maven-kotlin/analytics"]
    env:
      JDK_VERSION:  ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build Projects
        run: ./gradlew micronautRabbitmqGenerateProjects
      - name: Build with Maven
        run: 'cd build/code/micronaut-rabbitmq/${{ matrix.testproject }};./mvnw test'
  gradle-test:
    if: ${{ true }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["8","11","17"]
        testproject: ["micronaut-rabbitmq-gradle-java/books","micronaut-rabbitmq-gradle-java/analytics","micronaut-rabbitmq-gradle-groovy/books","micronaut-rabbitmq-gradle-groovy/analytics","micronaut-rabbitmq-gradle-kotlin/books","micronaut-rabbitmq-gradle-kotlin/analytics"]
    env:
      JDK_VERSION: ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build Projects
        run: ./gradlew micronautRabbitmqGenerateProjects
      - name: Build with Gradle
        run: 'cd build/code/micronaut-rabbitmq/${{ matrix.testproject }};./gradlew test'
