name: Test micronaut-oauth2-client-credentials-cognito
on:
  push:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
    paths: ["version.txt","guides/micronaut-oauth2-client-credentials-cognito/**"]
  pull_request:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
    paths: ["version.txt","guides/micronaut-oauth2-client-credentials-cognito/**"]
jobs:
  maven-test:
    if: ${{ true }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["8","11","17"]
        testproject: ["micronaut-oauth2-client-credentials-cognito-maven-java/bookcatalogue","micronaut-oauth2-client-credentials-cognito-maven-java/bookinventory","micronaut-oauth2-client-credentials-cognito-maven-java/bookrecommendation","micronaut-oauth2-client-credentials-cognito-maven-groovy/bookcatalogue","micronaut-oauth2-client-credentials-cognito-maven-groovy/bookinventory","micronaut-oauth2-client-credentials-cognito-maven-groovy/bookrecommendation","micronaut-oauth2-client-credentials-cognito-maven-kotlin/bookcatalogue","micronaut-oauth2-client-credentials-cognito-maven-kotlin/bookinventory","micronaut-oauth2-client-credentials-cognito-maven-kotlin/bookrecommendation"]
    env:
      JDK_VERSION:  ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build Projects
        run: ./gradlew micronautOauth2ClientCredentialsCognitoGenerateProjects
      - name: Build with Maven
        run: 'cd build/code/micronaut-oauth2-client-credentials-cognito/${{ matrix.testproject }};./mvnw test'
  gradle-test:
    if: ${{ true }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["8","11","17"]
        testproject: ["micronaut-oauth2-client-credentials-cognito-gradle-java/bookcatalogue","micronaut-oauth2-client-credentials-cognito-gradle-java/bookinventory","micronaut-oauth2-client-credentials-cognito-gradle-java/bookrecommendation","micronaut-oauth2-client-credentials-cognito-gradle-groovy/bookcatalogue","micronaut-oauth2-client-credentials-cognito-gradle-groovy/bookinventory","micronaut-oauth2-client-credentials-cognito-gradle-groovy/bookrecommendation","micronaut-oauth2-client-credentials-cognito-gradle-kotlin/bookcatalogue","micronaut-oauth2-client-credentials-cognito-gradle-kotlin/bookinventory","micronaut-oauth2-client-credentials-cognito-gradle-kotlin/bookrecommendation"]
    env:
      JDK_VERSION: ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build Projects
        run: ./gradlew micronautOauth2ClientCredentialsCognitoGenerateProjects
      - name: Build with Gradle
        run: 'cd build/code/micronaut-oauth2-client-credentials-cognito/${{ matrix.testproject }};./gradlew test'
