name: Python Scripts
on:
  push:
    branches:
      - master
    paths:
      - '.github/scripts/**'
      - '.github/workflows/python-scripts.yml'
  pull_request:
    branches:
      - master
    paths:
      - '.github/scripts/**'
      - '.github/workflows/python-scripts.yml'

jobs:
  test:
    name: Test Python Scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run Tests
        run: python3 -m unittest discover -s .github/scripts -p 'test_*.py'
