name: Validate Python Guides
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/python-guides.yml'
      - 'buildSrc/**'
      - 'guides/**'
      - 'settings.gradle'
      - 'src/docs/common/**'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/python-guides.yml'
      - 'buildSrc/**'
      - 'guides/**'
      - 'settings.gradle'
      - 'src/docs/common/**'

jobs:
  validate:
    name: Generate Python Guides
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-java@v5.2.0
        with:
          distribution: adopt
          java-version: '25'
      - uses: actions/cache@v5.0.5
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Validate build infrastructure
        run: ./gradlew buildSrc:test --stacktrace
      - name: Generate Python guides
        run: ./gradlew generateAllPythonGuideTestScripts --stacktrace
