common:header-top.adoc[]

== Getting Started

In this guide, you will set up JWT-based authentication and configure it so that JWT tokens are transported and read via cookies.

The following sequence illustrates the authentication flow:

image::jwt-cookie.svg[]

common:requirements.adoc[]

common:completesolution.adoc[]

common:create-app-features.adoc[]

=== Configuration

Add the following configuration:

:exclude-for-languages:python

resource:application.properties[tag=security]

:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin

resource:application.toml[tag=security]

:exclude-for-languages:

<1> Enable Cookie authentication.
<2> If the login fails, redirect to `/login/authFailed`
:exclude-for-languages:python
<3> You can create a https://micronaut-projects.github.io/micronaut-security/latest/api/io/micronaut/security/token/jwt/signature/secret/SecretSignatureConfiguration.html[SecretSignatureConfiguration] named `generator` via configuration as illustrated above. The `generator` signature is used to sign the issued JWT claims.
<4> Change this to your own secret and keep it safe.
:exclude-for-languages:
:exclude-for-languages:java,groovy,kotlin
<3> Accept GET requests to the `/logout` endpoint.
<4> You can create a https://micronaut-projects.github.io/micronaut-security/latest/api/io/micronaut/security/token/jwt/signature/secret/SecretSignatureConfiguration.html[SecretSignatureConfiguration] named `generator` via configuration as illustrated above. The `generator` signature is used to sign the issued JWT claims.
<5> Change this to your own secret and keep it safe.
:exclude-for-languages:

=== Authentication Provider

To keep this guide simple, create a naive `AuthenticationProvider` to simulate user authentication.

source:AuthenticationProviderUserPassword[]

callout:singleton[]
callout:http-request-authentication-provider[]

=== Apache Velocity

By default, Micronaut controllers produce JSON. Usually, you consume those endpoints with a mobile phone application, or a JavaScript front end (Angular, React, Vue.js, etc.). However, to keep this guide simple, we will produce HTML in our controllers.

In order to do that, we use https://velocity.apache.org/[Apache Velocity] and the Micronaut https://docs.micronaut.io/latest/guide/#views[Server Side View Rendering Module].
____
Velocity is a Java-based template engine. It permits anyone to use a simple yet powerful template language to reference objects defined in Java code.
____

Create two Velocity templates in `src/main/resources/views`:

resource:views/home.vm[]

resource:views/auth.vm[]

=== Controllers

Create `HomeController` which resolves the base URL `/`:

source:HomeController[]

<1> Annotate with `io.micronaut.security.Secured` to configure security access. Use `isAnonymous()` expression for anonymous access.
<2> Annotate with `io.micronaut.http.annotation.Controller` to designate the class as a Micronaut controller.
<3> You can specify the HTTP verb that a controller action responds to. To respond to a GET request, use `io.micronaut.http.annotation.Get`
<4> Use @api@/io/micronaut/views/View.html[View] annotation to specify which template to use to render the response.
:exclude-for-languages:python
<5> If you are authenticated, you can use the `java.security.Principal` as a parameter type. For parameters which may be null, use `io.micronaut.core.annotation.Nullable`.
:exclude-for-languages:
:exclude-for-languages:java,groovy,kotlin
<5> The request exposes the current user principal when the request is authenticated.
:exclude-for-languages:

=== Login Form

Next, create `LoginAuthController` which renders the login form.

source:LoginAuthController[]

<1> Annotate with `io.micronaut.security.Secured` to configure security access. Use `isAnonymous()` expression for anonymous access.
<2> Annotate with `io.micronaut.http.annotation.Controller` to designate the class as a Micronaut controller.
<3> Responds to GET requests at `/login/auth`
<4> Use @api@/io/micronaut/views/View.html[View] annotation to specify which template to use to render the response.
<5> Responds to GET requests at `/login/authFailed`

== Tests

:exclude-for-languages:python

common:geb.adoc[]

Create two pages:

rawTest:HomePage[]

rawTest:LoginPage[]

Create tests to verify the user authentication flow.

rawTest:AuthenticationSpec[]

callout:micronaut-test[]
<2> Inject the `EmbeddedServer` bean.

:exclude-for-languages:

:exclude-for-languages:java,groovy,kotlin

Create a test to verify the user authentication flow.

test:AuthenticationTest[]

callout:micronaut-test[]
<2> Use `requests.with_context` to send HTTP requests to the running test server.

:exclude-for-languages:

common:testApp.adoc[]

common:runapp.adoc[]

common:graal-with-plugins.adoc[]

common:next.adoc[]

common:helpWithMicronaut.adoc[]
