micronaut:
  application:
    name: app
---
#tag::oauth2[]
micronaut:
  security:
    authentication: cookie # <1>
    token:
      jwt:
        signatures:
          secret:
            generator: # <2>
              secret: '${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}' # <3>
    oauth2:
      clients:
        linkedin: # <4>
          client-id: '${OAUTH_CLIENT_ID:xxx}' # <5>
          client-secret: '${OAUTH_CLIENT_SECRET:yyy}' # <6>
          scopes:
            - r_liteprofile # <7>
          authorization:
            url: https://www.linkedin.com/oauth/v2/authorization # <8>
          token:
            url: https://www.linkedin.com/oauth/v2/accessToken # <9>
    endpoints:
      logout:
        get-allowed: true # <10>
#end::oauth2[]
---
#tag::micronaut-http-services[]
micronaut:
  http:
    services:
      linkedin:
        url: "https://api.linkedin.com"
#end::micronaut-http-services[]