micronaut:
  application:
    name: bookrecommendation # <1>
endpoints:
  health:
    enabled: true
    sensitive: false
---
#tag::oauth2[]
micronaut:
  security:
    oauth2:
      clients:
        oci: # <1>
          client-id: '${OAUTH_CLIENT_ID:xxx}' # <2>
          client-secret: '${OAUTH_CLIENT_SECRET:yyy}' # <3>
          grant-type: 'client_credentials' # <4>
          token:
            url: '${OAUTH_TOKEN_URL:`https://idcs-12bzlaba1124141.identity.oraclecloud.com/oauth2/v1/token`}' # <5>
            auth-method: 'client_secret_post' # <6>
          client-credentials:
            scope: 'offline_access'
            service-id-regex: 'bookcatalogue|bookinventory' # <7>
#end::oauth2[]
