#tag::control-panel[]
endpoints.all.enabled=true
# <1>
endpoints.all.sensitive=false
# <2>
endpoints.health.details-visible=ANONYMOUS
# <3>
endpoints.loggers.write-sensitive=false
# <4>
#end::control-panel[]
