external:micronaut-email/header.adoc[]

external:micronaut-email/controller.adoc[]

external:micronaut-email/configuration.adoc[]

=== SendGrid

https://sendgrid.com/[SendGrid] is a transactional email service.

____
SendGrid is responsible for sending billions of emails for some of the best and brightest companies in the world.
____

==== SendGrid API Key

To use the Micronaut Sendgrid integration, you need an https://app.sendgrid.com/settings/api_keys[API Key].

You need to https://micronaut-projects.github.io/micronaut-email/latest/guide/#io.micronaut.email.sendgrid.SendGridConfigurationProperties[configure] the `sendgrid.api-key` property. However, don't put it in `application.yml`. It's a password. Expose it via the `SENDGRID_API_KEY` environment variable, using a secret manager or create an environment specific configuration file that won't be included in source version control.

==== Dependency

Because we added the `email-sendgrid` feature, the application contains the following dependency:

dependency:micronaut-email-sendgrid[groupId=com.micronaut.email]

external:micronaut-email/test.adoc[]

== Running the Application

=== API Key

Set the SendGrid API Key as an environment variable before you run the application:

[source, bash]
----
export SENDGRID_API_KEY=xxx
----

=== From email address

Change the property `micronaut.email.from.email` to match your SendGrid configuration.

=== Run
common:runapp-instructions.adoc[]

=== Invoke

[source, bash]
----
curl -d '{"to":"john@micronaut.example"}' \
     -H "Content-Type: application/json" \
     -X POST http://localhost:8080/mail/send
----

external:micronaut-email/next.adoc[]

common:helpWithMicronaut.adoc[]
